### ISSUE TITLE
fstrim.service conflicting arguments

### ISSUE THREAD

**Issue by smopucilowski** [karelzak/util-linux#1001]
https://github.com/karelzak/util-linux/blob/a971746370b5ec3f923f31dcc2ab51e2975ef6fb/sys-utils/fstrim.service.in#L8

Having both `--quiet` and `--verbose` seems conflicting. 

Specifying `--quiet` means we also lose helpful diagnostic information in system logs:

````
Mar 30 00:33:17 wanderweg.local systemd[1]: Starting Discard unused blocks on filesystems from /etc/fstab...
Mar 30 00:34:23 wanderweg.local fstrim[1830528]: /: 1.5 GiB (1638895616 bytes) trimmed on /dev/sda2
Mar 30 00:34:23 wanderweg.local systemd[1]: fstrim.service: Succeeded.
Mar 30 00:34:23 wanderweg.local systemd[1]: Finished Discard unused blocks on filesystems from /etc/fstab.
````

This temporal information is not available elsewhere. Such diagnostic information is provided with other packages typically, for example `btrfs-scrub`:

````
Mar 31 14:59:17 wanderweg.local systemd[1]: Starting Scrub BTRFS filesystem, check volume for errors...
Mar 31 14:59:17 wanderweg.local kernel: BTRFS info (device sda2): scrub: started on devid 1
Mar 31 14:59:23 wanderweg.local kernel: BTRFS info (device sda2): scrub: finished on devid 1 with status: 0
Mar 31 14:59:23 wanderweg.local btrfs[523577]: scrub done for 6df412a0-b671-46df-8ac8-4c128e61ebbf
Mar 31 14:59:23 wanderweg.local btrfs[523577]: Scrub started:    Tue Mar 31 14:59:17 2020
Mar 31 14:59:23 wanderweg.local btrfs[523577]: Status:           finished
Mar 31 14:59:23 wanderweg.local btrfs[523577]: Duration:         0:00:06
Mar 31 14:59:23 wanderweg.local btrfs[523577]: Total to scrub:   5.03GiB
Mar 31 14:59:23 wanderweg.local btrfs[523577]: Rate:             556.92MiB/s
Mar 31 14:59:23 wanderweg.local btrfs[523577]: Error summary:    no errors found
Mar 31 14:59:23 wanderweg.local systemd[1]: btrfs-scrub.service: Succeeded.
Mar 31 14:59:23 wanderweg.local systemd[1]: Finished Scrub BTRFS filesystem, check volume for errors.
````

Suppressing this information means we can't look back through history to make sure things are performing as expected.

**Comment by karelzak** [comment]
Well, --quiet is a pretty bad name for the option, it should be --quiet-unsupported.

We need this option in the service file, because some filesystems/devices do not support trim, but we have no way how to detect it before we call the trim operation. If you do not like it then remove the option from your service file. 

I don't think we can create default configuration which will work everywhere...

**Comment by karelzak** [comment]
And note that --quiet does not suppres all warnings/errors.

**Comment by karelzak** [comment]
@kerolasa any objection?  (sorry for the commit subject, should be s/quite/quiet/)
 
I think we can rename  --quiet to --quiet-unsupported without break backward compatibility as getopt_long() supports abbreviations.

**Comment by smopucilowski** [comment]
This is a great fix. Maybe --silence-unsupported instead of --quiet-unsupported?

**Comment by karelzak** [comment]
We need --quiet-* because it's backwardly compatible. The fstrim code will interpret '--quite-unsupported' in the same way as '--quiet'. If we will introduce a new option that we have to keep the old one supported too.

**Comment by kerolasa** [comment]
No objections. Looking old commit 374baa6f64cafe7f1455d68da4fe7069ffbfe6c8 the option name made sense when just staring that change alone. In hindsight we should have considered how options are used together when adding the `--quiet` option. Lets hope that same mistake is not repeated in future user interface changes.
