### ISSUE TITLE
Ambiguity in scriptlive.1 man page

### ISSUE THREAD

**Issue by mariobl** [karelzak/util-linux#1004]
In scriptlive.1, the term »typescript« is widely used, but also »transcript« appears:

-m, --maxdelay number
              Set the maximum delay between transcript updates  to  number  of
              seconds.   The argument is a floating point number.  This can be
              used to avoid long pauses in the transcript replay.

Are »typescript« and »transcript« to be considered as synonyms? Then it should be used consistently.

**Comment by karelzak** [comment]
Good point. Fixed. Thanks.
