### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by gustavotemple** [karelzak/util-linux#1006]
```shell
nsenter --version                
nsenter from util-linux 2.31.1
```

I opened two terminals, in the first one:
```shell
unshare -r --pid --mount-proc --fork /bin/bash
```

And in the second one:
```shell
ps aux # to get the PID
nsenter -t <PID> -p -m true
nsenter: reassociate to namespace 'ns/pid' failed: Operation not permitted
```

So I did a second try, in the first terminal:
```shell
unshare --setgroups=allow --user --pid --mount-proc --fork /bin/bash
```

And in the second one:
```shell
ps aux # to get the PID
nsenter -t <PID> -m -p true
nsenter: reassociate to namespace 'ns/pid' failed: Operation not permitted
nsenter -t <PID> -U -m -p true
nsenter: setgroups failed: Operation not permitted
```

But if I try with `sudo` works well:
```shell
sudo nsenter -t <PID> -m -p true
```

I read https://unix.stackexchange.com/a/113561 and https://github.com/karelzak/util-linux/issues/315, and I didn't understand this behavior.

**Comment by karelzak** [comment]
For me it works, 

unprivileged in the namespace:
   ```unshare  --user --pid --mount-proc --fork /bin/bash```
and
   ```nsenter --preserve-credentials --user --mount --pid -t <pid>```

uid=0 in the namepsace:
  ```unshare  --map-root-user --pid --mount-proc --fork /bin/bash```
and 
  ```nsenter --preserve-credentials --user --mount --pid -t  <pid>```

**Comment by gustavotemple** [comment]
Thank you very much @karelzak !

**Comment by navytux** [comment]
@karelzak, I've tried to do what you suggesed in https://github.com/util-linux/util-linux/issues/1006#issuecomment-613359972, and, unfortunately, it does not work for me. Please find details in https://github.com/util-linux/util-linux/issues/1510.
