### ISSUE TITLE
column: provide support for terminal capabilities

### ISSUE THREAD

**Issue by jsamr** [karelzak/util-linux#1011]
Currently, there is no way to instruct `column` utility to adjust width computation with terminal capabilities. Example:

```bash
$ echo -e "$(tput smul)A$(tput rmul) B\nC D"
A B
C D
$ echo -e "$(tput smul)A$(tput rmul) B\nC D" | column --table
A  B
C                 D
```

When provided with `--term` option, `column` could use `terminfo` database to adjust the computation of column width accordingly.

EDIT:

Version tested: 2.35.1-1.1
Related issue #252 
Terminal emulator: urxvt, alacritty
Shell: bash 5.0.16

**Comment by jsamr** [comment]
By the way, it would be nice to have the feature consistently implemented across other utils such as `fmt`.

**Comment by karelzak** [comment]
It's libsmartcols bug. It uses by default calculation that assumes \x<hex> for all unprintable chars -- this feature is disabled for column(1), but  libsmartcols still uses it in many places.

The problem should be fixed now.
