### ISSUE TITLE
pylibmount mixes up error codes in UL_RaiseExc

### ISSUE THREAD

**Issue by devurandom** [karelzak/util-linux#1013]
The error codes and their description in `libmount.h` do not match what pylibmount outputs in `UL_RaiseExc` and `MNT_ERR_LOOPDEV` is missing entirely:

https://github.com/karelzak/util-linux/blob/b1bc5ae39ee6b90da53d7e17b1e6fbe0341433fa/libmount/src/libmount.h.in#L157-L180

https://github.com/karelzak/util-linux/blob/b1bc5ae39ee6b90da53d7e17b1e6fbe0341433fa/libmount/python/pylibmount.c#L60-L67

**Comment by karelzak** [comment]
Thanks for your report! Fixed now.

It would be nice to have someone who can help me with pylibmount -- unfortunately I have no enough time for this task... There are some others new features in libmount which are not available in Py binding yet.
