### ISSUE TITLE
agetty: cycling through baud rates causes the initial baud rate from --keep-baud to be lost

### ISSUE THREAD

**Issue by jjakob** [karelzak/util-linux#1025]
Take the typical systemd config:
```
/sbin/agetty -o '-p -- \\u' --keep-baud 115200,38400,9600 /dev/ttyS0 vt220
```
We set the kernel's console to 57600. The initial baud rate is correct and the console works. Then we cycle baud rates by sending a break character. As expected, the baud rate is switched.
But no matter how many times we send break (switch baud rates), we never get back to the initial speed of 57600.

I confirmed this by looking at the source of agetty - the --keep-baud rate isn't saved anywhere.

This is a significant issue, as using the systemd default settings, the user has to set a special baud rate twice: in the kernel's console and a systemd service override. It can be worked around by not adding any additional baud rates and keeping just --keep-baud or the fixed rate that we want (via the service override), but this means changing a setting in two places.
Otherwise, if agetty switches rates due to noise (in my case almost always when plugging in the cable) we can't get the initial baud rate console back.

Related systemd issue: https://github.com/systemd/systemd/issues/15611

**Comment by karelzak** [comment]
Well, it behaves as described in the man page ;-)

But yes, I see the pain. It should be simple to save the current speed to the end of the array of the speeds and re-use it later.

**Comment by karelzak** [comment]
Fixed (I hope). It would be nice if you can test it with your environment. I have no opportunity to do it right now. Thanks!
