### ISSUE TITLE
ionice: default to -c3

### ISSUE THREAD

**Issue by madduck** [karelzak/util-linux#1026]
I think it would make sense to default to `-c3`, rather than `-c2 -n4`, which seems the default for processes without ionice anyway. `-c2 -n7` might also make sense, but I think `-c3` is the best option when people just want to be nice in terms of I/O.

**Comment by karelzak** [comment]
Thanks for your report (and sorry for the delay ;-)). 

The best-effort scheduling class (-c2) and -n4 is what we use since the year 2005. I don't see a relevant reason to change this default after so many years, BE is also kernel default. We care about backward compatibility ;-)  

Closing.
