### ISSUE TITLE
Debian bugs

### ISSUE THREAD

**Issue by jidanni** [karelzak/util-linux#1027]
Downstream closed a lot of bugs, telling the reporter to file them again here,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=325230#8
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=718668#14
Alas, the reporter is now retired.

**Comment by karelzak** [comment]
Not sure about the fstab repeating lines (the 1st Debian report). We usually don't use any error messages for fstab if formatting is correct. I think the current semantic is pretty obvious and we do not need a change here.

The second issue should be fixed.

**Comment by jidanni** [comment]
@karelzak Actually I was hoping you would notice the complete list of bugs he closed was
- https://bugs.debian.org/314605
- https://bugs.debian.org/324852
- https://bugs.debian.org/325230
- https://bugs.debian.org/364178
- https://bugs.debian.org/372110
- https://bugs.debian.org/403098
- https://bugs.debian.org/430678
- https://bugs.debian.org/470097
- https://bugs.debian.org/493654
- https://bugs.debian.org/507084
- https://bugs.debian.org/508720
- https://bugs.debian.org/509941
- https://bugs.debian.org/647899
- https://bugs.debian.org/653648
- https://bugs.debian.org/682785
- https://bugs.debian.org/300960
- https://bugs.debian.org/718939
- https://bugs.debian.org/814184
- https://bugs.debian.org/870364
- https://bugs.debian.org/907536

And
- https://bugs.debian.org/718668
- https://bugs.debian.org/754523
- https://bugs.debian.org/756187
