### ISSUE TITLE
sfdisk 2.35.1 fails to read its dumped script

### ISSUE THREAD

**Issue by stevenshiau** [karelzak/util-linux#1031]
I encountered an issue when using sfdisk to create the partition table by reading its dumped script. 
The version I am using is from Debian Sid, 2.35.1-1.
How to reproduce it:
1. sfdisk -d /dev/sda > sda.sf
2. Clean the partition table of sda by:
    sgdisk -Z /dev/sda
3. sfdisk /dev/sda < sda.sf
It gave this error:
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> line 7: unsupported command

The line 7 in sda.sf is:
sector-size: 512

Attached please find the whole process about the mentioned commands.
If you need more info, please let me know. Thank you very much.

[sfdisk-issue.txt](https://github.com/karelzak/util-linux/files/4584329/sfdisk-issue.txt)

**Comment by stevenshiau** [comment]
Sorry, this is a duplicated report. I found it was fixed in #949

**Comment by karelzak** [comment]
Yes, it's already fixed in stable/v2.35 branch too. It seems we need v2.35.2 ASAP :-)

**Comment by stevenshiau** [comment]
Thank you very much.
