### ISSUE TITLE
Feature request: support MOTD dropin directories (motd.d)

### ISSUE THREAD

**Issue by rfairley** [karelzak/util-linux#1034]
For Fedora CoreOS (FCOS), it'd be useful to have the ability to drop dynamic (runtime) MOTD snippets into a directory for display upon login through a serial console (e.g. by `agetty --autologin` - see [1]).

There are a couple ways to approach this I see:

1. Add a new `MOTD_DIR` option for specifying a `:`-delimited list of directories, and simply display any file with a `.motd` prefix that exists in the given directories, reading in the order of directories given. I believe this would most naturally accompany the current configuration option `MOTD_FILE` in `/etc/login.defs`.

2. Align with lexicographically ordered overlay/dropin semantics like `pam_motd` does today through the `pam.d` `MOTD_DIR` option [2] [3].

    Like 1., add a new option `MOTD_DIR` to `login.defs`, but snippets in the earliest directory override snippets of the same filename of later directories. E.g., for `MOTD_DIR=/etc/motd.d:/run/motd.d`, where snippets at `/etc/motd.d/01_foo.motd` (A), `/run/motd.d/01_foo.motd` (B), and `/run/motd.d/02_bar.motd` (C) exist in the filesystem, the contents only from A and C would be shown as MOTD upon login, in order AC.

    The complication here is trying to align the `MOTD_FILE` option in `login` and `MOTD` option in `pam_motd`. Today in `pam_motd` **only the first** file found in the configured list in `pam.d` using the `MOTD` option is displayed, whereas in `login`, all MOTDs listed are displayed. If `login` were to be changed to adopt the same behavior, it would break existing systems that expect all listed files to be displayed. Since the feature to specify multiple files using `MOTD` in `pam.d` is relatively new, it may be acceptable to change the behaviour of `MOTD` in `pam.d` to display all files instead of just the first found file, to align with `login`. However for now, adding new functionality only for `MOTD_DIR` would be great.

With either approach implemented, distributions could include a config option in `login.defs` like `MOTD_DIR=/etc/motd.d:/run/motd.d:/usr/lib/motd.d` to use the layered host config/runtime/vendor MOTD snippet pattern (possibly make this a default if `MOTD_DIR` not specified).

Look forward to hear thoughts from others on either approach / alternatives.

[1] https://github.com/coreos/fedora-coreos-config/pull/371
[2] https://www.mankier.com/8/pam_motd
[3] https://github.com/linux-pam/linux-pam/issues/69

**Comment by karelzak** [comment]
$MOTD_DIR sounds good, or we can introduce $MOTH_PATH (like $PATH) and support directories as well as files in the path (e.g. MOTD_PATH="/etc/motd:/etc/motd.d:/run/motd.d" ...)

I'd like to keep this semantic pretty simple and without overriding -- it means always print all .motd files and use versionsort() to order the files in the directory. If more directories or files specified than print it in the specified order. 

If your intension is to use /run and some generators than the simple semantic is good enough and you can compose all the content in the right way in your generator and we do not need any complicated hardcoded semantic in login(1).

I don't plan to change the current login(1) *default behavior* ;-), but I don't see a problem adding a new option (for example MOTD_FIRSTONLY=<boolean>) to make it easy to reconfigure for compatibility with pam_motd.

**Comment by rfairley** [comment]
> $MOTD_DIR sounds good, or we can introduce $MOTH_PATH (like $PATH) and support directories as well as files in the path (e.g. MOTD_PATH="/etc/motd:/etc/motd.d:/run/motd.d" ...)
> 

$MOTD_PATH allowing files or directories sounds good as well! Either $MOTD_PATH or $MOTD_DIR as described would be suitable.

> I'd like to keep this semantic pretty simple and without overriding -- it means always print all .motd files and use versionsort() to order the files in the directory. If more directories or files specified than print it in the specified order.
> 

Keeping the simpler semantic, in this way described, sounds reasonable to me. This would suit our use of `/run`, to show some information generated during boot or later on (e.g. indicating a new upgrade available/in progress after a periodic check).

This shouldn't be a common case - but if users/administrators wished to silence/change the messages displayed as part of the distribution (through changing something in `/etc`), they'd still always have full control to change the directories in $MOTD_DIR/$MOTD_PATH in `/etc/login.defs`, which I think is enough reconfigurability without needing the overrides.

> 
> I don't plan to change the current login(1) _default behavior_ ;-), but I don't see a problem adding a new option (for example MOTD_FIRSTONLY=) to make it easy to reconfigure for compatibility with pam_motd.

+1 to keeping the default behaviour the same. Having an option MOTD_FIRSTONLY= or so sounds good!

**Comment by karelzak** [comment]
Maybe it would be enough to extend the current $MOTD_FILE to support also directories rather than introduce a new $MOTD_PATH configuration option.

**Comment by karelzak** [comment]
Implemented by commits: 5a528e2c6ff9735266fc2607c359e925b074bf2c, 9789d21a96be47fdd9b2c330b640e23254a22194 and 72b155ea6e25730d7c01d345cc2df269c2c47635

I have only extended MOTD_FILE= to support directories and added MOTD_FIRSTONLY= to improve compatibility with pam_motd. 

The last commit revets the default MOTD_FILE= change from the first commit :-(. It seems better for backward compatibility do not add any existing directory to the default as for example /etc/motd.d is probably already used by pam_motd and semantic may be different.

**Comment by rfairley** [comment]
Thanks @karelzak! These LGTM. Makes sense to stick with the same default files for backwards compatibility.

It is unfortunate that a mismatch still exists right now - pam_motd processes files specified with pam.d's MOTD= first, then dirs with MOTD_DIR= afterwards. The unified MOTD_FILE= here does provide more flexibility though, being able to interleave files and directories in the list to specify order.

Some modifications could possibly be done in pam_motd to further align the two - e.g. add a similar MOTD_FIRSTONLY= option, let MOTD= accept directories as well as files, and maybe a flag to turn overrides on/off. For now these are just papercuts though - the addition of this change will definitely suit the use case of generating MOTD fragments, and content can always be arranged to have equivalent configs between pam_motd and login. Thank you again for implementing this!
