### ISSUE TITLE
Fstatat is called with invalid flags in blkid__scan_dir

### ISSUE THREAD

**Issue by t11230** [karelzak/util-linux#1037]
Not sure if this issue impacts other users but I was unable to use libblkid to list block devices due to this bug.

It appears that during a refactor to remove the openat fallback functions `fstatat` was inadvertently called with the wrong `flags` argument. In the code before that change `fstat_at` was called with `1` passed to indicate that we shouldn't follow symlinks. `fstat_at` would then convert that into the correct flag (`AT_SYMLINK_NOFOLLOW`) for the real `fstatat`. Now `1` is incorrectly passed directly to `fstatat` which may return `EINVAL` and prevent recursive directory traversal during `blkid__scan_dir`.

Here is the offending line:
https://github.com/karelzak/util-linux/blob/4a52959d18ecd57a90680961fc1e3c57c34bf145/libblkid/src/devno.c#L148

**Comment by karelzak** [comment]
Oh, good catch. It seems for many users this bug has been hiden due to `if (dp->d_type == DT_LNK)`. Thanks for your report!
