### ISSUE TITLE
umount's bash completion doesn't escape spaces in mount point names

### ISSUE THREAD

**Issue by kraai** [karelzak/util-linux#1039]
umount's Bash tab completion doesn't escape spaces in mount points, so I have to manually escape them.

For example, if the mount point is `/media/kraai/Seagate Backup Plus Drive` and I type `umount /media` and then press tab, it is expanded to

```
umount /media/kraai/Seagate Backup Plus Drive
```

I expect it to behave link `ls`'s completion, which puts backslashes before the spaces.

This was originally reported as https://bugs.debian.org/923610.

**Comment by karelzak** [comment]
@kerolasa any suggestion? Patch? :-)

**Comment by karelzak** [comment]
https://github.com/karelzak/util-linux/pull/1045 :-)
