### ISSUE TITLE
Feature request: display multiple issue files/directories through agetty

### ISSUE THREAD

**Issue by rfairley** [karelzak/util-linux#1041]
In Fedora CoreOS (FCOS), similar to MOTD in #1034, we plan to generate runtime issue fragments to display through agetty, which should remain visible to the serial console before login at any time after boot - [an example](https://github.com/coreos/fedora-coreos-config/pull/344/files#diff-3c0868dd12c335aa63d723523b862190). Currently in FCOS this is handled through `console-login-helper-messages`, which [generates a combined runtime snippet](https://github.com/coreos/console-login-helper-messages/blob/efb7dad13b59b08dfac96e0c2e3d3ba605882122/usr/libexec/console-login-helper-messages/issuegen#L51-L55) and symlinks from `/etc/issue.d` for agetty to display. Ideally, we would like to write snippets directly to `/run/issue.d` without symlinking.

Currently in agetty, `/run/issue` and `/run/issue.d` are read as a backup if `/etc/issue` does not exist, but `--issue-file` will override and read the specified file or directory.

Could `--issue-file` be extended to accept a list of files/directories, which would all be displayed in the order given? That way, FCOS (and other distributions) could pass something like `agetty --issue-file=/etc/issue:/etc/issue.d:/run/issue:/run/issue.d:/usr/lib/issue:/usr/lib/issue.d` when setting up the serial console.

An alternative, which would also fit our use case, could be adding an `--issue-fallthrough` flag, which would display all of the default `{issue,issue.d}` files under `{/etc,/run,/usr/lib}`, i.e. not stopping if `/etc/issue` is found. Extending `--issue-file` to accept multiple directories may be a more natural addition though.

Passing either of the two proposed options would mean all of the snippets under `/run` and `/usr/lib` would be displayed in addition to under `/etc`, overriding the default behavior added in #828 where `/run/issue` is only shown as a backup for `/etc/issue`. Is there any reason that distributions generally should not do this (override the default "backup" behavior in this way)?

**Comment by karelzak** [comment]
The current agetty issue file semantic is complicated because "no file" has been standard way how to disable issue file printing at all (so, admins used "rm /etc/issue" rather than touch agetty setting...).

Extending --issue-file to accept multiple files/directories sounds good and it's possible to implement it in a backwardly compatible way.

**Comment by karelzak** [comment]
Implemented. It will be in v2.36.

**Comment by rfairley** [comment]
Thanks @karelzak!
