### ISSUE TITLE
sfdisk: "default" partition offset creates overlapping partitions

### ISSUE THREAD

**Issue by philhofer** [karelzak/util-linux#1044]
If a disk is formatted such that the first partition starts after the first available LBA, then any further partitions that begin at a "default" offset end up overlapping with the first partition:

For example:
```
$ truncate -s 1G img
$ sfdisk img <<EOF
8MiB 32MiB L -
- 256MiB L -
EOF
Checking that no-one is using this disk right now ... OK

Disk img: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Created a new DOS disklabel with disk identifier 0x1ba0d96e.
img1: Created a new partition 1 of type 'Linux' and of size 32 MiB.
img2: Created a new partition 2 of type 'Linux' and of size 256 MiB.
img3: Done.

New situation:
Disklabel type: dos
Disk identifier: 0x1ba0d96e

Device Boot Start    End Sectors  Size Id Type
img1        16384  81919   65536   32M 83 Linux
img2         2048 526335  524288  256M 83 Linux

Partition table entries are not in disk order.

The partition table has been altered.
Syncing disks.
```

(I first encountered this situation when using `sfdisk --append`, which I expected to append a partition after the last used LBA, but ended up creating a partition that encompassed my whole disk, leading to some super fun disk corruption.)

Is this the desired behavior?

(This is sfdisk version 2.35.1, built from source via the 2.35 util-linux release tarball on gcc 9.3.0.)

**Comment by philhofer** [comment]
I'll add that I *do* get the expected behavior I expected as long as the first partition starts on a default boundary:

```
$ truncate -s 1G img
$ sfdisk img <<EOF
- 32MiB L -
- 256MiB L -
EOF
Checking that no-one is using this disk right now ... OK

Disk img: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Created a new DOS disklabel with disk identifier 0x3d26146f.
img1: Created a new partition 1 of type 'Linux' and of size 32 MiB.
img2: Created a new partition 2 of type 'Linux' and of size 256 MiB.
img3: Done.

New situation:
Disklabel type: dos
Disk identifier: 0x3d26146f

Device Boot Start    End Sectors  Size Id Type
img1         2048  67583   65536   32M 83 Linux
img2        67584 591871  524288  256M 83 Linux

The partition table has been altered.
Syncing disks.
```

**Comment by karelzak** [comment]
Well, the default start is defined as the first free space, but this behavior is pretty user-unfriendly. You're right that libfdisk should be more smart and a select area where is possible to create the partition in specified size.

Fixed in git tree. I need to add a regression test for this use-case.

**Comment by rwmjones** [comment]
The fix for this has caused the following regression:

https://bugzilla.redhat.com/show_bug.cgi?id=1860461
