### ISSUE TITLE
agetty: typing ^C at login prompt causes agetty to hang for 10 seconds and die

### ISSUE THREAD

**Issue by danc86** [karelzak/util-linux#1046]
With agetty 2.32.1 and earlier, ^C at the login prompt is ignored. I noticed when upgrading to agetty 2.34, typing ^C now causes agetty to stop responding for 10 seconds and then it dies (and gets restarted by system and a new login prompt is printed).

It logs this message:

```
agetty[46048]: ttyS0: invalid character 0x3 in login name
```

I think the cause is commit 5de9751997cf490088f62f41fd92be57cf7ceea4. Previously the `!isprint(ascval)` condition would have caused control characters like ^C (\x03) to be discarded, whereas now it falls through to trying to decode it as part of a UTF-8 sequence, and then fails.

A patch like this seems to restore the old behaviour:

```
diff --git a/term-utils/agetty.c b/term-utils/agetty.c
index 43dbd6dea..7dd573431 100644
--- a/term-utils/agetty.c
+++ b/term-utils/agetty.c
@@ -2174,6 +2174,9 @@ static char *get_logname(struct issue *ie, struct options *op, struct termios *t
                                break;
                        case CTL('D'):
                                exit(EXIT_SUCCESS);
+                       case CTL('C'):
+                               /* Ignore it. */
+                               break;
                        default:
                                if ((size_t)(bp - logname) >= sizeof(logname) - 1)
                                        log_err(_("%s: input overrun"), op->tty);
```

but I'm not sure if that is the best solution. It seems like the previous version was ignoring ^C only by accident, since there was no case to handle it explicitly. A user might actually expect ^C to behave more like ^U or perhaps to re-print the login prompt. It would be interesting to compare against other getty implementations.

**Comment by karelzak** [comment]
I have applied your sugesstion -- commit 88aefd4c461713977f2f6f86c4a0209f5925e5b6.

IMHO it's good enough for now. We can change it later if we will have some idea what is the best for users. Thanks!

**Comment by Bogdan107** [comment]
I have proble with `Ctrl-C` combination in login line in `util-linux-2.37.1`.
Bug registered firstly in Gentoo bug tracking system with number [804972](https://bugs.gentoo.org/804972).

**Incorrect login name, that remains on the display, can help hackers penetrate the system.**

#### Reproducible:
Always

#### Steps to Reproduce:
1. Switch to tty2 by pressing Ctrl-Alt-F2.
2. See login prompt.
3. Put incorrect login name.
4. Press Ctrl-C combination (while login name not confirmed by `Enter` button).

#### Actual Results:  
The login / password request is not resets, the displayed login remains on the display.

#### Expected Results:  
Login/password lines must be cleared by calling Ctrl-C combination.
Login prompt must be reseted fully, not just adding new login prompt to new line at the end of display buffer (as in qingy).

#### Additional info
qingy resets the login prompt by Ctrl-C combination from login, but not resets by password line.
And qingy resets prompt from login by adding new prompt to the end of buffer - e.g. not clear display before putting new prompt, and previous login still stay on display.
But qingy resets login prompt so quickly, that pressed Ctrl-C combination may call qingy trigger, which block tty after some number of prompt resettings.

Please, also add some timeout after resetting terminal, before enabling read info from stdin. For example - this timeout may be 333ms (1/3 of second) - it is enough to delay before entering a new login and comfort for human, but not enough to overload the system.
