### ISSUE TITLE
Configure from tarball archive give version=Unknown

### ISSUE THREAD

**Issue by farox1** [karelzak/util-linux#1049]
Hi
when i do ./autogen.sh and ./configure from a tarball archive (util-linux-2.33 in my case)  it did goes to the end without errors but the version number of the package is recognised as Unknown.
I can't use git on my Linux machine ( a game handheld).
Maybe there is some way to obtain this but i'm not expert.
Here is the log of configure
[configure_log.txt](https://github.com/karelzak/util-linux/files/4674020/configure_log.txt)

Let me know if you need more infos.

Thanks

**Comment by karelzak** [comment]
It's usually unnecessary to use ./autogen.sh for tarballs (you need it only if you modify package build system).

Anyway, the version is stored in the .tarball-version file. Not sure way, but it seems the file is missing or unreadable. You can try `echo "2.33" > .tarball-version` to fix it.

**Comment by farox1** [comment]
Thanks a lot for you reply.
 The .tarball-version file is not on the archive i checked many of them.
 After i generated it with echo "2.33" > .tarball-version on the main directory,
re-runned  ./configure but the version is always Unknown.
I tested creating a .version file but is the same.

**Comment by farox1** [comment]
Ok i must redo ./autogen.sh and ./configure after creating the ./tarball-version file to obtain a correct version number.
You should consider add this infos to the read me for other people who need to configure the package from a tarball archive.

Thanks a lot for your help.
