### ISSUE TITLE
sfdisk -V

### ISSUE THREAD

**Issue by Smi1984** [karelzak/util-linux#1051]
Hello,
I've updated my ubuntu from 14.04 to 20.04. And the behavior of the code has change quite a lot. 
I have an application that calls sfdisk -V in order to check if it is ok or not the partition table created. What I found that in the old versions I used to have an ok message (version 2.20), and in the 2.34 version i don't receive it.

I've passed of receiving this message:

```
Warning: no primary partition is marked bootable (active)
This does not matter for LILO, but the DOS MBR will not boot this disk.
/dev/sdb: OK
```

To this one:

```
/dev/sda:
Remaining 2382844 unallocated 512-byte sectors.
```

The partition table that I have to create, doesn't allocate the whole memory (i can not change it), but the partitions are created ok. Can be this message considered as ok? 

Sorry if this message doesn't go here, but i didn't where to send it. If it is a wrong place i can remove it if you can tell me where to send it.

Thanks for your time.

**Comment by karelzak** [comment]
The partition table is OK ;-)

Anyway, you're right that the output should be more evident for users. Fixed. 

The next version will report:
```
./sfdisk --verify /dev/sdc
/dev/sdc:
No errors detected.
```
or
`<N> errors detected.` in case of error.

Thanks for your report!
