### ISSUE TITLE
login(1) "-f" wrong man page description

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#1053]
>       -f     Used to skip a second login authentication.  This specifically
>              does not work for root, and does not appear to work well under
>              Linux.

This does not seem accurate. `aggety` itself passes `-f username` to `login` when called with `--autologin username`. And, at least in my Arch Linux systems, it works fine for root.

**Comment by karelzak** [comment]
Good point. Fixed. Thanks for your report!

**Comment by marcosfrm** [comment]
https://github.com/karelzak/util-linux/blob/f0833edc1204bd039d364710bb7700a747270330/login-utils/login.c#L1181

https://github.com/karelzak/util-linux/blob/f0833edc1204bd039d364710bb7700a747270330/login-utils/login.c#L1245

PAM is kind of magic to me... what's about this "second" authentication?

**Comment by marcosfrm** [comment]
Another thing... man page and command help output assume `-f` must be before the user name. The code does not enforce this.

**Comment by karelzak** [comment]
> https://github.com/karelzak/util-linux/blob/f0833edc1204bd039d364710bb7700a747270330/login-utils/login.c#L1181
> 
> https://github.com/karelzak/util-linux/blob/f0833edc1204bd039d364710bb7700a747270330/login-utils/login.c#L1245
> 
> PAM is kind of magic to me... what's about this "second" authentication?

Ah, I missed that. Fixed.

**Comment by karelzak** [comment]
> Another thing... man page and command help output assume `-f` must be before the user name. The > code does not enforce this.

You can also read it as "username" has to be specified if -f is used :-) I think it's good enough.
