### ISSUE TITLE
Can't get the files while using the formated disc on windows

### ISSUE THREAD

**Issue by runningsnaile** [karelzak/util-linux#1056]
Hello, erveryone
I have a case as below steps, hope can get your comments, thanks.

1) I have a new empty disc and set it as "like a usb flash drive" on windows, after that, i copy 2 files and can get the details on linux system.

2) I format the disc on windows with udf 2.01 and copy the same 2 files on this disk. but unfortunately, i can't get the file details on linux system anymore.

3) I degrad the blk lib from libblkid1_2.33.1 to libblkid1_2.27-1, and then i can get the udf files now.

so, i think there may be any issue caused this case. please verify this case, any comments are appreciated, thanks.

--- new empty disc and set it as "like a usb flash drive":
![flash-disc](https://user-images.githubusercontent.com/30650195/84374506-984c3d00-abcd-11ea-868a-50c8182048b2.png)

--- two files on this disc:
![flash-disc_one_time](https://user-images.githubusercontent.com/30650195/84374639-d0ec1680-abcd-11ea-9e6e-187437d8aa4f.png)

--- format the disc on windows:
![format](https://user-images.githubusercontent.com/30650195/84374641-d0ec1680-abcd-11ea-87ff-7fd9aeb1e400.png)

--- can' get the details any more on linux with libblkid1_2.33.1 :
![image](https://user-images.githubusercontent.com/30650195/84376015-ebbf8a80-abcf-11ea-8a34-a544042e86c9.png)

**Comment by HeroesLoveToRoujiamo** [comment]
I think this problem is the same as #1161 and can be turned off.

**Comment by karelzak** [comment]
Thanks!
