### ISSUE TITLE
Correct changelog URL

### ISSUE THREAD

**Issue by kurthindenburg** [karelzak/util-linux#1061]
The URL in the ChangeLog file doesn't work.  I think it needs to be "https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/log?h=v2.35.2"

**Comment by karelzak** [comment]
Which file do you mean? I don't see any URL in the https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.36/v2.36-rc1-ChangeLog

**Comment by kurthindenburg** [comment]
% cat util-linux-2.35.2/ChangeLog
See version control history.

https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/log;h=2.35.2

**Comment by karelzak** [comment]
Ah, this file ;-) (we have it without version in the git-tree and I do not use tarball)

Anyway, it's already fixed by commit 595e901b5c9d666917eebca759dff15f96d70aa9. The bugfix will be in v2.36.

Thanks for your feedback.
