### ISSUE TITLE
Automatic root filesystem detection in fstab file

### ISSUE THREAD

**Issue by adam4235** [karelzak/util-linux#1064]
It would be convenient if there were a way in fstab to specify "the current partition", i.e. the one that the fstab file is located on.

The motivation for this is that to copy your Linux installation to from one drive to another, it's currently necessary to update the UUID of the root partition in fstab to that of the new drive.  If it could figure it out automatically, then that would be one less step needed to copy the OS to another drive.  Although this is often treated as something only an "advanced user" would do, it seems to me that wanting to move the OS to a new drive is something that's pretty common - for example, because the old drive is having problems, or because the user has a newer, faster drive (such as an SSD).

I notice that if I comment everything in fstab, my system still boots, but mounts the root partition read-only.  This behaviour is fine, and tells me that the UUID doesn't need to be in fstab for the system to be able to find the root partition (I assume because grub already specifies it).

I'd suggest allowing the first field of an entry to be a special string, perhaps a /, so it could look something like this:

`/ / ext4 defaults`

Of course there are cases where the fstab isn't on the root partition (e.g. if /etc is mounted on a separate partition).  That's fine - for complicated partition schemes like that the user would simply have to use the existing behaviour of specifying the UUID, which would of course still be available.

**Comment by mator** [comment]
if I understand you correctly, you could try to use `LABEL=/` instead of `UUID`

**Comment by adam4235** [comment]
I think there would then still be an extra thing for the user to do when copying their filesystem to a new drive, and it would be about as advanced a task as the current one (probably more advanced, since "A device or partition must not be mounted before attempting to label them").  If distributions were to set a label such as "Debian" on the drive and boot the root filesystem based on that label, then copying the filesystem to a new drive without installing the distribution again would mean that the label on the new drive wouldn't get set, unless the user sets it manually, right?

Remember my idea is to allow a Linux distribution to set up its root filesystem in such a way that somebody could copy it to a new drive without changing its contents.  I.e. to make it agnostic of the hardware on which it's stored.

**Comment by marcosfrm** [comment]
Use PARTUUID?

It is supported by the kernel, libblkid and GRUB even on MBR partitioned disks:

https://github.com/torvalds/linux/commit/d33b98fc82b0908e91fb05ae081acaed7323f9d2 (3.8)
https://github.com/karelzak/util-linux/commit/d67cc2889a0527b26d7bb8c76f2acac46751d673 (2.24)
http://git.savannah.gnu.org/cgit/grub.git/commit/?id=51be3372ec8ba07ef68a409956ea0eefa89fe7c5 (2.04)

**Comment by adam4235** [comment]
Same deal - if I copied the filesystem to a new drive, I'd have to update the PARTUUID in fstab, wouldn't I?

**Comment by marcosfrm** [comment]
How exactly are you cloning the disk?

**Comment by mator** [comment]
i mean cloning the disk is "some" operation anyway, how hard it could be to add a command to label partition or changing fstab with proper uuid at the end of cloning/copy....

**Comment by adam4235** [comment]
I want to clone the disk by copying the files, with e.g. cp.

I think maybe you meant that by cloning the partition table too, then the PARTUUID would also be copied?  However, I would see that as problematic.  A PARTUUID is supposed to be unique, so having another disk with the same partition PARTUUID could cause problems if somebody then later plugs both those hard drives into the same computer.

It's not hard for me to do an extra thing at the end of the copy.  But I'm thinking about others.  As I mentioned, this is a common operation that ordinary users, who perhaps aren't used to using the command line at all, may well want to do.  It's reasonable for a naive person to assume that moving their OS to a new hard drive would mean copying the files to it.  If there's one less extra advanced step for them to do after doing so, it would make it that much easier for them, and that much more likely that they won't give up on Linux as being something for more advanced users.  It's about automating things, and letting the computer figure things out so the user can focus on their applications instead of configuration of the computer itself.

**Comment by mator** [comment]
besides of a simple file copy, you will need to install a boot loader to a new disk anyway...

**Comment by marcosfrm** [comment]
https://systemd.io/DISCOVERABLE_PARTITIONS/

**Comment by adam4235** [comment]
Thanks - it looks like the "Discoverable Partitions Specification" should pretty much solve this problem.  I wasn't aware of it.  It looks like it does require EFI hardware, and also requires the use of systemd, which I read some people don't want to use.  So the advantage of still adding this option to the fstab would be to remove those restrictions.  However, since EFI seems to be the way of the future, I'm OK with not bothering to do so.

**Comment by karelzak** [comment]
> I think maybe you meant that by cloning the partition table too, then the PARTUUID would also be copied? However, I would see that as problematic. A PARTUUID is supposed to be unique, so having another disk with the same partition PARTUUID could cause problems if somebody then later plugs both those hard drives into the same computer.

Always when you clone (copy byte to byte the block device) then you get exactly the same disk, including LABELs, UUIDs, and PARTUUIDs. All these identifiers should be unique otherwise the result is a mess. I don't think any extra feature may help you, the only way is to fix the identifiers.

Ad the original request -- mount(8)/fstab goes to late to the party when you boot your system. The root partition is usually probed and mounted by initramfs (etc.). The fstab is used later to remount according to flags in the file.

Conclusion, don't use two identical disks in the same system -- after cloning, do your homework and change all the identifiers.
