### ISSUE TITLE
Please could sort have a new option to pass through header line(s)

### ISSUE THREAD

**Issue by Fustbariclation** [karelzak/util-linux#1067]
As an enhancement, could sort have an option to ignore, and pass through the header line(s)?

The -l option, with a number would do the trick. For example:

`$ cat fred

header 1

header 2

oranges

apples

grapes`

`$ sort -l 2 <fred

header 1

header 2

apples

grapes

oranges`

**Comment by karelzak** [comment]
sort(1) is from the coreutils package, no util-linux.
