### ISSUE TITLE
A couple of compiler warnings

### ISSUE THREAD

**Issue by evverx** [karelzak/util-linux#1083]
GCC-10 is complaining about [an unaligned pointer value](https://travis-ci.org/github/karelzak/util-linux/jobs/703189200)
```
sys-utils/blkzone.c: In function ‘blkzone_report’:
sys-utils/blkzone.c:259:35: warning: taking address of packed member of ‘struct blk_zone_report’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  259 |    const struct blk_zone *entry = &zi->zones[i];
      |             
```

clang-10 is complaining about [a tautological-type-limit-compare](https://travis-ci.org/github/karelzak/util-linux/jobs/703189203)
```
libblkid/src/llseek.c:101:14: warning: result of comparison 'blkid_loff_t' (aka 'long') < -9223372036854775808 is always false [-Wtautological-type-limit-compare]
            (offset < ((blkid_loff_t) 1 << ((sizeof(off_t)*8) -1))))
             ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

As an aside, I wonder why `-Werror` isn't passed on Travis CI? I think `-Wall` and `-Wextra` don't make much sense without `-Werror`.

**Comment by karelzak** [comment]
* I do not see the warning about packed stuff with kernel-headers-5.6.18-200, gcc-10.1.1 and -Waddress-of-packed-member, and I'm not sure why compiler believes that the struct is packed (it's nowhere marked as packed).

* I'll remove the file libblkid/src/llseek.c, it's unnecessary legacy.

I don't think use blindly -Werror (=make all warnings into errors) is a good idea for project like util-linux. The warnings are pretty common due to random library versions, and bugs -- compiler is not always right.

**Comment by evverx** [comment]
> I'm not sure why compiler believes that the struct is packed (it's nowhere marked as packed)

It was packed before https://github.com/torvalds/linux/commit/b3e7e7d2d668de0102264302a4d10dd9d4438a42 was merged. That commit has never been (and probably will never be) backported on Ubuntu Bionic (where 4.15 is used) so here's what blk_zone_report looks like there
```
struct blk_zone_report {
        __u64           sector;
        __u32           nr_zones;
        __u8            reserved[4];
        struct blk_zone zones[0];
} __packed;
```

> I don't think use blindly -Werror (=make all warnings into errors) is a good idea for project like util-linux

Unfortunately, `-Werror` is the only way to catch warnings automatically without looking at all the logs all the stages on Travis CI produce.

> The warnings are pretty common due to random library versions, and bugs

As far as I can see, the codebase is pretty solid in the sense that `gcc` and `clang` couldn't find a lot of things to complain about.

> compiler is not always right

Can't argue with that :-) Though false positives can easily be ignored by turning off noisy checks globally or by wrapping code in something like
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Waddress-of-packed-member"
...
#pragma GCC diagnostic pop
```
I agree it looks ugly but it makes it clear that it has been looked into and is ignored on purpose. Another upside is that nobody is going to report the same warning over and over again.

**Comment by karelzak** [comment]
> ```
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Waddress-of-packed-member"
> ...
> #pragma GCC diagnostic pop
> ```

Well, it's not so ugly. I think we can use it especially for a temporary issue like this "packed" problem. What about clang? 

OK, we can try to enable -Werror, but it would be nice to have it only for travis and optionally for other users. I really don't want to use it as default in distros etc. (it's nothing unusual that people try cross-compile util-linux, non-Linux OS, non-glibc, etc.)

 I'll add --enable-werror to configure.ac (or do you have e better idea?).

**Comment by evverx** [comment]
> What about clang?

clang can handle this: https://clang.llvm.org/docs/UsersManual.html#pragma-gcc-diagnostic.

> OK, we can try to enable -Werror, but it would be nice to have it only for travis and optionally for other users. I really don't want to use it as default in distros etc. (it's nothing unusual that people try cross-compile util-linux, non-Linux OS, non-glibc, etc.)

Agreed. I wouldn't advocate for turning it on everywhere :-)

> I'll add --enable-werror to configure.ac (or do you have e better idea?).

I'd pass it via CFLAGS probably but looking at `configure.ac` and `--enable-asan` I think it seems `--enable-werror` would be more consistent.

**Comment by karelzak** [comment]
OK, --enable-werror implemented,  you can use it for CI (probably also with the #pragma) patch.
