### ISSUE TITLE
udisks exfat label test failure with util-linux 2.5

### ISSUE THREAD

**Issue by seb128** [karelzak/util-linux#1085]
The udisks exfat set-label test started failing in Ubuntu after the new util-linux 2.5 serie landed, initially reported to https://github.com/storaged-project/udisks/issues/784 but it sounds like it could be an issue with util-linux...

```
=====================================================================
FAIL: test_exfat (__main__.FS)
fs: exFAT
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 716, in test_exfat
    self._do_fs_check('exfat')
  File "src/tests/integration-test", line 873, in _do_fs_check
    self._do_cli_check(fs_type, 'test%stst' % fs_type)
  File "src/tests/integration-test", line 905, in _do_cli_check
    self.assertEqual(l, label or '')
AssertionError: 'testexfatts' != 'testexfattst'
- testexfatts
+ testexfattst
?            +
```

Checking the util-linux upstream commits this one sounds like it could have to do with the issue
https://github.com/karelzak/util-linux/commit/fb4ed8a5
'According to released exfat specification, label is only 22 bytes long.'

Normal ascii chars should only take 1 byte though right?

**Comment by seb128** [comment]
The udisks tests log is available there
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/amd64/u/udisks2/20200629_170414_54dfb@/log.gz

Trying to workaround by changing the test to use shorter label didn't resolve the issue
http://launchpadlibrarian.net/486534732/udisks2_2.9.0-1ubuntu1_2.9.0-1ubuntu2.diff.gz

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/amd64/u/udisks2/20200630_134953_622b7@/log.gz

```
AssertionError: 'n"a\\m\\"eexf' != 'n"a\\m\\"eexfat'
- n"a\m\"eexf
+ n"a\m\"eexfat
```

so it does sound like something weird is going on there, the test is basically calling mkfs then reading the label on the partition
https://github.com/storaged-project/udisks/blob/master/src/tests/integration-test#L306

**Comment by karelzak** [comment]
Yes, it's the commit fb4ed8a (revert fixes the problem). mkfs.exfat uses 15 bytes and in this case, it sets exfat_entry_label->length to 30, but we have restricted it to 22 bytes. Smaller labels work for me:

```
# mkfs.exfat -n 1234567 /dev/sdc1 &> /dev/null
# ./blkid -p /dev/sdc1 -s LABEL
/dev/sdc1: LABEL="1234567"

# mkfs.exfat -n 123456789x1 /dev/sdc1 &> /dev/null
# ./blkid -p /dev/sdc1 -s LABEL
/dev/sdc1: LABEL="123456789x1"

# mkfs.exfat -n 123456789x12 /dev/sdc1 &> /dev/null
# ./blkid -p /dev/sdc1 -s LABEL
/dev/sdc1: LABEL="123456789x1"  <-------- !!!

# mkfs.exfat -n 123456789x12345 /dev/sdc1 &> /dev/null
# ./blkid -p /dev/sdc1 -s LABEL
/dev/sdc1: LABEL="123456789x1"   <----- !!!
```
@pali any idea?

**Comment by seb128** [comment]
(I've confirmed with a revert of that commit also that it fixes the udisk tests)

**Comment by seb128** [comment]
The length topic is discussed on e.g https://superuser.com/questions/1206131/exfat-volume-label-length-11-or-15-characters

So limiting the label to 11 chars seems right, shouldn't the tool warn when the label is too long and truncated though?

**Comment by pali** [comment]
Per exFAT documentation, section 7.3 Volume Label Directory Entry, _VolumeLabel_ is 22 bytes long and stored in UTF-16. Therefore maximal length of volume label on exFAT is 11 UNICODE code points. Which also means that you cannot store more then 11 7-bit ASCII characters in exFAT volume label.

https://docs.microsoft.com/en-us/windows/win32/fileio/exfat-specification#table-26-volume-label-directoryentry-structure
https://docs.microsoft.com/en-us/windows/win32/fileio/exfat-specification#733-volumelabel-field

**Comment by karelzak** [comment]
exfat-utils (mkfs.exfat) assumes 30 bytes (le16_t are 2 bytes):

https://github.com/relan/exfat/blob/master/libexfat/exfatfs.h
```
#define EXFAT_ENAME_MAX 15
struct exfat_entry_label			/* volume label */
{
	uint8_t type;					/* EXFAT_ENTRY_LABEL */
	uint8_t length;					/* number of characters */
	le16_t name[EXFAT_ENAME_MAX];	/* in UTF-16LE */
}
```
https://github.com/relan/exfat/blob/master/libexfat/byteorder.h
```
typedef struct { uint16_t __u16; } le16_t;
```

**Comment by pali** [comment]
> exfat-utils (mkfs.exfat) assumes 30 bytes (le16_t are 2 bytes):

So it violates specification and also is incompatible with MS Windows implementation.

**Comment by pali** [comment]
exfatprogs assumes 22 bytes (11 __le16 members):
https://github.com/exfatprogs/exfatprogs/blob/50d96810809777092297d26ce9fca1b4a0d8e49e/include/exfat_ondisk.h#L145-L155

**Comment by karelzak** [comment]
OK, I'll report it to exfat project.

**Comment by karelzak** [comment]
@seb128 it seems you need to update udisk tests to use shorter labels. 

I guess we can close this issue as it is not libblkid issue.

**Comment by seb128** [comment]
@karelzak right, I tried that earlier but it gave some corrupted result for some reason, it does seem an issue on the udisk side though

I will let you close the report if you think it's the right outcome, I think it's right to not set a label longer than the specification allows but there is an argument for reading the 30 bytes and reflecting the 'real' label (even if it's longer than what the specification allows)

Thanks @karelzak and @pali for the replies!

**Comment by pali** [comment]
> but there is an argument for reading the 30 bytes and reflecting the 'real' label (even if it's longer than what the specification allows)

Problem is that with above approach you are trying to read additional 8 bytes and then trying to interpret them as part of volume label. But specification says that these 8 bytes are reserved and MS can use it for any other purpose. So if you set it to non-zero values, you may set something undocumented or currently unspecified which may cause problems. Also if MS is already using it for some purpose (or would start using it) then all these tools which read them as label would/could report some bogus values in volume label.

So we should follow specification and implement filesystem according to specification. Specification is there to ensure interoperability between different implementation. And if every implementation violates it, it does not make sense to have specification...

... I know that e.g. even Microsoft violates their own FAT32/VFAT specification, so here is better to follow Microsoft reference fastfat.sys FAT32/VFAT implementation.

So if we find out that in exFAT specification are similar problems which also Microsoft implements differently in their reference exfat.sys implementation, we can "adjust" also implementations on linux/userspace. But such thing needs to be checked and verified.

Now it can be "observed" that volume label on exfat is really limited to 11 UNICODE code points even on MS implementation, so I would really propose to stick with this.

**Comment by seb128** [comment]
Alright, your argument is convincing enough for me, thanks again for taking the time to comment here! I'm closing the bug now

**Comment by seb128** [comment]
just as a follow up, setting a shorter label does fix the udisk test, I got confused because it's failing in another test now which set names to escape (explaining the weird chars mentioned before)
