### ISSUE TITLE
sfdisk use of type=U/S/L, etc Fails with Invalid argument

### ISSUE THREAD

**Issue by rickyrockrat** [karelzak/util-linux#1113]
2.33 exhibits this issue. 2.25.2 did not. When using sfdisk as a script, the script is broken between 2.25.2 and 2.33.
In 2.25.2, this works:
label:gpt
/dev/sdc1 : start=2048, size=204800, type=U, bootable
In 2.33, it errors out with:
Old situation:

>>> Script header accepted.
>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: F8FB2DBB-511C-1A4B-8F28-F86253B108AA).
/dev/sdc1: Failed to add #1 partition: Invalid argument
Leaving.

2.33 behaviour both breaks old scripts and is not consistent with the man page. 
The issue is twofold: 
One, the message printed 'Invalid argument' is surely a copy of 'something went wrong', i.e. completely useless. 
The second is that the behaviour does not match the man page. In string_to_guid, it never handles the single-letter cases. 
It should be possible to alter string_to_guid to look for a string of length 1, and call gpt_entry_set_uuid to obtain a GUID such that this is compatible with the original sfdisk and the man page.

**Comment by karelzak** [comment]
Please. update. It's implemented by commit 08474fde6669d89f5b77653ba9d378fc16e19903 since v2.35.
