### ISSUE TITLE
column: limit amount of columns

### ISSUE THREAD

**Issue by LadyAleena** [karelzak/util-linux#1124]
In column, it would be nice if I could limit the amount of columns, especially when the last field may include the separator character.

Example: When I use column with `grep`, I would use `:` as the separator. However, what I am looking for may include `:`, so I would want to delimit the amount of columns to 2 or 3.

Please consider it?

**Comment by karelzak** [comment]
You can hide unwanted columns by "--table-hide [list]" where the [list] is a column number or name:
```
# echo -e "A B C D\nA B C D" | column --table --table-hide 4
A  B  C
A  B  C
```
or all unnamed columns by ""--table-hide -"
```
$ echo -e "A B C D\nA B C D" | column --table --table-columns one,two,three --table-hide -
one  two  three
A    B    C
A    B    C
```
(use --table-noheadings to avoid the header line).

**Comment by LadyAleena** [comment]
I do not want to hide columns, but I want to limit how many that are created.

For example, I often use `grep` to find where I am using certain Perl modules. `grep` separates its fields with `:`. Perl modules also use `:` as a separator. So when I columnize the output of `grep`, not only are the fields created by `grep` separated into columns, so are my Perl module names.

Here is example output from `grep` without columns:
```
me@office:~/site$ grep -r --include=*.p[lm] 'use Util::Sort' | sort
Fandom/Crossovers/timeline.pl:use Util::Sort     qw(article_sort);
Movies/index.pl:use Util::Sort     qw(article_sort);
Role_playing/Magic_items/spell_scrolls.pl:use Util::Sort     qw(article_sort);
Role_playing/Player_characters/Spellbooks.pl:use Util::Sort     qw(name_sort);
files/lib/Page/Menu.pm:use Util::Sort     qw(article_sort name_sort);
files/lib/Page/People.pm:use Util::Sort     qw(name_sort);
files/lib/Page/Story/Magic/MagicItem.pm:use Util::Sort     qw(name_sort);
files/lib/Util/Data.pm:use Util::Sort qw(article_sort name_sort);
working/Role_playing/Player_characters/index.pl:use Util::Sort     qw(name_sort);
```
Here is what column does.
```
me@office:~/site$ grep -r --include=*.p[lm] 'use Util::Sort' | sort | column -t -s ':'
Fandom/Crossovers/timeline.pl                    use Util  Sort     qw(article_sort);
Movies/index.pl                                  use Util  Sort     qw(article_sort);
Role_playing/Magic_items/spell_scrolls.pl        use Util  Sort     qw(article_sort);
Role_playing/Player_characters/Spellbooks.pl     use Util  Sort     qw(name_sort);
files/lib/Page/Menu.pm                           use Util  Sort     qw(article_sort name_sort);
files/lib/Page/People.pm                         use Util  Sort     qw(name_sort);
files/lib/Page/Story/Magic/MagicItem.pm          use Util  Sort     qw(name_sort);
files/lib/Util/Data.pm                           use Util  Sort qw(article_sort name_sort);
working/Role_playing/Player_characters/index.pl  use Util  Sort     qw(name_sort);
```
So instead of getting the two columns I wanted, I got three. While I understand how the items I wanted are lined up nicely, visually, I lost the `::` in the module names. Here is what I would prefer.
```
me@office:~/site$ grep -r --include=*.p[lm] 'use Util::Sort' | sort | column -t -s ':'
Fandom/Crossovers/timeline.pl                    use Util::Sort     qw(article_sort);
Movies/index.pl                                  use Util::Sort     qw(article_sort);
Role_playing/Magic_items/spell_scrolls.pl        use Util::Sort     qw(article_sort);
Role_playing/Player_characters/Spellbooks.pl     use Util::Sort     qw(name_sort);
files/lib/Page/Menu.pm                           use Util::Sort     qw(article_sort name_sort);
files/lib/Page/People.pm                         use Util::Sort     qw(name_sort);
files/lib/Page/Story/Magic/MagicItem.pm          use Util::Sort     qw(name_sort);
files/lib/Util/Data.pm                           use Util::Sort qw(article_sort name_sort);
working/Role_playing/Player_characters/index.pl  use Util::Sort     qw(name_sort);
```
So, I would need a way to limit the column creation to `2`. Maybe add `-l` to limit the amount of times line is split into columns?

**Comment by kerolasa** [comment]
Wouldn't it be easier to temporarily replace the characters you don't want to use as a separator to something else, and after getting a table change them back?

```
grep -r --include=*.p[lm] 'use Util::Sort'  | sed 's/::/¬¬/' | column -t -s : | sed 's/¬¬/::/'
```

**Comment by LadyAleena** [comment]
I could try that for now, but in the future, it would be nice if I didn't have to do that.

**Comment by karelzak** [comment]
It seems your problem is not the number of columns, but you want to use "::" as non-separator when ":" is interpreted as a separator ...

**Comment by LadyAleena** [comment]
This could be a problem no matter what pattern a person wants to use as a separator.

I keep thinking about Perl's `split` function that allows users to set a limit on how many times a string can be split.
```perl
split(/:/, $line, "2");
```
So, I just want 2 columns (unless I add line numbers to my grep, then it is 3).

Is this something difficult to add?

**Comment by karelzak** [comment]
Ah, I have read your examples in a bad way. I undestand now.

**Comment by karelzak** [comment]
OK, implemented. Example:
```
$ echo -e 'AAA:BBB:CCC:DDD\n' | column -t -s ':'
AAA  BBB  CCC  DDD
    
$ echo -e 'AAA:BBB:CCC:DDD\n' | column -t -s ':' -l 2
AAA  BBB:CCC:DDD
    
$ echo -e 'AAA:BBB:CCC:DDD\n' | column -t -s ':' -l 3
AAA  BBB  CCC:DDD
```

**Comment by LadyAleena** [comment]
Thank you very much!
