### ISSUE TITLE
lsblk: Specifying -T without a 'column' parameter results in diagnostic

### ISSUE THREAD

**Issue by ahmogit** [karelzak/util-linux#1132]
**Description:**
The man page and --help blurb pertaining to `-T, --tree`  seem to indicate that the 'column' parameter is optional, and if not supplied, it defaults to 'NAME'. This defaulting works as expected if the option is given as `--tree`, but does not work as expected if given as `-T`.  

**Steps to reproduce:**

       $ lsblk --tree

produces the expected output, treeified on NAME.

But

        $ lsblk  -T

produces the diagnostic `lsblk: option requires an argument -- 'T'`

**Comment by karelzak** [comment]
Good catch. Thanks for your report!

Fixed now. The bugfix will be in releases v2.37 and v2.36.1.
