### ISSUE TITLE
.tarball-version missing in 2.36

### ISSUE THREAD

**Issue by chowbok** [karelzak/util-linux#1133]
.tarball-version was included with the 2.34 tarball but is missing from 2.36. This causes the version of the compiled binaries to be reported as "UNKNOWN". I figured it out, but it seems like it should be included in future releases.

**Comment by karelzak** [comment]
It works for me:

$ wget https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.xz
$ tar -Jxf util-linux-2.36.tar.xz
$ cd util-linux-2.36/
$ cat .tarball-version
2.36

$ make cal
$ ./cal -V
cal from util-linux 2.36
