### ISSUE TITLE
findmnt --json --type btrfs returns zero bytes (not JSON)

### ISSUE THREAD

**Issue by jernst** [karelzak/util-linux#1136]
If there is no btrfs filesystem, and specifying ``--json``, I would expect result:
```
{}
```
not zero bytes. This means any JSON parser attempting to parse the output will report an error.

This is findmnt from util-linux 2.35.1 on Arch.

**Comment by karelzak** [comment]
This is common --json behavior in all tools from util-linux. The libsmartcols does not print an empty table at all.

Is the expected output `{}` or `{ "filesystems": [] }` ?  (In all normal cases we use named array.)

**Comment by jernst** [comment]
IMHO the goals should be, in order:
* always valid JSON output: so parsers don't need to implement a special case
* make (valid) JSON output easy to parse: so having an empty `filesystems` array is a better idea than merely contains `{}` (so I change my mind from the original issue)
* make user errors less likely: so having that `filesystems` step in there is probably a better idea than what `systemctl list-units --output=json` does, which is to emit an array that's not wrapped in a hash.

**Comment by karelzak** [comment]
OK, implemented in `{ "filesystems": [] }` way for all libsmartcols utils.
