### ISSUE TITLE
libfdisk/liblkid with small disk images is buggy

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#1147]
So i did some experiments with really small disk images where i wrote a GPT partition table with sfdisk, then read it back with fdisk and used "blkid -p" to determine if they are properly recognized. sfdisk succeeded each time, but what was generated was rubbish. images of 4K size where entirely bogus, fdisk couldn't read it. at 1M fdisk worked, but blkid -p didn't recognize anyting. At 16M both worked fine.

It would be great if libfdisk would refuse operation if disk images are too small for a valid GPT rather than silently succeed but generate rubbish. And something is off with blkid -p on very small disks, since it didn't see the GPT disk label at all even though fdisk did.

**Comment by karelzak** [comment]
For libblkid we have 1MiB limit to avoid search on small devices ... but we can make this limit smaller as GPT detection is pretty cheap and simple.

Anyway, 4K should be enough (for 512-byte sector). I need to check libfdisk, it sounds like the default first-usable-sector issue.

**Comment by poettering** [comment]
hmm, i see, not doing the full probing might make sense on tiny/slow disks. That said I figure libblkid should do some minimal probing even then, probably matching the part probe checking the kernel does in those cases. i.e. i think keeping kernel probing and libblkid probing roughly in sync in these cases would make a ton of sense. (that said i never checked what the kernel actually does with such small disks)

**Comment by karelzak** [comment]
It's ready for 4K images now.
```
$ echo ',,L' | ./sfdisk --label gpt ../4K.img 
Checking that no-one is using this disk right now ... OK

Disk ../4K.img: 4 KiB, 4096 bytes, 8 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 66E39094-ED04-0A4C-BF75-81C9CE3DD937
...
>>> Created a new GPT disklabel (GUID: A23102D9-AED8-0744-8FB3-707C700E1054).
The maximal number of partitions is 8 (default is 128).                                           <--- !
...
New situation:
Disklabel type: gpt
Disk identifier: A23102D9-AED8-0744-8FB3-707C700E1054

Device     Start End Sectors  Size Type
../4K.img1     4   4       1  512B Linux filesystem
```
libblkid is able to detect it too:
```
# ./blkid ../4K.img
../4K.img: PTUUID="a23102d9-aed8-0744-8fb3-707c700e1054" PTTYPE="gpt"
```
and kernel is able to use it (so it's valid GPT :-)):
```
$ sudo losetup -P -f ../4K.img 
$ lsblk /dev/loop0
NAME      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0       7:0    0    4K  0 loop 
└─loop0p1 259:5    0  512B  0 part 
```
