### ISSUE TITLE
util-linux-2.34 and later: blkid does not discover md-raid device that is LUKS formatted

### ISSUE THREAD

**Issue by nkichukov** [karelzak/util-linux#1151]
Hello team,

This is an upstream report that was originally created at:

https://bugs.gentoo.org/741654

For completeness, I will put the summary of the issue in here. More information on what has been attempted can be found on the link above, if required.

blkid binary from util-linux-2.34 and later no longer recognizes md-raid (linux-raid) device that is LUKS formatted. The result is failure to boot the system if the raid device is crypt_root (manually specificy /dev/mdXXX allows the system to continue to boot) and failure to list it with blkid while the system is running (lsblk lists it fine).

Downgrading to util-linux-2.33.2 fixes the issue.

To note, the versions of util-linux that are greater than util-linux-2.33.2 were compiled with cryptsetup use flag but still failed to list the device.

Info about raid array and the LUKS partition:

# mdadm --detail --verbose /dev/md1
/dev/md1:
           Version : 1.2
     Creation Time : Fri May 24 09:51:52 2019
        Raid Level : raid1
        Array Size : 167640064 (159.87 GiB 171.66 GB)
     Used Dev Size : 167640064 (159.87 GiB 171.66 GB)
      Raid Devices : 2
     Total Devices : 2
       Persistence : Superblock is persistent

       Update Time : Fri Sep 11 14:43:17 2020
             State : active 
    Active Devices : 2
   Working Devices : 2
    Failed Devices : 0
     Spare Devices : 0

Consistency Policy : resync

              Name : della:1
              UUID : 2f24d0e2:c5d528f5:a443c4ad:a25cab6d
            Events : 283545

    Number   Major   Minor   RaidDevice State
       6       8        6        0      active sync   /dev/sda6
       2       8       22        1      active sync   /dev/sdb6

# cryptsetup luksDump /dev/md1
LUKS header information for /dev/md1

Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha256
Payload offset: 4096
MK bits:        512

Here is how blkid from util-linux-2.33.2 lists the volume:

# blkid | grep e1188
/dev/md1: UUID="e11887f5-4104-4a9e-9c53-7e1d904a0b28" TYPE="crypto_LUKS"

Same command with any of the later versions of util-linux produces no output, though the device is there.

Reproducible: Always

Steps to Reproduce:
1. On a system that makes use of dm-raid and dm-crypt(cryptsetup), setup a raid1 array and format it in LUKS1 (version 1) format.
2. Upgrade util-linux to anything after version sys-apps/util-linux-2.33.2
3. run blkid and see how your dm-raid device is not listed in the output (but lsblk shows it for comparison)
Actual Results:  
The assembled raid device is not visible to blkid utility.

Expected Results:  
Even when running with versions greater than sys-apps/util-linux-2.33.2, blkid should continue to detect the raid device.

This may be a corner case, as blkid failed for this specific raid device, but it does not fail for all such devices, so perhaps related to something in the specific mdraid device itself. But even then, it is a regression as something got broken.

**Comment by Polynomial-C** [comment]
`were compiled with cryptsetup use flag` is the Gentoo way of running configure with `--with-cryptsetup` option.

**Comment by karelzak** [comment]
Please, try  `blkid -o udev -p /dev/md1` and it would be nice to have output from `LIBBLKID_DEBUG=all blkid`. 

Maybe the prioblem is commit 969e8cbeb124581b376bc5534c716d1b18144190.

**Comment by karelzak** [comment]
It works for me with v3.35.2 and the current upstream tree.
```
$ lsblk --merge /dev/sdc
    NAME   MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
    sdc      8:32   0  100M  0 disk  
┌┈▶ ├─sdc1   8:33   0   40M  0 part  
└┬▶ └─sdc2   8:34   0   40M  0 part  
 └┈┈md0      9:0    0   39M  0 raid1 

# rm -f /run/blkid/blkid.tab

# ./blkid | grep md0
/dev/md0: UUID="79916061-c39c-4c68-9d26-269f7d296693" TYPE="crypto_LUKS"
```

I have tried md0 as the last entry in /proc/partitions as well as entry somewhere in the middle of the list -- all works for me.

**Comment by nkichukov** [comment]
Hi,
There is no difference in the output of the first command, they both return:

ID_FS_VERSION=1
ID_FS_UUID=e11887f5-4104-4a9e-9c53-7e1d904a0b28
ID_FS_UUID_ENC=e11887f5-4104-4a9e-9c53-7e1d904a0b28
ID_FS_TYPE=crypto_LUKS
ID_FS_USAGE=crypto

libblkid debug output from both versions can be found here:
https://kichukov.home.xs4all.nl/bug-reports/util-linux/github_issue_1151/

(note, labels have been redacted).

And last, I have reversed the patch you mentioned 969e8cbeb124581b376bc5534c716d1b18144190 and applied it on top of 2.36 and it worked as expected! The device gets listed by blkid version 3.36. Nice catch!

**Comment by karelzak** [comment]
Nice, it seems you have md12{5,6,7}, and libblkid /proc/partitions parsers assumes that md1 is their "parent" (whole disk device).

**Comment by karelzak** [comment]
@nkichukov can you try the current upstream tree? The problem should be fixed now.

**Comment by nkichukov** [comment]
Confirmed, current upstream has a working fix. Thank you.

The only issue I had after compiling it was a missing reference to:
`/usr/share/doc/util-linux/getopt/getopt-parse*`

Were there any recent changes in regards to those getopt-parse files no longer being installed?

This issue can now be closed. I am looking forward to the next stable release that will include these patches.

Thank you,
-Nikolay

**Comment by karelzak** [comment]
Thanks for your test!

(The file getopt-parse has been renamed to getopt-example._
