### ISSUE TITLE
issue with outpout of lsblk

### ISSUE THREAD

**Issue by DanRod1** [karelzak/util-linux#1153]
HI,
The output of lsblk as change between util-linux 2.17 on rehl6/centos6 and util-linux 2.23 on rhel7/centos7.

In prior version lsblk show the dm device associate to disk block device 
  **sdb                                     8:16   0   50G  0 disk
├─vgpki-lvpkietc (dm-8)               253:8    0  100M  0 lvm**
In 2.23 version this information is lost 
**sdc                             8:32   0    50G  0 disk
├─vgpki-lvpkietc              253:8    0   100M  0 lvm**

if I strace lsblk i can confirm that the information is consult by the process but not written to output 
**open("/sys/block/dm-8/dm/name", O_RDONLY|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ffff7ff8000
read(6, "vgpki-lvpkietc\n", 4096)       = 15
....
write(1, "\342\224\234\342\224\200vgpki-lvpkietc            "..., 61) = 61**

I don't see any issue related to this, could you check this ? Any idea ?

best regards

**Comment by karelzak** [comment]
Yes, this change was intorduced by commit c7e76cd145b0c40e1d346203f3222f5937146939 (Mar 2013, v2.23).

The reson is:
* complicated semantic; different output in parsable formats and normal output
* multiple information in one column
* dm-N is internal DM device name and DM devels don't want to show it to end-users by default

The current lsblk provides separate KNAME (kernel name) column, for example "lsblk -o+KNAME" with dm-N stuff.

And we will not revert this change ;-) Closing.

**Comment by DanRod1** [comment]
ok thanks
