### ISSUE TITLE
[libsmartcols] watch vs tty column detection

### ISSUE THREAD

**Issue by eMPee584** [karelzak/util-linux#1160]
Running `lsblk` under `watch`  makes output overflow the terminal width; running outside of `watch` makes columns adjust appropriately.

```
watch -c -d -n 0.2 -- LIBSMARTCOLS_DEBUG_PADDING=on lsblk --paths \
--output VENDOR,MODEL,SERIAL,RO,RM,NAME,SIZE,FSUSE%,FSAVAIL,FSTYPE,LABEL,MOUNTPOINT,STATE
```

Use case: wanted to have a live view of plugged in USB pen drives (whilest flashing our https://schulstick.org/ ).. but some devices have _insanely_ long serial numbers xD
![insanely-long-serial-number_2020-10-09_20-09-34](https://user-images.githubusercontent.com/1227833/95617983-90fa4a80-0a6c-11eb-993b-fa17c6da0bbf.png)

**Comment by karelzak** [comment]
In this case, lsblk (and other tools) does not assume it's executed on the terminal and it does not restrict output and columns  width. It's the same as "lsblk > file".  

The ideal soution would be to improve watch(1) to execute commands in a own terminal (like script(1)), but it's not trivial ...

Anyway, you do not need watch(1) at all ;-), you can use bash loop + clear:
```
while true; do printf  "%${COLUMNS}s\n" "$(date)"; lsblk --paths \
  --output VENDOR,MODEL,SERIAL,RO,RM,NAME,SIZE,FSUSE%,FSAVAIL,FSTYPE,LABEL,MOUNTPOINT,STATE; sleep 0.2; clear; done
```
(the command printf is there only to provide date and demostrate it works).

For lsblk, we can add --term-width to restrict libsmartcols table formatting. I'll implement it as it seems usable in another use-cases too.

**Comment by eMPee584** [comment]
A loop is ok – but watch does the **difference** _highlighting_ 😎
Thanks for adding the option though. What a dream **to-the-point**-feature request delivery .. may the universe expand this pattern to all sentient programs, and may many more feature requests be fulfilled in this way. What a contrast to systemd style RESOLVED WONTFIX 👌😏
