### ISSUE TITLE
more ignores --

### ISSUE THREAD

**Issue by rowlap** [karelzak/util-linux#1162]
Trying to open a file with an unusual name, more does not follow the POSIX convention on '--' delimiting end-of-options.

Steps to reproduce:
```
$ touch +filename-with-plus

$ more --version
more from util-linux 2.35.2

$ more -- +filename-with-plus
more: bad usage
Try 'more --help' for more information.

$ more ./+filename-with-plus
# works, but shouldn't be necessary
```

**Comment by kerolasa** [comment]
I am not able to reproduce.

    $ touch '+filename-with-plus' && ./more +filename-with-plus && ./more --version
    more from util-linux 2.36.177-27114

Compiling commit before e3cb27f5358ccdd8c4a10ccf13e0f37ab9953332 made the 'bad usage' to re-appear. That commit is part of quite large refactoring and improving effort. I doubt the change will or should be backported to older release(s).

    $ git tag --contain git tag --contain git tag --contain e3cb27f5358ccdd8c4a10ccf13e0f37ab9953332
    v2.36
    v2.36-rc1
    v2.36-rc2

**Comment by karelzak** [comment]
Yes, it's already fixed in the current upstream tree (thanks to Sami).

**Comment by rowlap** [comment]
Ah, I thought checking the latest Fedora package would be enough, but if v2.36 has moved to getopt_long that's great.
