### ISSUE TITLE
Feature Request: Add time filter for "dmesg"

### ISSUE THREAD

**Issue by MrPippin66** [karelzak/util-linux#1166]
In troubleshooting, you're often only interested in events within a given time period.

I wish to advocate for an option to filter the output by events that have only occurred in a given time-frame.

For example, "ausearch" provides a "--start" and "--end" options to filter the time period.

I'd like to include the same filter type options as stated for "ausearch", though I'd primarily only be interested in being able to specify a unit of time with a value, namely minutes, hours and days.

So, an example might be:

"--start 2h" show all events from 2 hours ago till present

"--start 4h --end 2h" show all events from 4 hours ago till 2 hours ago

Having the command perform this would be far more efficient than scripting the timestamp comparison externally to the command.

**Comment by karelzak** [comment]
Yes, this is a good idea. I have thought about it time ago; my idea was --since and --until like used by git-log.

**Comment by karelzak** [comment]
Implemented (the first commit is obsolete and with broken commit message).
