### ISSUE TITLE
Partition #1 contains a zfs_member signature.

### ISSUE THREAD

**Issue by devZer0** [karelzak/util-linux#1177]
after wiping a disk with wipefs, i'm re-creating a partition/filesystem and fdisk is telling that a freshly created partition contains a zfs signature.

apparently wipefs did not delete it (i wiped with "wipefs -a -f /dev/diskid")

i'm not sure if this is expected/by design, but i would expect that wipefs would remove such.

wrong expectation?

Created a new DOS disklabel with disk identifier 0xc4d50fc6.

Command (m for help): n
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (1-4, default 1): 1
First sector (2048-4294967295, default 2048):
Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-4294967294, default 4294967294):

Created a new partition 1 of type 'Linux' and of size 2 TiB.
Partition #1 contains a zfs_member signature.

Do you want to remove the signature? [Y]es/[N]o: ^C
Command (m for help): ^C

using wipefs from util-linux 2.33.1 / proxmox 6.2 (debian 10.6)

**Comment by karelzak** [comment]
It depends on what you have removed. If you removed only PT than after re-create zfs will be visible again.

**Comment by devZer0** [comment]
i did wipefs the whole device , i.e. /dev/sdc

after re-reading the manpage it seems, i did have to high expectation what wipefs can do and what not. i thought it would scan through parition tables and remove all relevant signatures before removing the whole partition table.

my expectation from wipefs would be to have a tool which safely wipes all filesystem related information from disk, so recreation should work without any warnings from  partitioning tools, mkfs/zpool create, mdadm & lvm & co.  , i.e. i use wipefs because i want to avoid writing terabytes from /dev/zero to the whole disk to make it safely/easily re-usable (as this lasts very long and costs a lot of time)

thank you for making wipefs, though

**Comment by karelzak** [comment]
The issue is that `wipefs /dev/disk` does not see the content of the partitions. It would be possible to implement it (and libbblkid is ready for this), but I have doubts it's expected by other users.

For your use-case is probably better to use `wipefs /dev/sdc*`.

**Comment by devZer0** [comment]
>For your use-case is probably better to use wipefs /dev/sdc*.

thanks for the hint, it wasn't clear to me that using it THIS way would do what i want.

perhaps it could be helpful to put a hint in the manpanpage, that for a thorough wipe, you should first wipefs all partitions and then the device/PT afterwards

btw, using /dev/sdX* can be dangerous, as it may include /dev/sdcard or /dev/sdXa, /dev/sdXb , ... (on a system with a large number of disks)

**Comment by ctrahey** [comment]
In my case, I needed to zero out 2MB to stop seeing this error message when reusing a disk that had been a ZFS member. 

```bash
# dd if=/dev/zero of=/dev/nvme2n1 bs=2k count=1k
```
It is possible that less would do it, but not much less (1MB did not clear it)

**Comment by karelzak** [comment]
@ctrahey `wipefs` is not enough? (And if not, what version do you have?)

**Comment by ctrahey** [comment]
I didn't try - I landed here via googling the error `Partition #11 contains a zfs_member signature.` and have been in the habit of using dd to clear my tables. Tossed in my comment because it "worked", in case future Googlers benefit from that. My case was specifically blanking at the disk level, to be clear.

**Comment by karelzak** [comment]
dd(1) is always a good choice if you know what are you doing :-)
