### ISSUE TITLE
flock(1) does not document system-wide exit code limitations

### ISSUE THREAD

**Issue by nirgal** [karelzak/util-linux#1180]
Hello

When using flock --nonblock --conflict-exit-code 600 on a locked file, the returned value is 88.

I expected it to be 600.

This can re reproduced by running:
$ flock --nonblock --conflict-exit-code 600 test.lock -c "sleep 10"&
a few times in a shell.

flock should fail immediately if the number parameter is out of acceptable range and will never be returned.

Additionally, flock(1) should document the fact that number must be <= 255.

**Comment by karelzak** [comment]
Good point. Fixed and man page updated. Thanks!
