### ISSUE TITLE
Column quits unexpectedly when it hits unicode characters and the Lang is not UTF-8

### ISSUE THREAD

**Issue by aussiestorblog** [karelzak/util-linux#1183]
Found this issue on Centos 7

With locale UTF-8,  if I send non-ASCII characters to column, it print them.
```
[root@demo-oracle-4 ~]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
[root@demo-oracle-4 ~]# column -V
column from util-linux 2.23.2

[root@demo-oracle-4 ~]# locale
LANG=en_AU.UTF-8
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
[root@demo-oracle-4 ~]# foo="곤충"
[root@demo-oracle-4 ~]# echo $foo
곤충
[root@demo-oracle-4 ~]# echo $foo | column
곤충
```
I now change LANG to POSIX and now column no longer prints.
```
[root@demo-oracle-4 ~]# export LANG=POSIX
[root@demo-oracle-4 ~]# locale
LANG=POSIX
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
[root@demo-oracle-4 ~]# echo $foo | column
[root@demo-oracle-4 ~]#
```

This is worse if half way through output, column encounters one non-ASCIC character, like a long dash (em dash), it stops printing and half the output is not shown due to one long dash.

**Comment by karelzak** [comment]
The current upstream release is v2.36, the difference between v2.23 and v2.36 is (for the column command) ~70 commits ;-)

Anyway: the current upstream:
```
 $ foo="곤충"
 $ export LANG=POSIX
 $ echo $foo | ./column
 \xea\xb3\xa4\xec\xb6\xa9
```
it means that the input is interpreted as unprintable chars and it;s converted to \x notation. I guess this correct behavior as we have no clue and way how to work with the chars in non-UTF8 locales. Right?

**Comment by aussiestorblog** [comment]
Shame on me for not testing with the latest build, though in my defence all my Linux boxes are Centos 7.8 and yum seems to want to always install 2.23.      My main desire is to at least not abort output, when one mystery character that someone foolishly added to a VM name sneaks out into my output.   If column in 2.36 does this,  then I am happy.    Will test when I get the latest build installed and let you know if anything further crops up.
