### ISSUE TITLE
lsblk does not show pktcdvd0 as child of sr0

### ISSUE THREAD

**Issue by pali** [karelzak/util-linux#1185]
Here is ouput of lsblk on tested machine:
```
sdb        8:16   0 111,8G  0 disk
...
├─sdb6     8:22   0    40G  0 part  
│ └─data 254:4    0    40G  0 crypt /data
└─sdb7     8:23   0  13,6G  0 part  
sr0       11:0    1  1024M  0 rom   
pktcdvd0 253:0    1     0B  0 disk
```
It correctly detects that sdb6 and sdb7 are children of sdb and also that data (luks mapper device) is child of sdb6. But it does not detect that pktcdvd0 (packet writing device) is child of sr0 (optical device).

pktsetup (via ioctl) can show this missing mapping between sr0 and pktcdvd0:
```
$ /usr/sbin/pktsetup -s
 0 : 253:0 -> 11:0
```

New kernels export this mapping also via sysfs:
```
$ cat /sys/class/pktcdvd/device_map
pktcdvd0 253:0 11:0
```

Basically each optical drive can have maximally one packet writing device.

It would be nice if lsblk would be able to detect and show correct mapping between optical devices and packet writing devices.

**Comment by karelzak** [comment]
lsblk uses  /sys/block/*/{holders,slaves} for dependencies and /sys/block/*/*<n> for partitions. These directories are not used by sr0 and pktcdvd0.

It seems we need extra check for /sys/class/pktcdvd/device_map. It's painful that the file is global for all class, so it's necessary to parse it, etc. It would be better to have a per-device "blkdevid" attribute in /sys/block/pktcdvd0/. Maybe we can ask kernel developers to implement it.

**Comment by karelzak** [comment]
Implemented:
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 223.6G  0 disk 
├─sda1        8:1    0   200M  0 part /boot/efi
├─sda2        8:2    0     5G  0 part /boot
├─sda3        8:3    0 125.5G  0 part 
├─sda4        8:4    0    50G  0 part /
└─sda5        8:5    0  42.9G  0 part /home/archive
sdb           8:16   0  74.5G  0 disk 
sr0          11:0    1  1024M  0 rom  
└─pktcdvd0  252:0    1     0B  0 disk 

```
