### ISSUE TITLE
umount by fstype seems dangerous

### ISSUE THREAD

**Issue by jengelh** [karelzak/util-linux#1189]
On util-linux 2.35.1, I am observing:

```
# rm -Rf tmpfs; mkdir tmpfs;
# df -Tah >m1; umount tmpfs; df -Tah >m2; diff -dpru m1 m2

--- m1  2020-11-16 15:29:48.397945072 +0100
+++ m2  2020-11-16 15:29:53.821951190 +0100
@@ -37,5 +37,3 @@ securityfs     securityfs     0     0
 tmpfs          tmpfs        32G  136K   32G   1% /var/run
 tmpfs          tmpfs       6.3G  8.0K  6.3G   1% /run/user/25121
 tmpfs          tmpfs       6.3G  8.0K  6.3G   1% /var/run/user/25121
-tmpfs          tmpfs        32G  3.6G   28G  12% /run/ob
-tmpfs          tmpfs        32G  3.6G   28G  12% /var/run/ob

# rmdir tmpfs
# umount tmpfs; echo $?
0
```

This behavior is uncanny. What I expected to see instead:

```
umount: tmpfs: not mounted.

umount: cannot access "tmpfs": No such file or directory
```

Perhaps umount could be made to reject umount-by-devicename for "nodev" devices?

**Comment by karelzak** [comment]
This is not umount based on fstype, but based on source, in your case source is "tmpfs" string, you can try to use `mount -t tmpfs bar /foo` and than `umount bar`. 

If you don't like the current behaviour than do not use 'tmpfs' as source string on mount to mount tmpfs.

**Comment by jengelh** [comment]
One does not always have a choice to set the string (reasonably); quite a bit is hardcoded in the init system and then some.
