### ISSUE TITLE
"lsblk -P -f" output cannot be parsed by shell

### ISSUE THREAD

**Issue by magic-david** [karelzak/util-linux#1201]
Given:

```
lsblk -P /dev/disk/by-id/google-persistent-disk-1 -f
```

Output is:

```
NAME="sdb" FSTYPE="ext4" LABEL="" UUID="060038ea-ba10-462e-99ec-79a0f8b2f0e1" FSAVAIL="" FSUSE%="" MOUNTPOINT=""
```

Given:

```
eval $( lsblk -P /dev/disk/by-id/google-persistent-disk-1 -f )
```

Error is:

```
FSUSE%=: command not found
```

Suggest removing the `%` from the variable name. Will send patch later if I have some free time

**Comment by karelzak** [comment]
Good point, it seems we have the same thing in lsipc and findmnt. 

The question if we need to care about it as there is always non-% variant of the number and you should not blindly use defaults (like -P) in your scripts as it is subject to change (as described in the man page).

Now when I think about it then the column rename is a backwardly incompatible change, let's imagine you have 
```
 FOO=$(lsblk -nro FSUSE% /dev/sda1)
```
 in your script. I think we should not touch the name, maybe improve the way how libsmartcols prints the variable name for -P:

https://github.com/karelzak/util-linux/blob/master/libsmartcols/src/print.c#L474-L479

maybe remove % (and other bad chars) in from variable name or use some escape for %, or so.

**Comment by magic-david** [comment]
Maybe a search-replace for % -> PCT? Sucky I know

**Comment by karelzak** [comment]
Fixed. Note that we had an issue also with many variables (column names) like MIN-IO.
