### ISSUE TITLE
lscpu against Amlogic Meson G12B (S922X) returning inconsistent data

### ISSUE THREAD

**Issue by heitbaum** [karelzak/util-linux#1207]
ARM big.LITTLE CPU showing up with incorrect details.
It should show up as a 2 cluster CPU with 4+2 cores. Where as the cores per socket numbers don’t match this. The Model name does not match the big.LITTLE nature of this either.

This particular CPU is in an Odroid N2+, it is part of the G12B http://linux-meson.com/

SoC – Amlogic S922X Rev.C hexa-core big.LITTLE processor with 4x Arm Cortex A73 cores @ up to 2.2/2.4GHz, 2x Arm Cortex A53 cores @ 2.0GHz, Arm Mali-G52 GPU @ 846MHz; 12nm manufacturing process

# uname -a
Linux groovy-server 5.10.0-odroid-panfrost-arm64 #1 SMP PREEMPT Ubuntu 5.10.0-202011272305~groovy (2020-11-27) aarch64 aarch64 aarch64 GNU/Linux

# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          6
On-line CPU(s) list:             0-5
Thread(s) per core:              1
Core(s) per socket:              3
Socket(s):                       2
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     2400.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        48.00
NUMA node0 CPU(s):               0-5
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

# lscpu -e
CPU NODE SOCKET CORE L1d:L1i:L2 ONLINE    MAXMHZ    MINMHZ
  0    0      0    0 0:0:0         yes 2016.0000 1000.0000
  1    0      0    1 1:1:0         yes 2016.0000 1000.0000
  2    0      1    2 2:2:0         yes 2400.0000 1000.0000
  3    0      1    3 3:3:0         yes 2400.0000 1000.0000
  4    0      1    4 4:4:0         yes 2400.0000 1000.0000
  5    0      1    5 5:5:0         yes 2400.0000 1000.0000

# dmesg | grep -e soc0 -e EL
[    0.008807] CPU features: detected: 32-bit EL0 Support
[    0.008817] CPU features: detected: 32-bit EL1 Support
[    0.022467] CPU: All CPU(s) started at EL2
[    1.353064] soc soc0: Amlogic Meson G12B (S922X) Revision 29:c (40:2) Detected

# lscpu --version
lscpu from util-linux 2.36

# In the below cpu info you will note 2 * 0xd03 and 4 * 0xd09 CPU parts
# cat /proc/cpuinfo

BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 3
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 4
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 5
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

**Comment by karelzak** [comment]
Wait for v2.37 :-) or try the current upstream tree. For example:
```
$ ./lscpu --sysroot ../dumps/lscpu-Cortex-A72+A53/
Architecture:           x86_64
  Byte Order:           Little Endian
CPU(s):                 6
  On-line CPU(s) list:  0-5
Vendor ID:              ARM
  Model name:           Cortex-A53
    Model:              4
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r0p4
    CPU max MHz:        1416.0000
    CPU min MHz:        408.0000
    BogoMIPS:           48.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
  Model name:           Cortex-A72
    Model:              2
    Thread(s) per core: 1
    Core(s) per socket: 2
    Socket(s):          1
    Stepping:           r0p2
    CPU max MHz:        1800.0000
    CPU min MHz:        408.0000
    BogoMIPS:           48.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
NUMA:                   
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-5
Vulnerabilities:        
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Spec store bypass:    Not affected
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Mitigation; Branch predictor hardening
  Tsx async abort:      Not affected

```

**Comment by heitbaum** [comment]
Looks good

**Comment by heitbaum** [comment]
Hi @karelzak - would like to reopen this issue. I have compiled master up and note that the display is backwards. There should be 4 * A73 and 2 * A53.

https://en.wikipedia.org/wiki/Amlogic#Media_player_SoCs_(S8_&_S9_family_gen_4)
Amlogic S922X – Quad-core ARM Cortex-A73+Dual-Core ARM Cortex-A53-based SoC with a Mali-G52 MP4 GPU

Details below - https://paste.ubuntu.com/p/PBqNDkJhZW/

It would be nice to have the CPU Model name included too? Same as Soc0 from dmesg.

**Comment by karelzak** [comment]
Thanks for the test!

Now lscpu supports two types of model names. The first is from /sys -- this one you see on the output and the second is from BIOS -- unfortunately, this is accessible only for the root user. So, try it as root, maybe you will see `BIOS Model name:`.

For more details see https://www.spinics.net/lists/util-linux-ng/msg16541.html and another related discussion about it on util-linux mailing list (you can also contribute without subscribing to the list).

For PAT_IMPLEMENTER / PAT_PART / PAT_VARIANT / PAT_REVISION it would be nice to have /proc/cpuinfo. 

We have `https://github.com/karelzak/util-linux/blob/master/tests/ts/lscpu/mk-input.sh` script to dump /sys and /proc, if you send me the tarball then I can see what is happening to the values from /sys.

**Comment by karelzak** [comment]
It's also strange that you have only "Caches" header on output, but no list of the caches.
```
Caches:                 
NUMA:                   
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-5

```

**Comment by heitbaum** [comment]
Whilst waiting for 5.10.y and then spending some time on both the ODROID N2+ and shortly the Khadas VIM 3. Thought it would be good to go through the motions with testing the hardware out fully, so using groovy with some upstream hirsute pkgs. Before moving to using them for development for LibreELEC 10 testing. 

Using the kernel from: http://ppa.linuxfactory.or.kr groovy

`Linux groovy-server 5.10.0-odroid-panfrost-arm64 #1 SMP PREEMPT Ubuntu 5.10.0-202012021439~groovy (2020-12-02) aarch64 aarch64 aarch64 GNU/Linux`

Have identified that fwupd has some vendor anomalies too (with DT) - so am drilling in to this further.

https://github.com/fwupd/fwupd/issues/2648

Waiting for my A311D https://www.khadas.com/vim3 - so will test lscpu on this too.

I’ll have a look at the PR and I’ll post the outputs. I have confirmed the lscpu definitely running as root. https://paste.ubuntu.com/p/wrS4bBTRBd/ I included an `lscpu -C`  too

**Comment by heitbaum** [comment]
> We have https://raw.githubusercontent.com/karelzak/util-linux/master/tests/ts/lscpu/mk-input.sh script to dump /sys and /proc, if you send me the tarball then I can see what is happening to the values from /sys.

https://github.com/heitbaum/util-linux/blob/1207/1207.tar.gz

**Comment by heitbaum** [comment]
Here is the data from /sys

```shell
root@groovy-server:/sys/devices/soc0# ls -la
total 0
drwxr-xr-x 3 root root    0 Jan  1  1970 .
drwxr-xr-x 8 root root    0 Jan  1  1970 ..
-r--r--r-- 1 root root 4096 Dec 10 12:14 family
-r--r--r-- 1 root root 4096 Dec 10 12:14 machine
drwxr-xr-x 2 root root    0 Dec 10 11:49 power
-r--r--r-- 1 root root 4096 Dec 10 12:14 revision
-r--r--r-- 1 root root 4096 Dec 10 12:14 soc_id
lrwxrwxrwx 1 root root    0 Jan  1  1970 subsystem -> ../../bus/soc
-rw-r--r-- 1 root root 4096 Jan  1  1970 uevent
root@groovy-server:/sys/devices/soc0# cat family machine revision soc_id 
Amlogic Meson
Hardkernel ODROID-N2Plus
29:c - 40:2
G12B (S922X)
```

**Comment by karelzak** [comment]
Good point, we currently use only /proc/cpuinfo for CPU identifiers (and the BIOS). Maybe fallback to /sys/devices  is also a good idea.

**Comment by heitbaum** [comment]
@karelzak 
- looks good on 2.37-rc1
- Did we expect NUMA on this?
- Did we expect Caches information.

```
odroid:~ # lscpu -V
lscpu from util-linux 2.37-rc1
odroid:~ # lscpu 
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 6
  On-line CPU(s) list:  0-5
Vendor ID:              ARM
  Model name:           Cortex-A53
    Model:              4
    Thread(s) per core: 1
    Core(s) per socket: 2
    Socket(s):          1
    Stepping:           r0p4
    CPU max MHz:        1800.0000
    CPU min MHz:        100.0000
    BogoMIPS:           48.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
  Model name:           Cortex-A73
    Model:              2
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r0p2
    CPU max MHz:        2208.0000
    CPU min MHz:        100.0000
    BogoMIPS:           48.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
Caches (sum of all):    
Vulnerabilities:        
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Spec store bypass:    Vulnerable
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Vulnerable
  Srbds:                Not affected
  Tsx async abort:      Not affected
```

**Comment by karelzak** [comment]
The "Caches ... " header should not be printed if there nothing to show about caches (fixed now). 

It prints nothing about caches because very probably there is no /sys/devices/system/cpu/cpu*/cache/index*/size file (at least I do not see it in your dump (1207.tar.gz). I guess `lscpu --caches` will print more details.

Not sure why we do not see NUMAs, in your dump is /sys/devices/system/node/node* and I see files and it works as expect with the dump.

**Comment by heitbaum** [comment]
`ls /sys/devices/system/cpu/cpu*/cache/index*/* | pastebinit `
http://ix.io/3ip6

this is the lscpu
```
# lscpu --caches
NAME ONE-SIZE ALL-SIZE WAYS TYPE        LEVEL SETS PHY-LINE COHERENCY-SIZE
L1d                         Data            1               
L1i                         Instruction     1               
L2                          Unified         2
```
I’ll check the kernel configuration
```
odroid:~ # ls -la /sys/devices/system/node/
ls: /sys/devices/system/node/: No such file or directory
odroid:~ # ls -la /sys/devices/system/
total 0
drwxr-xr-x    6 root     root             0 Mar 31 07:59 .
drwxr-xr-x    8 root     root             0 Jan  1  1970 ..
drwxr-xr-x   10 root     root             0 Mar 31 07:59 clockevents
drwxr-xr-x    4 root     root             0 Mar 31 07:59 clocksource
drwxr-xr-x    3 root     root             0 Apr 28 19:22 container
drwxr-xr-x   14 root     root             0 Mar 31 07:59 cpu
```

**Comment by heitbaum** [comment]
I can confirm all looks good with https://github.com/karelzak/util-linux/releases/tag/v2.37-rc2 in LibeeELEC build across: Amlogic, Allwinner, Rockchip, x86_64. lscpu looking good on all these CPUs. S922X, H6, RK3399pro, TGL
