### ISSUE TITLE
Open `cfdisk` in Read-Only mode

### ISSUE THREAD

**Issue by Atralb** [karelzak/util-linux#1209]
I like the `cfdisk` visualisation a lot and would love to be able to run it in a sort of read-only mode, in order to open a simple viewport to a partition table, for reviewing it and its elements. I find it much enjoyable than other commands like `file -s` etc...

This could also allow to run `cfdisk` as a normal user at the same time, by making this mode the default and only one available in that case (maybe with some protections for multi-human systems)

Unless I'm mistaken, there isn't such an option currently.

I believe it wouldn't be much code to add, and that would make Linux shipped-ins even better :). Would you consider adding such a feature ?

PS: I would love to help you myself on that, but I'm far from skilled enough to touch on such critical tools, working at the root of our systems.

**Comment by karelzak** [comment]
I have doubts --read-only will be usable for non-root users on mainstream distributions. The whole-disk device is for security reasons not readable for non-root users. For example Fedora:
```
 brw-rw---- 1 root disk 8, 0 Dec  4 13:06 /dev/sda
```
you need to add the user to the group `disk`, but it's probably a bad idea.

Don't forget that anyway who can read your disk block device have access to everything on the disk independently on any protections implemented by kernel/filesystem. The only way how to protect data, in this case, is encryption.

So, --read-only makes sense, but as an option for privileged users.

**Comment by Atralb** [comment]
@karelzak Alright. I entirely understand, and honestly guessed so. I simply wanted to explicitly mention that second point so that more experienced people like you who have the necessary knowledge in order to judge the "appropriateness" of this approach, could chip in and give their advice about it.

The ability to conceptually have a RO mode at hand in order to visualise the disk safely is the most important part of this issue, and if it should still need us to be the root user then so be it :).

Thanks a lot for your time and the whole `util-linux` project !

**Comment by karelzak** [comment]
Implemented. 

I like this feature -- it seems pretty useful if you want to use the current disk layout as a start point to generate some sfdisk script (`[Dump]` cfdisk menu).
