### ISSUE TITLE
Explicitly ignore 33553920 optimal I/O size

### ISSUE THREAD

**Issue by rfinnie** [karelzak/util-linux#1221]
Behold! the USB enclosure brokenness:

```
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 33553920 bytes
```

I see https://github.com/karelzak/util-linux/commit/acb7651f8 which would have ignored this situation if the physical sector size was 4096 bytes, but as 33553920 is a multiple of 512, it's allowed. As this affects things like minimum first sector, I needed to switch to gdisk to be able to start the first partition at 1MiB.

I can't see there ever being a situation where 32MiB - 512 would be a real optimal transfer size, so I think there should be an explicit check for 33553920. Ideally also a command line flag which allows you to override io_size would be nice.

FYI, found via http://gparted-forum.surf4.info/viewtopic.php?id=17839

**Comment by karelzak** [comment]
Thanks for your report!
