### ISSUE TITLE
Wrong size in blockdev command when used on HDDs inside external enclosure

### ISSUE THREAD

**Issue by AndreaPro** [karelzak/util-linux#1226]
Hello, I have [this](https://www.orico.cc/us/product/detail/6764/9528U3-BK.html) Orico 4 Bay enclosure that I use with 2 HDDs for now on a Rspberry Pi4 64 bit updated to the latest version of Debian Buster and running OMV.
If I turn on the enclosure and afterwards the system everything works fine. If I reboot the system, or if I turn it of and turn it on again without turning off the enclosure at the next boot the `blockdev` 

This is the output of the command when I turn on the enclosure and power up the system afterwards:

```
pi@raspberrypi:~ $ sudo blockdev --getsize64 /dev/sdb
8001563222016
pi@raspberrypi:~ $ sudo df -PTh | grep /dev/sdb
/dev/sdb1      btrfs     7.3T  2.2T  5.2T  29% /srv/dev-disk-by-label-01
```

This is the output of the command if I reboot or if I shutdown and power on again without turning off and on the enclosure:

```
pi@raspberrypi:~ $ sudo blockdev --getsize64 /dev/sdc
129986248068418560
pi@raspberrypi:~ $ sudo df -PTh | grep /dev/sdc
/dev/sdc1      btrfs     7.3T  2.2T  5.2T  29% /srv/dev-disk-by-label-01
```

If I use the system in this condition after some minutes it becomes unstable and I have to turn everything off and back on.

This emerged during a debugging session for OpenMediaVault [here](https://github.com/openmediavault/openmediavault/issues/896#issuecomment-751761912)

**Comment by karelzak** [comment]
blockdev(8) is a command-line interface to ioctl syscall (BLKGETSIZE64 in your case) -- try `strace blockdev --getsize64 /dev/sdc` to see more details. It seems the problem is in the kernel.

Please, report the issue to Debian maintainers or/and kernel maintainers. Thanks.
