### ISSUE TITLE
fsck.cramfs crashes on blocksizes > 4K

### ISSUE THREAD

**Issue by ToddRK** [karelzak/util-linux#1232]
fsck.cramfs crashes when extracting a cramfs image with a 16KB blocksize because the read_buffer is hardcoded for a 4KB blocksize.  When using a blocksize larger than 4KB, the program's code uses indexes that go past the end of the allocated space for the read_buffer and this causes the crash.

The following changes fix the problem for me in the latest 2.36.1 release of fsck.cramfs.c however there are hardcoded values of 4096 in the code that might cause problems under other circumstances and I have not attempted to fix those.

[diff.txt](https://github.com/karelzak/util-linux/files/5822474/diff.txt)

[fsck.cramfs.c.fixed.txt](https://github.com/karelzak/util-linux/files/5822480/fsck.cramfs.c.fixed.txt)
89,93c89,96
< /* Guarantee access to at least 8kB at a time */
< #define ROMBUFFER_BITS	13
< #define ROMBUFFERSIZE	(1 << ROMBUFFER_BITS)
< #define ROMBUFFERMASK	(ROMBUFFERSIZE - 1)
< static char read_buffer[ROMBUFFERSIZE * 2];
---
> /* Guarantee access to at least 2 * blksize at a time */
> #define INIT_ROMBUFFER_BITS	13
> #define INIT_ROMBUFFERSIZE	(1 << INIT_ROMBUFFER_BITS)
> #define INIT_ROMBUFFERMASK	(INIT_ROMBUFFERSIZE - 1)
> static size_t rombufbits = INIT_ROMBUFFER_BITS;
> static size_t rombufsize = (1 << INIT_ROMBUFFER_BITS);
> static size_t rombufmask = INIT_ROMBUFFERMASK- 1;
> static char *read_buffer;
301c304
< 	unsigned int block = offset >> ROMBUFFER_BITS;
---
> 	unsigned int block = offset >> rombufbits;
306c309
< 		if (lseek(fd, block << ROMBUFFER_BITS, SEEK_SET) == (off_t) -1)
---
> 		if (lseek(fd, block << rombufbits, SEEK_SET) == (off_t) -1)
309c312
< 		x = read(fd, read_buffer, ROMBUFFERSIZE * 2);
---
> 		x = read(fd, read_buffer, rombufsize * 2);
313c316
< 	return read_buffer + (offset & ROMBUFFERMASK);
---
> 	return read_buffer + (offset & rombufmask);
650a654
> 	size_t bufsize = 0;
706a711,715
> 		bufsize = rombufsize = blksize * 2;
> 		rombufbits = 0;
> 		while (bufsize >>= 1) { rombufbits++; }
> 		rombufmask = rombufsize - 1;
> 
707a717
> 		read_buffer = xmalloc(rombufsize * 2);

Edit - attached files since there is strange formatting happening when pasting the diffs

**Comment by karelzak** [comment]
Yes, it would be nice to have your changes in `diff -u` format ;-) or send it to kzak@redhat.com as a patch.

Hmm... it seems like a design problem if it's possible to create a filesystem with variable block size, but there is nowhere in the superblock blocksize field ...

**Comment by kerolasa** [comment]
Getting author & email fixed to following patch file would be nice.

[0001-fsck.cramfs-fix-fsck.cramfs-crashes-on-blocksizes-4K.txt](https://github.com/karelzak/util-linux/files/5882081/0001-fsck.cramfs-fix-fsck.cramfs-crashes-on-blocksizes-4K.txt)

**Comment by karelzak** [comment]
Thanks. Merged (and thanks @kerolasa for a more readable version).

I'll try to clean up all the code by other patches to remove the magic constants and calculations.

**Comment by ToddRK** [comment]
Thanks for following up on this.

If you want my name & email address, they are

   Todd Kelner
   tsopdump@gmail.com
