### ISSUE TITLE
mount -r seems to be ignored for non-root users

### ISSUE THREAD

**Issue by zeha** [karelzak/util-linux#1235]
Debian bug#980828 reports that `mount -r` previously worked for non-root users.

I've quickly checked on 2.36.1: `mount -r` with a `user`-/etc/fstab entry indeed silently mounts read-write.

Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980828

**Comment by karelzak** [comment]
The option "-r" is between allowed options for non-root users in mount.c.  Unfortunately, libmount uses "replace" mode for all options from the command line for non-root users, so all is overwritten by options from fstab.

It seems like a bug, a pretty old bug.

**Comment by zeha** [comment]
Thanks!
