### ISSUE TITLE
zramctl usage listing weirdness

### ISSUE THREAD

**Issue by rpodgorny** [karelzak/util-linux#1237]
hi, i'm not really sure if this is the correct place to submit issues for zramctl but lemme try:

```
[radek@safra ~]$ cat /proc/swaps
Filename                                Type            Size            Used            Priority
/dev/zram0                              partition       2993148         239872          100
/dev/sda2                               partition       976892          0               -2
[radek@safra ~]$ zramctl 
NAME       ALGORITHM DISKSIZE  DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram0 lzo-rle       2.9G  1.5M  1.5M  1.5M       4 [SWAP]
```

clearly ~240MB of zram0 swap device is occupied (out of ~3GB total) but zramctl only shows 1.5MB - what's going on? :-O

**Comment by karelzak** [comment]
What version?     
                  
We had an issue with sizes calculation and formatting for sizeSuffix
outputs in versions <2.36.                                           
                  
Try, "zramctl --bytes" to get a raw size. You can also try to check  
/sys/block/zram#/mm_stat to verify information provided by kernel.

**Comment by rpodgorny** [comment]
```
[radek@safra ~]$ zramctl --version
zramctl from util-linux 2.36.1
[radek@safra ~]$ uname -a
Linux safra 5.10.11-arch1-1 #1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000 x86_64 GNU/Linux
[radek@safra ~]$ zramctl --bytes
NAME       ALGORITHM   DISKSIZE    DATA   COMPR   TOTAL STREAMS MOUNTPOINT
/dev/zram0 lzo-rle   3064987648 1871872 1867856 1880064       4 [SWAP]
[radek@safra ~]$ cat /sys/block/zram0/mm_stat 
 1875968  1871952  1884160        0  1884160        0        0      457
[radek@safra ~]$ cat /proc/swaps 
Filename                                Type            Size            Used            Priority
/dev/zram0                              partition       2993148         273408          100
/dev/sda2                               partition       976892          0               -2
```
...so it seems like the kernel is providing bad data. if so, where should i report it?

**Comment by karelzak** [comment]
Frankly, I'm not sure if assume that zramctl.DATA and swap.Used has to match. It's possible that swap counts all assigned memory pages, but zram counts only really used data.

Anyway, you can ask kernel developers. From kernel MAINTAINERS file:
```
ZRAM COMPRESSED RAM BLOCK DEVICE DRVIER
M:      Minchan Kim <minchan@kernel.org>
M:      Nitin Gupta <ngupta@vflare.org>
R:      Sergey Senozhatsky <sergey.senozhatsky.work@gmail.com>
L:      linux-kernel@vger.kernel.org
S:      Maintained
F:      Documentation/admin-guide/blockdev/zram.rst
F:      drivers/block/zram/
```

**Comment by polarathene** [comment]
If you have zswap in use as well, note that it's memory pool cache will report allocations to swap devices including zram swap, even though zramctl will accurately report actual allocation AFAIK.

If you disable/clear the zswap cache you'd find the reported usage matches zramctl more accurately, while if you reset the zram swap device to clear it's data, the zswap cache usage for it still remains. That can be a bit misleading of a gotcha to be aware of :sweat_smile:

**Comment by karelzak** [comment]
BTW, if you have something that we can explain in man pages then send a patch.

**Comment by polarathene** [comment]
I'm not sure if it's something that belongs in zramctl docs? (maybe a FAQ, but I've not seen many people discuss the topic)

It's not really a fault of it, the misunderstanding (assuming my observation is correct) is that zswap in-memory compressed cache if present is pretending some of it's cached data belongs to a swap device, even if those pages aren't actually allocated on the swap device.

`zramctl` isn't doing anything wrong there, and presumably for regular swap metrics, it's important for it to work correctly by reporting whatever zswap is managing as being backed by swap devices?

We'd need @rpodgorny to also respond that they were using zswap with zram to confirm my theory :sweat_smile:
