### ISSUE TITLE
configure does not support enabling term-utils/script* after --disable-all-programs

### ISSUE THREAD

**Issue by ppenguin** [karelzak/util-linux#1244]
**Describe the bug**
It is not possible to selectively build any of `term-utils/script*` when trying with `./configure --disable-all-programs --enable-script`.

It appears `configure` does not support selecting `script`:

```
configure: WARNING: unrecognized options: --enable-script
```

even though `enable-...` works for most other programs.

**To Reproduce**
1. `./autogen.sh`
2. `./configure --disable-all-programs --enable-script`
3. `make script` or `make`

**Expected behavior**
`script` is built.

**Desktop (please complete the following information):**
 - OS: `manjaro linux`

**Additional context**
Pretty much all programs can be selected with `--enable-*` except `script*` (and possibly a few others).
Since I'm doing cross-compiling for (semi-)embedded I seek to limit the number of built programs to the minimum to avoid having to provide additional dev libs.

**Comment by karelzak** [comment]
I have added --disbale-scriptutils to disable script, scriptreplay and scriptlive. It seems better than add --disable-* for each of the script(1) related utils.
