### ISSUE TITLE
util-linux 2.36.2 osx build failure

### ISSUE THREAD

**Issue by chenrui333** [karelzak/util-linux#1251]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure</summary>

```
lib/procutils.c:16:10: fatal error: 'sys/vfs.h' file not found
#include <sys/vfs.h>
         ^~~~~~~~~~~
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1895732139
relates to https://github.com/Homebrew/homebrew-core/pull/71109

**Comment by karelzak** [comment]
Fixed, I hope. Please, test it on OSX.

**Comment by bayandin** [comment]
Yep, that helped, thanks @karelzak!
`util-linux` has been updated to 2.36.2 in homebrew https://github.com/Homebrew/homebrew-core/pull/71750
