### ISSUE TITLE
[Feature Request] Create mountpoint automatically with `mount` if it doesn't already exist

### ISSUE THREAD

**Issue by Atralb** [karelzak/util-linux#1253]
It would be a cool reduction of characters in our scripts, especially if it also makes `umount` also automatically delete the directory afterwards (in the spirit of hot plugging), while not being too difficult to code IMHO.

However I may totally be wrong on that question, I don't know any C, nor the codebase.

Just thought I'd leave the idea there, in case it would inspire someone more experienced and talented than me to tackle on the task.

**Comment by karelzak** [comment]
Implemented for pretty long time ;-)

man mount:

       X-mount.mkdir[=mode]
              Allow to make a target directory (mountpoint) if it does not exit yet.  The optional argument mode specifies the
              filesystem  access  mode  used for mkdir(2) in octal notation.  The default mode is 0755.  This functionality is
              supported only for root users or when mount executed without suid permissions.
