### ISSUE TITLE
Missing release documentations.

### ISSUE THREAD

**Issue by johannbg** [karelzak/util-linux#1254]
The NEWS file being shipped with the latest release ( https://github.com/karelzak/util-linux/releases/tag/v2.36.2 ) reference to non existing release Documentations for the minor releases ( 2.36.2, 2.36.1 )

util-linux 2.36.2: Feb 12 2021
* see Documentation/releases/v2.36.2-ReleaseNotes <--- does not exist
 
util-linux 2.36.1: Nov 16 2020
* see Documentation/releases/v2.36.1-ReleaseNotes <-- does not exist.

On top of that the NEWS file in the root ( https://github.com/karelzak/util-linux/blob/master/NEWS ) has not been updated with these changes so the release tool/script is not updating the NEWS file for minor releases when it creates the release as well as generating/creating the minor release documentation accordingly.

**Comment by karelzak** [comment]
Not sure if I good understand, maybe you forgot to switch a branch on github UI. I see the files on github:

https://github.com/karelzak/util-linux/blob/v2.36.2/Documentation/releases/v2.36.1-ReleaseNotes
https://github.com/karelzak/util-linux/blob/v2.36.2/Documentation/releases/v2.36.2-ReleaseNotes

and in git tree:
```
 $ git checkout -f stable/v2.36
Switched to branch 'stable/v2.36'

$ ls -la   Documentation/releases/v2.36.*-ReleaseNotes
-rw-rw-r-- 1 kzak kzak 4560 Feb 22 11:05 Documentation/releases/v2.36.1-ReleaseNotes
-rw-rw-r-- 1 kzak kzak 3087 Feb 22 11:05 Documentation/releases/v2.36.2-ReleaseNotes
```

and I see the files also in https://www.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.2.tar.xz tarballs.

I see the files also in tarballs generated by github ( https://github.com/karelzak/util-linux/releases/tag/v2.36.2 ).

Note that the master branch is not affected by changes in the stable/ branches, these branches are independent. See https://github.com/karelzak/util-linux/blob/master/README#L96. The master branch is used only for v2.<y> release.

**Comment by johannbg** [comment]
@karelzak Yup PEBKAC branch issue, closing...
