### ISSUE TITLE
mountpoint exits with status 1 on I/O error

### ISSUE THREAD

**Issue by Silveere** [karelzak/util-linux#1260]
util-linux 2.36.2, Arch Linux on WSL2

When the `mountpoint` command is ran and encounters an I/O error, it exits with a status of 1. This makes it impossible to differentiate if the directory is a mount point with an error such as a disconnected network filesystem, or if it is just a regular directory; since it is the same exit status as when `mountpoint` is ran on a regular directory

**Comment by karelzak** [comment]
Sounds like a good point. Fixed, now:
```
EXIT STATUS
       mountpoint has the following exit status values:

       0      success; the directory is a mountpoint, or device is block device on --devno

       1      failure; incorrect invocation, permissions or system error

       32     failure; the directory is not a mountpoint, or device is not a block device on --devno

```
