### ISSUE TITLE
`prlimit` command-line argument parsing bug

### ISSUE THREAD

**Issue by pxeger** [karelzak/util-linux#1265]
I think there is a bug in the command-line argument parsing of `prlimit(1)`. Or, at least, the actual behaviour does not match the documentation and the standard GNU style.

Specifically, I would expect this (for example) to work:

```bash
prlimit -f=100:100
```

But this gives an error `failed to parse FSIZE limit`. Instead, I have to use two dashes:

```bash
prlimit --f=100:100
```

which is not what the documentation says, and not in the typical GNU option style. The behaviour works as expected with the long option style (like `--fsize=100:100`)

Additionally and maybe unrelatedly, you can't use `--fsize 100:100` (as two separate arguments); you have to use an equals sign in between. This is not really very important though. 

I'm using `prlimit from util-linux 2.36.2` from the [Arch Linux package](https://archlinux.org/packages/core/x86_64/util-linux/).

**Comment by karelzak** [comment]
Thanks! Good catch.

> Additionally and maybe unrelatedly, you can't use --fsize 100:100 (as two separate arguments); you have to use an equals sign > in between. This is not really very important though.

The argument is optional (you can use alone '-f'), so '=' is necessary otherwise there is no way how to interpret the argument.
