### ISSUE TITLE
Help with script usage!! 

### ISSUE THREAD

**Issue by pooja-choudhari** [karelzak/util-linux#1268]
I am trying to use script command to record my shell activity!! I wanted to check if there is a way to skip recording few commands like vi, less(visual editing). This can cause loopback recording of the activity when opening a typescript log file.

-c command starts an records on particular function but I need to log everything and for a few commands skip recording. Any helpful pointers?

**Comment by karelzak** [comment]
For now, it's impossible. I'll think about it, the problem is that script(1) works per-char, so a complete line with a "command" is very often multiple lines in the log.

**Comment by pooja-choudhari** [comment]
Okay thank you!! Are there good practices/examples to start script when a particular user is switched or when a process is detected ?

**Comment by karelzak** [comment]
> Okay thank you!! Are there good practices/examples to start script when a particular user is switched or when a process is detected ?

Sorry for the delay, I've missed your question. I know that some people use it in this way for some paranoid setups to record command-line activities, but personally, I have no experience with it.
