### ISSUE TITLE
feature request: rfkill toggle

### ISSUE THREAD

**Issue by rpodgorny** [karelzak/util-linux#1269]
"rfkill toggle" would be a nice addition to "rfkill block" and "rfkill unblock" - so one can easily map "rfkill toggle wifi" to a keyboard shortcut without resolving to creating custom script which parses "rfkill list" etc...

**Comment by karelzak** [comment]
Good idea. 

I have implemented it in the topic/rfkill branch, but it's absolutely not tested yet (I'm on a workstation without any wireless device). I'm going to test it later (or you can try it ;-)).

**Comment by rpodgorny** [comment]
wow, that was fast!

...compiled and successfully tested on current 64bit arch linux.

p.s.: i did not really study the implementation but i've noticed the following in rfkill linux documentation:

https://www.kernel.org/doc/html/latest/driver-api/rfkill.html

```

soft block

    writable radio block (need not be readable) that is set by the system software.

```

...that would mean the proper implementation may be impossible. :-(

still, i'd be happy for the changes you've made to be included!

**Comment by karelzak** [comment]
The "soft" setting is used also by block/unblock, so the toggle is no exception and it works in the same way.

**Comment by rpodgorny** [comment]
> The "soft" setting is used also by block/unblock, so the toggle is no exception and it works in the same way.

yeah but i meant something different - i assume the logic goes like this:

1. read the current soft block state
2. set the opposite

...step 1 may be theoretically unavailable/unreliable? but i know basically nothing about the inner workings so it may be fine - just wanted to mention that. ;-)

**Comment by karelzak** [comment]
Well, if read() is unavailable then it ends with an error or hangs up if the kernel return EAGAIN. Not sure if we have any other way.

**Comment by karelzak** [comment]
Merged to the master branch.
