### ISSUE TITLE
Btrfs subvolume in lsblk

### ISSUE THREAD

**Issue by 13werwolf13** [karelzak/util-linux#1272]
If you have in fstab one section of btrfs with its subvolume mentioned several times then lsblk will show only the last point of mounting. I can't say it's a big problem, but it's definitely a problem.

**Comment by karelzak** [comment]
Already fixed,  see https://github.com/karelzak/util-linux/commit/c6648d2db1716978c8344c046ea6c94a68d27238
it will be in the next release v2.37 -)

**Comment by karelzak** [comment]
Note that the new column "MOUNTPOINTS" (pl.) will be used in the default output instead of the original "MOUNTPOINT".

**Comment by 13werwolf13** [comment]
> Already fixed, see [c6648d2](https://github.com/karelzak/util-linux/commit/c6648d2db1716978c8344c046ea6c94a68d27238)
> it will be in the next release v2.37 -)

Fastest fix in the wild west ))
