### ISSUE TITLE
Cfdisk allows work on the partition it's run from.

### ISSUE THREAD

**Issue by TheGamingCoderNoob** [karelzak/util-linux#1278]
This is a really big issue. Most partition editors don't allow this, and for good reason. I almost had to rewrite my partition table! Add a check to see if the partition modified is the one it's run from.

**Comment by karelzak** [comment]
We can add an extra warning when you want to modify a disk that is in use. Not sure about individual partitions. I'll think about it.

**Comment by TheGamingCoderNoob** [comment]
> We can add an extra warning when you want to modify a disk that is in use. Not sure about individual partitions. I'll think about it.

The disk thing is what i want, yes.
