### ISSUE TITLE
Check pointer before use in libsmartcols/src/buffer.c

### ISSUE THREAD

**Issue by XidongWang-coder** [karelzak/util-linux#1279]
In function _buffer_append_data()_ in libsmartcols/src/buffer.c, it's better to check _buf->cur_ and _buf->begin_ at line 61 before use. _buf->cur_ should also be checked before use at line 65. 
https://github.com/karelzak/util-linux/blob/e741653d22ac7a42cc80a3720da1edc7def5ad73/libsmartcols/src/buffer.c#L51-L68

This is similar to the function _ul_buffer_append_data()_ in lib/buffer.c. A previous similar fix is in [https://github.com/karelzak/util-linux/commit/f831651e3abe5eef3eaf6c5148268a3358705a8d](url).

**Comment by karelzak** [comment]
Good point.

The ideal solution would be to use ul_buffer_* also in libsmartcols, or keep libsmartcols/src/buffer.c as an extension to lib/buffer.c.
