### ISSUE TITLE
zramctl(8) man page outdated

### ISSUE THREAD

**Issue by zeha** [karelzak/util-linux#1283]
Someone reported this bug against Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969656

The submitter claims this paragraph is outdated, giving the reason "Since Kernel 4.7, it defaults to one stream per CPU":

> Regardless of the value passed to this attribute, ZRAM will always
> allocate multiple compression streams - one per online CPU - thus
> allowing several concurrent compression operations. The number of
> allocated compression streams goes down when some of the CPUs
> become offline. There is no single-compression-stream mode anymore,
> unless you are running a UP system or have only 1 CPU online.

In the current man page, this is kept as the description for "--streams": "The default is one stream."

Unfortunately I know exactly nothing about zramctl, so I would appreciate if someone could confirm this and provide a patch.

**Comment by mator** [comment]
kernel commid id https://github.com/torvalds/linux/commit/da9556a2367cf2261ab4d3e100693c82fb1ddb26#diff-4c7ea5d7aa5010eb97dfee5cb720d3bedc72d62f8535e28f5b0819e2268f0056

documentation link https://www.kernel.org/doc/html/latest/admin-guide/blockdev/zram.html#set-max-number-of-compression-streams

current man page reads as:
```
       -t, --streams number
              Set the maximum number of compression streams that can be used for the device.  The default is one stream.
```

we could probably try to rephrase it like `the default is use all CPUs and one stream for kernels older than 4.6`

**Comment by karelzak** [comment]
Thanks for your report and references to the kernel tree!
