### ISSUE TITLE
hwclock does not work properly when compiled on 32-bit linux with 64-bit time_t

### ISSUE THREAD

**Issue by arbego** [karelzak/util-linux#1293]
When compiling `hwclock` on a 32-bit linux (kernel 5.1+) with musl 1.2+ (or glibc 2.32+) warnings are generated. In consequence `hwclock` does not work properly when performing a `--hctosys` with dates beyond year 2038. This is mainly because when `/etc/adjtime` file is written/read the width of the variable in the format string is wrong.

For example in file `sys-utils/hwclock.c`:

    sscanf(line2, "%ld", &adjtime_p->last_calib_time);

This does not work when `last_calib_time` (time_t) is 64-bit wide. Thus `"%lld"`should be used instead of `"%ld"`.

Also in function `struct timeval time_inc(...)` there is a downcast happening when `time_t` is 64-bit:

    newtime.tv_sec = addend.tv_sec + (int)increment;
    newtime.tv_usec = addend.tv_usec + (increment - (int)increment) * 1E6;

This is because the two `(int)` casts will snip 4 bytes off of `addend.tv_sec` and `addend.tv_usec` leading to odd behaviour. The casts should be changed to `(time_t)` casts.

**Comment by arbego** [comment]
Fixed in #1294

**Comment by karelzak** [comment]
Closing. Fixed by #1294
