### ISSUE TITLE
[enhancement] add sparc64 cpu cache information

### ISSUE THREAD

**Issue by mator** [karelzak/util-linux#1296]
Hello!
Is it possible to add linux sparc64 cpu cache information to the output of `lscpu`? Someone can use existing /sys fs archive/tree in [util-linux.git/tests/ts/lscpu/dumps/sparc64.tar.gz](https://github.com/karelzak/util-linux/blob/master/tests/ts/lscpu/dumps/sparc64.tar.gz) for getting cache information. 
Thanks!

**Comment by karelzak** [comment]
Implemented.
```
$ lscpu --caches
NAME ONE-SIZE ALL-SIZE WAYS TYPE        LEVEL SETS PHY-LINE COHERENCY-SIZE
L1d       16K      96K      Data            1                           32
L1i       16K      96K      Instruction     1                           32
L2         1M       6M      Unified         2                           64
```
Unfortunately, I'm not sure if it's correct for all cases. The dumps that I have do not contain any information on how the caches are shared between CPUs, so my code assumes that it's not shared at all.
