### ISSUE TITLE
Meson build fails if systemd is not found

### ISSUE THREAD

**Issue by concatime** [karelzak/util-linux#1301]
As you probably know why, systemd should not be a hard-dependency.
That being said, both master and v2.37-rc1 fail with this:
```
../util-linux-2.37-rc1/meson.build:713:0: ERROR: 'not-found' is not a pkgconfig dependency
```
Relevant [part](/karelzak/util-linux/blob/v2.37-rc1/meson.build#L713):
```
systemdsystemunitdir = systemd.get_pkgconfig_variable('systemdsystemunitdir')
```

Thank you!

**Comment by karelzak** [comment]
Good catch. Thanks!
