### ISSUE TITLE
mounting nfs server which is down blocks all other nfs mounts on same machine

### ISSUE THREAD

**Issue by alex-vmw** [karelzak/util-linux#1309]
mounting nfs server which is down blocks all other nfs mounts on same machine. The default timeout seems to be set at 3mins, but for those 3 minutes all other mount commands for any other nfs servers just hang. Why does a single hanging NFS mount blocking all other nfs mounts on the same machine?

How to re-create:
1. Try to mount some NFS Server at an IP that you know is down. For example, if you know that 10.10.10.10 IP is down, run `mkdir /tmp/test; mount 10.10.10.10:/test /tmp/test`.
2. At this point the mount command will hang for 3 minutes.
3. Open a second terminal on your machine and try to mount an NFS server which you know 100% works. For example, if you know that NFS mount for 10.10.20.20:/test2 should succeed, run `mkdir /tmp/test2; mount 10.10.20.20:/test2 /tmp/test2`.
4. At this point the second mount command will also hang until the first mount command in another terminal will timeout.

P.S. This issue, combined with Kubernetes, where you can easily have multiple pods constantly trying to mount down NFS servers, results in linux nodes that can't mount anything because mount commands are just constantly hanging.

**Comment by karelzak** [comment]
In this case, mount(8) from util-linux is just a stupid wrapper for kernel and mount.nfs (from nfs-utils) functionality. I do not see a way how to improve it. It would be better to talk to NFS developers. Please, see https://linux-nfs.org/wiki/index.php/Main_Page.

Thanks.
