### ISSUE TITLE
lscpu does not show current frequency anymore

### ISSUE THREAD

**Issue by t-8ch** [karelzak/util-linux#1314]
With v2.37-rc2 and current master the default invocation of `lscpu` does not print the current CPU frequency anymore.

**Comment by karelzak** [comment]
The question is what does it mean "current CPU frequency", it makes sense for systems with one CPU only. I have added MHZ column to the default -e, --extended output. For example
```
$ lscpu -e
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE    MAXMHZ   MINMHZ      MHZ
  0    0      0    0 0:0:0:0          yes 4400.0000 800.0000  800.000
  1    0      0    1 1:1:1:0          yes 4400.0000 800.0000 4400.000
  2    0      0    2 2:2:2:0          yes 4400.0000 800.0000 2900.000
  3    0      0    3 3:3:3:0          yes 4400.0000 800.0000 2900.000
  4    0      0    0 0:0:0:0          yes 4400.0000 800.0000 4218.095
  5    0      0    1 1:1:1:0          yes 4400.0000 800.0000 4400.000
  6    0      0    2 2:2:2:0          yes 4400.0000 800.0000 3532.777
  7    0      0    3 3:3:3:0          yes 4400.0000 800.0000  800.000

```

**Comment by t-8ch** [comment]
Thanks!

It could also show the current frequencies for all CPUs.
Either one CPU per line, or all of them in one line.

For me the only regular usecase of lscpu is to check the current CPU frequencies.
And while I now know how to do this with 2.37, I suspect other users to use lscpu similarly.
So this may lead to some regression reports as soon as 2.37 get's released.

**Comment by karelzak** [comment]
Well, it's no a problem to have a system with 64 CPUs these days. I don't think we want to see all the frequencies in the default output :-)

Note that the old version shows only MHz from the first CPU, so the information is pretty useless.

If you have a system with more CPUs then try 
```
watch -n 0.5  "lscpu -e=CPU,MHZ"
```
to see how often the frequencies are changed and how big differences are between the individual CPUs.

I think we need something better for this purpose than the default lscpu output. Maybe add --freq as a shortcut for "lscpu -e=CPU,MHZ" and add some visualization to the output (like htop uses).

Something like:
```
CPU    MHZ   Use  
 0    2900   65% ||||||||||||
 1    4400  100% ||||||||||||||||||||
 2     800   18% ||
 3     800   18% ||
 4     800   18% ||
 5    4400  100% ||||||||||||||||||||
 6    4044   91% ||||||||||||||||||  
 7    2800   63% ||||||||||||
```
I'll add it to the TODO for the next version.

**Comment by karelzak** [comment]
Now when I think about it we can calculate one percent number for all CPUs (sum of all MAXMHZ = 100%). This is something that will be useful in the default output.

**Comment by t-8ch** [comment]
While I like the ideas, I fear that anything called "usage" and being a percentage may be confused with the cpu usage as shown by htop.

**Comment by karelzak** [comment]
I think about "USEMHZ%" as column name and ""CPU use MHz:  n%" in the summary output.

**Comment by t-8ch** [comment]
My only other idea would be "SCALINGMHZ" and "CPU scaling MHz: n%".
("Scaling" seems to be what the kernel is using for this)

**Comment by karelzak** [comment]
OK, let's try it with "scaling" rather than "use". Implemented in the "next" branch. maybe we can later backport it to v2.37.x, we will see.

Summary output:
```
$ lscpu
...
  Model name:           Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    CPU family:         6
    Model:              60
    Thread(s) per core: 2
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           3
    CPU(s) scaling MHz: 61%
    CPU max MHz:        4400.0000
    CPU min MHz:        800.0000
...
```
and per CPU:
```
$ lscpu -e=CPU,MAXMHZ,MINMHZ,MHZ,SCALMHZ%
CPU    MAXMHZ   MINMHZ      MHZ SCALMHZ%
  0 4400.0000 800.0000 2800.000      64%
  1 4400.0000 800.0000 4000.146      91%
  2 4400.0000 800.0000 2800.000      64%
  3 4400.0000 800.0000 2800.000      64%
  4 4400.0000 800.0000 2800.000      64%
  5 4400.0000 800.0000 4400.000     100%
  6 4400.0000 800.0000  800.000      18%
  7 4400.0000 800.0000 2800.000      64%

```


Thanks for your feedback!

**Comment by t-8ch** [comment]
Looks good.
Thanks for your work!
