### ISSUE TITLE
after successfully autogen, configure make 2.36.1

### ISSUE THREAD

**Issue by noknok79** [karelzak/util-linux#1321]
after i successful autogen, configure, make the source of 2.36.1 the app still not taking effect.

[root@DESKTOP-NOKIE-wsl util-linux-2.36.1]# runuser --version
runuser from util-linux 2.29

i have restarted the machine wsl2 but still the same.

What I am missing? please help. thank you!

**Comment by karelzak** [comment]
Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

**Comment by noknok79** [comment]
i have tried make install-strip, but the OS turns corrupted. I was wondering, what are the requirements for the installation?

I also tried the 2.31-1, its the same, the OS turs courrupted, even i have set the selinux=permissive  or disable.
thank you!

    On Wednesday, 26 May 2021, 3:50:06 pm GMT+8, Karel Zak ***@***.***> wrote:  
 
 


Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try ./runuser --version to execute the binary from the build directory?

**Comment by noknok79** [comment]
> 
> 
> Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

any docs on how to make compile the package based on the CenOS7 rpm? maybe that's the reason why the compile does not take effect.

thank you!

**Comment by noknok79** [comment]
> 
> 
> Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

do we have spec files for how to packed these sources? I have been trying to create the RPM for this, but after the make, I do not have any idea how to install this to my CentOS7.

thank you.

**Comment by noknok79** [comment]
> 
> 
> Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

I was able to create specs file to packed for RPM but when I tried to install the RPM i'm receveing error

error: Failed dependencies:
        /sbin/nologin is needed by (installed) openssh-7.4p1-21.el7.x86_64

I receive the same errors with make or make install as command for install. here's the spec i have created.

Name:           util-linux
Version:        2.34
Release:        0
Summary:        Specifically compiled for the use in genie-wsl2 for CentOS7/RHEL7
Group:          Applications/Utilities
License:        GPL
URL:            http://
Vendor:         Personal Package
Source:         https://github.com/karelzak/util-linux/archive/refs/tags/util-linux-2.34.tar.gz
Prefix:         %{_prefix}
Packager:       tarball
BuildRoot:      %{_tmppath}/%{name}-root

%description
util-linux utilties specifically to run genie-wsl for CentOS7/RHEL7

%prep
%setup

%build
./autogen.sh && ./configure --disable-nologini && make

%install
make install RPM_OPT_FLAGS="$RPM_OPT_FLAGS"

%clean

%files

%defattr(-,root,root)


thanks

**Comment by noknok79** [comment]
> 
> 
> Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

trying to complie the source runuser.c in the build directory i'm getting an error

[root@DESKTOP-NOKIE login-utils]# gcc runuser.c -o test
/tmp/ccIYu89u.o: In function `main':
runuser.c:(.text+0x21): undefined reference to `su_main'
collect2: error: ld returned 1 exit status

[root@DESKTOP-NOKIE login-utils]# ls
auth.c       chfn.c     last.1     libuser.h    lslogins.1            newgrp.1   runuser.1        setpwnam.h   sulogin.8           sulogin.o   vipw.8
auth.h       chsh.1     lastb.1    login.1      lslogins.c            newgrp.c   runuser.c        su.1         sulogin.c           utmpdump.1  vipw.c
ch-common.c  chsh.c     last.c     login.c      lslogins-logindefs.o  nologin.8  selinux_utils.c  su.c         sulogin-consoles.c  utmpdump.c
ch-common.h  islocal.c  last.o     logindefs.c  lslogins-lslogins.o   nologin.c  selinux_utils.h  su-common.c  sulogin-consoles.h  utmpdump.o
chfn.1       islocal.h  libuser.c  logindefs.h  Makemodule.am         nologin.o  setpwnam.c       su-common.h  sulogin-consoles.o  vigr.8

**Comment by noknok79** [comment]
> 
> 
> Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

no binaries of runuser inside the build folder

[root@DESKTOP-NOKIE util-linux-2.36.1]# ./r
raw          readprofile  rename       renice       resizepart   rev          rfkill       rtcwake

this is probably the reason, why the runuser is not taking effect as there is no binary for the runuser application.

**Comment by noknok79** [comment]
> 
> 
> Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

tryiing to run from the source file of runuser still getting errors.

[root@DESKTOP-NOKIE login-utils]# pwd
/util-linux-2.29.1/login-utils
[root@DESKTOP-NOKIE login-utils]# gcc -o runuser runuser.c
/tmp/cc02Q4x6.o: In function `main':
runuser.c:(.text+0x21): undefined reference to `su_main'
collect2: error: ld returned 1 exit status
[root@DESKTOP-NOKIE login-utils]# ls
auth.c       chfn.c     last.1     libuser.h    lslogins.1            newgrp.1   runuser.1        setpwnam.h   sulogin.8           sulogin.o   vipw.8
auth.h       chsh.1     lastb.1    login.1      lslogins.c            newgrp.c   runuser.c        su.1         sulogin.c           utmpdump.1  vipw.c
ch-common.c  chsh.c     last.c     login.c      lslogins-logindefs.o  nologin.8  selinux_utils.c  su.c         sulogin-consoles.c  utmpdump.c
ch-common.h  islocal.c  last.o     logindefs.c  lslogins-lslogins.o   nologin.c  selinux_utils.h  su-common.c  sulogin-consoles.h  utmpdump.o
chfn.1       islocal.h  libuser.c  logindefs.h  Makemodule.am         nologin.o  setpwnam.c       su-common.h  sulogin-consoles.o  vigr.8

**Comment by noknok79** [comment]
> 
> 
> Is it after "make install"? ... but note that "make install" is not recommended if you use distribution based on packages (e.g. deb or rpm). Did you try `./runuser --version` to execute the binary from the build directory?

configure: WARNING: ncursesw, ncurses or slang library not found; not building irqtop
configure: WARNING: linux/blkzoned.h header not found; not building blkzone
checking for LIBUSER... no
configure: WARNING: PAM header file not found; not building chfn_chsh
configure: WARNING: PAM header file not found; not building login
configure: WARNING: PAM header file not found; not building su
configure: WARNING: PAM header file not found; not building runuser
configure: WARNING: ncursesw or ncurses libraries not found; not building ul
configure: WARNING: ncursesw or ncurses libraries not found; not building more
configure: WARNING: ncursesw or ncurses library not found; not building setterm

how to fix this? PAM header file not found, not buildin runuser

**Comment by karelzak** [comment]
`# runuser --version` executes binary from $PATH, `# ./runuser --version` from the current directory. https://askubuntu.com/questions/320632/why-do-i-need-to-type-before-executing-a-program-in-the-current-directory

Note that --disable-runuser means that runuser will not be compiled.

**Comment by noknok79** [comment]
> 
> 
> `# runuser --version` executes binary from $PATH, `# ./runuser --version` from the current directory. https://askubuntu.com/questions/320632/why-do-i-need-to-type-before-executing-a-program-in-the-current-directory
> 
> Note that --disable-runuser means that runuser will not be compiled.

thereafter ./autogen.sh then ./confugre then make

there were no runuser in green color meaning binaries (I am using powershell) so i cannot display it. when run just plain ./configures, I am getting a PAM header errors, so runuser will not appear.

any howto to fix PAM header?
