### ISSUE TITLE
How make arm compiled binary on windows 7 x64 ?

### ISSUE THREAD

**Issue by Mitezuss** [karelzak/util-linux#1322]
How i can compile ? 

or can anyone give the fstrim arm 2.37 rc2 binary ? Thank

**Comment by karelzak** [comment]
The command fstrim is Linux specific (it's a wrapper that provides a command-line interface for features implemented by the Linux kernel), it will not work on another OS. Anyway, I guess you can download some binary util-linux package for ARM and extract the binary from the package.

**Comment by Mitezuss** [comment]
Yes, i wanna make a arm binary for android. I know this is possible, but idk how cross-compile on windows =c

**Comment by karelzak** [comment]
Frankly, I have no clue how to cross-compile for Android on Windows. Sounds like you need to ask on some Android-related forum.
