### ISSUE TITLE
configure: WARNING: unrecognized options: --enable-mkfs

### ISSUE THREAD

**Issue by multiple1** [karelzak/util-linux#1326]
Hello!

My goal is to build only `mkfs` using this cmd:
`./configure --disable-all-programs --enable-mkfs`

but this results in:
`configure: WARNING: unrecognized options: --enable-mkfs`

Is this supposed to work or am I missing something?

**Comment by karelzak** [comment]
Fixed by commit 5ec1108c00, The change will be in v2.37.
