### ISSUE TITLE
Question: mount -o remount flush & sync guarantees

### ISSUE THREAD

**Issue by dumblob** [karelzak/util-linux#1330]
Does mount -o remount,rw on an already rw-mounted mountpoint **guarantee** a flush & sync with **all** existing filesystems Linux supports?

If so, is it only `util-linux` behaving like that or may one anticipated flushing on remount also under other POSIX systems? I couldn't find it in POSIX **explicitly**, but it might be **implicitly** implied due to some other POSIX-mandated behavior.

If there are any exceptions (maybe `tmpfs` etc.), could you list them?

**Comment by karelzak** [comment]
It would be better to ask kernel developers (mount(8) is just syscall wrapper only in this case).

I guess that remount behavior is filesystem-specific and depends on the kernel FS driver. I see in VFS code that it only shrinks the directory cache and then it calls superblock function, but again -- ask at kernel mailing list or fs-devel list :-)

**Comment by dumblob** [comment]
Thanks for the push in the right direction! I found out `sync_filesystem` is since 2014 (Theodore Tso provided the patch) not anymore part of VFS but of each individual filesystem where it really depends what will happen (there are even filesystems which do **not** flush when remounting rw->ro).

E.g. for ext4 remount rw->rw does **not** flush buffers. I didn't check others, but I suppose XFS will also **not** flush.
