### ISSUE TITLE
Cfdisk wakes up all disks and blocks until they're up

### ISSUE THREAD

**Issue by Atemu** [karelzak/util-linux#1331]
When selecting a partition (i.e. after having created one) cfdisk wakes my hard drives and completely blocks until they've up.

This is extremely annoying because A. I usually want my drives to stay asleep when I'm partitioning a completely unrelated one and B. don't want the partitioning program to block for multiple seconds thanks to that.

Repro:

1. Have to HDDs, one asleep (drive B)
2. cfdisk -z A
3. Create a new partition
4. cfdisk blocks until drive is up
5. cfdisk shows partition metadata

A might need to have been formatted before.

**Comment by karelzak** [comment]
This is because cfdisk checks for a mounpoint (by libmount and it uses /dev/disk/by-partuuid). This is overkill for new partitions. 

Fixed (I hope). Thanks for your report!
