### ISSUE TITLE
2.37: pcre2 10.37 no longer provides posix API/ABI

### ISSUE THREAD

**Issue by kloczek** [karelzak/util-linux#1332]
https://vcs.pcre.org/pcre2/code/trunk/NEWS?revision=1310&view=markup

It would be good to move away from pcre2 posix API/ABI.

**Comment by karelzak** [comment]
Well, fortunately as the fallback solution we're able to use regex.h in hardlink.c. Not sure, if this has any impact on the features.

**Comment by kloczek** [comment]
At the moment looks like only util-linux and haproxy are still using pcre posix API (zabbix moved away from that code ~2 years ago).

Just as side comment/though ..
Someone should make a decision about kick off regex from glibc (it is really huge chunk of the glibc code because that implementation is really bloated) and start using pcre2  or focus on use glibc regex  .. everywhere :/

**Comment by karelzak** [comment]
Is there any documentation on how to easily convert from POSIX to native pcre2?

**Comment by kloczek** [comment]
I have no idea ..

**Comment by karelzak** [comment]
I have removed PCRE2 from hardlink. Now it uses classic libc regex.h only.  

Patches to use a more recent PCRE2 interface are welcomed.
