### ISSUE TITLE
lscpu does not show current cpu speed anymore.  just min and max

### ISSUE THREAD

**Issue by mrsteve0924** [karelzak/util-linux#1338]
after updating util-linux to ver. 2.37-1, lscpu does not show current cpu speed anymore.  just min and max

**Comment by karelzak** [comment]
Already fixed by https://github.com/karelzak/util-linux/commit/9b9e4f5d06be55f4b9e1a52b448055933df92c6b

For more detauls see: https://github.com/karelzak/util-linux/issues/1314
