### ISSUE TITLE
[Feature Request] Add partition start to `lsblk`

### ISSUE THREAD

**Issue by michael-schaller** [karelzak/util-linux#1340]
The `start` of a partition is currently only available via `/sys/class/block/<partition>/start` (needs to be multiplied with 512) or by printing the partition table details with a partitioning tool like `parted`.

Rationale: This would make it easier to write an integration test to ensure that partitions are properly aligned.

**Comment by karelzak** [comment]
I guess all you need to ensure that a partition is aligned is to see `/sys/block/disk/partition/alignment_offset`, you need zero there. If I good remember kernel calculates it for you (or export it from HW for whole-disk devices if alignment compensation by HW is enabled). The alignment_offset is also provided by lsblk in the ALIGNMENT column.

You can also read the start (offset) of the partition from udev, for example:
```
$ udevadm info /dev/sda1 | grep ID_PART_ENTRY
E: ID_PART_ENTRY_SCHEME=gpt
E: ID_PART_ENTRY_NAME=EFI\x20System\x20Partition
E: ID_PART_ENTRY_UUID=2062335e-51b6-49e8-bc3c-4c6d449e6805
E: ID_PART_ENTRY_TYPE=c12a7328-f81f-11d2-ba4b-00a0c93ec93b
E: ID_PART_ENTRY_NUMBER=1
E: ID_PART_ENTRY_OFFSET=2048
E: ID_PART_ENTRY_SIZE=409600
E: ID_PART_ENTRY_DISK=8:0
```
The nice thing is that you do not need to root permissions and access to the device.

Anyway, added to lsblk too.

**Comment by michael-schaller** [comment]
Thank you, Karel.

`alignment_offset` didn't work for our partition alignment integration test as we wanted to test an alignment to 1 MiB instead of the physical sector size. 1 MiB is apparently the [current recommendation](https://gparted.org/display-doc.php?name=help-manual#gparted-specify-partition-alignment). I'm however lost on what to believe in this [whole discussion](https://superuser.com/questions/1243559/is-partition-alignment-to-ssd-erase-block-size-pointless). *shrug*

**Comment by karelzak** [comment]
Ah, in this case, you're right. 

And yes, we decided to use 1 MiB as the default for good reason in fdisks and parted years ago. I still remember this discussion we had on IRC and the result was  https://people.redhat.com/msnitzer/docs/io-limits.txt and commit 40c7aaf3958c28b38772f38ee245b20afe3c1373. /me fills old :-)

**Comment by michael-schaller** [comment]
That document in conjunction with [this discussion](https://superuser.com/questions/1243559/is-partition-alignment-to-ssd-erase-block-size-pointless) seem to indicate that partition alignment to 1 MiB seems unnecessary. However 1 MiB is simpler to read and shouldn't be wrong in any case. Karel, thanks for the extra details.

**Comment by michael-schaller** [comment]
I couldn't find any good resources that would explain the origin of 1 MiB alignment recommendation though.

The only article I could find on the Window side that uses 1 MiB alignment is this one:
https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/disk-performance-slower-multiple-disks 

Even Wikipedia doesn't explain the origin of the 1 MiB alignment. https://en.wikipedia.org/wiki/Partition_alignment -> `1 MB partition alignment` -> `A typical practice for personal computers is to have each partition aligned to start at a 1 MiB (= 1,048,576 bytes) mark, which covers all common SSD page and block size scenarios, as it is divisible by all commonly used sizes - 1 MiB, 512 KiB, 128 KiB, 4 KiB, and 512 B.`

So to me it looks like 1 MiB alignment is a just good best practice so that one doesn't have to worry about the nitty gritty details.
And that is a best practice I can wholeheartedly agree with and I'm admittingly just satisfying my curiosity here. ;-)
