### ISSUE TITLE
mkswap on file full of holes gets stuck in an infinite loop

### ISSUE THREAD

**Issue by bcl** [karelzak/util-linux#1348]
This is related to https://bugzilla.redhat.com/show_bug.cgi?id=1971877, I think I see the problem:

https://github.com/karelzak/util-linux/blob/master/disk-utils/mkswap.c#L269

needs to check n to see if it is 0 and if so, exit the loop.

**Comment by karelzak** [comment]
Oh, you're right. It seems like pretty stupid code as we also use `n` later to access the array of extends (`fiemap->fm_extents[n - 1]`).
