### ISSUE TITLE
mount: man (8) does not document all overlayfs options

### ISSUE THREAD

**Issue by iam-TJ** [karelzak/util-linux#1350]
The section in `man 8 mount` for overlay is missing nine options which aren't documented elsewhere either and are useful features to be aware of and use.

From the kernel source in `fs/overlayfs/super.c` these are:
```
default_permissions
redirect_dir=
index=
userxattr
uuid=
nfs_export=
xino=
metacopy=
volatile
```
Kernel documentation for these is in `Documentation/filesystems/overlayfs.rst` but is scattered rather than summarised and difficult to digest.

A concise summary in the man page would be extremely helpful.

**Comment by iam-TJ** [comment]
It looks like `default_permissions` is now a no-op. I'm raising an issue about it on the `linux-unionfs` mailing list.

**Comment by karelzak** [comment]
Good points.

Do you want to send a patch to util-linux sys-utils/mount.8.adoc?

It would be also nice to add somewhere at the beginning of the file Documentation/filesystems/overlayfs.rst some very basic summary of the mount options. Now it's really hard to use.
