### ISSUE TITLE
setgroups desired in setgid + setuid situations

### ISSUE THREAD

**Issue by adelton** [karelzak/util-linux#1354]
When dropping privileges, it might be desirable to get rid of any supplementary groups that the setuid binary might have gotten. In a couple of places of util-linux code, `setgroups(0, NULL)` is used. It might be useful for security and consistency reasons to add them to the following code as well:

https://github.com/karelzak/util-linux/blob/master/lib/canonicalize.c#L174
https://github.com/karelzak/util-linux/blob/master/libblkid/src/topology/dm.c#L77-L80
https://github.com/karelzak/util-linux/blob/master/libblkid/src/topology/lvm.c#L86-L89
https://github.com/karelzak/util-linux/blob/master/libmount/src/context_umount.c#L699-L703
https://github.com/karelzak/util-linux/blob/master/libmount/src/context_mount.c#L648-L652
https://github.com/karelzak/util-linux/blob/master/sys-utils/mount.c#L57
https://github.com/karelzak/util-linux/blob/master/sys-utils/eject.c#L659
https://github.com/karelzak/util-linux/blob/master/sys-utils/swapon.c#L338
https://github.com/karelzak/util-linux/blob/master/sys-utils/umount.c#L122
https://github.com/karelzak/util-linux/blob/master/text-utils/more.c#L1253

An alternative would be to use `initgroups` but that seens like unnecessarily heavyweight approach.

**Comment by karelzak** [comment]
Please, review the commit 17fc869. 

I've created just one function that we can use everywhere to avoid possible mistakes.

**Comment by adelton** [comment]
LGTM. Thanks!
