### ISSUE TITLE
Exact utility location might be compile-time option, rather than cycling through paths

### ISSUE THREAD

**Issue by adelton** [karelzak/util-linux#1355]
The location of `dmsetup` and `lvdisplay` utilities might be ideally compile-time option determined in built-time, specific for particular environment or distribution, rather than cycling through hardcoded paths and using the first that exists, at

https://github.com/karelzak/util-linux/blob/master/libblkid/src/topology/dm.c#L52
https://github.com/karelzak/util-linux/blob/master/libblkid/src/topology/lvm.c#L57

**Comment by karelzak** [comment]
I don't think so, we still support /usr/local (etc.), and hardcoded paths without the ability to bypass distributions hardcoded default is a bad manner. This is Linux, we support humans creativity :-) I think it's an important to feature for low-level tools and libs.

And note, for the usual use-case (=mainstream distro) it's just one extra stat(), it's pretty cheap when the goal is to exec dmsetup and lvm. BTW, this libblkid functionality is very rarely used, I guess it's used by mkfs.xfs only.
