### ISSUE TITLE
When using the strto* family of function, errno should be checked

### ISSUE THREAD

**Issue by adelton** [karelzak/util-linux#1356]
When using the `strto*` family of functions, `errno` should be zeroed and then checked for the correctness of the conversion. In the following locations, this logic seems to be missing:

https://github.com/karelzak/util-linux/blob/master/libblkid/src/partitions/partitions.c#L1043
https://github.com/karelzak/util-linux/blob/master/libblkid/src/read.c#L304
https://github.com/karelzak/util-linux/blob/master/libmount/src/tab_parse.c#L54
https://github.com/karelzak/util-linux/blob/master/disk-utils/fsck.c#L172
https://github.com/karelzak/util-linux/blob/master/misc-utils/wipefs.c#L337
https://github.com/karelzak/util-linux/blob/master/misc-utils/lslocks.c#L196
https://github.com/karelzak/util-linux/blob/master/misc-utils/kill.c#L179
https://github.com/karelzak/util-linux/blob/master/sys-utils/lsmem.c#L351
https://github.com/karelzak/util-linux/blob/master/libblkid/src/probe.c#L1335
https://github.com/karelzak/util-linux/blob/master/libblkid/src/read.c#L302
https://github.com/karelzak/util-linux/blob/master/libblkid/src/read.c#L307
https://github.com/karelzak/util-linux/blob/master/libblkid/src/read.c#L309
https://github.com/karelzak/util-linux/blob/master/libmount/python/pylibmount.c#L225
https://github.com/karelzak/util-linux/blob/master/libmount/src/tab_parse.c#L70
https://github.com/karelzak/util-linux/blob/master/libmount/src/context_veritydev.c#L64
https://github.com/karelzak/util-linux/blob/master/libuuid/src/parse.c#L73-L82
https://github.com/karelzak/util-linux/blob/master/login-utils/lslogins.c#L914
https://github.com/karelzak/util-linux/blob/master/sys-utils/hwclock-rtc.c#L428
https://github.com/karelzak/util-linux/blob/master/sys-utils/lscpu-virt.c#L169
https://github.com/karelzak/util-linux/blob/master/sys-utils/ipcrm.c#L132
https://github.com/karelzak/util-linux/blob/master/sys-utils/lsmem.c#L368
https://github.com/karelzak/util-linux/blob/master/sys-utils/lsmem.c#L454
https://github.com/karelzak/util-linux/blob/master/sys-utils/chmem.c#L267
https://github.com/karelzak/util-linux/blob/master/sys-utils/ipcmk.c#L125
https://github.com/karelzak/util-linux/blob/master/sys-utils/readprofile.c#L227

**Comment by karelzak** [comment]
Should be fixed now. Thanks for your report.
