### ISSUE TITLE
The __attribute__ format usage is not consistent

### ISSUE THREAD

**Issue by adelton** [karelzak/util-linux#1359]
In the following cases, the `__attribute__((format(  printf/scanf, ... ))` is likely missing:

https://github.com/karelzak/util-linux/blob/master/include/strv.h#L16
https://github.com/karelzak/util-linux/blob/master/include/strv.h#L26
https://github.com/karelzak/util-linux/blob/master/include/path.h#L26
https://github.com/karelzak/util-linux/blob/master/include/path.h#L87
https://github.com/karelzak/util-linux/blob/master/include/strutils.h#L51
https://github.com/karelzak/util-linux/blob/master/libfdisk/src/libfdisk.h.in#L878-L880
https://github.com/karelzak/util-linux/blob/master/libmount/src/mountP.h#L453
        ^^ here `fmt` should also likely be `const`

https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L144-L146
https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L701
https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L750
https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L764
https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L799
https://github.com/karelzak/util-linux/blob/master/misc-utils/logger.c#L622
https://github.com/karelzak/util-linux/blob/master/misc-utils/findmnt-verify.c#L47
https://github.com/karelzak/util-linux/blob/master/misc-utils/findmnt-verify.c#L57
https://github.com/karelzak/util-linux/blob/master/misc-utils/findmnt-verify.c#L67
https://github.com/karelzak/util-linux/blob/master/sys-utils/ldattach.c#L133
https://github.com/karelzak/util-linux/blob/master/sys-utils/eject.c#L113
https://github.com/karelzak/util-linux/blob/master/sys-utils/eject.c#L125
https://github.com/karelzak/util-linux/blob/master/term-utils/script.c#L150
https://github.com/karelzak/util-linux/blob/master/term-utils/script.c#L522
        ^^ here `msgfmt` should also likely be `const`

https://github.com/karelzak/util-linux/blob/master/term-utils/wall.c#L299
https://github.com/karelzak/util-linux/blob/master/text-utils/more.c#L1212
        ^^ here `cmd` should also likely be `const`

https://github.com/karelzak/util-linux/blob/master/include/c.h#L221

In the following cases, it is also likely missing, specifically with the third value to be 0:
https://github.com/karelzak/util-linux/blob/master/include/path.h#L58
https://github.com/karelzak/util-linux/blob/master/include/path.h#L63
https://github.com/karelzak/util-linux/blob/master/include/path.h#L66
https://github.com/karelzak/util-linux/blob/master/include/path.h#L75

In the following cases, the third value likely should not be 0 as the arguments are available to be checked:
https://github.com/karelzak/util-linux/blob/master/include/strv.h#L18
https://github.com/karelzak/util-linux/blob/master/include/strutils.h#L376

**Comment by karelzak** [comment]
> https://github.com/karelzak/util-linux/blob/master/include/strv.h#L16
Fixed.

> https://github.com/karelzak/util-linux/blob/master/include/strv.h#L26
No formatting, list of strings terminated by NULL.

> https://github.com/karelzak/util-linux/blob/master/include/path.h#L26
Fixed.

> https://github.com/karelzak/util-linux/blob/master/include/path.h#L87
Fixed.

> https://github.com/karelzak/util-linux/blob/master/include/strutils.h#L51
No formatting, list of strings terminated by NULL.

> https://github.com/karelzak/util-linux/blob/master/libfdisk/src/libfdisk.h.in#L878-L880
Fixed.

> https://github.com/karelzak/util-linux/blob/master/libmount/src/mountP.h#L453
> ^^ here `fmt` should also likely be `const`
Fixed.
 
> https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L144-L146
> https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L701
> https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L750
> https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L764
> https://github.com/karelzak/util-linux/blob/master/disk-utils/cfdisk.c#L799
Fixed (all).

> https://github.com/karelzak/util-linux/blob/master/misc-utils/logger.c#L622
Fixed.

> https://github.com/karelzak/util-linux/blob/master/misc-utils/findmnt-verify.c#L47
> https://github.com/karelzak/util-linux/blob/master/misc-utils/findmnt-verify.c#L57
> https://github.com/karelzak/util-linux/blob/master/misc-utils/findmnt-verify.c#L67
Fixed (all).

> https://github.com/karelzak/util-linux/blob/master/sys-utils/ldattach.c#L133
Fixed.

> https://github.com/karelzak/util-linux/blob/master/sys-utils/eject.c#L113
> https://github.com/karelzak/util-linux/blob/master/sys-utils/eject.c#L125
Fixed.

> https://github.com/karelzak/util-linux/blob/master/term-utils/script.c#L150
> https://github.com/karelzak/util-linux/blob/master/term-utils/script.c#L522
> ^^ here `msgfmt` should also likely be `const`
Fixed.

> https://github.com/karelzak/util-linux/blob/master/term-utils/wall.c#L299
Fixed.

> https://github.com/karelzak/util-linux/blob/master/text-utils/more.c#L1212
> ^^ here `cmd` should also likely be `const`
Fixed.

> https://github.com/karelzak/util-linux/blob/master/include/c.h#L221
> 
> In the following cases, it is also likely missing, specifically with the third value to be 0:
> https://github.com/karelzak/util-linux/blob/master/include/path.h#L58
> https://github.com/karelzak/util-linux/blob/master/include/path.h#L63
> https://github.com/karelzak/util-linux/blob/master/include/path.h#L66
> https://github.com/karelzak/util-linux/blob/master/include/path.h#L75
Fixed.

> In the following cases, the third value likely should not be 0 as the arguments are available to be checked:
> https://github.com/karelzak/util-linux/blob/master/include/strv.h#L18
Fixed.

> https://github.com/karelzak/util-linux/blob/master/include/strutils.h#L376
Fixed.

**Comment by karelzak** [comment]
Thanks!
