### ISSUE TITLE
cfdisk: Partition size without units yields confusing error message

### ISSUE THREAD

**Issue by dagbrown** [karelzak/util-linux#136]
I'm a developer for the Lunar Linux distribution.

A user recently came to us saying that when he tried to create a disk partition in cfdisk, he was given the error message "internal error: unsupported dialog type 2".  After some back and forth, it turned out that when he tried to create a new partition, he entered a number without any units, and it yielded that error message.

I tried it myself and sure enough, no matter what label type was selected, entering a number without units resulted in the same error message.  Entering a number with units worked fine.

I guess the correct thing to do would be to detect this situation and output an appropriate error message.

**Comment by karelzak** [comment]
Thanks!

**Comment by dagbrown** [comment]
You're welcome!  And thank you for sorting it out.
