### ISSUE TITLE
Comment says first four characters are checked but code does not have the limit

### ISSUE THREAD

**Issue by adelton** [karelzak/util-linux#1360]
The code at
https://github.com/karelzak/util-linux/blob/master/login-utils/sulogin.c#L386-L389
runs until the end of string or until it finds a dollar sign, even if the comment indicates that only the first four characters (max) are looked at. It might make sense to make the comment and code consistent.

**Comment by karelzak** [comment]
I guess the comment is not only for the next `for()` loop, but all the part of the code; there is:
```c
      if ((off = (off_t)(s-pass)) > 4 || off < 3)
                return 0;                
```
