### ISSUE TITLE
how to pass argument with dash(-) to command in nsenter

### ISSUE THREAD

**Issue by aagu** [karelzak/util-linux#1362]
I want to use nsenter to modify iptables rules on host machine inside container, but when I try to pass `-t` arg to iptables, nsenter complain about the pid is not valid(since it is iptables table). Is there any way to pass arguments to the iptables command in nsenter?
My command looks like this:
```
nsenter -t 1 -i -m -u -n iptables -t nat -S OUTPUT
```

**Comment by karelzak** [comment]
Sure, the common way is to use `--` to separate arguments and options. Try
```
nsenter -t 1 -i -m -u -n -- iptables -t nat -S OUTPUT
```

**Comment by aagu** [comment]
Thanks karelzak, it works now
