### ISSUE TITLE
How does the file /run/blkid/blkid.tab trigger the update?

### ISSUE THREAD

**Issue by HeroesLoveToRoujiamo** [karelzak/util-linux#1363]
When we insert or delete a new disk, how does the file "/run/blkid/blkid.tab" trigger an update? I checked systemd and some other codes and found nothing. thank you very much!

**Comment by karelzak** [comment]
It's updated when you use the "high-level" libblkid interface, for example when you execute "blkid" (without -p). This old interface is rarely used in the last years and in udevd/systemd we use a low-level interface where the blkid.tab cache file is not used at all. 

The udev db is used as a primary source for information about devices in all mainstream Linux distros as it's updated when a new event is triggered by the kernel (etc.).

Why do you care? ;-) It's a private library file. It's better to use lsblk, findmnt, or directly search in udev db, for example by `udevadm info /dev/sda1`.

**Comment by HeroesLoveToRoujiamo** [comment]
I found that when the disk was renamed, the corresponding disk label of this file was not updated. But every time I plug in or unplug the disk, it is updated, so I want to find out where it triggered the update. Now that this file exists, I think I should improve it.


Especially I found that the command blkid -o list is very useful, but I don't know why the code remarks have been deprecated. Maybe it is my personal complex!

**Comment by karelzak** [comment]
You can use for example "lsblk --fs" (or define your own columns by "-o  ..."). lsblk reads data from /sys and udev and it's always up to date. 

"blkid -o list" needs root permissions to read the information from the devices and update blkid.tab file, if you do not have permissions then it returns old cached data ... 

Try `sudo rm /run/blkid/blkid.tab` and then as a regular user `blkid -o list` ... blkid cache is a way you do not want to go ;-) We maintain it only for backward compatibility.

**Comment by HeroesLoveToRoujiamo** [comment]
Okay, I see, thank you very much!
