### ISSUE TITLE
switch_root: About question of arg

### ISSUE THREAD

**Issue by mzhan0170** [karelzak/util-linux#1366]
Hello Experts,

When I use switch_root to run the systemd service, I would like add some parameters to systemd, like:
--default-standard-error=journal+console --default-standard-output=journal+console

But the switch_root always report error:
/sbin/switch_root: unrecognized option '--default-standard-error=journal+console'
Try 'switch_root --help' for more information.

Any solution for this kind of problem?

Thanks,
Mark

**Comment by karelzak** [comment]
You need to use '--' to separate arguments and options. Something like:

 `switch_root -- /dir init  --foo --bar`

**Comment by mzhan0170** [comment]
Karelzak, Thank you.
