### ISSUE TITLE
Spaces before serial when using --json flag

### ISSUE THREAD

**Issue by Mithrandir2k18** [karelzak/util-linux#1368]
When I call `lsblk --json -o +serial` on Ubuntu 20.04(kernel 5.4.0-71-generic ), devices that have a serial number prepend some extra spaces before the serial number inside the string.

```
{
   "blockdevices": [
      {"name":"nvme0n1", "maj:min":"259:0", "rm":false, "size":"477G", "ro":false, "type":"disk", "mountpoint":null,
"serial":"      SXXXXXXXXXXXX0", ...}
      ...
      
]}
```

**Comment by karelzak** [comment]
This is probably how the SERIAL is stored in udev DB. I guess we can in lsblk a little bit to clean up the string before we use it.
