### ISSUE TITLE
libsmartcols ASCII art problem

### ISSUE THREAD

**Issue by martinpitt** [karelzak/util-linux#137]
Forwarding from https://launchpad.net/bugs/1406133:

The libsmartcols component used by findmnt to draw the filesystem tree is smart enough to wrap lines in case the output doesn’t fit into the screen. However, it fails to draw the lines correctly in this case. Attached patch fixes the problem. Someone more knowledgeable in libsmartcols internals might want to change the buffer size from an arbitrary 1024 to something taken from actual data, the best way to do that eludes me.

Sample of incorrect output:

    ├─/boot /dev/sda1 ext3 rw,relatime,data=ordered
    ├─/usr /dev/mapper/vgshadow-ubuntu_usr
                                                    ext4 rw,noatime,data=ordered
    ├─/var /dev/mapper/vgshadow-ubuntu_var
                                                    ext4 rw,noatime,data=ordered
    ├─/home /dev/mapper/vgshadow-home
                                                    ext4 rw,noatime,data=ordered
    └─/srv /dev/mapper/vgshadow-srv
                                                    reiserfs rw,noatime,notail

Patch adds missing vertical lines at any level necessary.

The patch is here: https://launchpadlibrarian.net/193614209/libsmartcols-art-fix.diff

**Comment by martinpitt** [comment]
The bug report/patch is by Roman Odaisky (https://launchpad.net/~rdaysky), but he did not provide an email address.

**Comment by karelzak** [comment]
Should be fixed now.
