### ISSUE TITLE
NUL response is super old and interacts poorly with freeipmi

### ISSUE THREAD

**Issue by rlpowell** [karelzak/util-linux#1371]
freeipmi has a "serial-keepalive" mode, where it sends NUL characters occasionally to keep SOL (serial over LAN) connections open, because IPMI sucks and BMCs all suck.

This interacts poorly with agetty's default configuration on CentOS of changing baud rates in response to a NUL.

A fact I discovered by locking up ~10,000 consoles.

Does this actually have a valid use case in modern times?  Does anyone really need or use this?

If the answer is "yes", I'd like to suggest an extension: by running strace, I discovered that sending obvious keys (like "enter") when the baud rate was bad would generate characters like \377 and \374 (those are octal).  These are not valid characters, and are in fact entirely outside of the range of what can be generated by an actual keyboard, as far as I know.

If we're going to keep this NUL thing, could we enhance it by *also* changing baud rates if it sees characters above, say, \370 ?

If that seems appropriate I'm happy to put together a PR.

(I am, separately, opening a PR with freeipmi about significantly enhancing their documentation to warn about this issue.)

**Comment by karelzak** [comment]
The speed change is a pretty commonly used feature (you can see on many places agetty command line with multiple speeds). So, I do not think that remove it or change the current behavior for NUL (read() with zero return) is a good idea.

Not sure about your idea with \370. The first problem is that the code can accept also wide-chars (etc.) when enabled by -8|--8bits, in this case, it does not check for parity bits.  (BTW, chars above \370 are valid Latin-2, for example in my native language \370 is small R with caron in Latin-2 and we have a key on the standard keyboard for this purpose ;-)) The other question is if you see really \377 or it's something else with parity bit (but it will be easy to debug).

See https://github.com/karelzak/util-linux/blob/master/term-utils/agetty.c#L2200 for more details.

The ideal solution would be to differentiate between "serial-keepalive" situation and a normal situation when the user really writes to the terminal.

I mean somehow inform agetty that it's a user who generates the chars. For example, there is --login-pause which forces users to press any key before there they start to type username (it prints "[press ENTER to login]" before prompt for username and it ignores one char after it). Maybe we can somehow extend this functionality and for example, wait for CR/NL (--login-pause=NL) and ignore everything else (include the problematic NUL) until it gets the expected char. Just idea ... :-)

**Comment by rlpowell** [comment]
Ugh, I was worried it would turn out to be complicated like this.  -_-;

The read() call in strace definitely sees \377, FWIW.

Feels like this is best fixed at the freeipmi end.  Thanks for thinking it through!

**Comment by rlpowell** [comment]
Also feel free to close this out if you like.
