### ISSUE TITLE
Mysterious test suite failures when CONFIG_BLK_DEV_SD isn't enabled in kernel

### ISSUE THREAD

**Issue by rossburton** [karelzak/util-linux#1376]
If for some reason `CONFIG_BLK_DEV_SD` isn't enable in the kernel or `sd-mod` isn't installed, the test suite fails in somewhat mysterious ways:

```
[ 1163.699863] scsi host0: scsi_debug: version 0190 [20200710]
                 dev_size_mb=8, opts=0x0, submit_queues=1, statistics=0
[ 1163.705067] scsi 0:0:0:0: Direct-Access     Linux    scsi_debug       0190 PQ: 0 ANSI: 7
grep: /sys/block/*/device/model: No such file or directory
timeout waiting for scsi_debug device
```

`scsi_debug` created the virtual devices, but without the actual SCSI disk support nothing can happen.

I think `ts_scsi_debug_init` should somehow check that SCSI disk support is enabled, somehow.  My SCSI-fu was garbage collected years ago so I can't think of an easy way to do this right now...

**Comment by karelzak** [comment]
Oh ... that's crazy. I have a little bit improved the test function where we initialize scsi_debug to avoid "No such file or directory" message and to skip the test if scsi_debug does not work as expected.
