### ISSUE TITLE
libblkid: Btrfs duplicate "filesystem" block devices for a single filesystem.

### ISSUE THREAD

**Issue by cheako** [karelzak/util-linux#1382]
Looking at changing the code on my system, just wanted to send a heads-up.

Working on https://gitlab.gnome.org/GNOME/gvfs/-/issues/519

Traced value for `"usage" => "filesystem"` coming from `libblkid`.  When btrfs has multiple devices I plan on adding a check, along with the obvious magic number matches, that `/dev/disk/by-uuid/%s`(*follow symlinks) has the same device id as the current device.  Idealy in that case usage would be `"filesystem-part"` with everything else the same.

After working on this issue for several days, I feel this is for the best.  RFC.

**Comment by cheako** [comment]
```diff
cheako@mx1:~/src/gitlab/util-linux$ git diff|cat
diff --git a/libblkid/src/blkidP.h b/libblkid/src/blkidP.h
index e3a160aa9..82b3985e8 100644
--- a/libblkid/src/blkidP.h
+++ b/libblkid/src/blkidP.h
@@ -163,6 +163,7 @@ struct blkid_idinfo
 {
        const char      *name;          /* fs, raid or partition table name */
        int             usage;          /* BLKID_USAGE_* flag */
+       int             (*usagefunc)(blkid_probe pr);
        int             flags;          /* BLKID_IDINFO_* flags */
        int             minsz;          /* minimal device size */
 
diff --git a/libblkid/src/superblocks/btrfs.c b/libblkid/src/superblocks/btrfs.c
index 03aa7e979..8ef159391 100644
--- a/libblkid/src/superblocks/btrfs.c
+++ b/libblkid/src/superblocks/btrfs.c
@@ -17,6 +17,7 @@
 #endif
 
 #include "superblocks.h"
+#define BLKID_USAGE_FILESYSTEM_PART (1 << 5)
 
 struct btrfs_super_block {
        uint8_t csum[32];
@@ -197,6 +198,9 @@ out:
 static int probe_btrfs(blkid_probe pr, const struct blkid_idmag *mag)
 {
        struct btrfs_super_block *bfs;
+       struct blkid_prval *v;
+       char tmpdev[55];
+       struct stat statbuf;
 
        if (pr->zone_size) {
 #ifdef HAVE_LINUX_BLKZONED_H
@@ -228,13 +232,50 @@ static int probe_btrfs(blkid_probe pr, const struct blkid_idmag *mag)
        blkid_probe_set_uuid_as(pr, bfs->dev_item.uuid, "UUID_SUB");
        blkid_probe_set_block_size(pr, le32_to_cpu(bfs->sectorsize));
 
+       strncpy(tmpdev, "/dev/disk/by-uuid/", sizeof(tmpdev));
+       snprintf(tmpdev + 18, sizeof(tmpdev) - 18,
+                        "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
+                        bfs->fsid[0], bfs->fsid[1], bfs->fsid[2], bfs->fsid[3],
+                        bfs->fsid[4], bfs->fsid[5],
+                        bfs->fsid[6], bfs->fsid[7],
+                        bfs->fsid[8], bfs->fsid[9],
+                        bfs->fsid[10], bfs->fsid[11], bfs->fsid[12], bfs->fsid[13], bfs->fsid[14], bfs->fsid[15]);
+
+       v = blkid_probe_assign_value(pr, "CHILD_DEVICE");
+
+       v->len = 1;
+       v->data = calloc(1, 1);
+
+       if (stat(tmpdev, &statbuf) == 0 &&
+               S_ISBLK(statbuf.st_mode) &&
+               blkid_probe_get_devno(pr) != statbuf.st_rdev)
+       {
+               *v->data = 'y';
+       }
+       else
+               *v->data = 'n';
+
        return 0;
 }
 
+static int usage_func(blkid_probe pr)
+{
+       const char *v;
+       int ret = BLKID_USAGE_FILESYSTEM;
+
+       if (blkid_probe_lookup_value(pr, "CHILD_DEVICE", &v, NULL) != 0)
+               return ret;
+
+       if (v[0] == 'y')
+               ret = BLKID_USAGE_FILESYSTEM_PART;
+
+       return ret;
+}
+
 const struct blkid_idinfo btrfs_idinfo =
 {
        .name           = "btrfs",
-       .usage          = BLKID_USAGE_FILESYSTEM,
+       .usagefunc      = usage_func,
        .probefunc      = probe_btrfs,
        .minsz          = 1024 * 1024,
        .magics         =
diff --git a/libblkid/src/superblocks/superblocks.c b/libblkid/src/superblocks/superblocks.c
index f21365538..6ee93d681 100644
--- a/libblkid/src/superblocks/superblocks.c
+++ b/libblkid/src/superblocks/superblocks.c
@@ -425,9 +425,13 @@ static int superblocks_probe(blkid_probe pr, struct blkid_chain *chn)
                                (const unsigned char *) id->name,
                                strlen(id->name) + 1);
 
-               if (!rc)
-                       rc = blkid_probe_set_usage(pr, id->usage);
-
+               if (!rc) {
+                   if(!id->usagefunc) {
+                           rc = blkid_probe_set_usage(pr, id->usage);
+                       } else
+                           rc = blkid_probe_set_usage(pr, id->usagefunc(pr));
+               }
+
                if (!rc && mag)
                        rc = blkid_probe_set_magic(pr, off, mag->len,
                                        (const unsigned char *) mag->magic);
@@ -578,6 +582,8 @@ static int blkid_probe_set_usage(blkid_probe pr, int usage)
                u = "crypto";
        else if (usage & BLKID_USAGE_OTHER)
                u = "other";
+       else if (usage & (1 << 5))
+               u = "filesystem-part";
        else
                u = "unknown";
 
```

**Comment by cheako** [comment]
This works great on the blkid command line, in both cached(after `-g`) and probe modes.  However, it's not effecting my target `xfdesktop` or `gio mount` as I had expected.  More testing is needed.

**Comment by cheako** [comment]
There is still a feature, apparently the code that checks the mountpoint is not using the same selection.  Looking into it.

**Comment by tbzatek** [comment]
I think you should talk to btrfs developers first as this is likely an intention. Besides, you shouldn't be changing this in already released software. Additional udev attribute could still come useful.

**Comment by cheako** [comment]
@tbzatek  I don't think so.

1. I'm a solo player, not really concerned with good intentions.
2. Don't know what u mean by "released software."  Bug fixes should be useful enough to break static friction.
3. udev keeps coming up, I think ppl are assigning it more credit than it warrants.  With the above patch, udev gains a `CHILD_DEVICE` attribute(adding things to libblkid adds them to udev).

**Comment by cheako** [comment]
```diff
diff --git a/libblkid/src/blkidP.h b/libblkid/src/blkidP.h
index e3a160aa9..82b3985e8 100644
--- a/libblkid/src/blkidP.h
+++ b/libblkid/src/blkidP.h
@@ -163,6 +163,7 @@ struct blkid_idinfo
 {
        const char      *name;          /* fs, raid or partition table name */
        int             usage;          /* BLKID_USAGE_* flag */
+       int             (*usagefunc)(blkid_probe pr);
        int             flags;          /* BLKID_IDINFO_* flags */
        int             minsz;          /* minimal device size */
 
diff --git a/libblkid/src/superblocks/btrfs.c b/libblkid/src/superblocks/btrfs.c
index 03aa7e979..b9ce12042 100644
--- a/libblkid/src/superblocks/btrfs.c
+++ b/libblkid/src/superblocks/btrfs.c
@@ -17,6 +17,7 @@
 #endif
 
 #include "superblocks.h"
+#define BLKID_USAGE_FILESYSTEM_PART (1 << 5)
 
 struct btrfs_super_block {
        uint8_t csum[32];
@@ -197,6 +198,8 @@ out:
 static int probe_btrfs(blkid_probe pr, const struct blkid_idmag *mag)
 {
        struct btrfs_super_block *bfs;
+       char tmpdev[55];
+       struct stat statbuf;
 
        if (pr->zone_size) {
 #ifdef HAVE_LINUX_BLKZONED_H
@@ -228,13 +231,43 @@ static int probe_btrfs(blkid_probe pr, const struct blkid_idmag *mag)
        blkid_probe_set_uuid_as(pr, bfs->dev_item.uuid, "UUID_SUB");
        blkid_probe_set_block_size(pr, le32_to_cpu(bfs->sectorsize));
 
-       return 0;
+       strncpy(tmpdev, "/dev/disk/by-uuid/", sizeof(tmpdev));
+       snprintf(tmpdev + 18, sizeof(tmpdev) - 18,
+                        "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
+                        bfs->fsid[0], bfs->fsid[1], bfs->fsid[2], bfs->fsid[3],
+                        bfs->fsid[4], bfs->fsid[5],
+                        bfs->fsid[6], bfs->fsid[7],
+                        bfs->fsid[8], bfs->fsid[9],
+                        bfs->fsid[10], bfs->fsid[11], bfs->fsid[12], bfs->fsid[13], bfs->fsid[14], bfs->fsid[15]);
+
+
+       if (stat(tmpdev, &statbuf) == 0 &&
+               S_ISBLK(statbuf.st_mode) &&
+               blkid_probe_get_devno(pr) != statbuf.st_rdev)
+         return blkid_probe_set_value(pr, "CHILD_DEVICE", (const unsigned char *)"true", 4);
+
+       return blkid_probe_set_value(pr, "CHILD_DEVICE", (const unsigned char *)"f", 1);
+
+}
+
+static int usage_func(blkid_probe pr)
+{
+       const char *v;
+       int ret = BLKID_USAGE_FILESYSTEM;
+
+       if (blkid_probe_lookup_value(pr, "CHILD_DEVICE", &v, NULL) != 0)
+               return ret;
+
+       if (v[0] == 't')
+               ret = BLKID_USAGE_FILESYSTEM_PART;
+
+       return ret;
 }
 
 const struct blkid_idinfo btrfs_idinfo =
 {
        .name           = "btrfs",
-       .usage          = BLKID_USAGE_FILESYSTEM,
+       .usagefunc      = usage_func,
        .probefunc      = probe_btrfs,
        .minsz          = 1024 * 1024,
        .magics         =
diff --git a/libblkid/src/superblocks/superblocks.c b/libblkid/src/superblocks/superblocks.c
index f21365538..510d74925 100644
--- a/libblkid/src/superblocks/superblocks.c
+++ b/libblkid/src/superblocks/superblocks.c
@@ -425,9 +425,13 @@ static int superblocks_probe(blkid_probe pr, struct blkid_chain *chn)
                                (const unsigned char *) id->name,
                                strlen(id->name) + 1);
 
-               if (!rc)
-                       rc = blkid_probe_set_usage(pr, id->usage);
-
+               if (!rc) {
+                   if(!id->usagefunc) {
+                           rc = blkid_probe_set_usage(pr, id->usage);
+                       } else
+                           rc = blkid_probe_set_usage(pr, id->usagefunc(pr));
+               }
+
                if (!rc && mag)
                        rc = blkid_probe_set_magic(pr, off, mag->len,
                                        (const unsigned char *) mag->magic);
@@ -578,6 +582,8 @@ static int blkid_probe_set_usage(blkid_probe pr, int usage)
                u = "crypto";
        else if (usage & BLKID_USAGE_OTHER)
                u = "other";
+       else if (usage & (1 << 5))
+               u = "f1lesystem-part";
        else
                u = "unknown";
 
 ```

**Comment by tbzatek** [comment]
>     2. Don't know what u mean by "released software."  Bug fixes should be useful enough to break static friction.

What I was trying to tell you was that various information exposed publicly by low-level components carry some degree of stability guarantee. In this case the `ID_FS_USAGE=filesystem` is considered of high importance and changing the behaviour would break number of other tools. In such case even a bad design often needs to be preserved for the sake of general stability.

I've also noticed you've found my https://github.com/kdave/btrfs-progs/issues/302 ticket that is somewhat related to what you're trying to solve. My original intention was to convince btrfs folks to expose `ID_FS_USAGE=filesystem` exactly on one block device only for a couple of reasons. However at the end I realized the existing design was done on purpose and consumers should align to the unique specifics.

**Comment by cheako** [comment]
> changing the behaviour would break number of other tools.

A guess, assumption?  Got any examples?  For a detailed look at the "but sometimes" theory or way of thinking, watch this video https://youtu.be/GiYO1TObNz8

I believe a failure to timely fix bugs because "It's dangerous", is an indicator that a project has an issue effectively managing risk.

**Comment by karelzak** [comment]
I have doubts about the suggested solution. 

The problem is that libblkid is a library for block-device content identification and nothing more. There is no place to be smart and to try to guess how the block devices will be used or filesystem assembled by another subsystem (device-mapper, btrfs, ...), so things like CHILD_DEVICE= where the result depends on the external use of another device seems like something we do not want in the library.

I guess all the high-level tools (like gvfs) have enough information to detect more devices with the same `UUID=`, but with the different `UUID_SUB=`. It would be also possible to export (by libblkid to udev DB) num_devices from btrfs superblock if you see this information as useful.

I think `filesystem-part`, as well as `CHILD_DEVICE=`, are unnecessary. All you need is to carefully evaluate the UUIDs in the desktop tools, for example, aggregate all the same UUIDs under one desktop icon, or when FS with the UUID is ready mounted then do not offer other devices with the same UUID, etc.

**Comment by cheako** [comment]
There is no `num_devices` or anything of the like.  There are three ways I can think of to even know there is an array:
1. Is by looking at all the devices and finding matching UUIDs.
2. Looking at the UUID in `/dev/disk/by-uuid` and noticing the device doesn't match...  I.E. this doesn’t work for exactly one device.
3. Implement the internals of btrfs.

"1" doesn't translate well outside `libblkid`, where devices are treated like individuals and having to look at every device to get the parameters of a single device is made difficult, likely an antipattern.
"3" I looked into this, you'd basically need to recursively follow a tree till you get to the proper node type and that gives you a struct with useful bits.  To get all the nodes needed to build a map of the RAID you might need to completely enumerate the entire tree.  When I understood this, I gave up looking into it.
"2" Was simple to implement and has a clear advantage in golf.

**Comment by cheako** [comment]
Sorry, I'm blind.  The problem is `external use of another device`, I don't see where that is.  The suggested probe is `if(udev assign this UUID to current device)`.  `CHILD_DEVICE` is a hack for passing this concept around, the probe could be done in `usage_func()`, I just thought it would be strange to probe things in that function.

**Comment by karelzak** [comment]
stat(/dev/disk/by-uuid/something) means that we will provide information about device content (filesystem vs. filesystem-part) according to any symlink to some device maintained by some udev rule. Sorry, it sounds like a fragile hack (and if I good remember then there is no lock and udev can probe more devices at the same time, so you can still get multiple devices with "filesystem" although you assume "filesystem-part").

I understand your motivation and see the frustration, but libblkid is really not the right place to improve how systems see btrfs devices. In the library is fine to read whatever from the device (or parental whole-disk device), or from /sys, but anything other is a bad idea. We need to keep the library stupid  ;-)

If you need any smart logic then you can introduce special udev rules for btrfs and add/modify whatever in udev DB. 

libblkid is the wrong layer.

**Comment by cheako** [comment]
Everyone is saying, "Not I."  udev DB looked like a pass through, like just forwarding the libblkid data.  Once you start getting further from libblkid there are more places that need the corrective lenses.  It doesn't make sense to re-correct for bad device probing anywhere but libblkid.

**Comment by cheako** [comment]
As for locking... it's if btrfs, if exists, if (block || true), if not matches.  At some point you just have to accept that the *sometimes in "but sometimes" is not so often as to expect to see it over the lifetime of the universe, and even then it's if the users doesn't think to try **booting again.

* https://youtu.be/GiYO1TObNz8

** Critical systems won't have removable devices, so add an if booting to that sometimes.

**Comment by karelzak** [comment]
Well, see your /usr/lib/udev/rules.d/, there are many many rules to extend or modify what blkid returns. I guess you need something like:
```
   ACTION=="add", SUBSYSTEM=="block", ENV{ID_FS_TYPE}=="btrfs", TEST=="/dev/disk/by-uuid/$env{ID_FS_UUID_ENC}", <<< whatever to change DB content >>>
```

**Comment by cheako** [comment]
I'd love to click on the icon that fixes what is wrong, but labeling an icon as "Comment: Fix what I find wrong" and having someone click on it... is not a usable solution.

I didn't see anywhere in `/usr/lib/udev/rules.d/` to tell libblkid not to return `filesystem` for every btrfs device, even when doing so _exactly once_ per filesystem is what's expected by higher layers.

This is still a bug.

**Comment by cheako** [comment]
https://youtu.be/RdggLr6cMIA
