### ISSUE TITLE
Upgrading to 2.37.1 breaks mount.davfs

### ISSUE THREAD

**Issue by stovocor** [karelzak/util-linux#1398]
After upgrading to 2.37.1, mount.davfs stopped working. It quits with this error message:

    /usr/bin/mount.davfs: can't read group data base

Downgrading to 2.37 fixed the problem and mounting DAV volumes is possible again. Since I am not sure about the root cause, I also opened a [ticket for davfs](https://savannah.nongnu.org/support/?110519). Another user pointed out that mount.sshfs is broken, too.

**Comment by tummychow** [comment]
Hey, I'm the anon who complained about sshfs not working. I realized I misspoke on the davfs ticket so I did a little bit more debugging. The specific behavior I observe is that I have this in my fstab:

```
sshfs#192.168.1.149:/mnt/extern	/mnt/extern	fuse	reconnect,max_conns=10,noauto
```

Then if I run:

```
$ mount -v /mnt/extern
# returns 1, mount does not happen
```

I simply get an exit code of 1, with no mount. There's no output either. Here's the output with `LIBMOUNT_DEBUG=all`: https://gist.github.com/tummychow/13d0a0b259e9330c5d31470dac824c78

Note that other helpers (not part of util-linux) still work. Eg `mount.fuse`, which is part of the fuse2 package on arch, works with no issues:

```
$ mount.fuse 'sshfs#192.168.1.149:/mnt/extern' /mnt/extern
# returns 0, mount succeeds
```

Or `mount.sshfs`, which is part of the sshfs package on arch, also no issues:

```
$ ls -lah /usr/bin/mount.sshfs
lrwxrwxrwx 1 root root 5 Jun 17 09:50 /usr/bin/mount.sshfs -> sshfs
$ mount.sshfs 192.168.1.149:/mnt/extern /mnt/extern
# returns 0, mount succeeds
```

As with stovocor, downgrading to 2.37 fixes my problem.

**Comment by karelzak** [comment]
The only difference between v2.37 and v2.37.1 is that mount(8) calls setgroups(0, NULL) to drop user's supplementary groups, before the external mount helper is executed. See commit 17fc8693cd60733227204fe31395575778984e3c.

I cannot reproduce the problem, it works for me. Maybe our setup depends on the supplementary groups (see `id` output).

Please, try `LIBMOUNT_DEBUG=all mount /mnt/extern` to get more details. 

Note that `sshfs#192.168.1.149` is deprecated syntax, it's better to use `type.subtype` (e.g. fuse.sshfs) than `subtype#source`:
```
   192.168.1.149:/mnt/extern /mnt/extern		fuse.sshfs reconnect,max_conns=10,noauto
```

**Comment by karelzak** [comment]
Now when I think about it again then the supplementary groups drop does not make sense. We need to drop suid, but it's fine to keep users' original permissions.

**Comment by karelzak** [comment]
Ah, I see debug output now (sorry).

OK, the issue is that we call setgroups() without care about the current permissions, this operation requires root permissions, but since v2.36 mount(8) is able to drop suid and continue as a normal user (which is usable for example for fuse, etc.).

**Comment by karelzak** [comment]
It would be nice to test the bugfix in your environment (but it's a little bit tricky as you have to install the mount(8) binary with suid rights as usually in distributions, try it by `./mount ` after `make mount` is not enough :-))

Thanks, @stovocor, and @tummychow! 

I'll release v2.37.2 asap (next Monday or so)...

**Comment by stovocor** [comment]
Fortunately, it is quite easy to build a patched version from master since the [build files](https://github.com/archlinux/svntogit-packages/tree/packages/util-linux/trunk) are easily available.

However, mount.davfs is still broken but with a different error message:

    $ LANG=C mount /path
    /usr/bin/mount.davfs: user username must be member of group network
    $ groups
    lp wheel network [...]

I created the [debug info](https://github.com/karelzak/util-linux/files/6902627/debug.txt) you requested earlier with the new version.

**Comment by karelzak** [comment]
Ah, so your use-case depends on supplementary groups. Hmm... I'll drop setgroups() call at all.

**Comment by karelzak** [comment]
OK, now it should be fixed. Thanks for your feedback.

**Comment by stovocor** [comment]
Yes, I can confirm that the latest commit fixed it. Thank you very much for the quick support! 👍

**Comment by Polynomial-C** [comment]
> I'll release v2.37.2 asap (next Monday or so)...

Will that happen anytime soon?

**Comment by karelzak** [comment]
> > I'll release v2.37.2 asap (next Monday or so)...
> 
> Will that happen anytime soon?

v2.37.2 released (https://www.kernel.org/pub/linux/utils/util-linux/v2.37/). Sorry for the delay.

**Comment by johnhamelink** [comment]
Thank you, 2.37 fixed mount.davfs for me!
