### ISSUE TITLE
sulogin broken in version 2.37.1

### ISSUE THREAD

**Issue by bob23450** [karelzak/util-linux#1400]
In stable version 2.37.1 sulogin does no longer accept any root password.
This leads to weird behaviours when trying to enter maintenance (aka single-user) mode at boot.
For example, Artix Linux with runit keeps asking for the root password forever.
The report [FS#71625](https://bugs.archlinux.org/task/71625?project=1&string=util-linux) in Arch Linux bug tracker might be related to this issue as well.
Looking at the source code (sulogin.c), it seems that the regression could have been introduced by commit ee06531. The function getpasswd() always return NULL.
The master branch should not be affected.
I tried to address the issue with the attached patch which apparently restores the right behaviour (tested in Artix Linux/runit).
[sulogin.patch.txt](https://github.com/karelzak/util-linux/files/6901306/sulogin.patch.txt)
Hope it helps.

**Comment by karelzak** [comment]
Oh, that's a stupid bug... I'll fix it in v2.37.2. Thanks!

**Comment by bob23450** [comment]
Well, to be pedantic, commit  2d8a9fc  on branch master is redundant because the statement 'ret = pass;' was already there a couple of lines above and now is repeated twice.
Commit 3c466f7 on stable/2.37 indeed closes this issue.

**Comment by karelzak** [comment]
> Well, to be pedantic, commit [2d8a9fc](https://github.com/karelzak/util-linux/commit/2d8a9fcee2e3d63deb6bcba650894ff14d8e2d3b) on branch master is redundant because the statement 'ret = pass;' was already there a couple of lines above and now is repeated twice.

Nice. This explains all the problems.

I have implemented ee0653123c1ef9cada9734a0ba995cdd5c63bb00 in the master branch, where is also 0d092db5c40b94e1ea9529f3f1c384a74eca19f8 (introduced ret = pass). After checry-pick my change to the stable/v2.37 where is missing  0d092db5c40b94e1ea9529f3f1c384a74eca19f8 we get the issue in stable.

Thanks!
