### ISSUE TITLE
lscpu: lscpu_cputype_get_default() return value used without NULL check -> segfaults on rv64

### ISSUE THREAD

**Issue by mkszuba** [karelzak/util-linux#1401]
according to sys-utils/lscpu-cputype.c#L99, `lscpu_cputype_get_default()` can return a null pointer. However, with `print_summary()` having called this function in sys-utils/lscpu.c#L975 `lscpu` proceeds to dereference the return value (lines: 994, 1036 and 1038) without checking it for NULL first. This results in a segmentation fault when `lscpu` is run on a Linux/rv64 system. For more details on the segfault, see here: https://bugs.gentoo.org/802606#c8 .

Nb. as far as  I can see every other time `lscpu_cputype_get_default()` is called (once more in `lscpu.c`, once in `lscpu-virt.c`, three times in `lscpu-cputype.c`) its return value is checked before dereferencing.

**Comment by karelzak** [comment]
Good catch. Thanks!

Please, can you send me /proc and /sys dump from your Linux/rv64? There is a script to create the dump, see:
https://raw.githubusercontent.com/karelzak/util-linux/master/tests/ts/lscpu/mk-input.sh

It would be nice to have a dump from the system in util-linux test suite to detect this kind of bug.

**Comment by mkszuba** [comment]
Here you go! This is for a dual-core SiFive U74 (specifically from the prototype BeagleV Starlight board) but I expect it will look much the same on other U74 systems, HiFive Unmatched for instance.
[rv64-linux.tar.gz](https://github.com/karelzak/util-linux/files/6907680/rv64-linux.tar.gz)

**Comment by karelzak** [comment]
Thanks!
