### ISSUE TITLE
Wrong use of sector_size in blkdev_get_physector_size

### ISSUE THREAD

**Issue by NykauToutcourt** [karelzak/util-linux#1402]
`blkdev_get_physector_size` forwards the *address* of `sector_size` instead of the *address it points to* (i.e. the mere value of `sector_size`) when calling `ioctl`. It does not fail because the address is valid, but reading sector_size after calling `blkdev_get_physector_size` must result in undefined behavior. In my case, I spotted it because it returned `0` where a direct call to `ioctl` with the same parameters returned the expected value.

```
int blkdev_get_physector_size(int fd, int *sector_size)
{
    if (ioctl(fd, BLKPBSZGET, &sector_size) >= 0)
        return 0;
    return -1; 
}
```
This can be easily fixed by removing `&` in line 229 of `lib/blkdev.c`. I will see if I can send a merge request with that very quick fix

**Comment by karelzak** [comment]
Oh, fortunately, we use the function in this code only.

Good catch, thanks!

**Comment by karelzak** [comment]
Fixed by https://github.com/karelzak/util-linux/pull/1403
