### ISSUE TITLE
Double hyphen replaced by dash in man pages

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#1411]
https://asciidoctor.org/docs/asciidoc-writers-guide/#replacements

> Only replaced if between two word characters, between a word character and a line boundary, or flanked by spaces.
>
> When flanked by space characters (e.g., a -- b), the normal spaces are replaced by thin spaces (\&#8201;).

Hence…

https://github.com/karelzak/util-linux/blob/5a72054bd0e4590ed5f17ed862dcfeeb568f1c91/term-utils/agetty.8.adoc#L129

needs escaping:

```
*--login-options '-h darkstar \-- \u'*
```

You can see it wrong in https://man7.org/linux/man-pages/man8/agetty.8.html .

Did not check if other man pages have this issue.

**Comment by karelzak** [comment]
Thanks!

I have also found `--` in the examples in sys-utils/unshare.1.adoc, but it seems it works as expected there.
