### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by linuxgcc** [karelzak/util-linux#1421]
About text-utils/more.c:405 translation error

**Comment by karelzak** [comment]
This is not the right way to update translations. The po/ directory is updated before release by stuff from  http://translationproject.org/domain/util-linux.html, so your changes will be overwritten.

Please, contact
   Last-Translator: Boyuan Yang <073plan@gmail.com>
   Language-Team: Chinese (simplified) <i18n-zh@googlegroups.com>
to submit your changes.

Thanks!
