### ISSUE TITLE
Ubuntu 20.04: su command bash-autocomplete stopped working

### ISSUE THREAD

**Issue by NikEasY** [karelzak/util-linux#1424]
The su autocomplete stopped working. For example when I type:
su `Tab` `Tab`
It lists the files and directories of the current directory, where as it should list the available users.
[source](https://serverfault.com/questions/1069884/ubuntu-20-04-su-command-bash-autocomplete-stopped-working)
There is solution how to fix it

**Comment by karelzak** [comment]
Thanks!
