### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [karelzak/util-linux#1434]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [env_list_add](https://github.com/karelzak/util-linux/blob/ba3b93525920f2782e12016e7444fca89fb5bb9c/lib/env.c#L71)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [test_append](https://github.com/karelzak/util-linux/blob/5a72054bd0e4590ed5f17ed862dcfeeb568f1c91/libmount/src/optstr.c#L1182)

**Comment by karelzak** [comment]
For the tests it would be good enough to use xstrdup() (from inlude/xalloc.h), but malloc() in env_list_add is definitely bug.

**Comment by elfring** [comment]
Thanks for your small source improvements.

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software? :thinking:
