### ISSUE TITLE
Grammar error in eject(1)

### ISSUE THREAD

**Issue by climbTheStairs** [karelzak/util-linux#1436]
In the "-m, --no-unmount" section of [eject.1.adoc](https://github.com/karelzak/util-linux/blob/master/sys-utils/eject.1.adoc),
it says...

> If this option is not specified than eject opens the device [...]

...when it should say...

> If this option is not specified **then** eject opens the device [...]

**Comment by karelzak** [comment]
Fixed, thanks!
