### ISSUE TITLE
update docs for switch_root

### ISSUE THREAD

**Issue by iwelch** [karelzak/util-linux#144]
per https://bbs.archlinux.org/viewtopic.php?pid=1493980 , if switch_root maintains /run, too, it should probably mention this in the man page.  it would also be nice to give an example in the man page of how to rescue some more information across the root pivot via /run, which is presumably used by systemd to pick up messages from before it was invoked.

PS: If I understand the docs, switch_root is ruthless.  I would recommend some additional precautionary safety checks and/or prompts before a disk root is recursively deleted.  if the abandoned filesystem is on a ram filesystem, wiping it out was probably intended.  if the abandoned filesystem is on /dev/sda*, my guess is that it was not.

**Comment by karelzak** [comment]
The directory /run added to the man page. Thanks.

Note that If I good remember than systemd has private independent switch_root implementation.
