### ISSUE TITLE
raw fails to compile due to linux/raw.h gone since 5.14

### ISSUE THREAD

**Issue by Hello71** [karelzak/util-linux#1442]
https://bugs.gentoo.org/811702

**Comment by karelzak** [comment]
BUILD_RAW is optional by default and ./configure checks for linux/raw.h, so I guess it's problem only when you explicitly specify --enable-raw.

**Comment by Hello71** [comment]
also for meson

**Comment by Hello71** [comment]
why's it xlinux/raw.h?

**Comment by karelzak** [comment]
> why's it xlinux/raw.h?

Typo, fixed.
