### ISSUE TITLE
logger: --prio-prefix doesn't use --priority default

### ISSUE THREAD

**Issue by lukem** [karelzak/util-linux#1450]
## Bug
The logger(1) documentation for `--prio-prefix` says:
> Look for a syslog prefix on every line read from standard input. This prefix is a decimal number within angle brackets that encodes both the facility and the level.  The number is constructed by multiplying the facility by 8 and then adding the level.  For example, **local0.info**, meaning facility=16 and level=6, becomes **<134>**.
>
> If the prefix contains no facility, the facility defaults to what is specified by the **-p** option.  Similarly, if no prefix is provided, the line is logged using the _priority_ given with **-p**.

This does not work; if the facility is not provided, it defaults to LOG_USER rather than what's specified in **-p**.

## Reproduce
```sh
echo "<3> should be err to local7 not user" | logger -p local7.debug --prio-prefix
```
gets logged to user.err not local7.err.

Applications using sd-daemon(3) prefixes for `systemd`-compatible log output to stderr only output `<0>`..`<7>`, without a facility embedded, so we currently can't use a trick such as the following to capture the stderr to syslog local5, and still output the stdout to stdout, because the `-p local7` isn't used when stderr just starts with, say `<5>`:
```sh
((somecmd 3>&1 1>&2 2>&3- ) | logger -t somecmd -p local7.debug --prio-prefix) 2>&1
```

## Analysis
Examining the code in misc-utils/logger.c, it appears that the original implementation intended to support this. The original get_prio_prefix() in commit 98920f80591b61ffdf7bfd99e2dd824406276e78 used at [line 564](https://github.com/karelzak/util-linux/blame/2b3f40c5978569f15e30836cf99f34f31c163d1c/misc-utils/logger.c#L564) used the -p argument as the default and overrode the facility, priority, or both from the `<value>` parsing.

With the security fix in commit b9ef27f59bffbeaf5397538ea16065d4eb6364c8, the fallback to the -p as default was lost. Now, if you don't provide a facility (facility == 0, AKA LOG_KERN), it gets changed to facility 1 (LOG_USER).

## Possible fix (untested)
Refactor the code from [line 1000](https://github.com/karelzak/util-linux/blame/master/misc-utils/logger.c#L1000) to mask in the facility or priority from default_priority as appropriate, similar to the previous code.

Replace
```c
if (pri < 8)
	pri |= 8;
```
with
```c
if ((pri & LOG_FACMASK) == 0) {	/* no facility? use previous facility */
	pri |= (default_priority & LOG_FACMASK);
}
```
?

I don't think there needs to be special case handling for LOG_KERN, because if a user does
```sh
echo "<4> warning at dash p" | logger -p kern.notice --prio-prefix
```
then that will go to kern.warning, just as if they did
```sh
logger -p kern.warning "warning at dash p"
```
The default -p is user.notice anyway.

**Comment by karelzak** [comment]
Thanks for your debugging!
