### ISSUE TITLE
[FR] Add i18n support for human readable time formats (-T and -e)

### ISSUE THREAD

**Issue by jmontane** [karelzak/util-linux#1451]
Hi,

dmesg time format strings are hard-coded (see [1]  and [2]). Yes, months and days names are translated to current locale, but I don't see how to change these time format strings.

For instance,
"%a %b %e %H:%M:%S %Y" uses month/day order, but many languages use day/month. So
"%a %e %b %H:%M:%S %Y" would be a good option for Catalan, Spanish, French... languages

I know «ls» command allow to customize time format via gettext translation file [3]. I wonder if dmesg could add this feature too.

[1] https://github.com/karelzak/util-linux/blob/master/sys-utils/dmesg.c#L852
[2] https://github.com/karelzak/util-linux/blob/master/sys-utils/dmesg.c#L859
[3] https://github.com/coreutils/coreutils/blob/master/src/ls.c#L768

**Comment by karelzak** [comment]
Good idea, thanks!
