### ISSUE TITLE
Ldattach doesn't set non-standard baudrate

### ISSUE THREAD

**Issue by rbalykov** [karelzak/util-linux#1452]
I'm using ldattach to test tty line discipline.
Stuck with wrong baudrate while using -s250000 option.

Lines 245-250, values are written to termios, but no ioctl is called.

Compared this to proven-working case, they call TCSETS2 ioctl.

**Comment by rbalykov** [comment]
https://github.com/OpenLightingProject/ola/blob/master/common/io/ExtendedSerial.cpp

Lines 64-69

**Comment by karelzak** [comment]
> I'm using ldattach to test tty line discipline. Stuck with wrong baudrate while using -s250000 option.
> 
> Lines 245-250, values are written to termios, but no ioctl is called.

The function follows cfsetspeed() semantic, so it modifies `struct termios` only. The change is applied later by tcsetattr() in main() (see line 451).

> Compared this to proven-working case, they call TCSETS2 ioctl.

This should be unnecessary. 

So, something else has to be wrong with your use-case/setup ;-)

**Comment by rbalykov** [comment]
thank you
