### ISSUE TITLE
Provide a easy way for mkswap to avoid creating a UUID

### ISSUE THREAD

**Issue by nl6720** [karelzak/util-linux#1453]
UUIDs can sometimes be unnecessary. For example, for swap files.
To avoid having a UUID (as far as it's possible) currently requires running `mkswap -U 00000000-0000-0000-0000-000000000000`. Typing that out is not fun.

It would be great if there would be an easier way to accomplish this. 
Basically, I'd like something equivalent of `mkfs.ext4`'s `-U clear`.

**Comment by karelzak** [comment]
Good idea, let's support -U {clear,random,time,uuid} like mkfs.ext4.
