### ISSUE TITLE
Boot code missing when creating DOS disk label

### ISSUE THREAD

**Issue by RESP3CT88** [karelzak/util-linux#1456]
I have noticed that when I create a dos disk label with fdisk it does not add the boot code in the first sector. 

See below for what the boot code should look like:

00000000: fab8 0010 8ed0 bc00 b0b8 0000 8ed8 8ec0  ................
00000010: fbbe 007c bf00 06b9 0002 f3a4 ea21 0600  ...|.........!..
00000020: 00be be07 3804 750b 83c6 1081 fefe 0775  ....8.u........u
00000030: f3eb 16b4 02b0 01bb 007c b280 8a74 018b  .........|...t..
00000040: 4c02 cd13 ea00 7c00 00b0 a103 0000 0000  L.....|.........

When using fdisk this is all 00's and no boot code exists here.

**Comment by karelzak** [comment]
It's a partitioning tool, it does not write anything else than MBR to the device.
