### ISSUE TITLE
Building libuuid always generates libuuid.so.1.3.0 and not say libuuid.so.2.37.2

### ISSUE THREAD

**Issue by prafulk** [karelzak/util-linux#1460]
I recently updated libuuid shared objects in my project to fix integer overflow issues which was supposedly fixed as a part of this commit https://github.com/karelzak/util-linux/commit/1c9143d0c1f979c3daf10e1c37b5b1e916c22a1c.
This was also discussed as the right fix in this issue: https://github.com/karelzak/util-linux/issues/1395 and was released as a part of 2.37.2 version

Compiled https://github.com/karelzak/util-linux using `./autogen.sh && ./configure && make` but it generates a libuuid of version 1.3.0 instead of libuuid.so.2.37.2. Is this expected?

**Comment by karelzak** [comment]
Yes, this is expected. The number 1.3.0 is a library API version, and it's not related to the package version. We keep API stable, so this number does not change.

You can see the same for others libs too, for example, glibc:
```
$ rpm -qf /usr/lib/libc.so.6
glibc-2.33.9000-40.fc35.i686
```
the package version is 2.33, library version is 6.
