### ISSUE TITLE
`cal` week number offset by 1

### ISSUE THREAD

**Issue by Stephen-Seo** [karelzak/util-linux#1461]
In the week of 2021 October 1st, Task Warrior and Google Calendar reports that week as week number 39. `cal -w` reports the same week as week number 40.

Additionally, when checking the week numbers starting in 2022, the `cal` utility reports January 1st as week number 1, but the other tools report it as part of week 52 of the previous year.

![Screenshot of week-number bug](https://seodisparate.com/static/uploads/2021-10-01_weeknumber.png)

**Comment by karelzak** [comment]
We have two "week" definitions -- ISO and US -- cal(1) selects it by week start (Su/Mo). It also depends on the way how the first week in the year is calculated.

* ISO - week start on Monday, and definition is "The ISO 8601 definition for week 01 is the week with the first Thursday of the Gregorian year (i.e. of January) in it." https://en.wikipedia.org/wiki/ISO_week_date
```
$ cal -w -m 01 2021; cal -w -m 10 2021;
      January 2021     
   Mo Tu We Th Fr Sa Su
53              1  2  3
 1  4  5  6  7  8  9 10
 2 11 12 13 14 15 16 17
 3 18 19 20 21 22 23 24
 4 25 26 27 28 29 30 31
                       
      October 2021     
   Mo Tu We Th Fr Sa Su
39              1  2  3
40  4  5  6  7  8  9 10
41 11 12 13 14 15 16 17
42 18 19 20 21 22 23 24
43 25 26 27 28 29 30 31
```

* US - 1st Jan is always the first week, this is cal(1) default

```cal -w -s 01 2021; cal -w -s 10 2021;
      January 2021     
   Su Mo Tu We Th Fr Sa
 1                 1  2
 2  3  4  5  6  7  8  9
 3 10 11 12 13 14 15 16
 4 17 18 19 20 21 22 23
 5 24 25 26 27 28 29 30
 6 31                  
      October 2021     
   Su Mo Tu We Th Fr Sa
40                 1  2
41  3  4  5  6  7  8  9
42 10 11 12 13 14 15 16
43 17 18 19 20 21 22 23
44 24 25 26 27 28 29 30
45 31                  
```
It seems the "other tools" mix Su week start and ISO week calculation.

If you want to play with it more try for example
https://www.timeanddate.com/calendar/custom.html?year=2021&country=1&cols=0&wno=1&cdt=1&typ=0&display=3&df=1
"More  Options -> Advanced Customization -> Weeks" where you select from more weeks definitions.

**Comment by Stephen-Seo** [comment]
Thank you for clearing it up for me, I honestly thought there was some mistake, but it seems I was mistaken.
