### ISSUE TITLE
RFE: add support for choosing "pre-timeout" governors in wdctl

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#1475]
This came up here:

https://github.com/systemd/systemd/pull/19970/commits/16ddf9d26a937cdfede1498a000b3d5f6c3d19b0#r689506513

i.e. setting a pre-timeout only really makes sense if one also configures a governor for it. For that it would be great if wdctl could do so and list available governors, i.e. expose these two sysfs files:

/sys/class/watchdog/watchdog0/pretimeout_available_governors
/sys/class/watchdog/watchdog0/pretimeout_governor

**Comment by karelzak** [comment]
Good idea.

 I'll also add --setpretimeout (as we already have --settimeout) to make it possible to set the pre-timeout from the command line.

**Comment by karelzak** [comment]
Implemented; added a new options `--setpretimeout`, `--setpregovernor`, and the output prints the current and all available governors. Now it should be possible to fully control pre-timeout behavior from the command line too.

It's not well tested yet (so I'll keep this issue open for now), I need to compile it on HW with pre-timeout support.

**Comment by karelzak** [comment]
Fixed, implemented. Closing.
