### ISSUE TITLE
unshare: better manipulation of mount namespace behavior

### ISSUE THREAD

**Issue by dustymabe** [karelzak/util-linux#148]
In the email exchange at [1] there was talk about an additional feature to be able to remount the root filesystem with --make-rprivate or --make-rslave.. Here was the proposed option and text:

--propagation=slave|shared|private|none

Is this something worth doing? 

[1] - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739593

**Comment by karelzak** [comment]
Implemented by commit f0f22e9c6f109f8c1234caa3173368ef43b023eb.
