### ISSUE TITLE
Optionally don't call vhangup() in login

### ISSUE THREAD

**Issue by DaanDeMeyer** [karelzak/util-linux#1484]
As discussed in https://github.com/systemd/systemd/pull/21171, when the last fd to a tty is closed, it is reset by the kernel (at least for QEMU's tty driver, not sure if this is true for all drivers). This means any preconfigured tty size (and likely other termios settings) are lost and reset back to 0x0.  From what I understand, the tty needs to be closed for vhangup() to work. However, when systemd is used, the serial-getty service already calls vhangup() on the tty so I don't think login needs to do so again.

Ideally, login would work like agetty. If a tty is connected to STDIN_FILENO, it would just use that tty instead of trying to reopen it like login does now. If I understand correctly, agetty already configures the tty on stdin, stdout and stderr so when login is invoked by agetty, can't it just reuse the stdin, stdout and stderr fds that are already there instead of closing them and reopening the tty?

**Comment by karelzak** [comment]
The default behaviour should be paranoid and we should not assume agetty and systemd, but we can add an option to /etc/login.defs to disable vhangup(). It should be enough to use
```
   if (getlogindefs_bool("LOGIN_DISABLE_VHANGUP", 0) == 0) {
      ...
   }
```
around the code in init_tty(), and explain it in login.1.adoc man page (CONFIG FILE ITEMS section).

Please, send patch :-)

**Comment by DaanDeMeyer** [comment]
I'd prefer if login could somehow detect if it's running under systemd or not but that's probably not all too simple. Anyway; the alternative solution I came up with also fixes the tty size issue without being too intrusive so I don't mind login closing the file  descriptors and calling vhangup().

**Comment by karelzak** [comment]
OK, your "restrore tty size" patch has been merged.
