### ISSUE TITLE
logger: man page slightly incorrect

### ISSUE THREAD

**Issue by rgerhards** [karelzak/util-linux#165]
The man page still says that "logger provides a shell-command internface to the syslog (3) system log module". This is mentioned at various places. However, starting with 2.26 this is no longer true. While I think this has been changed for good reasons and with good intention, my feeling is that the doc should be updated to be precise here. Otherwise one may be mislead to syslog (3) when troubleshooting issues. But that may also be just nit-picking to the non-syslog expert person...

**Comment by karelzak** [comment]
Fixed.
