### ISSUE TITLE
logger: tcp syslog framing is broken, -T unusable

### ISSUE THREAD

**Issue by rgerhards** [karelzak/util-linux#166]
Logger can send via plain tcp syslog if -n -T options are given. However, the framing is broken so that a syslog receiver can not know where the first message ends and the next one starts. It actually looks like no framing at all is used. Plain TCP syslog framing is described in RFC6587.

I don't yet know if this is a regression or not, but my gut feeling is that this bug is around for a longer period of time.

**Comment by rgerhards** [comment]
quick test shows -T was not present in 2.20, so it's probably only in a limited set of versions.

**Comment by karelzak** [comment]
The -T has been introduced by commit 68265d07 (v2.23).
