### ISSUE TITLE
logger: check for timex.h

### ISSUE THREAD

**Issue by wbx-github** [karelzak/util-linux#174]
Hi,

the header check for timex.h is problematic because musl libc and uClibc without UCLIBC_NTP_LEGACY
does not provide ntp_gettime and compile will fail.
Wouldn't it be possible to avoid ntp_gettime?

best regards
 Waldemar

**Comment by karelzak** [comment]
On Mon, Mar 09, 2015 at 03:51:57PM -0700, Waldemar Brodkorb wrote:
> the header check for timex.h is problematic because musl libc and uClibc without UCLIBC_NTP_LEGACY
> does not provide ntp_gettime and compile will fail.
> Wouldn't it be possible to avoid ntp_gettime?

It's idiotic code, it's necessary to check for the function rather than
for a header file. I'm going to fix it tomorrow. Thanks.

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com
