### ISSUE TITLE
test more/regexp fails if TERM is unset

### ISSUE THREAD

**Issue by rudimeier** [karelzak/util-linux#179]
$ TERM= make check TS_OPTS="--parallel=1 more" 
  more: regexp                   ... FAILED (more/regexp)
  more: squeeze                  ... OK

Without TERM it prints a '\r' because of text-utils/more.c:1083:
```c
void kill_line(void)
{
        erasep(0);
        if (!eraseln || dumb)
                putchar('\r');
}
```

**Comment by karelzak** [comment]
I have added export TERM=linux to the tests.

All the more(1) stuff depends on terminal and it does not make sense to call the test with random TERM setting (include unset terminal)

**Comment by rudimeier** [comment]
Would it be interesting to run tests also with other defined TERM settings like xterm, xterm-color, screen, linux, vt100, dumb, whatever ... ?

Maybe also for other tests like "cal".

**Comment by karelzak** [comment]
It depends on utility. The difference between the terminals is usually only in output escape sequences (e.g. cal(1) reads tinfo).

 The more visible difference in behaviour is when the terminal is undefined/unknown/unsupported. For example lib/colors.c stuff checks if the current terminal supports colors, so 

 $ TERM=vt100 dmesg

provides a different output than

 $ TERM=linux dmesg

There are some exceptions like in more(1) are special options for hardcopy (legacy printers?) terminals, line breaks, etc.  but this is (I hope) very unusual for rest of the 
of the util-linux.
