### ISSUE TITLE
sparc compile issue

### ISSUE THREAD

**Issue by wbx-github** [karelzak/util-linux#187]
From: Waldemar Brodkorb <wbx@openadk.org>
Date: Sun, 29 Mar 2015 15:00:30 +0200
Subject: [PATCH] fix regression for sparc builds

With following commit:
5edb0ea6bbd57dd916417737f98c9109dc1ecb5b

Sparc cross-compile fails.

Signed-off-by: Waldemar Brodkorb <wbx@openadk.org>
---
 sys-utils/setarch.c |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/sys-utils/setarch.c b/sys-utils/setarch.c
index 337f8fb..b6159c5 100644
--- a/sys-utils/setarch.c
+++ b/sys-utils/setarch.c
@@ -309,7 +309,7 @@ int main(int argc, char *argv[])
 #if defined(__sparc64__) || defined(__sparc__)
        if (archwrapper && strcmp(arch, "sparc32bash") == 0) {
                if (set_arch(arch, 0L, 0))
-                       err(EXIT_FAILURE, _("Failed to set personality to %s"), p);
+                       err(EXIT_FAILURE, _("Failed to set personality to %s"), arch);
                execl("/bin/bash", NULL);
                err(EXIT_FAILURE, _("failed to execute %s"), "/bin/bash");
        }
--
1.7.10.4

**Comment by rudimeier** [comment]
Markdown screwed your patch, here again:

```diff
From: Waldemar Brodkorb <wbx@openadk.org>
Date: Sun, 29 Mar 2015 15:00:30 +0200
Subject: [PATCH] fix regression for sparc builds

With following commit:
5edb0ea6bbd57dd916417737f98c9109dc1ecb5b

Sparc cross-compile fails.

Signed-off-by: Waldemar Brodkorb <wbx@openadk.org>
---
 sys-utils/setarch.c |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/sys-utils/setarch.c b/sys-utils/setarch.c
index 337f8fb..b6159c5 100644
--- a/sys-utils/setarch.c
+++ b/sys-utils/setarch.c
@@ -309,7 +309,7 @@ int main(int argc, char *argv[])
 #if defined(__sparc64__) || defined(__sparc__)
 	if (archwrapper && strcmp(arch, "sparc32bash") == 0) {
 		if (set_arch(arch, 0L, 0))
-			err(EXIT_FAILURE, _("Failed to set personality to %s"), p);
+			err(EXIT_FAILURE, _("Failed to set personality to %s"), arch);
 		execl("/bin/bash", NULL);
 		err(EXIT_FAILURE, _("failed to execute %s"), "/bin/bash");
 	}
--
1.7.10.4

```

**Comment by karelzak** [comment]
> With following commit:
> 5edb0ea
oh... so my typos in me commit message.

Thanks, applied.
