### ISSUE TITLE
RFE: fdisk: add root partition GUIDs for ARM

### ISSUE THREAD

**Issue by ciupicri** [karelzak/util-linux#203]
fdisk (from util-linux 2.26.2) includes the __Linux root (x86)__ and __Linux root (x86-64)__ GUIDs in the list of available codes ("type L to list all codes"), but the root partition GUIDs for ARM systems, defined in the [Discoverable Partitions Specification][1], are missing:

>  Partition Type GUID                   | Name                       | Allowed File Systems           | Explanation
> ---------------------------------------|----------------------------|--------------------------------|------------
> `69dad710-2ce4-4e3c-b16c-21a1d49abed3` | Root Partition (32bit ARM) | Any native, optionally in LUKS | On 32bit ARM systems the first ARM root partition on the disk the EFI ESP is located on is automatically mounted to the root directory /. If the partition is encrypted with LUKS the device mapper file will be named /dev/mapper/root.
> `b921b045-1df0-41c3-af44-4c6f280d3fae` | Root Partition (64bit ARM) | Any native, optionally in LUKS | On 64bit ARM systems the first 64bit ARM root partition on the disk the EFI ESP is located on is automatically mounted to the root directory /. If the partition is encrypted with LUKS the device mapper file will be named /dev/mapper/root.

[1]: http://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/

**Comment by karelzak** [comment]
Thanks!
