### ISSUE TITLE
[libfdisk] Proper way to create primary partition

### ISSUE THREAD

**Issue by atefhaloui** [karelzak/util-linux#204]
Hi,
  What is the best way to create a set of primary partitions (MBR) ? I've used the following code but the library libfdisk (v 2.26.2) keeps asking me to choose the correct partition type (primary vs extended):

``` C
struct fdisk_context   *cxt = NULL;
struct fdisk_partition *pa = NULL;
struct fdisk_parttype  *type = NULL;
struct fdisk_label     *label = NULL;

cxt = fdisk_new_context();
pa = fdisk_new_partition();

type = fdisk_new_parttype();
fdisk_parttype_set_code(type, 0x83);

fdisk_assign_device(cxt, ".....", 0);

fdisk_create_disklabel(cxt, "dos");
fdisk_reset_alignment(cxt);

label = fdisk_get_label(cxt, "dos");
fdisk_dos_enable_compatible(label, 0);

for (i = 0; i < max; i++)
{
   size_t partno;

   fdisk_reset_partition(pa);
   fdisk_partition_set_type(pa, type);
   fdisk_partition_size_explicit(pa, 0);
   fdisk_partition_start_follow_default(pa, 1);
   fdisk_partition_partno_follow_default(pa, 0);
   fdisk_partition_set_partno(pa, i);

   if (-1 == part[i].size)
   {
      fdisk_partition_end_follow_default(pa, 1);
   }
   else
   {
      fdisk_partition_set_size(pa, part[i].size/fdisk_get_sector_size(cxt));
   }

   fdisk_add_partition(cxt, pa, &partno);
 }

fdisk_write_disklabel(cxt);
fdisk_deassign_device(cxt, 1);
```

Is there any way to pass the partition type information ?
To quickly resolve my issue I've created a patch that will add a new function:

``` C
extern int fdisk_add_partition_with_flags(struct fdisk_context *cxt, struct fdisk_partition *pa, size_t *partno, unsigned int flags)
// where flags is one of:
#define DOS_FLAG_ACTIVE     1
#define DOS_FLAG_PRIMARY        2
#define DOS_FLAG_LOGICAL        3
#define DOS_FLAG_EXTENDED       4
```

but that's not the best way definitely 

Thank you

**Comment by jsolla** [comment]
Any fix to this situation? Just did a workaround using: fdisk_ask_menu_set_result(ask, 'p'); whenever libfdisk asks for primary / extended. But I think is really ugly.

**Comment by karelzak** [comment]
Ah, sorry I somehow miss this your question.

Well, it's dialog driven by default, otherwise you have to specify all by "pa" template.

* pa specifies start within extended partition - add logical
* pa specifies extended partition type - add extended
* pa specifies start, but outside extended partition - add primary

See MBR driver code: https://github.com/karelzak/util-linux/blob/master/libfdisk/src/dos.c#L1526

It seems the problem is  fdisk_partition_start_follow_default() in your code. In this case it uses dialog if no script is specified (script is used for example by sfdisk). IMHO this is API disadvantage, but it should not be difficult to fix it to follow parttype. I'll try it.

Thanks.

**Comment by karelzak** [comment]
I did a change to the library to make it possible to differentiate between primary and logical by partno. The sample code it there:

 https://github.com/karelzak/util-linux/blob/master/libfdisk/samples/mkpart.c

It's not well tested yet (need test it with another disklabels and write regression test for this), but it seems it works.

Example ("make sample-fdisk-mkpart"  is your friend):
```
# modprobe scsi_debug dev_size_mb=100; 
# ./sample-fdisk-mkpart --device /dev/sdc 1M 2M 3M - 5M
Created a new DOS disklabel with disk identifier 0xbdc00e11.
Created a new partition 1 of type 'Linux' and of size 1 MiB.
Created a new partition 2 of type 'Linux' and of size 2 MiB.
Created a new partition 3 of type 'Linux' and of size 3 MiB.
Created a new partition 4 of type 'Extended' and of size 93 MiB.
Adding logical partition 5
Created a new partition 5 of type 'Linux' and of size 5 MiB.

#  fdisk -l /dev/sdc
Disk /dev/sdc: 100 MiB, 104857600 bytes, 204800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 524288 bytes
Disklabel type: dos
Disk identifier: 0xbdc00e11

Device     Boot Start    End Sectors Size Id Type
/dev/sdc1        2048   4095    2048   1M 83 Linux
/dev/sdc2        4096   8191    4096   2M 83 Linux
/dev/sdc3        8192  14335    6144   3M 83 Linux
/dev/sdc4       14336 204799  190464  93M  5 Extended
/dev/sdc5       16384  26623   10240   5M 83 Linux
```
I'll continue on this next week.

**Comment by squimrel** [comment]
In case someone needs to work around this issue on an older version.
You can simply tell it to answer questions with the default answer:
```
int ask_callback(struct fdisk_context *context, struct fdisk_ask *ask, void *data) {
  switch (fdisk_ask_get_type(ask)) {
    case FDISK_ASKTYPE_MENU:
      fdisk_ask_menu_set_result(ask, fdisk_ask_menu_get_default(ask));
      break;
   ...
}

...
fdisk_set_ask(ctx, ask_callback, NULL);
```
