### ISSUE TITLE
readutmp.c and LGPLv2

### ISSUE THREAD

**Issue by atefhaloui** [karelzak/util-linux#208]
Hi,
   From my understanding libblkid is licensed under LGPL 2 or higher. However, it depends on the file `readutmp.c` that is licensed under GPLv3.
The `readutmp` is only required when compiling `lslogins`. Would it be possible to include this file only when required ?

```diff
diff -rup util-linux-2.26.2/lib/Makemodule.am util-linux-2.26.2.new/lib/Makemodule.am
--- util-linux-2.26.2/lib/Makemodule.am	2015-04-29 11:11:51.723818551 +0100
+++ util-linux-2.26.2.new/lib/Makemodule.am	2015-07-03 16:23:00.697224993 +0100
@@ -24,8 +24,11 @@ libcommon_la_SOURCES = \
 	lib/sysfs.c \
 	lib/timeutils.c \
 	lib/ttyutils.c \
-	lib/exec_shell.c \
-	lib/readutmp.c
+	lib/exec_shell.c
+
+if BUILD_LSLOGINS
+libcommon_la_SOURCES += lib/readutmp.c
+endif
 
 if LINUX
 libcommon_la_SOURCES += \
````

Thank you

**Comment by karelzak** [comment]
On Tue, Jul 07, 2015 at 03:34:57AM -0700, atefhaloui wrote:
>    From my understanding libblkid is licensed under LGPL 2 or higher. However, it depends on the file `readutmp.c` that is licensed under GPLv3.

Well, the library is usually installed (by distros) after strip, so
the read_utmp() symbol is removed from the library as it's
unnecessary.

> The `readutmp` is only required when compiling `lslogins`. Would it be possible to include this file only when required ?

The code is necessary only in lslogins. I have modified and moved the
code to lslogins.c.

Thanks!

 Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com
