### ISSUE TITLE
pseudofs list is out of order

### ISSUE THREAD

**Issue by falconindy** [karelzak/util-linux#212]
84ceaf7a196b1c026b9ce91472e4b8c reversed the ordering of fusectl and fuse.gvfs-fuse-daemon. I suspect this wrong -- the list should be sorted according to LC_COLLATE=C since the underlying comparison is done by strcmp.

    $ printf '%s\n' fusectl fuse.gvfs | LC_COLLATE=C sort
    fuse.gvfs
    fusectl
    $ printf '%s\n' fusectl fuse.gvfs | LC_COLLATE=en_US.utf8 sort
    fusectl
    fuse.gvfs

**Comment by karelzak** [comment]
Ah, good point. I usually use ":sort!" vim command, it's mistake with non-LC_COLLATE=C locales.

**Comment by falconindy** [comment]
You can use vim's internal ":sort" rather than forking to the external command, and this just works.
