### ISSUE TITLE
79738105 ("lscpu: cleanup ppc virtualization detection") breaks PowerVM LPAR hypervisor detection

### ISSUE THREAD

**Issue by nacc** [karelzak/util-linux#218]
So I'm trying to fix some corner cases under pHyp, and noticed that after calling read_hypervisor() in an LPAR, desc->hyper is NONE. That is because this commit assumes that /compatible only exists for PowerNV systems. On this LPAR:

# ls /proc/device-tree/compatible 
/proc/device-tree/compatible

Also, I think that means the qemu case of read_hypervisor_powerpc() can't be reached... Shouldn't these be && conditions not nested ifs?

**Comment by karelzak** [comment]
Really good catch, should be fixed now. Thanks!
