### ISSUE TITLE
[RFE] su: Allow environment variable whitelisting for --login

### ISSUE THREAD

**Issue by praiskup** [karelzak/util-linux#221]
This would be similar to sudo's feature `Defaults env_keep += "ENVNAME"` in `/etc/sudoers`.

**Comment by karelzak** [comment]
We already have --preserve-environment, it's now ignored for --login, but maybe we can improve it, and make it usable with --login when a list of env.variables is specified, for example

    su --login --preserve-environment=TERM,HOME

**Comment by praiskup** [comment]
It would be nice to be able to specify this distro-wide, in particular to help with:
https://bugzilla.redhat.com/show_bug.cgi?id=1262837

**Comment by rapgro** [comment]
:+1: 
This feature could be useful for any display manager with automatic login and avoiding usage of PAM configuration to set environment.
