### ISSUE TITLE
Probably Stupid: mount --bind eventually spikes cpu and ram

### ISSUE THREAD

**Issue by tdrusk** [karelzak/util-linux#230]
Debian 8, util-linux package 2.25.2-6

I setup a cron job to run every 5 minutes.

mount --bind /var/www/html/website1/public_html /home/website1/www
mount --bind /var/www/html/website2/public_html/ /home/website2/www
mount --bind /var/www/html/website3/public_html/ /home/website3/www

This caused a spike in my server's CPU and RAM.

About every hour and a half, so every 18 times the server would run out of memory.

I understand I was probably using mount --bind in an uneducated way. Can you explain why this happened?

**Comment by karelzak** [comment]
I guess your /proc/self/mountinfo and in-kernel mount table has been so huge that system run out of memory.

**Comment by tdrusk** [comment]
Sounds like a good guess. Thank you.
