### ISSUE TITLE
PowerVM/PowerKVM: RTAS call should be used for determining the topology

### ISSUE THREAD

**Issue by nacc** [karelzak/util-linux#231]
After some discussion in IBM, I'm now fairly convinced that the "topology" reported by `lscpu` is nonsense on Power systems :). This is because the sysfs contents are not the physical topology (i.e., if you go look at the box itself) but the topology of the LPAR or KVM guest.

There is a PAPR-documented RTAS call that exists and could be used. Would it make sense to try to link lscpu against librtas? Or should I use a dlopen-like call and handle failure to find the library gracefully?

We also need to update what PowerNV is reporting (also wrong), but obviously can't use the RTAS call there. I'm working on the right solution in those environments separately.

**Comment by karelzak** [comment]
Well, lscpu reports information from /sys and goal is to report how *system* sees your CPUs. I don't see a problem to introduce something like --system (default) and --physical to distinguish between these point of views.

It would be better to optionally (e.g. when detected by ./configure) link with librtas than play any games with dlopen.

**Comment by nacc** [comment]
Right, there's just this notion that things like "CPU caches", "cache sharing", etc. are part of the "system" when in fact they are part of the "physical" information. I guess they aren't really changeable (not sure how/if qemu emulates that level of the CPU information?). I will work on adding the flags as you suggest, with an appropriate default.

I'll also work on the configure side of things to add the librtas support. Thanks!

**Comment by karelzak** [comment]
librtas support merged
