### ISSUE TITLE
line(1) reads past the new line

### ISSUE THREAD

**Issue by mwgamera** [karelzak/util-linux#236]
The important feature distinguishing `line` from `sed 1q` or `head -1` was always that it read one byte at a time never reading more than one line. This was working correctly in older versions of util-linux, but it's not the case any more.

For example consider something like `printf 'a\nb\n' | echo $(line) :: $(line)`. The expected output is `a :: b`, but currently it echoes `a ::` with the first `line` reading up the whole input because of libc buffering.

It seems that c2e1ebb is at fault here. Whatever the reason for using `getwchar` instead of `read` was, setting `stdin` to unbuffered should fix it.

**Comment by karelzak** [comment]
Fixed, thanks!
