### ISSUE TITLE
[libsmartcols] [rfe] line_set_data to work with libscols_column *

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#251]
it would be great to have it (especially for bindings for other languages)

**Comment by karelzak** [comment]
Do you mean something like:

```
int scols_line_set_column_data(struct libscols_line *ln, struct libscols_column *cl, const char *data) {
   return scols_line_set_data(ln, cl->seqnum, data);
}
```

.. it should not be a problem.

**Comment by ignatenkobrain** [comment]
Yes, exactly. And also add to API pls.

**Comment by karelzak** [comment]
Test it! ;-)

**Comment by ignatenkobrain** [comment]
Yes! It works! Can I kindly ask you to make new release? ;)

**Comment by karelzak** [comment]
The plan is make release in February.

**Comment by ignatenkobrain** [comment]
OK, I will try to implement everything what I wanted before.
