### ISSUE TITLE
column -s X -t fails when there are colour escapes before X

### ISSUE THREAD

**Issue by voidus** [karelzak/util-linux#252]
To Reproduce:

```
test='\033[33mb\033[mXFoo\n\033[33mbar\033[mXFoo'
echo -e $test
echo '=>'
echo -e $test | column -s X -t
```

Expected:
```
bXFoo
barXFoo
=>
b    Foo
bar  Foo
```

Actual:
```
bXFoo
barXFoo
=>
b   Foo
bar   Foo
```

I'm not quite sure how the escapes should be correctly handled. Colours and other formatting should obviously be stripped, but other escapes could necessitate other handling.

The column from bsdmainutils available in debian does not have this problem. I'm on arch using util-linux 2.27.

I already opened issues on bugzilla.kernel.org [1] and on bugs.archlinux.org [2].

[1] https://bugzilla.kernel.org/show_bug.cgi?id=108521
[2] https://bugs.archlinux.org/task/47240#comment141431

**Comment by karelzak** [comment]
What version of the command do you have in Debian? Is it another implementation or old version from util-linux?

**Comment by voidus** [comment]
Ah, sorry about that. Looks like the debian version I tested is actually the bsd version, it's from bsdmainutils-9.0.6

**Comment by karelzak** [comment]
Fixed, thanks!
