### ISSUE TITLE
libsmartcols: dont crash if developer didn't set cmptfunc

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#256]
Currently it just crashes.

We have 2 ways to fix it:
* Don't execute any comparsions if `cmpfunc` is not set
* The same as 1st but also set default cmpfunc to `scols_cmpstr_cells()`

Thoughts?

**Comment by karelzak** [comment]
Fixed, 1/ ... EINVAL if no cmpfunc specified seems like a good idea.
