### ISSUE TITLE
libsmartcols: cutting last column if no enough space

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#257]
![screenshot from 2016-01-18 19-35-14](https://cloud.githubusercontent.com/assets/2866862/12399524/e135c608-be1a-11e5-9980-2fc6cfde3a62.png)

Last line must be:
```
└─mmcblk0p1              179:1    0  29.5G  1 part /run/media/brain/2A44-3378
```

I think we should somehow move characters to a new line. Also there another bug (let's track it in one GitHub issue):

![screenshot from 2016-01-18 19-41-06](https://cloud.githubusercontent.com/assets/2866862/12399622/71c3cfc6-be1b-11e5-82f4-73e47d01fc7c.png)

I put very long line and it is just continuing last column on next line without indenting (I mean something like we have now in DNF):

![screenshot from 2016-01-18 19-42-47](https://cloud.githubusercontent.com/assets/2866862/12399661/abac1216-be1b-11e5-90bf-9f59f85d4ab2.png)

It is not very well done in DNF, but at least it is more readable.
so instead of:
```
NAME            AGE
Grandfather Bob 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
```
I would like to see
```
NAME            AGE
Grandfather Bob 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
                9 9 9 9 9 9 9 9 9 9 9
```

**Comment by karelzak** [comment]
1/ the lsblk last column is not a bug, but feature of the SCOLS_FL_TRUNC flag. For example findmnt allows to disable this feature by "findmnt --notruncate". Sometimes is more important to keep the output "nice" than print all information :-)


2/ libsmartcols does not wraps too long cells (in another words we **don't modify cell data**). It prints the cell data and if the cell data is too long then indent the next cell. 
This concept follows standard way how all stuff use terminal, we does not add line break (\n) to the cell data and for example if you copy & past the output by mouse then you will *not* see the \n in the data.

```
# mkdir /mnt/test/looooooooooooooooooooooooooooooooooooooooooooooooooooooooong
# mount --bind /mnt/test/looooooooooooooooooooooooooooooooooooooooooooooooooooooooong /mnt/test/looooooooooooooooooooooooooooooooooooooooooooooooooooooooong
```
For example:
```
./findmnt -o FSTYPE,SOURCE,SIZE,USED
FSTYPE          SOURCE                                           SIZE   USED
vfat            /dev/sda1                                      199.8M   8.1M
rpc_pipefs      sunrpc                                              0      0
cifs            //sr.net.home/sounds                             1.8T 232.4G
ext4            /dev/sda4[/mnt/test/looooooooooooooooooooooooooooooooooooooooooooooooooooooooong]
                                                                49.1G  16.8G
```
"looo...ong" has been on two lines, but after copy & past to web browser it's one string.

**Comment by karelzak** [comment]
Note that we can add SCOL_FL_WRAP flag to implement your idea to keep data always in the column.

**Comment by ignatenkobrain** [comment]
Cool, I will implement SCOLS_FL_WRAP in few days.

**Comment by karelzak** [comment]
OK, please use print_empty_cell() to print empty cells after \n.
