### ISSUE TITLE
libsmartcols: print table name

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#258]
I think would be nice to have optional printing table name in center of terminal before table.

I'm thinking to change `scols_table_print(libscols_table *tb)` to `scols_table_print(libscols_table *tb, int print_header)` or store some flags in table like we have for JSON, Human, etc.

What you think would be better?

**Comment by karelzak** [comment]
Well, don't change API :-) 

For JSON we use scols_table_set_name(), if this is not enough then we can add 
```
scols_table_set_title(libscols_table *tb, const char *str, int flag)
```
where flag specifies left/center/right.

**Comment by karelzak** [comment]
Note that "name" is mostly object name from JSON point of view. 

Maybe is better to keep is independent and introduce "title" where you can use more words, colors etc. Hmm.. colors, when we need "color" parametr to scols_table_set_title() ;-)

**Comment by ignatenkobrain** [comment]
OK, lets introduce new API and mark as deprecated in future.
