### ISSUE TITLE
libsmartcols: aligning title with unicode symbols

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#262]
![screenshot from 2016-01-22 14-43-23](https://cloud.githubusercontent.com/assets/2866862/12512106/80863f46-c116-11e5-9b2e-04d5cb07d170.png)

I wasn't thinking about this when I implemented table's title.

It should be easy to fix with just replacing `len = strlen(tb->title);` with some function which returns number of cells taking by this string.

@karelzak Unfortunately I don't have time to find such function - so please fix this bug yourself.

**Comment by ignatenkobrain** [comment]
I also didn't know about `mbsalign()`. Probably we should use it for `SCOLS_FL_RIGHT` and for titles.....

**Comment by karelzak** [comment]
OK, I have reimplemented print_title() by stuff from lib/mbalign.c. I have also renamed title_wrap to title_padding.

- multi-byte titles are supported
- multi-byte padding is not supported yet 
- API is ready for multi-byte padding, but lib/mbalign.c: mbs_align_pad () uses one char for now. I will fix it later.

**Comment by ignatenkobrain** [comment]
Also you forcing to align title to center....

**Comment by ignatenkobrain** [comment]
And I didn't check if padding char also adding after text, but before end of width..

**Comment by karelzak** [comment]
What do you mean by "forcing to align title to center" ? The default is left.

**Comment by ignatenkobrain** [comment]
Sorry, display on my phone is too small that I didn't see code. It is OK.

What about second? Does it ends string with padchar?

**Comment by ignatenkobrain** [comment]
I finally reached my laptop and it works perfectly. Thank you!
