### ISSUE TITLE
RFE: add shortcut for ESP in sfdisk

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#267]
A common use case is create just an ESP and a Linux partition (and maybe swap too). sfdisk today does not have handy shortcut for ESP.

```
echo -e ',512M,U\n,,L' | sfdisk --label gpt /dev/foo
```

Assuming "U" as a shotcut to "EFI system" type. Would make things easier.

**Comment by karelzak** [comment]
Good idea, thanks.

Implemented by commit d09c06baf4eccfb81cb9a5d0285ba6337aec2919.

**Comment by marcosfrm** [comment]
@karelzak thanks. I never tested UEFI with MBR partitioning, but 0xEF is suposed to be also 'EFI system' in MBR. Maybe support it too?

**Comment by karelzak** [comment]
There is officially nothing like EFI+MBR.

EFI uses protective MBR (PMBR) and it has 0xEF as partition type. This PMBR is created automatically when you create EFI partition table. Nobody has to care about it.

The another story is hybrid stuff where people use EFI+MBR, but nothing in util-linux allows to create it by standard way. You have to manually switch to --label-nested mbr and manually create MBR entries.

**Comment by marcosfrm** [comment]
Ok, sorry for my ignorance.

**Comment by grawity** [comment]
The [UEFI specification][2], pages 61, 72, 113–115, actually does require MBR disk support and define an UEFI System Partition for MBR disks. The partition type is 0xEF (do not confuse with the protective-MBR partition type 0xEE).

[1]: http://www.uefi.org/sites/default/files/resources/UEFI%20Spec%202_6.pdf
[2]: http://www.uefi.org/sites/default/files/resources/UEFI%202_5.pdf

**Comment by marcosfrm** [comment]
Right, 0xEE != 0xEF. @karelzak ?

**Comment by karelzak** [comment]
OK, sorry... Legacy MBR, you're right.

**Comment by marcosfrm** [comment]
For consistency, I think you missed a `break;`, no?

**Comment by karelzak** [comment]
Yes :-)
