### ISSUE TITLE
libsmartcols: wrap does not work correctly in start/middle column

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#269]
![screenshot from 2016-02-03 01-51-11](https://cloud.githubusercontent.com/assets/2866862/12769484/a6414810-ca18-11e5-8e74-4d03f2c59eeb.png)

![screenshot from 2016-02-03 01-53-11](https://cloud.githubusercontent.com/assets/2866862/12769517/e771b874-ca18-11e5-9d2e-3c2ec73333ba.png)

But it works perfectly with last column:
![screenshot from 2016-02-03 01-54-07](https://cloud.githubusercontent.com/assets/2866862/12769538/0941c002-ca19-11e5-9810-18b0a0420df8.png)

**Comment by karelzak** [comment]
Yes, we do not use \n ... the problem is that we're trying to print all the cell when we print one line, but it's multi-line cell. The best would be to print a table line in a loop until there is any multi-line column and all cell data are not printed yet. 

The result should be something like:

```
AAA    BBB     CCC                            DDD
  1    hello   long multi-line                something
               cells are supported
  2       hi   short data                     another data    
```

... where CCC is WRAP column with multi-line cell on line 1. I'll try to implement it. It would be useful for more things.

**Comment by karelzak** [comment]
```
$ make ./sample-scols-wrap
$ ./sample-scols-wrap 
NAME                DESC       FOO                         LIKE TEXT                   
A-N-AAAAAAAAAAx     A-D-AAAAAx A-U-AAAAAAAAAAAAAAAAAAAAAAA    1 A-T-AAAAAAAAAAAAAAAAAAA
│                              AAAAAAAAAAAAAAAAAAAAAAAAAAA      AAAAAAAAAAAAAAAAAAAAAAA
│                              xxxxxxxxxxxxxxxxxxxxxxxxxxx      AAAxxxxxxxxxxxxxxxxxxxx
├─aa-N-aaaaaaaaax   aa-D-aaaax aa-U-aaaaaaaaaaaaaaaaaaaaaa    1 aa-T-aaaaaaaaaaaaaaaaaa
│                              aaaaaaaaaaaaaaaaaaaaaaaaaaa      aaaaaaaaaaaaaaaaaaaaaaa
│                              xxxxxxxxxxxxxxxxxxxxxxxxxxx      aaaxxxxxxxxxxxxxxxxxxxx
└─ab-N-aaaaaaaaax   ab-D-aaaax ab-U-aaaaaaaaaaaaaaaaaaaaaa    1 ab-T-aaaaaaaaaaaaaaaaaa
                               aaaaaaaaaaaaaaaaaaaaaaaaaaa      aaaaaaaaaaaaaaaaaaaaaaa
                               xxxxxxxxxxxxxxxxxxxxxxxxxxx      aaaxxxxxxxxxxxxxxxxxxxx
```

... where FOO and TEXT are SCOLS_FL_WRAP columns with long text.
