### ISSUE TITLE
‘look’ uses definition of ‘-d’ inconsistent with ‘sort’

### ISSUE THREAD

**Issue by huftis** [karelzak/util-linux#284]
The man page for `look` says:

    As look performs a binary search, the lines in file must
    be sorted (where sort(1) was given the same options -d
    and/or -f that look is invoked with).

However, the defintion of ‘-d’ in `look` and `sort` is different, so files sorted with `sort -d` does not necessarily work correctly with `look`. The man page for `sort -d` in coreutils says:

       -d, --dictionary-order
              consider only blanks and alphanumeric characters

while the same man page for POSIX sort says:

       −d        Specify  that  only  <blank>  characters and alphanumeric characters, according to the
                 current setting of LC_CTYPE, shall be significant  in  comparisons.  The  behavior  is
                 undefined for a sort key to which −i or −n also applies.

In other words, for both man pages, blanks should be considered when using `-d`. But `look` ignores them. Example:

    # Create a test file
    echo -e 'foo\nfoo bar' > test.txt

This file is sorted, according `sort -d`, also in the C locale, as confirmed by:

    cat test.txt
    sort -d test.txt
    LC_ALL=C sort -d test.txt

However, the last of the following commands returns a wrong/unexpected result:

    look foo test.txt
    look foo\  test.txt
    look -d foo\  test.txt

The last command return both `foo` and `foo bar`, instead of just `foo bar`.

Technically, one might argue that `look` isn’t wrong here, since its definition of `-d` doesn’t formally state that blanks are included in the definition. But the text ‘the lines in file must be sorted (where sort(1) was given the same options -d and/or  -f that look is invoked with)’ do imply that `-d` (and `-f`) is *supposed* to have the same meaning as for `sort`.

AFAICS, the source code for `look` contains the following for handling `-d`:

    175   if (dflag) {
    176     for (readp = writep = string; (ch = *readp++) != 0;) {
    177       if (isalnum(ch))
    178         *(writep++) = ch;
    179     }

and

    336     if (!dflag || isalnum(*s2))

while the source code for `sort` uses

    1280       nondictionary[i] = ! isalnum (i) && ! field_sep (i);

I think the best solution would be to make `look -d` consistent with `sort -d`, by including blanks in the definition of `-d`.

**Comment by karelzak** [comment]
Well, there is note about it in the look.1 man page.

It seems that fix the problem will introduce a small regression, but it's probably better to have documented regression than to be incompatible with sort(1), especially if sort -d is the expected and wanted way how to prepare files for look(1).

Fixed.
