### ISSUE TITLE
unshare: Persisting mount namespace no longer working

### ISSUE THREAD

**Issue by krobertson** [karelzak/util-linux#289]
Using the `--mount=<file>` option to have a mount namespace be persisted with a bind mount was working properly, however something recently triggered it not to. I am not sure exactly what was updated, but don't believe it was a kernel update.

Running on Arch, currently on the 4.4.1-2 kernel. Using util-linux 2.27.1-1 from Arch.

When I tried to persist the mount namespace, it simply gets an `EINVAL`. from the mount call.

```
$ sudo unshare --mount=./mntns bash
unshare: mount /proc/9562/ns/mnt on ./mntns failed: Invalid argument
```

In looking into the issue, had come across this StackOverflow question which linked back to the util-linux support: http://stackoverflow.com/questions/34783391/why-i-couldnt-use-mount-bind-proc-pid-ns-mnt-to-another-file-in-ubuntu/34786934

The little sample code they provide is also failing, and it is rather simple.

Let me know if there is any additional information I can provide.

**Comment by krobertson** [comment]
Worth noting: using the same code from SO, I copied it to another Ubuntu machine on 3.13 and confirmed it works.

However, copying it to another CoreOS based machine using 4.3.3 kernel, it was not working.

**Comment by krobertson** [comment]
Confirmed that this only happens when the filesystem the target being mounted to is mounted shared. If I convert it to private, then it works just fine. Arch and CoreOS default a shared root, Ubuntu doesn't.

Any known way around this, or should I just look at having a workaround for it? I can simply put the targets on a tmpfs perhaps.

**Comment by karelzak** [comment]
This is expected kernel behaviour, the bind mount (e.g. ./mntns) has to be be on private filesystem (but default on systemd based OS is shared).
```
 # mkdir /root/namespaces
 # mount --bind /root/namespaces /roo/namespaces 
 # mount --make-private /root/namespaces

 #  touch /root/namespaces/mnt
 # unshare --mount=/root/namespaces/mnt bash
``` 
.. and all works as expect (I guess). 

unshare does not create the mountpoint and parental directory for the target persistent bind, so I guess it's users responsibility to prepare the all the stuff. But yes, we need to describe the problem in the man page.
