### ISSUE TITLE
nsenter cannot enter unprivileged containers

### ISSUE THREAD

**Issue by jejb** [karelzak/util-linux#315]
When you do a setns on an unprivileged user namespace, you lose all your capabilities meaning you are unable to enter another namespace with setns.  I'm trying to enter an unprivileged build container with a uid/gid shift mapping away from root.  The container is a simple mount and user namespace.  This is what happens currently:

jarvis:~ # nsenter --user=/run/build-container/user --mount=/run/build-container/aarch64 
nsenter: reassociate to namespace 'ns/mnt' failed: Operation not permitted

The reason is nsenter is trying to do a setns on the mount ns *after* it did it on the user ns.

The fix is simple, enter the user namespace last:

diff --git a/sys-utils/nsenter.c b/sys-utils/nsenter.c
index d8690db..1525f15 100644
--- a/sys-utils/nsenter.c
+++ b/sys-utils/nsenter.c
@@ -52,13 +52,13 @@ static struct namespace_file {
         * first.  This gives an unprivileged user the potential to
         * enter the other namespaces.
         */
-       { .nstype = CLONE_NEWUSER,  .name = "ns/user", .fd = -1 },
        { .nstype = CLONE_NEWCGROUP,.name = "ns/cgroup", .fd = -1 },
        { .nstype = CLONE_NEWIPC,   .name = "ns/ipc",  .fd = -1 },
        { .nstype = CLONE_NEWUTS,   .name = "ns/uts",  .fd = -1 },
        { .nstype = CLONE_NEWNET,   .name = "ns/net",  .fd = -1 },
        { .nstype = CLONE_NEWPID,   .name = "ns/pid",  .fd = -1 },
        { .nstype = CLONE_NEWNS,    .name = "ns/mnt",  .fd = -1 },
+       { .nstype = CLONE_NEWUSER,  .name = "ns/user", .fd = -1 },
        { .nstype = 0, .name = NULL, .fd = -1 }
 };

**Comment by jejb** [comment]
Github is useless for cut and paste, lets try an attachment
[tmp.txt](https://github.com/karelzak/util-linux/files/221233/tmp.txt)

**Comment by rudimeier** [comment]
> Github is useless for cut and paste, lets try an attachment

In github markdown you can "quote" code with three backticks plus an optional hint what kind of code it is: 

    ```diff
    <here is the patch>
    ```
Looks like this:
```diff
From de72b2fbef3cccb0daaaac3b4fdcb017d6848683 Mon Sep 17 00:00:00 2001
From: James Bottomley <James.Bottomley@HansenPartnership.com>
Date: Fri, 15 Apr 2016 08:10:20 -0700
Subject: [PATCH] nsenter: enter user namespace last

If you enter it first, you lose privilege for subsequent namespace
enters (see issue

https://github.com/karelzak/util-linux/issues/315

Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>

diff --git a/sys-utils/nsenter.c b/sys-utils/nsenter.c
index d8690db..1525f15 100644
--- a/sys-utils/nsenter.c
+++ b/sys-utils/nsenter.c
@@ -52,13 +52,13 @@ static struct namespace_file {
 	 * first.  This gives an unprivileged user the potential to
 	 * enter the other namespaces.
 	 */
-	{ .nstype = CLONE_NEWUSER,  .name = "ns/user", .fd = -1 },
 	{ .nstype = CLONE_NEWCGROUP,.name = "ns/cgroup", .fd = -1 },
 	{ .nstype = CLONE_NEWIPC,   .name = "ns/ipc",  .fd = -1 },
 	{ .nstype = CLONE_NEWUTS,   .name = "ns/uts",  .fd = -1 },
 	{ .nstype = CLONE_NEWNET,   .name = "ns/net",  .fd = -1 },
 	{ .nstype = CLONE_NEWPID,   .name = "ns/pid",  .fd = -1 },
 	{ .nstype = CLONE_NEWNS,    .name = "ns/mnt",  .fd = -1 },
+	{ .nstype = CLONE_NEWUSER,  .name = "ns/user", .fd = -1 },
 	{ .nstype = 0, .name = NULL, .fd = -1 }
 };
 ```

Or just without using github at all:
```bash
git send-email --to=util-linux@vger.kernel.org  foo.patch
```

**Comment by karelzak** [comment]
@jejb it would be probably better to send this kind of change to mailing list (util-linux@vger.kernel.org) and CC to Eric Biederman <ebiederm@xmission.com>. 

It seems your patch is exactly against the logic suggested by Eric :-)

**Comment by jejb** [comment]
On Mon, 2016-04-18 at 05:08 -0700, Karel Zak wrote:
> @jejb it would be probably better to send this kind of change to
> mailing list (util-linux@vger.kernel.org) and CC to Eric Biederman <
> ebiederm@xmission.com>. 
> 
> It seems your patch is exactly against the logic suggested by Eric :
> -)

Mailing list suits me better than github; sent.

James

**Comment by tunacado** [comment]
In case anyone else starts looking for the patch in a mailing list, it is [archived here](https://marc.info/?l=util-linux-ng&m=146098239705650&w=2).
