### ISSUE TITLE
Mount: could nofail be silent for ntfs partition if Windows is hibernated?

### ISSUE THREAD

**Issue by williamh** [karelzak/util-linux#316]
All,

I am filing this issue due to a bug we got in Gentoo [1]. The user was attempting to reboot his system and he had an ntfs file system in fstabwith nofail in the options field. "mount -a" failed because Windows was hibernated.

I am wondering if nofail could be silent in this situation the same way it is when media or a device isn't present?

Thanks,

[1] https://bugs.gentoo.org/show_bug.cgi?id=579876#C0

**Comment by karelzak** [comment]
The question is how we can detect this situation?

 I have no clue what does it mean "Windows was hibernated" ... I guess that the device is available, but FS is in some unwanted state. It seems too FS specific situation.

**Comment by vapier** [comment]
in this case, `mount` is running `mount.ntfs-3g`.  should we push for `mount.ntfs-3g` to parse+respect nofail ?  or is `mount` consuming that token and not passing it on ?  in which case, so we only have exit codes to work with for IPC.  is there an existing exit code we could bucket this as, or should we define another one (and get `mount.ntfs-3g` to use it) ?

**Comment by karelzak** [comment]
mount(8) pass nofail to mount helper, to see more details try:

     LIBMOUNT_DEBUG=all mount -o nofail -t ntfs /dev/foo /mnt

unfortunately many mount helpers ignore the option :-( From mu point of view it would be better to keep the logic for nofail in mount helpers rather than try to be smart in mount(8) and try to evaluate helper's return codes.

**Comment by vapier** [comment]
that sounds reasonable to me

**Comment by karelzak** [comment]
Closing, seems more elegant to improve mount.ntfs-3g.
