### ISSUE TITLE
'mount --bind -o remount' broken in some cases

### ISSUE THREAD

**Issue by adityakali** [karelzak/util-linux#317]
The recent update from v2.25 to v2.27 (https://chromium-review.googlesource.com/#/c/325680/) triggered the following bug for us:

assume /tmp has following flags already
$ cat /proc/mounts | grep /tmp
tmp /tmp tmpfs rw,nosuid,nodev,noexec,relatime 0 0

In v2.25, following sequence of commands used to work to remove certain mount options from a bind mount (noexec in this example):
$ mkdir /tmp/test
$ mount --bind /tmp/test /tmp/test  # /tmp/test inherits all mount flags on /tmp
$ mount --bind -o remount,nosuid,nodev,^noexec /tmp/test

But with recent version of util-linux, this same command does nothing and returns success.
I pin pointed the problem to commit https://git.kernel.org/cgit/utils/util-linux/util-linux.git/commit/?id=ba986e815c36d733724ce5fa9914a2c9ac4f7432

It seems that "^noexec" is completely ignored because "noexec" is read from mtab. Looking at the code in detail, it seems this is going to affect all MS_NO{DEV|EXEC|SUID|*} mount flags.
There are few workarounds for this:
(1) pass both src and dst to the 'mount --bind -o remount...' command so that /etc/mtab is not read.
(2) pass 'exec' instead of '^noexec' to remove the flag (which seems weird to me personally since there is no MS_EXEC mount flag). 

Is the use of "^" to remove flags not supported anymore? I am not sure if this was intentional change or simply a bug.

**Comment by karelzak** [comment]
> Is the use of "^" to remove flags not supported anymore?

I don't remember it has been ever supported. I don't see support for something like this in any mount version.

Anyway, as described in the man page we have "exec" and "noexec" to control MS_NOEXEC flag usage. The flag MS_EXEC is unnecessary as it's default.

Note that from kernel point of view "remount" does not modify individual flags, but it replaces all the flags by a new set. This is reason why we read mtab by default do get the current setting, modify the setting and then send to kernel a new set of the flags.

It means that  "-o remount,nosuid,nodev,exec" on command line is the right thing as it appends all -o  after options from mtab/fstab and the last specified option wins.
