### ISSUE TITLE
zramctl: add support for /sys/class/zram-control/hot_add

### ISSUE THREAD

**Issue by Nefelim4ag** [karelzak/util-linux#318]
Hi @karelzak , zram module as of 4.2 kernel support hot_add function
My try: 0bc1888

**Comment by Nefelim4ag** [comment]
My try: 0bc18882fbe774018aa0e61c3d53f34d52a7cb8c

**Comment by karelzak** [comment]
Thanks you reminded this issue. I have applied a little bit different implementation.
