### ISSUE TITLE
script: SEGV in fclose(3) in 2.28-1 on Arch Linux

### ISSUE THREAD

**Issue by RalphCorderoy** [karelzak/util-linux#319]
Arch Linux util-linux 2.28-1.  Command was `sudo script PATH="/home/ralph/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/mh" -c 'env | grep PATH' /home/tmp/1463241644.035383444/t.1`

coredumpctl backtrace is

    #0  0x00007f066cd42424 fclose@@GLIBC_2.2.5 (libc.so.6)
    #1  0x0000000000402a5d n/a (script)
    #2  0x0000000000402b41 n/a (script)
    #3  0x0000000000401db1 n/a (script)
    #4  0x00007f066ccfd741 __libc_start_main (libc.so.6)
    #5  0x0000000000402769 n/a (script)

Output file was produced containing expected lines, including "Script (started|done)" head and tail.

**Comment by RalphCorderoy** [comment]
Have a simpler test case.  If the output file for the session can't be created then I think the FILE* is NULL and that's passed to fclose(3).

    $ script foo/bar
    Script started, file is foo/bar
    script: cannot open foo/bar: No such file or directory
                                                          Script done, file is foo/bar
    Segmentation fault (core dumped)
    $

**Comment by karelzak** [comment]
Already fixed by upstream commit 4b0b416acb182576ab1000a1df1ad3722a25f071.
