### ISSUE TITLE
RFE: [cal] use four digit dates

### ISSUE THREAD

**Issue by 2twong** [karelzak/util-linux#320]
This command:
```
$ cal 16
                                16                                

       January               February                 March       
Mo Tu We Th Fr Sa Su   Mo Tu We Th Fr Sa Su   Mo Tu We Th Fr Sa Su
```
outputs the calendar for 2000 years ago. Which is correct, I suppose.

Could cal format that year in the output to make it clearer? i.e. show the year "16" as "0016", so that less people are caught out?

**Comment by karelzak** [comment]
Patch sent to the mailing list. We will see.
