### ISSUE TITLE
infinite loop in blkid_put_cache()

### ISSUE THREAD

**Issue by zmike** [karelzak/util-linux#323]
Not entirely certain how it happened, but calling `mnt_free_cache()` calls 
`blkid_put_cache()`, and this triggered an infinite loop in the `while (!list_empty(&cache->bic_devs))` of that function: `dev` was continually NULL, and the list could never be cleared.

v2.28 on fc23

**Comment by karelzak** [comment]
Strange, sounds like the list is wrongly initialized or so.

It would be nice to have any use case how to reproduce the problem, and also debug output from:
      LIBBLKID_DEBUG=all <command>

**Comment by zmike** [comment]
I have no use case other than running a libmount-based utility that I wrote (based on your input) several years back: you can see the libmount usage here https://git.enlightenment.org/core/efl.git/tree/src/lib/eeze/eeze_disk_libmount_new.c

I've never seen this happen before, and I wasn't doing anything which would trigger mount point or fstab updates, so I'm not sure what further information I can provide.

**Comment by karelzak** [comment]
Can you run the utility with
    LIBMOUNT_DEBUG=all LIBBLKID_DEBUG=all
.. I'm not able to reproduce the problem, so you have to help me ;-)

**Comment by zmike** [comment]
Sure, I can do that. Wasn't sure if it would be useful without triggering the looping. I'll let it go for today and post the log tomorrow.

**Comment by zmike** [comment]
Hm I don't seem to be getting any output. Do I need a special build for this to work?

**Comment by karelzak** [comment]
Try "0xffff" rather than "all" if you have any older version. The debug should be enabled by default (to disable is necessary to modify header files, I hope this does not happen in distros).

**Comment by zmike** [comment]
Sorry for the (long) delay. I've had no success in getting any kind of debug output, and the issue has not occurred again since the original post.
