### ISSUE TITLE
runuser exec

### ISSUE THREAD

**Issue by glensc** [karelzak/util-linux#325]
can runuser be added support for replacing itself with the command to be ran, so it doesn't consume resources being in process table:

```
bash-4.3# runuser -u nobody ps axwuf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       131  0.0  0.0  14064  3184 ?        Ss   17:47   0:00 bash -l
root       160  0.0  0.0  75352  3736 ?        S+   17:50   0:00  \_ runuser -u nobody ps axwuf
nobody     161  0.0  0.0  23504  2496 ?        R+   17:50   0:00      \_ ps axwuf
```

**Comment by karelzak** [comment]
It's the same as su(1), the reason why we keep the "watching parent" is a PAM.

We start PAM sessions and at the end (child exit) we properly close the session. The implementation without parent process will not properly close PAM session and delete user's credentials. Note that PAM session configuration may be very complex, like filesystems mounts, extra logging, etc.

The "watching parent" is very lightweight process, suspended by waitpid().

**Comment by glensc** [comment]
maybe add some simple program that omits pam? there are dozens available there, but none of them are "standard", being one in util-linux has high chance being standard.

or commandline option `--no-pam`?

**Comment by karelzak** [comment]
We have setpriv(1), maybe it should be suitable.

**Comment by glensc** [comment]
ok, `setpriv` can be used, but it's overly verbose:

```
[root@5ec13d2b2e77 /]# setpriv --ruid gitlab-runner --euid gitlab-runner --clear-groups --rgid docker --egid docker -- id
uid=330(gitlab-runner) gid=296(docker) groups=296(docker)
[root@5ec13d2b2e77 /]# setpriv --ruid gitlab-runner --euid gitlab-runner --clear-groups --rgid docker --egid docker -- ps axwuf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      5594  0.0  0.0  14080  3192 ?        Ss   16:57   0:00 bash
gitlab-+  5633  0.0  0.0  23504  2404 ?        R+   16:59   0:00  \_ ps axwuf
```

need to set --[er][ug]id both, would be nice to have option that does the user switching:
- set egid/rgid
- set euid/rgid
- setup supplementary groups
- additionally can specify optionally specific egid/rgid/euid/ruid addition to above

**Comment by glensc** [comment]
also seems `--groups` doesn't take group name, needs numeric value:

```
[root@5ec13d2b2e77 /]# setpriv --ruid gitlab-runner --euid gitlab-runner --rgid gitlab-runner --egid gitlab-runner --groups docker -- id
setpriv: Invalid supplementary group id: 'docker'

[root@5ec13d2b2e77 /]# setpriv --ruid gitlab-runner --euid gitlab-runner --rgid gitlab-runner --egid gitlab-runner --groups $(getgid docker) -- id
uid=330(gitlab-runner) gid=330(gitlab-runner) groups=330(gitlab-runner),296(docker)
```

**Comment by glensc** [comment]
`setpriv(1)` also doesn't reset env, so it's more like low level tool to C functions

**Comment by glensc** [comment]
@karelzak do you have suggestion how to make `sudo -H -u` with util-linux tools?

`setpriv(1)` does almost, except [as noted](https://github.com/karelzak/util-linux/issues/325#issuecomment-227507534), env clearing.

so far i've come up with `env -i`  solution, but it means that i have to pass each and one env variable to preserve, and i don't even know what to preserve, except $PATH and $TERM top of my head.


```
# setpriv --reuid http --regid http --init-groups env -i PATH=$PATH TERM=$TERM SHELL=$SHELL env
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/games:/usr/local/sbin
TERM=screen
SHELL=/bin/bash

# setpriv --reuid http --regid http --init-groups env -i PATH=$PATH TERM=$TERM SHELL=$SHELL id -a
uid=51(http) gid=51(http) groups=51(http)
```

note: `--initgroups` is quite recent change (2.31)

**Comment by karelzak** [comment]
I don't see a problem with another new options and features (like env clearing). Maybe something like
```
--env-set  <name=data>
--env-remove  [<name>]    -- if no name specified, clear all
```
