### ISSUE TITLE
bare \S after \S{ANSI_COLOR} garbled

### ISSUE THREAD

**Issue by zdzichu** [karelzak/util-linux#329]
There seem to be issue in agetty when parsing \S macros. I tried to use following line:

\S{ANSI_COLOR} \S \e{reset}

the result was:

edora 25 (rawhide)m

in blue, i.e. the color was applied correctly, but first letter was cut and ”m” was added at the end.

Another test,
\S{ANSI_COLOR}foo\Sbar\e{reset}baz
resulted in
**edora 25 (rawhide)mbar**baz
(with bolded part in blue).

Workaround:
\S{ANSI_COLOR}\S{PRETTY_NAME}\e{reset}
gives proper result, although {PRETTY_NAME} should no be required (according to the documentation).

**Comment by karelzak** [comment]
Fixed, thanks!
