### ISSUE TITLE
Too long error mesage for invalid option

### ISSUE THREAD

**Issue by heroin-moose** [karelzak/util-linux#338]
When user invokes a program (say lsblk) with invalid command line option (say lsblk -z) the whole program's usage message is printed along with getopt's error message. The problem is that some utilities have a usage message so long that I can't see the actual error, only the last part of the usage message. My suggestion is to use coreutils-like style while reporting such errors:

`lsblk: invalid option -- 'z'`
`Try 'lsblk --help' for more information.`

If you guys are too busy right now I can write a patch.

**Comment by rudimeier** [comment]
I guess this "feature" to always print usage output was added on purpose. I also hate it. And more and more other non-util-linux programs are doing that too this way nowadays.

At least we should not print the usage messages if the programs are running within scripts (no tty). Maybe we could add an environment variable to change that behavior back to the short error message, like
```export UL_SHORT_USAGE_ERROR="yes/no/auto"```

Or even without UL_ prefix to push similar patched to any other projects to be able to disable this damn usage output system wide with one line in /etc/profile for as many programs as possible.

Though personally I would be really happy to disable the usage messages completely by default.

**Comment by heroin-moose** [comment]
Sorry, pushed the wrong button =/

**Comment by karelzak** [comment]
Well, print usage text saves time as you don't have to type --help ... but yes, I understand your point of view especially for programs with long usage() output (like lsblk).

I have personally nothing against coreutils-like way to disable usage messages by default. It would be possible to add ./configure option for this purpose to control this feature (or is it over-engineering?).

Anyway, it would be better to move this discussion to the mailing list.

**Comment by karelzak** [comment]
Note that if we decide to disable usage messages at all then it would be nice to use just one line for an error message. I don't like:
```
ls: unrecognized option '--foo'
Try 'ls --help' for more information.
```
IMHO better is:
```
$ ls --foo
ls:  unrecognized option '--foo' (try "--help" for more information).
```

**Comment by karelzak** [comment]
Implemented in the coreutils-way (first line is error message from getopt_long() and second is advice to use --help). I have originally thought about one line only, but it's too invasive idea. It seems better to use getopt_long() for the error message. 

$ lsblk --foo
lsblk: unrecognized option '--foo'
Try 'lsblk --help' for more information.
