### ISSUE TITLE
Remount operations should be propagated as well

### ISSUE THREAD

**Issue by nuxwin** [karelzak/util-linux#342]
Scenario:

I assume a shared root directory (as done by systemd)

```
mount --make-rshared /
```

We mount `A` on `B` and we make `B` a slave
```
mount --bind A B
mount --make-rslave B
```
We mount `C` in `A`
```
mount --bind C A/C
```
Now, we have:
```
A/C
B/C
```

We want make `A/C` read only and we expect `B/C` to become also readonly
```
mount -o bind,remount,ro A/C
```

Problem: `B/C` is still writable.

Currrently, only mount/umount events are propagated but it would be great if remount operations would be also propagated.

BTW: No sure that this should be done in mount(8). I think that it is more related to mount(2) but I don't known where is the code , nor their bugtracker.

**Comment by karelzak** [comment]
On Wed, Sep 07, 2016 at 06:11:42AM -0700, Laurent Declercq wrote:
> Scenario:
> 
> I assume a shared root directory (as done by systemd)
> 
> ```
> mount --make-rshared /
> ```
> 
> We mount `A` on `B` and I make `B` a slave
> ```
> mount --bind A B
> mount --make-rslave B
> ```
> We mount `C` in `A`
> ```
> mount --bind C A/C
> ```
> Now, we have:
> ```
> A/C
> B/C
> ```
> 
> We want make `A/C` read only and we expect `B/C` to become also readonly
> ```
> mount -o bind,remount,ro A/C
> ```> 
> Problem: `B/C` is still writable.

This is kernel *feature*. The MS_BIND|MS_REMOUNT flags has extra
semantic in the kernel and it's interpreted as "I want change node
flags" (well, it's implemented for RDONLY now).

And generally speaking "propagation event" is mount and umount. Not
remount, because remount changes superblock setting and this is always
shared between all the mounts for the filesystem. The exception is
MS_BIND|MS_REMOUNT.

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Comment by nuxwin** [comment]
@karelzak 

When you say: "The exception is MS_BIND|MS_REMOUNT.", do you mean that remouting a bind mount with for instance MS_NOSUID, will affect all mounts even if the bind mount is a slave?

**Comment by nuxwin** [comment]
@karelzak 

```
well, it's implemented for RDONLY now
```

As far as I know, we can also set MS_NOEXEC, MS_NODEV, MS_NOSUID ... with MS_BIND|MS_REMOUNT. mount(2) is not really clear about that because it is stated that only MS_RDONLY can be changed in this way. The point here is the word used `change` vs `set`. Indeed, there is no way to unset (change) those options once they are set.

I'm right?

**Comment by karelzak** [comment]
Sorry, you're right. It also modifies another node flags, as defined by kernel include/linux/mount.h:

```
#define MNT_USER_SETTABLE_MASK  (MNT_NOSUID | MNT_NODEV | MNT_NOEXEC \
                                 | MNT_NOATIME | MNT_NODIRATIME | MNT_RELATIME \ 
                                 | MNT_READONLY)
```
I had no clue about this kernel code change (2014, commit a6138db815df5ee542d848318e5dae681590fccd).

Anyway, MS_REMOUNT|MS_BIND applies flags changes per node (mountpoint), not to the superblock. See kernel fs/namespace.c: do_remount():
```
        if (flags & MS_BIND)
                err = change_mount_flags(path->mnt, flags);
        else if (!capable(CAP_SYS_ADMIN))
                err = -EPERM;
        else     
                err = do_remount_sb(sb, flags, data, 0);
```
You can use findmnt to see VFS (mountoint) and FS (superblock) flags:
```
# mount -o remount,bind,nodev,ro /mnt/test/A
# findmnt -o TARGET,VFS-OPTIONS,FS-OPTIONS
TARGET                           VFS-OPTIONS                     FS-OPTIONS
...
├─/mnt/test/A                    ro,nodev,relatime               rw,stripe=512,data=ordered
├─/mnt/test/B                    rw,relatime                     rw,stripe=512,data=ordered
...
```

**Comment by nuxwin** [comment]
@karelzak 

Thank you for your answers :+1:

**Comment by nuxwin** [comment]
@karelzak 

```
Anyway, MS_REMOUNT|MS_BIND applies flags changes per node (mountpoint), not to the superblock. See kernel fs/namespace.c: do_remount():

        if (flags & MS_BIND)
                err = change_mount_flags(path->mnt, flags);
        else if (!capable(CAP_SYS_ADMIN))
                err = -EPERM;
        else     
                err = do_remount_sb(sb, flags, data, 0);
```

This is almost what I'm doing in my own perl library: https://github.com/i-MSCP/imscp/blob/hotfixes/engine/PerlLib/iMSCP/Mount.pm#L176
