### ISSUE TITLE
[libsmartcols] 'int' scols_table_get_n(lines|cols)

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#349]
I think `int` is wrong in this context as we use `size_t` in `scols_table_get_(line|column)(struct libscols_table *tb, size_t n`

**Comment by ignatenkobrain** [comment]
ah, I see. It's for returning `-EINVAL`.

**Comment by ignatenkobrain** [comment]
Hmm, looks like that `scols_line_get_ncells()` returns `size_t`.

**Comment by karelzak** [comment]
I think it's better to keep the "get" functions simple and stupid (without -EINVAL errors).

Fixed, now it returns size_t everywhere to make the API consistent (get and set functions).
