### ISSUE TITLE
libmount: using libmount parser for ftab chks

### ISSUE THREAD

**Issue by cherusk** [karelzak/util-linux#351]
Although all means are there, mount util allows no chks so far.

like e.g. 

 **mount -f -c -T /test/fstab**

**mount -a** or **mount /mnt/pnt**  could do the trick, but have side effects.

**Comment by karelzak** [comment]
Well, not sure if I understand your bug report :-)

Do you want to use mount(8) to check your fstab consistence and usability?

**Comment by cherusk** [comment]
Yes, I agree, it's a little cryptic.

In the end, you got it right. As far as I skimmed the code, all would be there for that in the code, it's just a matter of making it accessible from outside.

**Comment by karelzak** [comment]
I like the idea (and it is not first time someone is asking for fstab verification), but  I'd  would like to avoid such code in mount(8) -- mount should be really about mounting filesystems only. What about:
```
  findmnt --verify [<file>]
```
where the default is /etc/fstab. We can check for:
- file parsing
- mount flags verification
- UUID/LABEL/etc parsing
- UUID/LABEL/etc conversion to the device name
- right order of the mountpoints
- existence of the mountpoints
- anything else?

If this sounds good I can try to implement it in the next days, it should be simple.

**Comment by cherusk** [comment]
Great to hear!

Yes, up to you. Don't want to enforce it being integrated into mount. We may still highlight or refer the existence of the functionality in mount man pages.

Additionally to yours, maybe:

- supported fs  check (**/proc/filesystems**)
- mount outcome fake by inference from already mounted FSes
- passno stability (at least warning if root not 1)

Let me know if I can help.

Thanks!

**Comment by karelzak** [comment]
I have merged findmnt --verify [--verbose], try it.

**Comment by cherusk** [comment]
I'm impressed. Still, could not test since of minor build issues, embarrassingly.

I did
**autogen.sh -> configure -> make**
and checked their output, installed some pkgs. No.

Unfortunately nothing obvious.  All built cleanly.

But  the bin
>findmnt --help | grep ver
only gives
 -e, --evaluate         convert tags (LABEL,UUID,PARTUUID,PARTLABEL) 
 -i, --invert           invert the sense of matching
 -V, --version  output version information and exit

I'm on **master** and I verified with git log the commit c768892f4c2c33e52e5e898ee8b552ece4dd5224 is in.

**Comment by karelzak** [comment]
Maybe you need "./findmnt --help | grep ver" in the source tree, rather than execute installed version (somewhere in /usr/bin) :-)

**Comment by cherusk** [comment]
Lol, was in build dir, but really missed local execution. It was late ...

**Comment by cherusk** [comment]
Tested it:

**- right order of the mountpoints**
>> not generically done:

Non working example:

DUMMY-FSTAB:
E1: /mnt (contains /mnt/sub)
E2: /mnt/sub (no mnt-pnt before fs on /mnt mounted)

Would imply dummy mount to verify it and that's may **overkill**.

**- mount flags verification**
Checked with garbled and all allowed opts - not done. Not discerned - every string is accepted, .

**- current kernel supported fs check**
Not done, fstab with fs not in /proc/filesystems was not detected.

No offense intended. Up to you. Great job anyways.

**Comment by karelzak** [comment]
**1/ right order of the mountpoints** -- that's true, and you're right this is overkill.

**2/ mount flags verification** -- this is impossible, we do not interpret mount options in userspace and all unknown options are kernel FS options, the final decision depends on FS driver.

**3/ current kernel supported fs check** -- findmnt does not use /proc/filesystems only, it also checks /lib/modules for FS modules.
```
$ echo "/dev/sda1 /mnt  isofs default 0 0" > ~/fstab
$ grep isofs /proc/filesystems 
$ ./findmnt --verify --tab-file ~/fstab
/mnt
   [W] cannot detect on-disk filesystem type
```
(the warning means that we have no access to the device)

```
$ echo "/dev/sda1 /mnt  CrazyFS default 0 0" > ~/fstab
$ ./findmnt --verify --tab-file ~/fstab
/mnt
   [W] CrazyFS seems unspported by the current kernel
```
