### ISSUE TITLE
[libsmartcols] scols_table_get_termwidth() modifies libscols_table in-place

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#356]
```c
if (tb->termwidth == 0)
    tb->termwidth = get_terminal_width(80);
return tb->termwidth;
```

IMO it should just return `get_terminal_width(80)` in case width is 0.

**Comment by karelzak** [comment]
Fixed.

I don't want to call get_terminal_width(80) often, it's expensive. So, let's call it when table is initialized.

**Comment by ignatenkobrain** [comment]
@karelzak why not while printing in HUMAN format?
