### ISSUE TITLE
fsck doesn't pass -r to fsck.vfat

### ISSUE THREAD

**Issue by arromdee** [karelzak/util-linux#362]
I reported this for Mageia Linux at https://bugs.mageia.org/show_bug.cgi?id=16430 but was told to submit it upstream.  The version of fsck is from util-linux 2.25.2 and fsck.fat 3.0.27.

The reply there was that it can't pass the -r because fsck might be called on a vfat filesystem on bootup, which doesn't make sense to me because by that reasoning it shouldn't be processing the -r for other filesystem types either.

**Comment by karelzak** [comment]
You have to differentiate between generic fsck options and filesystem specific options.
```
  fsck [options] -- [filesystem options]
```
"fsck -r"       reports certain statistics
"fsck -- -r"   pass "-r" to filesystem specific helper, e.g. executes "fsck.vfat -r"

And yes, fsck is not responsible for fs-specific options and it does not filter out the options according to filesystem type. It means "fsck -- -r" will use "-r" for all filesystems.

For such complicated use-cases it's recommended to call directly fsck.type helper.

Note that the latest upstream version v2.29-rc1 fsck man page does not contain fs-specific options at all (like -r or -y) to avoid misunderstandings.
