### ISSUE TITLE
libfdisk - various script parsing bugs

### ISSUE THREAD

**Issue by kFYatek** [karelzak/util-linux#367]
Hello,

I was recently playing with Clonezilla to make a backup of my laptop, and while testing the finished backup on a VM, I realized that GPT partition attributes were not preserved (which resulted in Windows treating its recovery partitions slightly incorrectly, but that's a whole another topic).

Anyway, after a bit of debugging, I found that it is indeed an `sfdisk` bug. For example (a more complete debugging log will follow), the following entry from the backup file (`sda-part.sf`):

`/dev/sda5 : start=   455086080, size=     2048000, type=DE94BBA4-06D1-4D40-A16A-BFD50179D6AC, uuid=1778DE2B-B2DF-457C-B1BC-786D43334014, name="Basic data partition", attrs="RequiredPartiton GUID:63"`

got restored to:

`/dev/sda5 : start=   455086080, size=     2048000, type=DE94BBA4-06D1-4D40-A16A-BFD50179D6AC, uuid=1778DE2B-B2DF-457C-B1BC-786D43334014, name="Basic data partition"`

So I opened the source code and I found quite a lot of bugs in the sfdisk script parsing code in `libfdisk`. This occured to me on 2.27.1 as used by Ubuntu (on which the Clonezilla Alternate image I used is based), but I see that the relevant code remains unchanged on the current master.

- `next_token()` in `script.c` - when the code encounters a closing `"`, it replaces it with a `\0` but does not increment the `str` pointer. In other words, any quoted token will immediately interrupt parsing, which explains why the `attrs` token is ignored in my example. **EDIT:** Also, there is no escaping mechanism in the quoting logic, which makes it impossible to encode a `"` *inside* an e.g. parition label.
- `parse_line_nameval()` in `script.c` equates `type=` with `Id=` and uses case-insensitive comparison on those. However, few lines below there's `p += (*p == 'I' ? 3 : 5);`. Imagine what may happen if we put a *lowercase* `id=` without a value at the end of a line ;)
- There was a typo ("RequiredParti**to**n") in `GPT_ATTRSTR_REQ` in `gpt.c`, but I see that it has already been addressed in the current revisions.
- `gpt_entry_attrs_from_string()` move past the tokens matched by `strncmp()` or `strtol()` and do not check what's there afterwards. This results in `62LegacyBIOSBootableGUID:GUID:GUID:NoBlockIOProtocol63RequiredPartiton` being treated as a perfectly valid attribute string...

These are just the bugs I was able to spot and that stood out for me while I was resolving my own issue (and searching for a workaround...). There are probably more - in particular, not checking if matched tokens are actually separated by anything looks like a common bug in `libfdisk`.

Anyway, here's a log file with this bug replicated and with debug info: https://gist.github.com/kFYatek/f1bc044bc3a5d47286922e1eae496b9a

**Comment by karelzak** [comment]
I'll fix it tomorrow. Thanks!

**Comment by karelzak** [comment]
All should be fixed and for all added regression tests.

The escaping mechanism added to TODO file (it's too late now before release and it's more complex as it would be nice to support non-printable chars too).
