### ISSUE TITLE
`mount` run by root ignores 'exec' option when specified with 'user' option

### ISSUE THREAD

**Issue by bkurtz** [karelzak/util-linux#368]
When `mount` is run as root (e.g. at system boot time), mounts with both `user` and `exec` options have the `exec` option ignored.  This appears to have been fixed in the old `mount`, but the fix seems not to have carried over to the new `mount` that uses libmount.

See commit a4c0cc75ff9744299f108c259efab1bd30c8007a and https://bugzilla.redhat.com/show_bug.cgi?id=769636

System calls seem to be different now (`mount` calls `mount(2)` directly instead of `execve(mount.nfs)`), but the symptoms are the same, and underlying cause is presumably similar.

**Comment by karelzak** [comment]
Are you talking about NFS?

It would be nice to have your fstab entry to reproduce the problem. The original problem with mount.nfs should be already covered by libmount.

**Comment by karelzak** [comment]
v2.28.2

fstab with user & exec:
```
/dev/sdc1       /mnt/test       ext4    noauto,user,exec
```
"strace -e mount  mount /mnt/test"" output:
```
mount("/dev/sdc1", "/mnt/test", "ext4", MS_MGC_VAL|MS_NOSUID|MS_NODEV, NULL) = 0
```
fstab without exec:
```
/dev/sdc1       /mnt/test       ext4    noauto,user

```
strace output:
```
mount("/dev/sdc1", "/mnt/test", "ext4", MS_MGC_VAL|MS_NOSUID|MS_NODEV|MS_NOEXEC, NULL) = 0
```
so it accepts the exec.

**Comment by bkurtz** [comment]
Yes, NFS sorry.  Looks like I jumped to conclusions a bit.  Oops!  Thinking now I should be submitting this as a bug to Ubuntu's nfs-utils package - does that sound right to you?  More info below if interested.

fstab:

    labserver.site.com:/Public	/mnt/lab_disk nfs	users,exec,nosuid   0 0

run as me (`sudo strace -u $UID -f mount /mnt/lab_disk`):

    execve("/sbin/mount.nfs", ["/sbin/mount.nfs", "labserver.site.com:/Public", "/mnt/lab_disk", "-o", "rw,nosuid,nodev,users"], [/* 14 vars */]) = 0
    ...
    mount("labserver.site.com:/Public", "/mnt/lab_disk", "nfs", MS_NOSUID|MS_NODEV, "addr=...,vers=3,proto"...) = 0

run as root (`sudo strace -f mount /mnt/lab_disk`):

    execve("/sbin/mount.nfs", ["/sbin/mount.nfs", "labserver.site.com:/Public", "/mnt/lab_disk", "-o", "rw,nosuid,nodev,users"], [/* 14 vars */]) = 0
    ...
    mount("labserver.site.com:/Public", "/mnt/lab_disk", "nfs", MS_NOSUID|MS_NODEV|MS_NOEXEC, "addr=...,vers=3,proto"...)

I'm on Ubuntu 16.04.  Tried this with both the built-in mount and a new version from git.  Versions:

    $ /bin/mount --version
    mount from util-linux 2.27.1 (libmount 2.27.0: selinux, assert, debug)
    $ /tmp/util-linux/mount --version
    lt-mount from util-linux 2.29.rc2-22-82e8d (libmount 2.29.0: btrfs, assert, debug)
    $ /sbin/mount.nfs --version
    mount.nfs: (linux nfs-utils 1.2.8)

**Comment by karelzak** [comment]
Ah, I see the problem. You use "users" rather than "user" and libmount does not support it for "users". I'll fix it, it seems like a bug. The old mount(8) supported it for "user" as well as for "users".

You don't need to report it to nfs guys.

**Comment by karelzak** [comment]
Thanks for your report!

**Comment by bkurtz** [comment]
Awesome, thanks!  I can confirm (no surprises) that behavior is now as expected.
