### ISSUE TITLE
verbose and version both have -V as option

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [karelzak/util-linux#371]
For mkfs command, both verbose and version both have -V as option.

It is better to have -v for version and -V for verbose.
This needs to be differentiated.

Also, not all file systems seems to support verbose, atleast xfs does not support.
Shouldn't mkfs make it mandatory to implement verbose / display some error message saying verbose is not supported ?

**Comment by karelzak** [comment]
Sure, we know about it and it was already discussed on mailing list and there is a note about it in the man page. The problem is backward compatibility. This is reason why -V is "--version" only when used alone.

mkfs is deprecated, there is no plan to improve it.
