### ISSUE TITLE
sfdisk --dump fails in a weird way on disk images with no partition table

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#375]
If I create an empty disk image and use "sfdisk --dump" on it, then sfdisk fails with this:

```truncate -s 1G empty && sfdisk --dump empty ; echo $?```

Not entirely sure what the right result of this should be, but I am pretty sure an error saying "Success" isn't right.

(Ideally I think this would be detected as empty disk label, and would be shown as such without an error).

**Comment by poettering** [comment]
```
$ rpm -qf /usr/sbin/sfdisk
util-linux-2.28.2-1.fc24.x86_64
```

**Comment by karelzak** [comment]
> Ideally I think this would be detected as empty disk label, and would be shown as such without an error

I think there is difference between empty disk (=no label at all) and empty label (= label with no partitions).

on empty disk it ends with error message (fixed version from master branch):
```
  sfdisk: empty: does not contain a recognized partition table
```
on empty partition table it returns basic header informartion:
```
label: gpt
label-id: 3BDC9077-D0CF-4DAC-B2E6-957504AF0E9D
device: empty
unit: sectors
first-lba: 2048
last-lba: 2097118
```

The next step will be to make this dump usable (aka #374).
