### ISSUE TITLE
sfdisk exits with 0 and no error message

### ISSUE THREAD

**Issue by aw** [karelzak/util-linux#376]
It seems there's a regression in sfdisk in regards to output/error codes:

```
# sfdisk -l /dev/nothing
# echo $?
0
```

I noticed this issue in versions `2.27`, `2.27.1` and `2.28.2`.

It works fine on version `2.25.2`, each version compiled using the exact same build flags:

```
# sfdisk -l /dev/nothing
sfdisk: cannot open /dev/nothing for reading: No such file or directory
# echo $?
1
```

Perhaps related to what @poettering mentioned in #374

**Comment by karelzak** [comment]
Thanks for your report!

**Comment by aw** [comment]
Awesome! Thank you so much!

**Comment by falconindy** [comment]
This seems to apply to fdisk as well.

```txt
# fdisk -l /dev/missing; echo $?
fdisk: cannot open /dev/missing: No such file or directory
0
```
