### ISSUE TITLE
Output of mount misleading for --bind

### ISSUE THREAD

**Issue by Toxantron** [karelzak/util-linux#388]
I think the output of `mount` is misleading when sub-directories where mounted using `mount --bind`. The real mount and all bind mounts on the same partition are shown identically in the output.

### Reproduce
Create a test directory, mount some other directory to it and run `mount`:

```sh
mkdir test
mount --bind /some/path/on/mounted/partition test
mount
```

For the directory *test* it will show the same device, partition and fs-type as for the partition of its binding target. However it does not display the `--bind` option nor its target path.

 From [this answer](http://unix.stackexchange.com/a/18067/175521) I understand, that this caused by identical information in */proc/mounts*. However it also states that the per-process mount at */proc/$pid/mount* contains the required information.

Is this:
a) intended and won't be changed
b) an idea to use the current PID mount information
c) something I should rather ask the kernel guys

**Comment by karelzak** [comment]
The mount(8) output is correct. The bind operation makes a new "connection" between a filesystem and the target mount point. The source directory for the bind operation is just a way how to specify source filesystem, nothing else.

In the system is nowhere recorded the original source directory, because it's irrelevant (you can for example delete the dir). In thins case you should think about bind mount as another way how to mount the filesystem to the target mountpoint.
```
mount /dev/sda1 /mnt/A
mount /dev/sda1 /mnt/B
```
is the same as
```
mount /dev/sda1 /mnt/A
mount --bind /mnt/A /mnt/B
```

Yes, there is nothing to fix or change :-)

**Comment by Toxantron** [comment]
I understand your example and this behavior is totally fine with me. What I meant is:

```sh
mount /dev/sda1 /mnt/A
mount --bind /mnt/A/Foo /mnt/B
```

mount(8) will then tell me that `/dev/sda1` is mounted on `/mnt/A` and `/mnt/B`. This gave me the impression that they should contain the same content and that the content of either _A_ or _B_ is the content of my partition. It took me a while to figure out the real content of `/dev/sda1` and the location of _B_ on that partition. Is this still intended?

**Comment by Toxantron** [comment]
@karelzak could you please comment on my last question? I will leave it at that, promised. ;-)

**Comment by karelzak** [comment]
For your example see findmnt output, you will see something like  /dev/sda1[/Foo] as SOURCE for the /mnt/B.

The same filesystem (superblock) is mounted on both mountpoints, but /mnt/B uses a different directory (/Foo) as root of the filesystem.

**Comment by Toxantron** [comment]
Now I got it. Thank you very much @karelzak . ;-)

If you don't mind I will link to this conversation on SO in the original question that brought me here.
