### ISSUE TITLE
problem with runuser command line parsing

### ISSUE THREAD

**Issue by fabiocannizzo** [karelzak/util-linux#399]
`runuser`'s [manual](http://man7.org/linux/man-pages/man1/runuser.1.html) says:
`runuser [options] -u user command [argument...]`
suggesting that anything passed on the command line after `-u user` is part of the command and its arguments.

However, the following command generates an error:
```
# runuser -u myuser ls -l
runuser: options --(shell,fast,command,session,session-command,login) and --user are mutually exclusive

```
The parser thinks that `-l` is an argument to `runuser`, rather than an argument to the command `ls`.

To get it to work I have to create a shell file (`file.sh`) containing `ls -l`, then use:
`runuser -u myuser /bin/bash file.sh`

Is it a bug or am I missing something obvious?

`runuser -V` returns `runuser from util-linux 2.28.2`

Thanks

**Comment by karelzak** [comment]
You have to use "--"  as a separator, for example:
```
runuser -u myuser -- ls -l
```
I have updated the man page. Thanks.

**Comment by fabiocannizzo** [comment]
Thank you.
