### ISSUE TITLE
[RFE] findmnt -o value

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#402]
I want to get exactly source of mountpoint, but without removing heading line I don't see any other option.

**Comment by karelzak** [comment]
Not sure if I fully understand
```
$ findmnt -o SOURCE /home
SOURCE
/dev/sda3
```
Or do you mean something else? 

The -n removed the "SOURCE" header line to make it usable for example in scripts, for example:
```
$ FOO=$(findmnt -no SOURCE /home)
$ echo $FOO
/dev/sda3
```

**Comment by ignatenkobrain** [comment]
ah, right: `-n`. Thanks for pointing out.
