### ISSUE TITLE
cfdisk: Trying to use the arrow keys to change partition size failed

### ISSUE THREAD

**Issue by jidanni** [karelzak/util-linux#403]
Trying to use the arrow keys to change
Partition size: 7.5G
to
Partition size: 7G
failed.
Had to use DEL DEL DEL G.
cfdisk from util-linux 2.29.1

**Comment by karelzak** [comment]
That's true, you have to use DEL or BACKSPACE.

I have somewhere patch to implement more feature rich editor for the UI fields, but it's not merged yet.

**Comment by jidanni** [comment]
(Well we can use arrows on other parts of the page but not here.)

**Comment by karelzak** [comment]
The problem should be fixed, the change will be available in v2.30
