### ISSUE TITLE
cfdisk: Trying to use ^L to refresh the screen failed

### ISSUE THREAD

**Issue by jidanni** [karelzak/util-linux#404]
Trying to use ^L to refresh the screen failed.
What if ever the console / X window has any other stray character
arriving, and needs to be refreshed?

OK I found a workaround! ^Z then fg.
cfdisk from util-linux 2.29.1

**Comment by karelzak** [comment]
Something like "refresh" is not implemented yet ;)

**Comment by karelzak** [comment]
Should be fixed. Try it.

**Comment by jidanni** [comment]
OK I'll try it when it hits Debian experimental/sid.
