### ISSUE TITLE
logger does not support private enterprise sub-tree.

### ISSUE THREAD

**Issue by aellisv** [karelzak/util-linux#406]
When specifying the RFC5424 SD-ID, I am prevented to use subtree specifications.  For example:
if I use: --sd-id "myname@1234", logger works.
If I use: --sd-id "nyname@1234.123, logger errors out with: logger: invalid structured data ID: 'myname@1234.123'

Adding the subtree is allowed in the RFC5424 spec, sec 7.2.2 as follows.
   An enterprise might decide to
   use sub-identifiers below its private enterprise number.  If sub-
   identifiers are used, they MUST be separated by periods and be
   represented as decimal numbers.  An example for that would be
   "32473.1.2".

**Comment by karelzak** [comment]
Good catch, thanks! Fixed.
