### ISSUE TITLE
[findmnt] "findmnt --pairs --poll" and "findmnt --raw --poll" do not separate each (un)(re)mount event's output by a new line \n.

### ISSUE THREAD

**Issue by Pedro-MC** [karelzak/util-linux#409]
"findmnt --pairs --poll" and "findmnt --raw --poll" do not separate each (un)(re)mount event's output by a new line.

Using "git bisect", I traced the first commit with this issue to:
346e3a40a0dd8ff543a3c3daf32d47783e8dc7a9 is the first bad commit
commit 346e3a40a0dd8ff543a3c3daf32d47783e8dc7a9
Author: Karel Zak <kzak@redhat.com>
Date:   Fri Sep 16 13:00:47 2016 +0200

    libsmartcols: cleanup line separator usage
    
     * use line separator only to separate lines, not after last line
     * explicitly print \n after table in scols_print_table()
     * don't terminate table by \n or line separator in scols_print_table_to_string()
    
    Note that the patch is little bit trick due to impact to the trees
    printing. Now print_tree_line() should be more readable.
    
    Signed-off-by: Karel Zak <kzak@redhat.com>

**Comment by karelzak** [comment]
I think the bug is visible for all formats (without --raw and --pairs). Fixed.

(Note that --json is not perfect in this case, but it's unfixable due to comma separators between lines)
