### ISSUE TITLE
Misleading error message in taskset

### ISSUE THREAD

**Issue by devkid** [karelzak/util-linux#413]
When a task is limited to a set of cores (either via `isolcpus` or via the `cpuset` cgroup), setting the scheduling affinity to a core outside of this set will fail.

When starting a new program (instead of modifying the affinity of a running one), taskset gives a misleading error message:
```
# taskset -a -c 1 ls
taskset: failed to set pid 0's affinity: Invalid argument
```

It says `pid 0` because that is the value that is passed to `sched_setaffinity` but this can be very misleading, especially if you use `taskset` inside scripts and question your sanity because you didn't tell it to do anything with PID 0. It would be better to not print the pid at all if none is given.

**Comment by karelzak** [comment]
Good point. Fixed.

**Comment by ZiwenZhuang** [comment]
Sorry, I still don't get the point. If this message appears, what will happen if I just leave the program running?

**Comment by karelzak** [comment]
> Sorry, I still don't get the point. If this message appears, what will happen if I just leave the program running?
The program will continue with the original affinity setting (I guess).
