### ISSUE TITLE
lscpu translations breaks output alignment and make it difficult to read

### ISSUE THREAD

**Issue by bigon** [karelzak/util-linux#419]
Hi,

When translated in French, the output of lscpu is completely misaligned.

This makes it difficult to read the values. I guess it can be the case for other languages as well.

Might be an issue with libsmartcols

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811488

**Comment by karelzak** [comment]
Unfortunately, the issue is that lscpu DON'T use libsmartcols for this basic output :-) I'll fix it.

**Comment by ignatenkobrain** [comment]
@bigon note that translators were putting ` ` before `:`, so new output can be a bit wrong as well.

![screenshot from 2017-03-15 18-25-34](https://cloud.githubusercontent.com/assets/2866862/23961937/cd37df9a-09ac-11e7-8a53-0f036651828c.png)

**Comment by bigon** [comment]
space before (and after) `:` is mandatory in French

But IMHO, these translations might be a bit too long as well
