### ISSUE TITLE
I/O error while ejecting a usb device 

### ISSUE THREAD

**Issue by liuzhengyuan** [karelzak/util-linux#423]
I  catch some IO error like "Buffer I/O error on dev sdc2, logical block 1, async page read"  while ejecting a mounted usb device which was formatted to ntfs, a userspace filesystem, using command eject.  I can reproduce this error with other fuse filesystem such as fuse-ext2, but it all seem to be OK while formatting the usb device to kernel filesystem such as ext4 and xfs.  The difference  from my observing between fuse filesystem and non-fuse filesystem was that the fuse filesystem will create a device node at /sys/devices/virtual/bdi/ when mounting  and delete the node when unmounting,  those create/delete action could raise some uevent which may cause  udev to read/write IO on block device we are ejecting.
 I viewed the source code of eject and found it mainly do two things, firstly try to unmount all mounted  partition  if possibility, then issue some ioctl to eject the device. The problem is that we can't guarantee there isn't IO request on flight  while we are doing eject ioctl. So I think we should keep other process out from opening the device while we have opened the device for eject.  This may could be realised by  placing a file  exclusive lock .

**Comment by karelzak** [comment]
Do you mean open(..., O_EXCL)? 

Hmm... maybe it's not bad idea, but it would be nice to use it as the first attempt and if unsuccessful than fallback to open() without the flag.

Send patch ;-)

**Comment by howaboutsynergy** [comment]
Is the ability to `eject` eg. the card reader while `umount` is in the process flushing all data a kernel [bug](https://bugzilla.kernel.org/show_bug.cgi?id=203441)(/feature?) or can `util-linux` do anything about preventing it?

> While `umount 1` (where 1 is a directory where /dev/sdd3 of card reader is mounted) is in process, I open another terminal and do a `sudo eject /dev/sdd`, fully expecting it to block until `umount 1` finishes, but it succeeded and thus interrupting the flush that umount was doing and thus making incomplete writes on the ext4 filesystem on /dev/sdd3 ...
[ 7247.611468] Buffer I/O error on device sdd3, logical block 376832
[ 7247.612952] sd 3:0:0:2: [sdd] tag#0 access beyond end of device
[ 7247.613583] JBD2: Detected IO errors while flushing file data on sdd3-8
[ 7247.613973] EXT4-fs (sdd3): I/O error while writing superblock
re-mounting afterwards:
[ 7396.385018] EXT4-fs (sdd3): recovery complete
[ 7396.387830] EXT4-fs (sdd3): mounted filesystem with ordered data mode. Opts: (null)
and a bunch of files are 0 bytes...

**Comment by karelzak** [comment]
Yes, eject checks kernel mount table -- if there is no entry for the device than it calls the ioctls to eject the device. So, no entry in mount table means that we're ready to eject. I have doubts we can do anything else (well, I've no tried to use O_EXCL).

**Comment by karelzak** [comment]
For fdisks we use fsync() on device file descriptor, the question is if this is relevant for filesystem on the device. I have ask some kernel devels :-)

**Comment by karelzak** [comment]
OK, so fsync()  is out of game, it has no effect for on-device filesystems. 

I have added O_EXCL to the code, it's possible to disable it by --force and --no-umount, otherwise (=default) it uses the exclusive open(). It seems like elegant way how to detect possible races (or bugs in eject).
