### ISSUE TITLE
[script] Output control of translations including new lines

### ISSUE THREAD

**Issue by renyuneyun** [karelzak/util-linux#427]
I found this when using the `script` tool. The translations for the "**start**" and "**done**" message doesn't contain the newline character `\n`, but the newline character is included in the **time** buffer. One example is:
```
strftime(buf, sizeof buf, "%c\n", localtime(&tvec));
...
fprintf(ctl->typescriptfp, _("Script started on %s"), buf);
```

This won't harm when it's English, but will mess up the translation in some languages (e.g. Chinese) because they will switch the order of the time string and some other words.

I'm trying to fix this, but there are two options (that will cause different problems):
1. Move the `\n` character directly to the `fprintf` line
2. Use another buffer to handle the result of the translation, and add newline there

If I choose the 1st option, does that involve the change of all translation files? If so, is that acceptable?
If I choose the 2nd option, the source code will be a little harder to read. Is that acceptable?

So generally, which would be preferred?

**Comment by karelzak** [comment]
Good point, maybe the best would be to avoid strftime() at all and use strtime_iso() from lib/timeutils.c, something like:

```
#include "timeutils.h"
...
char buf[ISO_8601_BUFSIZ];
...
strtime_iso(&tvec, SO_8601_DATE | ISO_8601_TIME | ISO_8601_DOTUSEC |
                                ISO_8601_TIMEZONE | ISO_8601_SPACE,
                               tbuf, sizeof(tbuf));
fprintf(ctl->typescriptfp, _("Script started on %s\n", buf);
```

It provides more standardized output without the \n issue.
