### ISSUE TITLE
losetup detach does nothing and doesn't return an error code

### ISSUE THREAD

**Issue by HaleTom** [karelzak/util-linux#431]
Below I am trying to detach `/dev/loop2`. 

If there is no error, why is the device still shown in the second `losetup -a` output?

```
@svelte /mnt# losetup --version
losetup from util-linux 2.29.1
@svelte /mnt# losetup -a
/dev/loop1: [0022]:327383 (/root/btrfs-home-loop/bifile2)
/dev/loop2: [2065]:58656 (/Backup/svelte-backup.btrfs)
/dev/loop0: [0022]:326005 (/root/btrfs-home-loop/bifile)
@svelte /mnt# losetup -vd /dev/loop2
@svelte /mnt# echo $?
0
@svelte /mnt# losetup -a
/dev/loop1: [0022]:327383 (/root/btrfs-home-loop/bifile2)
/dev/loop2: [2065]:58656 (/Backup/svelte-backup.btrfs)
/dev/loop0: [0022]:326005 (/root/btrfs-home-loop/bifile)
@svelte /mnt# 
```

**Comment by HaleTom** [comment]
The full path of the file should have been `/mnt/2TB/Backup/svelte-backup.btrfs`

The file `Backup/svelte-backup.btrfs` did not actually exist - I'm not sure how the kernel got confused about this!

**Comment by karelzak** [comment]
Not sure why the path is truncated. The kernel ioctls to get the path for loopdev has restriction, but it's 64 bytes and we don't use it by default. The default is to get path from /sys/block/loop2/loop/backing_file.

Anyway, the path is not important to detach the loop device.

Please, try:
```
LOOPDEV_DEBUG=all losetup -vd /dev/loop2
```
to get more details. Maybe also strace.

Note that "losetup" without "-a" provides a better output :-)

**Comment by HaleTom** [comment]
I had a kernel issue and got dropped to single user mode... And rebooted. 

Noted for next time though (which hopefully won't happen)

**Comment by qutorial** [comment]
Hello.

Unfortunately I have a similar problem:

```

root@test:~/devfiles# losetup -a  | sort
/dev/loop0: [64768]:43272 (/var/lib/snapd/snaps/core_4917.snap)
/dev/loop1: [64768]:2382 (/var/lib/snapd/snaps/core_6130.snap)
/dev/loop2: [64768]:133783 (/root/devfiles/sd1.img)     <=== Trying to detach this one
/dev/loop3: [64768]:133745 (/root/devfiles/sd2.img)
/dev/loop4: [64768]:133764 (/root/devfiles/sd3.img)

root@test:~/devfiles# LOOPDEV_DEBUG=all losetup -vd /dev/loop2
1237: loopdev:      CXT: [0x7ffec0c5c760]: initialize context
1237: loopdev:      CXT: [0x7ffec0c5c760]: init: ignore ioctls
1237: loopdev:      CXT: [0x7ffec0c5c760]: init: loop-control detected 
1237: loopdev:      CXT: [0x7ffec0c5c760]: /dev/loop2 name assigned
1237: loopdev:      CXT: [0x7ffec0c5c760]: open /dev/loop2 [ro]: Success
1237: loopdev:      CXT: [0x7ffec0c5c760]: device removed
1237: loopdev:      CXT: [0x7ffec0c5c760]: de-initialize
1237: loopdev:      CXT: [0x7ffec0c5c760]: closing old open fd
1237: loopdev:     ITER: [0x7ffec0c5c918]: de-initialize

root@test:~/devfiles# losetup --version
losetup from util-linux 2.31.1

root@test:~/devfiles# losetup -a
/dev/loop1: [64768]:2382 (/var/lib/snapd/snaps/core_6130.snap)
/dev/loop4: [64768]:133764 (/root/devfiles/sd3.img)
/dev/loop2: [64768]:133783 (/root/devfiles/sd1.img)   <===  No success :(
/dev/loop0: [64768]:43272 (/var/lib/snapd/snaps/core_4917.snap)
/dev/loop3: [64768]:133745 (/root/devfiles/sd2.img)
```

Linux version:
```
# uname -a
Linux test 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Question: where would it be smart to search for help?

Regards!

**Comment by anonymouse64** [comment]
I had a similar issue to @qutorial, but for me the issue was that I had a partition from the raw image mounted somewhere, and after removing that mount, I was able to detach the loop device successfully. Nothing from `losetup` or `kpartx` implied to me that this mount still existed, except that `losetup --list` showed:

```
 losetup --list | grep image
/dev/loop5          0 1260388352         1  0 /home/$USER/image.img (deleted)   0     512
```

and the `(deleted)` is what eventually led me to realize I still had the mount lying around.

**Comment by codefaux** [comment]
Had a kernel panic due to GPU fault, trying to gracefully bring down mounted drives. losetup refuses to detach.

`root@Tower:~# LOOPDEV_DEBUG=all losetup -vd /dev/loop2
9538: loopdev:      CXT: [0x7ffee6f6fa90]: initialize context
9538: loopdev:      CXT: [0x7ffee6f6fa90]: init: ignore ioctls
9538: loopdev:      CXT: [0x7ffee6f6fa90]: init: loop-control detected
9538: loopdev:      CXT: [0x7ffee6f6fa90]: /dev/loop2 name assigned
9538: loopdev:      CXT: [0x7ffee6f6fa90]: open /dev/loop2 [ro]: No such file or directory
9538: loopdev:      CXT: [0x7ffee6f6fa90]: device removed
9538: loopdev:      CXT: [0x7ffee6f6fa90]: de-initialize
9538: loopdev:      CXT: [0x7ffee6f6fa90]: closing old open fd
9538: loopdev:     ITER: [0x7ffee6f6fc20]: de-initialize
root@Tower:~# losetup -a
/dev/loop1: [2049]:4 (/boot/bzfirmware)
/dev/loop2: [2289]:17113098 (/mnt/disks/docker/btrfs-vdisk.img)
/dev/loop0: [2049]:3 (/boot/bzmodules)
`

Image file exists, is read/write, is valid/intrnally consistent, is on an accessible/working drive. The thread which died when the GPU faulted was a Docker container, and the Docker storage layer was on the btrfs loopback device, however the loopback device is not mounted anymore. Not something I'll be able to replicate, so this is probably worthless, lol

**Comment by kousu** [comment]
In case this is useful for someone else who googles this: a loop can also be held open by swap. For example:

```
$ losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                                DIO LOG-SEC
/dev/loop1         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test.img    0     512
/dev/loop2         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test.img    0     512
/dev/loop0         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test.img    0     512
/dev/loop3         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test2.img   0     512
$ sudo losetup -D
$ losetup   # no change
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                                DIO LOG-SEC
/dev/loop1         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test.img    0     512
/dev/loop2         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test.img    0     512
/dev/loop0         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test.img    0     512
/dev/loop3         0      0         1  0 /home/kousu/src/devices/arch-conf/arch-install/test2.img   0     512
```

But once I realized I had these:

```
$ swapon -s
Filename				Type		Size		Used		Priority
/dev/dm-2                               partition	2096124		0		-2
/dev/loop0p8                            partition	2097148		0		-3
/dev/loop1p8                            partition	2097148		0		-4
/dev/loop2p8                            partition	2097148		0		-5
/dev/loop3p8                            partition	2097148		0		-6
```

I did:

```
$ sudo swapoff /dev/loop0p8 
$ sudo swapoff /dev/loop1p8 
$ sudo swapoff /dev/loop2p8 
$ sudo swapoff /dev/loop3p8 
```

And then the loops detached automatically:

```
$ losetup
$
```

It doesn't count as an error for `losetup` to do nothing here -- it has done something, it's told the kernel to detach these loop devices; it's the kernel holding them open.

**Comment by wonderfly** [comment]
In a similar spirit to the previous comment, I'd like to share another possibility that could hold up a loopback device: `dmsetup`, which is used to setup encrypted disks.  In my case, after hours of unsuccessful `lsof`, `fuser` and `findmnt` tries, I ran `lsblk`, which showed me that a `dm` type mount existed on top of /dev/loop0.  That prompted me to do `dmsetup ls`, which revealed that I had an encrypted dm device on /dev/loop0, and that was it.  After running `dmsetup remove <the-dm-device>` I was then able to `losetup -D`.

**Comment by yurenchen000** [comment]
meet same issue many times, when use snap app.

```
 👉️ 💤 ~$ losetup  -l | grep loop7
/dev/loop7          0      0         1  1 /var/lib/snapd/snaps/core20_1822.snap (deleted)                     0     512
 👉️ 💤 ~$ ls -lh /dev/loop7
brw-rw---- 1 root disk 7, 7 2023-03-29 04:01 /dev/loop7
 👉️ 💤 ~$ sudo LOOPDEV_DEBUG=all losetup -vd /dev/loop7 
1331072: loopdev:      CXT: [0x7ffefc7ce290]: initialize context
1331072: loopdev:      CXT: [0x7ffefc7ce290]: init: ignore ioctls
1331072: loopdev:      CXT: [0x7ffefc7ce290]: init: loop-control detected 
1331072: loopdev:      CXT: [0x7ffefc7ce290]: /dev/loop7 name assigned
1331072: loopdev:      CXT: [0x7ffefc7ce290]: open /dev/loop7 [ro]: No such file or directory
1331072: loopdev:      CXT: [0x7ffefc7ce290]: device removed
1331072: loopdev:      CXT: [0x7ffefc7ce290]: de-initialize
1331072: loopdev:      CXT: [0x7ffefc7ce290]: closing old open fd
1331072: loopdev:     ITER: [0x7ffefc7ce468]: de-initialize
```

**Comment by karelzak** [comment]
man  losetup(1):
```
-d, --detach loopdev...
         Note that since Linux v3.7 kernel uses "lazy device destruction". The detach operation 
         does not return  EBUSY error anymore if device is actively used by system, but it is marked
         by autoclear  flag and destroyed later.
```

**Comment by phucly01** [comment]
Eight years after and it still a problem.  Not sure why the issue closed.
Doing losetup -d /dev/loop1 and nothing prints out and return code is 0
Doing LOOPDEV_DEBUG=all losetup -vd /dev/loop1 and nothing prints out and return code is also 0

**Comment by yurenchen000** [comment]
> Eight years after and it still a problem. Not sure why the issue closed. 

<br>

i guess it's kernel problems,
cause when it occur,  
 other tool also detach loop dev fail.  
 for example `umount -d`
