### ISSUE TITLE
libmount/src/context_mount.c:exec_helper() is POSIXly incorrect

### ISSUE THREAD

**Issue by jelmd** [karelzak/util-linux#441]
libmount/src/context_mount.c:exec_helper is not POSIX compatible (see [Utility Conventions | Utility Argument Syntax](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) ) and thus e.g. breaks "zfs create ...", because it re-orders arguments in a wrong way for exec_helper execution, i.e. puts the operands (source and target) at the start instead of the end of the argument list.

So if POSIXLY_CORRECT env var is set, one e.g. gets for:
```
# zfs create rpool/zones/bla
too many arguments
usage: mount <dataset> <mountpoint>
cannot mount 'rpool/zones/bla': Invalid argument
filesystem successfully created, but not mounted
```
because "zfs create ..." calls `/bin/mount -v -t zfs -o defaults,atime,dev,exec,rw,suid,nomand,zfsutil rpool/zones/bla /zones/bla` which in turn gets mangled to `/sbin/mount.zfs rpool/zones/bla /zones/bla -o rw,zfsutil`, but it **should be** `/sbin/mount.zfs -o rw,zfsutil rpool/zones/bla /zones/bla`!

**Comment by karelzak** [comment]
Well, the command line for external helpers is documented for years, see "man mount":
```
  The syntax of external mount helpers is:
         /sbin/mount.suffix spec dir [-sfnv] [-o options] [-t type.subtype]
```
it's mount.zfs responsibility to accept the options in this order to be compatible with mount.8. It's trivial to modify mount.zfs to be sure that functionality is not affected by POSIXLY_CORRECT env var.

 I have doubts we can change the default and introduce backwardly incompatible change...

Maybe we can check for POSIXLY_CORRECT in libmount and compose the argv[] in the POSIX proper way, but it's really necessary?

**Comment by jelmd** [comment]
Oh, what a pity (the mount helpers spec). Must be from a very ancient time. So yes, for now the ball jumps back to mount.zfs.

Agree, that changing the spec ad hoc possibly break things, however, one could deprecated it, and during transition time libmount could simply unsets/not pass POSIXLY_CORRECT.  BTW: Doesn't libmount filter env args anyway?

**Comment by karelzak** [comment]
We call sanitize_env() from mount/umount. The library does not reset environ[].
https://github.com/karelzak/util-linux/blob/master/lib/env.c#L54

**Comment by jelmd** [comment]
So adding this var to `forbid` could be an option ? ...

**Comment by karelzak** [comment]
Yes, but it will affect another tools (e.g. chfn, chsh) too. It would be better to add unsetenv("POSIXLY_CORRECT") to the code where libmount executes helpers.

**Comment by karelzak** [comment]
You can prepare a patch and send it to util-linux@vger.kernel.org (you don't have to subscribe to send to the mailing list).
