### ISSUE TITLE
/bin/su kills executed process with SIGKILL

### ISSUE THREAD

**Issue by mixalturek** [karelzak/util-linux#443]
We were facing a production issue with graceful shutdown of one node in our Apache Kafka cluster yesterday. The investigation clearly points to /bin/su that sends SIGTERM to the child process, waits 2 seconds and then forces termination by SIGKILL. This behavior effectively overwrites graceful shutdown configured in Kafka and explicitly defined 5 minutes timeout before sending SIGKILL in upstart configuration. We are using /bin/su to execute the service as a non-root user, to lower privileges.

```sh
/bin/su -s /bin/sh - kafka -c '/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties'
```

I'm creating this issue to suggest a change of the existing behavior. One doesn't expect /bin/su to forcefully SIGKILL its child process 2 seconds after it receives SIGTERM. We consider this "feature" as a bug, sending SIGKILL should be out of scope of /bin/su.

The relevant code is present in su-common.c and looks more like a try during development than something serious for long term.

```c
  if (caught_signal && child != (pid_t)-1)
    {
      fprintf (stderr, _("\nSession terminated, killing shell..."));
      kill (child, SIGTERM);
    }

  cleanup_pam (PAM_SUCCESS);

  if (caught_signal)
    {
      if (child != (pid_t)-1)
	{
	  sleep (2);
	  kill (child, SIGKILL);
	  fprintf (stderr, _(" ...killed.\n"));
	}
```

It was introduced long time ago in this commit, the reason is unknown.

```
commit 8171142ab66e94a409224547b33381259a0c3f72
Author: Ludwig Nussel <ludwig.nussel@suse.de>
Date:   Tue Aug 17 13:21:44 2010 +0200

    pam support for su
```

Known workaround is simply to not use /bin/su in such use case and choose an alternative tool like sudo, CentOS's runuser, Debian's start-stop-daemon and similar. Also note Debian doesn't use this implementation of /bin/su and has it's own which is probably safe (http://pkg-shadow.alioth.debian.org/).

**Comment by karelzak** [comment]
Well, I guess SIGKILL is used to be sure that child is really dead. I agree that sleep() is nothing elegant there, but not sure if want to ignore situation when SIGTERM is ignored by child.

**Comment by mixalturek** [comment]
Sure, I understand, there are two main possibilities and both are bad. I'm not sure which is worse, it heavily depends on use case.

- Current situation: If the sub-process doesn't terminate in 2 seconds after SIGTERM it will be forcefully killed with SIGKILL. It will be bad luck if the termination takes more 2 seconds.
- Proposed change: If the sub-process doesn't terminate on SIGTERM at all for any reason, it will remain running.

I think the proposed change is a little better because it behaves consistently in all cases.

- SIGTERM to su: Forward SIGTERM to sub-process and exit. Don't care about result because it's out of scope of su responsibility. Sub-process may remain running as orphan (init becomes parent).
- SIGKILL to su: Su is terminated immediately and has no chance to forward the signal. Sub-process always remains running as orphan (init becomes parent).

The best solution would be to not fork in su (the sub-process would be under shell or even the parent in the process tree), but this is very incompatible with current su behavior. There would be different process tree, one historically expects su is running and doesn't disappear.

The lesson learned is that one should never use for services impersonation su, sudo and any other tool that forks.

**Comment by karelzak** [comment]
The su(1) (and another similar tools) are not just uid/gid changers only. su(1) opens new *session* and we have to maintain and terminate the session. This is reason why we need fork() and babysitting.

For your use-case would be better tools like setpriv(1) (also util-linux) where is no PAM and another session management. (Note that runuser(1) from util-linux is like su(1), but it does not ask for password.)

**Comment by mixalturek** [comment]
We chose our home made tool, thanks for the support.

**Comment by edneville** [comment]
This looks like it can be closed now.
