### ISSUE TITLE
mount: fails for read-only ntfs devices

### ISSUE THREAD

**Issue by pothos** [karelzak/util-linux#460]
Here I forward a bug report coming from GNOME Disks/UDisks2 which I think should go to the mount utility, because it detects read-only devices for e.g. vfat and adds `ro`, but it does not add/forward it for ntfs-3g.

An example with a partition image mounted read-only loop device (e.g. `gnome-disk-image-mounter FILE`)
```
sudo mount -t vfat /dev/loop0 /mnt/test/
mount: /dev/loop0 is write-protected, mounting read-only
```
… no problem, works as expected. But it fails for ntfs because `ro` is not passed to ntfs-3g.

```
sudo mount -t ntfs /dev/loop0 /mnt/test/
ntfs-3g-mount: mount failed: Permission denied

```

**Comment by karelzak** [comment]
The logic behind "write-protected, mounting read-only" is a little bit different. 

mount(8)/libmount does not care about block device mode at all. It calls mount(2) syscall and if kernel  returns EROFS then it tries another attempt with MS_DRONLY flag. 

Unfortunately for ntfs we do not mount the filesystem by mount(8), but the request is redirected to /sbin/mount.ntfs. In this case we cannot do anything in mount(8), all has to be implemented by mount.<type> helper.

So, my suggestion is to improve ntfs-3g-mount to support this use-case.
