### ISSUE TITLE
script: ambiguous handling of the optional argument of -t

### ISSUE THREAD

**Issue by ao2** [karelzak/util-linux#463]
Hi,

the help text for the timing options of script(1) reads like this:
```
-t, --timing[=file]
```

meaning that the file name comes after an equal sign for both the short and long form of the option, however `getopt_long` handles the short and long formats differently wrt optional arguments, in the case of the short form the user is supposed to use something like `-t[file]`.

The ambiguity in the case of script(1) is that `-t=file` and `--timing=file` mean two different things, the former will consider the equal sign as part of the filename, the latter won't.

I see that other utils in util linux handle the equal sign in optional arguments: disk-utils/fdisk.c does it for the 'u' option, and it's done for the color options too in `colormode_or_err()`.

So should script handle this case as well, with a change like the following?

```diff
diff --git a/term-utils/script.c b/term-utils/script.c
index f2fc2f59c..ff0b36025 100644
--- a/term-utils/script.c
+++ b/term-utils/script.c
@@ -727,8 +727,11 @@ int main(int argc, char **argv)
                        ctl.quiet = 1;
                        break;
                case 't':
-                       if (optarg)
+                       if (optarg) {
+                               if (*optarg == '=')
+                                       optarg++;
                                ctl.tname = optarg;
+                       }
                        ctl.timing = 1;
                        break;
                case 'V':

```

with the change from above the degenerate case of an empty filename (`-t=`) gets treated in the same way as `--timing=` is currently handled.

The fix from above makes the help text accurate.

Similar issues possibly affect other commands using optional arguments, but I don't have the time to take a look.

**Comment by rudimeier** [comment]
Hm, I don't think the patch would be a good idea.

I read the documentation ```-t, --timing[=file]``` like this:

    --timing[=file]  ... has an optional argument
    - t              ... does not have an argument

so as documented ```script -t=bla ...``` should give and error ``script: invalid option '='. Of course we can't change the current behavior.

Compare `coreutils`

      tail   -f, --follow[={name|descriptor}]

and

    date  -I[TIMESPEC], --iso-8601[=TIMESPEC]

So IMO we should simply change the `script` documentation to what we have now:

    -t[file], --timing[=file]

In general we should avoid ambiguities like in the future for new options by using only long-options for optional arguments. In other words _either_ `-t` should not exist _or_ `--timing` should not take an argument . AFAIR we have agreed on the mailing list about this way.

**Comment by ao2** [comment]
> Hm, I don't think the patch would be a good idea.
> 
> I read the documentation -t, --timing[=file] like this:
> 
> --timing[=file]  ... has an optional argument
> -t               ... does not have an argument
> 

This is a valid interpretation too.

My interpretation derived from how the options with mandatory arguments are formatted, e.g.:

```
 -c, --command <command> run command rather than interactive shell
```

When reading that I assume `-c` also accepts an argument, so I thought `-t` is also supposed to accept an argument.

That space after the comma always bugged me but that's how man pages are formatted historically.

OTOH your interpretation could be supported by the fact that there are no spaces in `--timing[=file]` and so the argument refers only to the long option.

> so as documented script -t=bla ... should give an error script: invalid option '='. Of course we can't change the current behavior.
> 
> Compare coreutils
> 
>   tail   -f, --follow[={name|descriptor}]
> 
> and
> 
> date  -I[TIMESPEC], --iso-8601[=TIMESPEC]
> 
> So IMO we should simply change the script documentation to what we have now:
> 
> -t[file], --timing[=file]
>

This is perfectly fine by me.

If you prefer this solution I can send a pull request.

Thanks,
   Antonio

**Comment by karelzak** [comment]
Hmm, we use the same way to document optional arguments on many places... and on some places (e.g. fdisk) we really have 

                        if (optarg && *optarg == '=')
                                optarg++;

and for backward compatibility we have to support it (for example for fdisk).

**Comment by ao2** [comment]
Yeah, I mentioned fdisk in the original post.

Anyhow the two solutions are equivalent to me: either strip the `=` when using the short form or document that it's not supposed to be there. I sent a pull request that implements the latter because that's what @rudimeier requested.

**Comment by ao2** [comment]
ping

**Comment by karelzak** [comment]
Fixed by Antonio's patch. Thanks.

[The script usage() need our love due to fputs, all in one block, etc. but it's another story ;-) ]
