### ISSUE TITLE
man mount: made up wrong syntax for passing mount options along with `--bind`

### ISSUE THREAD

**Issue by sourcejedi** [karelzak/util-linux#464]
> since v2.27 allows to change the mount options by passing the
> relevant options along with
> .BR \-\-bind .
> For example:
> 
> .RS
> .br
> .B mount \-\-bind,ro foo foo

This is not true.  I have `util-linux-2.28.2-2.fc25.x86_64`.  But, using `mount --bind,ro` says `unrecognized option: '--bind,ro'`.

Instead, simply pass options using -o as normal.  This worked fine e.g. https://unix.stackexchange.com/a/371923/29483

**Comment by karelzak** [comment]
Typo, "-o bind,ro" is the correct syntax of course. Fixed. 

Thanks!
