### ISSUE TITLE
man mount: it seems you document "commit" option for ext4 wrong

### ISSUE THREAD

**Issue by safinaskar** [karelzak/util-linux#479]
Hi. Currently "commit" for ext3 documented so:
```roff
.BI commit= nrsec
Sync all data and metadata every
.I nrsec
seconds.  The default value is 5 seconds.  Zero means default.
```
And in the beginning of ext4:
```
The options
.B journal_dev, norecovery, noload, data, commit, orlov, oldalloc, [no]user_xattr
.B [no]acl, bsddf, minixdf, debug, errors, data_err, grpid, bsdgroups, nogrpid
.B sysvgroups, resgid, resuid, sb, quota, noquota, grpquota, usrquota
.B usrjquota, grpjquota and jqfmt
are backwardly compatible with ext3 or ext2.
```

So, it seems from man that ext4 has same "commit" option and its default value is 5 seconds (even if I don't specify "commit" at command line at all). But it seems that this is wrong ( https://lwn.net/Articles/322823/ ). So, please, fix the man

**Comment by safinaskar** [comment]
It seems https://www.kernel.org/doc/Documentation/filesystems/ext4.txt has the same issue?!

**Comment by karelzak** [comment]
We use kernel docs as the source :-) I'll ask extN developers for the help. Thanks.

**Comment by karelzak** [comment]
Note, I have removed extN from mount.8. The extN mount options will not be maintained by util-linux any more. You have to use "man ext4" (from e2fsprogs).
