### ISSUE TITLE
[agetty] --skip-login also skips issue

### ISSUE THREAD

**Issue by dasJ** [karelzak/util-linux#480]
When providing `--skip-login` (so the user isn't asked for a username), `/etc/issue` isn't printed anymore.

Full command line from systemd:
```
/usr/bin/agetty --noclear -n -l /usr/bin/alogin %I $TERM
```

**Comment by karelzak** [comment]
Fixed, will be in v2.31. Thanks!

**Comment by dasJ** [comment]
Thank you for the quick fix!
