### ISSUE TITLE
fdisk does not produce Protective MBR for GPT correctly

### ISSUE THREAD

**Issue by pali** [karelzak/util-linux#485]
Reproduce:
```
$ truncate -s 10G /tmp/gpt

$ printf "g\nw\n" | ./fdisk /tmp/gpt

Welcome to fdisk (util-linux 2.30.196-00b33-dirty).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x29ebb066.

Command (m for help): Created a new GPT disklabel (GUID: 466208E1-DFA3-FB41-8D8C-8CFC2B3618F8).

Command (m for help): The partition table has been altered.
Syncing disks.

$ ./fdisk -t dos -l -o Device,Boot,Start,End,Sectors,Size,Id,Type,Start-C/H/S,End-C/H/S,Cylinders,Attrs /tmp/gpt
Disk /tmp/gpt: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device      Boot Start      End  Sectors Size Id Type Start-C/H/S   End-C/H/S Cylinders Attrs
/tmp/gpt1            1 20971519 20971519  10G ee GPT        0/0/1 1023/254/63      1306
```

According to _UEFI Specification 2.6_, section _5 GUID Partition Table (GPT) Disk Layout_, subsection _5.2.3 Protective MBR_, Table 17. _Protective MBR Partition Record protecting the entire disk_, **StartingCHS** is 0x000200 (**0/0/2**) and **EndingCHS** is 0xFFFFFF (**1023/255/63**) if it is not possible to represent last logical block as C-H-S.

Here is output when GPT disk was initialized by gdisk:
```
$ truncate -s 10G /tmp/gpt2

$ printf "o\ny\nw\ny" | gdisk /tmp/gpt2
GPT fdisk (gdisk) version 0.8.1

Partition table scan:
  MBR: not present
  BSD: not present
  APM: not present
  GPT: not present

Creating new GPT entries.

Command (? for help): This option deletes all partitions and creates a new protective MBR.
Proceed? (Y/N): 
Command (? for help): 
Final checks complete. About to write GPT data. THIS WILL OVERWRITE EXISTING
PARTITIONS!!

Do you want to proceed? (Y/N): OK; writing new GUID partition table (GPT).
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot.
The operation has completed successfully.

$ ./fdisk -t dos -l -o Device,Boot,Start,End,Sectors,Size,Id,Type,Start-C/H/S,End-C/H/S,Cylinders,Attrs /tmp/gpt2
Disk /tmp/gpt2: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device      Boot Start      End  Sectors Size Id Type Start-C/H/S   End-C/H/S Cylinders Attrs
/tmp/gpt2p1          1 20971519 20971519  10G ee GPT        0/0/2 1023/255/63      1301
```

Protective MBR is there correct.

Please make fdisk compliant to UEFI/GPT specification.

**Comment by karelzak** [comment]
Nice catch! Fixed.

```
printf "g\nw\n" | ./fdisk img2

Welcome to fdisk (util-linux 2.30.235-c0eab-dirty).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Created a new GPT disklabel (GUID: 013F09DF-3E52-574F-901A-36E8395C5FBD).

Command (m for help): The partition table has been altered.
Syncing disks.

$ ./fdisk -t dos -l -o Device,Boot,Start,End,Sectors,Size,Id,Type,Start-C/H/S,End-C/H/S,Cylinders,Attrs img1
Disk img1: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start      End  Sectors Size Id Type Start-C/H/S   End-C/H/S Cylinders Attrs
img1p1              1 20971519 20971519  10G ee GPT        0/0/2 1023/255/63      1301      
```

**Comment by pali** [comment]
Commit https://github.com/karelzak/util-linux/commit/8ffa3b651d7e74acba8f1d831b7f68fdb3c66aae is not so correct as ** EndingCHS** needs to be calculated from C-H-S disk geometry and value 0xFFFFFF (**1023/255/63**) is used only if it is not possible to represent last logical block as C-H-S.

**Comment by karelzak** [comment]
Well, the same solution uses GNU Parted.. not sure if we have to care about this so much as nothing uses CHS.

**Comment by pali** [comment]
C-H-S is probably not used anymore... but UEFI/GPT specification clearly say what should be filled into structures. And tool which aim to support GPT should follow specification and do not invent its own rules. And at least gdisk has it implemented, so in case of problems, code can be reused.

**Comment by marcosfrm** [comment]
Microsoft appears to not follow it too...

http://thestarman.pcministry.com/asm/mbr/GPT.htm#GPTPT

**Comment by pali** [comment]
We know that Microsoft notoriously does not follow industrial standards or implement them differently (E, E, E strategy). So it is not a surprise that Microsoft implements also GPT in non-compliant way. But it does not mean that other developers should do same thing.

**Comment by karelzak** [comment]
The problem is that for CHS you need device geometry and it's not always available (e.g. some logical volumes, non block device partitioning, etc.) and it's poorly portable between devices (dd(1) PT from one disk to another). The reason why we want to use GPT is to avoid dos-like junk :-)

So from my point of view GNU Parted and MS solution makes sense and it improves things. IMHO it would be better to update the standard than force applications to care about absolutely obsolete CHS in year 2017.

**Comment by pali** [comment]
> The problem is that for CHS you need device geometry and it's not always available (e.g. some logical volumes, non block device partitioning, etc.)

Yes, and in most cases C-H-S does not make sense for hdds and BIOS uses some values... Looking at wikipedia there is interesting transition [table](https://en.wikipedia.org/wiki/Logical_block_addressing#LBA-assisted_translation) between LBA and C-H-S numbers. No idea what is the source of data...

> and it's poorly portable between devices (dd(1) PT from one disk to another).

GPT itself is not portable between devices (via dd) as it stores layout at beginning and also at the end of disk. Also GPT is addressed by logical sector size and now when usage of native 4K disks is increasing, more problems just come. Two identical disks should not have GPT problem, but probably would have also same C-H-S compatibility.

> IMHO it would be better to update the standard than force applications to care about absolutely obsolete CHS in year 2017.

I fully agree with you. Problem is that standard is not updated yet and so compliant applications still need to care...
