### ISSUE TITLE
column breaks ansi colours  

### ISSUE THREAD

**Issue by hcbraun** [karelzak/util-linux#490]
With column from util-linux 2.29.2 i could do:
echo '\033[34mBLUE{1\n\033[31mRED{2\n' | column -s '{' -t
which does display the coloured lines:
BLUE  1
RED   2

With column from util-linux 2.30.1 the same command does display without colour:
\x1b[34mBLUE  1
\x1b[31mRED   2

**Comment by karelzak** [comment]
Fixed, the change will be in v2.31.

**Comment by Julian** [comment]
Any chance there's a release coming soon?

**Comment by karelzak** [comment]
end of September (26th or so)
