### ISSUE TITLE
agetty: Issue file displays again after the enter key is pressed when using --login-pause

### ISSUE THREAD

**Issue by zeroxfourc** [karelzak/util-linux#491]
agetty displays the issue file twice when the --login-pause argument is used.
The behaviour I expected:
> Welcome to host!
> [press ENTER to login]
> 
> host login: user
> Password:
> *user is logged in*

The actual behaviour:
> Welcome to host!
> [press ENTER to login]
> 
> host login:
> Welcome to host!
> [press ENTER to login]
> user
> host login: Password:
> *user is logged in*

**Comment by karelzak** [comment]
Fixed. This feature has been probably tested with autologin only. 

Thanks!
