### ISSUE TITLE
support for rfc-4122 uuids (especially OID based uuids) would be useful

### ISSUE THREAD

**Issue by pprindeville** [karelzak/util-linux#495]
For provisioning IPv6 static reservations for DHCP, rfc-4122 version 3 (MD5) and version 5 (SHA1) named-based UUIDs (based on the MAC address of the first fixed network adapter) would be extremely handy.

**Comment by karelzak** [comment]
Nice examples: https://stackoverflow.com/questions/10867405/generating-v5-uuid-what-is-name-and-namespace

**Comment by pprindeville** [comment]
Thanks.  What's the chance of adding functions to generate v3 or v5 UUIDs directly into the API?  Are you accepting PR's for that?

**Comment by pprindeville** [comment]
Started PR #501.  Closing.
