### ISSUE TITLE
cfdisk - partition size backspace issue

### ISSUE THREAD

**Issue by dglava** [karelzak/util-linux#499]
Pressing backspace when trying to enter a partition size garbles the input line. It prints ^? and doesn't delete any characters. Here's a video demonstrating how it looks:

util-linux version 2.30.1
http://webm.land/media/T14S.webm

Using version 2.29.2 doesn't give me this problem.

I tried xfce4-terminal and lxterminal and they both had that issue. However, xterm worked fine. I am not sure if util-linux is solely responsible for this, but since an older version worked fine I thought I'd report it and get more info.

**Comment by karelzak** [comment]
We use a new code for input fields, so it could be cfdisk issue, but I'm not able to reproduce the problem. I've tried xfce4-terminal and lxterminal (on Fedora 25) ... all works as expected. 

Please, try:
```
#  CFDISK_DEBUG=all cfdisk /dev/something 2> log
```
and send me the log file. Thanks.

**Comment by dglava** [comment]
I am experiencing this issue on Arch Linux. xfce4-terminal version 0.8.6

Here's the output: https://file.io/ZaMrhN
Using the "delete" key works, but backspace is causing the above described issues.

**Comment by karelzak** [comment]
It seems like DEL key 0x7F rather than backspace. I'll add this key to the code, the question is how (del or backspace).

**Comment by karelzak** [comment]
Fixed. Please test it:

git pull
./configure
make cfdisk

**Comment by dglava** [comment]
I just tested it and it works.
Using "Backspace" key to delete is deleting characters normally.

Thanks for fixing this.
