### ISSUE TITLE
Bad version format in .pc files, if no version release

### ISSUE THREAD

**Issue by rezso** [karelzak/util-linux#504]
I tried to compile systemd with meson, but failed with this error:

Meson encountered an error in file meson.build, line 635, column 0:
Invalid version to compare against: '2.28.'; only numeric digits separated by "." are allowed: invalid literal for int() with base 10: ''

This line is:

libmount = dependency('mount', version : '>= 2.27')

And really, the mount.pc (and all other pc file) contains **2.28.** as version, instead of 2.28
I think the problem is comes from configure.ac.

**Comment by rudimeier** [comment]
This was already reported in #487, should be fixed in 2.29.

If your distribution is using 2.28 you could send a bug report there to motivate them to patch their package.
