### ISSUE TITLE
fdisk: wrong behaviour for SUN partition table

### ISSUE THREAD

**Issue by NordMike** [karelzak/util-linux#505]
After you create the first partition starting from 0 sector, all subsequent partitions are created right after it, not after previous one. Also the third partition should be whole disk for SUN partition table but fdisk doesn't allow to create it so if there are partition at 0 sector already.

This happens on both x86_64 and sparc64 machines. Tested on 2.28.2 and 2.30 version. The same behaviour.

Steps to Reproduce:
1. Run fdisk /dev/sdx.
2. Create new SUN partition table with command s.
3. Delete 3 default partitions with d.
4. Create the first partition from default to +10G with n.
5. Create the second partition from default to +8G.
6. Create the third partition from default to default.
7. Create the fourth partition from default to +30G.

Actual Results:  
```
Device        Start       End   Sectors   Size Id Type         Flags
/dev/sdc1         0  20971519  20971520    10G 83 Linux native
/dev/sdc2  20980890  37758105  16777216     8G 83 Linux native
/dev/sdc3  20980890 976768064 955787175 455.8G 83 Linux native
/dev/sdc4  20980890  83895449  62914560    30G 83 Linux native
```

Expected Results:  
```
Device        Start       End   Sectors   Size Id Type         Flags
/dev/sdc1         0  20971519  20971520    10G 83 Linux native
/dev/sdc2  20980890  37758105  16777216     8G 83 Linux native
/dev/sdc3         0 976768064 976773168 465.8G 83 Whole disk
/dev/sdc4  37758110 100672670  62914560    30G 83 Linux native
```

**Comment by karelzak** [comment]
Fixed by commit https://github.com/karelzak/util-linux/commit/27895be26074780aac5a849514b2a6f8560adfcd

Thanks!
