### ISSUE TITLE
The program does not compile into the static version

### ISSUE THREAD

**Issue by morteryler** [karelzak/util-linux#507]
I compile for the platform arm.
My script:

`#!/bin/bash

export CFLAGS=-static
export CPPFLAGS=-static
export LDFLAGS=-static

./configure --enable-static-programs=fdisk --disable-shared\
 --without-tinfo --without-ncurses --host=arm-linux-gnueabihf

make fdisk`

But the binary is not static:

`
fdisk: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=a482fd04bbeebfeab94587dfa1bfe33508d9347c, with debug_info, not stripped
`

What should I do?

**Comment by karelzak** [comment]
$ ./configure --enable-static-programs=fdisk
$ make fdisk.static
$ ldd fdisk.static 
not a dynamic executable

Note that you need static libs or disable the libs (since v2.27 also readline library).
