### ISSUE TITLE
blockdev setro to disable cd dvd writing?

### ISSUE THREAD

**Issue by krajorama** [karelzak/util-linux#509]
Hi,

we're trying to use "blockdev --setro /dev/sr0" to disable cd/dvd writing on Linux 2.6.32. We've added it to udev rules.
It seemed to work last Friday, but now that we tried to demo the solution, it does not. 
Is it supposed to disable CD/DVD writing?

setro does disable USB stick writing, so that's ok at least.

regards, krajo

**Comment by karelzak** [comment]
Frankly, I don't know - I didn't tried. 

Generally speaking, it affects non-yet used file descriptors. For example already mounted FS will not affected by "setro", and maybe another similar things.

**Comment by krajorama** [comment]
Thanks. I'm guessing that it doesn't work, because writing is done via ioctl and not write(2)? Not sure.
