### ISSUE TITLE
ipcrm translation error fr.po arg "-S" is not "-s"

### ISSUE THREAD

**Issue by cyril-corbon** [karelzak/util-linux#512]
Hi,

I just found a typo in ipcrm --help on LANG=fr (file po/fr.po)

`#: sys-utils/ipcrm.c:63
msgid " -S, --semaphore-key <key>  remove semaphore by key\n"
msgstr " -s, --semaphore-key <clef> retirer le sémaphore par clef\n"
`
The translation should use : 
`#: sys-utils/ipcrm.c:63
msgid " -S, --semaphore-key <key>  remove semaphore by key\n"
msgstr " -S, --semaphore-key <clef> retirer le sémaphore par clef\n"
`
Regards,

**Comment by karelzak** [comment]
Thanks!
