### ISSUE TITLE
setsid(1) only calls fork() if it is a process group leader

### ISSUE THREAD

**Issue by abacabadabacaba** [karelzak/util-linux#518]
Currently, `setsid(1)` only calls `fork(2)` if it is a process group leader. Otherwise, it executes a program in the current process.

This behavior is undocumented and highly nonintuitive. As a result, when `setsid` is called from an interactive shell, it returns immediately, but when called from a shell script, it seems to wait for the program to finish. This often leads to [confusion](https://stackoverflow.com/q/9677306).

I propose adding a command line switch to `setsid(1)` to make it always fork, regardless if whether or not it is a process group leader. Or better, make this the default behavior. The current behavior looks like a bad optimization, one which leads to a wrong and seemingly strange behavior.

**Comment by karelzak** [comment]
I don't think we want to change default behaviour of the command, but I don't see a problem with a new --fork command line option (added to TODO).

The man page has been improved.

**Comment by karelzak** [comment]
Implemented.
