### ISSUE TITLE
mount cifs + kernel 4.13.x results in incorrect ownership of mount

### ISSUE THREAD

**Issue by guzzard** [karelzak/util-linux#525]
Mounting cifs with kernel 4.13.x results in root having ownership of the mount leaving the user without write access. Identical mount command with kernel 4.12.x and older results in correct ownership of the mount, for example using uid/gid or mounting in a /home/username/folder. I can get write access by setting uid=username,gid=username in the options, but that was not needed before.

See full bug report [here](https://bugs.archlinux.org/task/55883).

Something must have changed in kernel 4.13.x breaking the mounting of cifs?

**Comment by karelzak** [comment]
Please, report it to the kernel community (kernel list or fs-devel@vger.kernl.org list).
