### ISSUE TITLE
sfdisk does not create an empty partition table in interactive mode

### ISSUE THREAD

**Issue by stikonas** [karelzak/util-linux#528]
I want to use sfdisk in KDE Partition Manager.

So basically I run sfdisk /dev/sdb and then write:

label: gpt (or msdos)
write

However a new partition table is not created. My util-linux version is 2.31

**Comment by karelzak** [comment]
Bug. 

You can use CTRL+D rather than "write" as workaround. I'll fix it ASAP.

**Comment by karelzak** [comment]
Fixed. Thanks for you report!

**Comment by stikonas** [comment]
I don't think I can use Ctrl+D. I can only send some bytes as input.

But it's fine. I'll just wait until new version is released and depend on that one.

**Comment by karelzak** [comment]
Ctrl+D (EOF) is the standard way (for year) how to force sfdisk to stop read and start write.

**Comment by stikonas** [comment]
Thanks again! I think I found a way how to send EOF (https://doc.qt.io/qt-5/qprocess.html#closeWriteChannel).
