### ISSUE TITLE
blockdev.8: BLKSSZ is called wrongly

### ISSUE THREAD

**Issue by sourcejedi** [karelzak/util-linux#535]
I suggest matching the following kernel comments instead.  This would make BLKSSZ "logical block size".

```
case BLKBSZGET: /* get block device soft block size (cf. BLKSSZGET) */
    return put_int(arg, block_size(bdev));
case BLKSSZGET: /* get block device logical block size */
    return put_int(arg, bdev_logical_block_size(bdev));
case BLKPBSZGET: /* get block device physical block size */
    return put_uint(arg, bdev_physical_block_size(bdev));
```

I wrote a longer explanation, but github and my browser conspired to eat it.  My reason for reporting this is here: https://unix.stackexchange.com/questions/403919/harddrive-with-4096-physical-sector-size-reported-as-512-behind-usb-bridge

**Comment by karelzak** [comment]
Well, I thing add "logical" is good enough.
