### ISSUE TITLE
Bash completion for umount fails if mount point contains a space

### ISSUE THREAD

**Issue by ttencate** [karelzak/util-linux#539]
Arch Linux, util-linux version 2.30.2.

For example, the mount point `/media/LUBUNTU 17_`:

    $ cat /proc/mounts | grep media
    /dev/sdb1 /media/LUBUNTU\04017_ vfat rw,nosuid,nodev,noexec,noatime,uid=1000,gid=1000,fmask=0133,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0

I type `umount /media/LU<tab>` and it gets completed to `umount /media/LUBUNTU`.

Maybe [umount](https://github.com/karelzak/util-linux/blob/master/bash-completion/umount) should take a page from the book of [bash-completions](https://github.com/scop/bash-completion/blob/master/completions/umount.linux) and parse `/proc/mounts`, instead of `mount` output.

(I originally thought this was a [bug](https://github.com/scop/bash-completion/issues/159) in `bash-completions`, until I realized that my distro replaces its `umount` completion in favour of that from `util-linux`.)

**Comment by karelzak** [comment]
I like the idea with findmnt. It's better than "mount | awk"...

The problem should be fixed now. Thanks!

**Comment by ttencate** [comment]
Sweet, saved me a PR, thank you!
