### ISSUE TITLE
hwclock on Raspberry Pi 2 with DS1307 RTC: operates correctly in util-linux 2.30.1, fails in 2.31

### ISSUE THREAD

**Issue by es30** [karelzak/util-linux#543]
On a Raspberry Pi 2 with DS1307 RTC running Arch Linux ARM with util-linux 2.30.1:

```
# hwclock -D
hwclock from util-linux 2.30.1
Trying to open: /dev/rtc0
Using the rtc interface to the clock.
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
/dev/rtc0 does not have interrupt functions. Waiting in loop for time from /dev/rtc0 to change
...got clock tick
Time read from Hardware Clock: 2017/11/21 20:27:03
Hw clock time : 2017/11/21 20:27:03 = 1511296023 seconds since 1969
Time since last adjustment is 1511296023 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2017-11-21 12:27:02.930019-0800
#
```

But with util-linux 2.31:

```
# hwclock -D
hwclock from util-linux 2.31
System Time: 1511286992.869143
Trying to open: /dev/rtc0
Using the rtc interface to the clock.
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
hwclock: ioctl(3, RTC_UIE_ON, 0) to /dev/rtc0 failed: Invalid argument
...synchronization failed
#
```

Reverting the function synchronize_to_clock_tick_rtc in hwclock-rtc.c to its definition in branch stable/v2.30 restores some semblance of correct operation (which is not to say that this is the fix to the problem):

```
# ./hwclock -D
hwclock from util-linux 2.31
System Time: 1511287003.907954
Trying to open: /dev/rtc0
Using the rtc interface to the clock.
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
/dev/rtc0 does not have interrupt functions. ioctl(3, RTC_UIE_ON, 0): Invalid argument
Waiting in loop for time from /dev/rtc0 to change
...got clock tick
Time read from Hardware Clock: 2017/11/21 17:56:45
Hw clock time : 2017/11/21 17:56:45 = 1511287005 seconds since 1969
Time since last adjustment is 1511287005 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2017-11-21 09:56:44.370380-0800
#
```

For other users experiencing the same problem, see thread [https://archlinuxarm.org/forum/viewtopic.php?f=57&t=12222](https://archlinuxarm.org/forum/viewtopic.php?f=57&t=12222).

**Comment by karelzak** [comment]
I guess we need 
```
- } else if (errno == ENOTTY) {
+ } else if (errno == ENOTTY || errno == EINVAL) {
```
@jwpi ?

**Comment by es30** [comment]
I can't speak to the general case, but the proposed fix works in my particular case:
```
# ./hwclock -D
hwclock from util-linux 2.31
System Time: 1511366637.637657
Trying to open: /dev/rtc0
Using the rtc interface to the clock.
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
ioctl(3, RTC_UIE_ON, 0): Invalid argument
Waiting in loop for time from /dev/rtc0 to change
...got clock tick
Time read from Hardware Clock: 2017/11/22 16:03:59
Hw clock time : 2017/11/22 16:03:59 = 1511366639 seconds since 1969
Time since last adjustment is 1511366639 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2017-11-22 08:03:58.097366-08:00
#
```

**Comment by jwpi** [comment]
On 11/22/2017 04:23 AM, Karel Zak wrote:
> @jwpi ?
> 

As the commit says, util-linux requires kernel >= 2.6.0 and the rtc
interface has not returned EINVAL for unimplemented ioctls since v2.5.8.

So it's your call Karel, does util-linux have a minimum kernel version?
See both commits below:

commit 1d5cffa16a0183175684809cf215294ec20b8fd9
Author: J William Piggott <elseifthen@gmx.com>
Date:   Sun Jul 23 20:16:03 2017 -0400

    hwclock: fix unimplemented ioctl test
    
    The rtc driver has not returned EINVAL for unimplemented ioctls since
    v2.5.8 in 2002. However, it does return it for other errors; making the
    current test potentially problematic. Since 9f3d0fc util-linux assumes
    kernel >= 2.6.0 so remove EINVAL as an ioctl test.


commit 9f3d0fce66279ea5f2b8ea694d3bf6a46682c8cd
Author: Ruediger Meier <ruediger.meier@ga-group.nl>
Date:   Thu Jun 29 04:09:06 2017 +0200

    docs: remove some old history from manpages
    
    We assume that users will have a kernel >= 2.6.0 and removel
    references to earlier kernels. There are still a few ones
    left.
    
    Signed-off-by: Ruediger Meier <ruediger.meier@ga-group.nl>

**Comment by es30** [comment]
Hmm, interesting. I would think that my kernel is sufficiently current:
```
$ uname -a
Linux Corvus 4.9.60-1-ARCH #1 SMP Mon Nov 6 10:03:15 PST 2017 armv7l GNU/Linux
```
Could the fact that I'm compiling the rtc-ds1307 driver into my kernel be making a difference?
```
$ diff config config.original
2667c2667
< CONFIG_I2C_BCM2835=y
---
> CONFIG_I2C_BCM2835=m
4606,4607c4606
< CONFIG_RTC_HCTOSYS=y
< CONFIG_RTC_HCTOSYS_DEVICE="rtc0"
---
> # CONFIG_RTC_HCTOSYS is not set
4626c4625
< CONFIG_RTC_DRV_DS1307=y
---
> CONFIG_RTC_DRV_DS1307=m
```
I'll try running hwclock against the stock kernel with loadable RTC driver, but it will take me a bit of time.

**Comment by jwpi** [comment]
On 11/22/2017 02:45 PM, Ed Snow wrote:
> Hmm, interesting. I would think that my kernel is sufficiently current:
> ```
> $ uname -a
> Linux Corvus 4.9.60-1-ARCH #1 SMP Mon Nov 6 10:03:15 PST 2017 armv7l GNU/Linux

I was wrong. The RTC returns ENOTTY when an ioctl is unrecognized, but
it looks like RTC_UIE_ON, which is  rtc_update_irq_enable(), does return
EINVAL when it is unsupported.

 drivers/rtc/interface.c:458
	if (rtc->uie_unsupported) {
		err = -EINVAL;
		goto out;
	}

So commit 1d5cffa16a0183175684809cf215294ec20b8fd9 should be reverted.
My apologies to all for the regression.

**Comment by karelzak** [comment]
The change will in v2.31.1 (probably end of Nov).

**Comment by jwpi** [comment]
On 11/23/2017 04:36 AM, Karel Zak wrote:
> The change will in v2.31.1 (probably end of Nov).
> 

Just a friendly reminder Karel, for the bug fix release?

**Comment by karelzak** [comment]
Ah, ... already December. OK, I'l fix it ASAP.
