### ISSUE TITLE
libuuid.a exports conflicting SHA1 symbol

### ISSUE THREAD

**Issue by Kagami** [karelzak/util-linux#548]
Steps to reproduce:

```
# get latest sources
./autogen.sh
./configure --enable-static
make && make install
nm /usr/lib/libuuid.a
```

```
libuuid_la-sha1.o:
                 U _GLOBAL_OFFSET_TABLE_
                 U memcpy
00000000000014a0 T SHA1
0000000000001380 T SHA1Final
00000000000011c0 T SHA1Init
0000000000000000 T SHA1Transform
0000000000001200 T SHA1Update
                 U __stack_chk_fail
```

As you can see, `libuuid.a` static library exports `SHA1` symbol which conflicts with e.g. openssl's `libcrypto.a` because it exports exactly same symbol. Is it possible to hide it? OpenSSL symbols are documented here: https://wiki.openssl.org/index.php/Manual:Sha(3)

Other symbols (`SHA1Final`, `MD5Final`, etc) seems to be different, because OpenSSL uses underscore, though very similar.

Thanks.

**Comment by karelzak** [comment]
Thanks. Fixed.
