### ISSUE TITLE
[Question] Alternatives to chkdupexe

### ISSUE THREAD

**Issue by aserrallerios** [karelzak/util-linux#550]
Does util-linux include any alternative to `chkdupexe`? If not, can anyone think of a good replacement?

Thanks.

**Comment by jwpi** [comment]
On 12/11/2017 02:57 AM, Albert Serrallé Ríos wrote:
> Does util-linux include any alternative to `chkdupexe`? If not, can anyone think of a good replacement?
> 
> Thanks.
> 

I'm not familiar with chkdupexe, but based on the what the old man page
say, is sounds like the closest posix command would be 'type':

type -a echo
echo is a shell builtin
echo is /usr/bin/echo
echo is /bin/echo

type -a ls
ls is aliased to `/bin/ls $LS_OPTIONS'
ls is /usr/bin/ls
ls is /bin/ls

Although it does not pickup dead links.

**Comment by aserrallerios** [comment]
That's exactly what I was looking for. Thank you!

**Comment by aserrallerios** [comment]
It also describes declared bash functions! Neat.
