### ISSUE TITLE
RFE: more partition type shortcuts in sfdisk

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#560]
_Linux RAID_ and _Linux LVM_ are pretty common on servers. What do you think about adding shortcuts for them?

Like:

**R** for Linux RAID (A19D880F-05FC-4D3B-A006-743F0F84911E, 0xfd)

**V** for Linux LVM (E6D6D379-F507-44C2-A23C-238F2A3DF928, 0x8e)

**Comment by karelzak** [comment]
Good idea, thanks.

**Comment by marcosfrm** [comment]
Nitpick: in both https://github.com/karelzak/util-linux/blob/master/disk-utils/sfdisk.8#L362 and https://github.com/karelzak/util-linux/blob/master/libfdisk/src/script.c#L1016 "fd" and "8e" are lower case, while "EF" is uppercase.

**Comment by marcosfrm** [comment]
@karelzak Ping. I know it is a cosmetic issue, but... thanks again.

**Comment by karelzak** [comment]
Fixed. it's nowhere visible :-)

**Comment by marcosfrm** [comment]
Man page too?
https://github.com/karelzak/util-linux/blob/master/disk-utils/sfdisk.8#L365

**Comment by karelzak** [comment]
OK, ok.... Fixed. thanks!
