### ISSUE TITLE
RFE: sfdisk: add option to lock device being partitioned

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#563]
udev 213+ has an API to suppress its event handling while an exclusive lock is held in the (parent) device.

https://bugzilla.gnome.org/show_bug.cgi?id=701676#c53
https://github.com/systemd/systemd/blob/master/src/udev/udevd.c#L421

Take this test script:

```
#!/bin/bash

export LANG=C

count=0
while (( $count < 500 )) ; do
    (( $RANDOM % 2 )) && pt=dos || pt=gpt
    cmdout=$(sfdisk --wipe=always --wipe-partitions=always --label=$pt /dev/sdx <<< ',,L' 2>&1)
    (( count++ ))
    grep -q 'Re-reading the partition table failed' <<< "$cmdout" && break
done

echo "Passes: $count"
```

It barely exceeds 10 passes on my hardware.

Now add `flock` to the mix:

```
#!/bin/bash

export LANG=C

count=0
while (( $count < 500 )) ; do
    (( $RANDOM % 2 )) && pt=dos || pt=gpt
    cmdout=$(flock /dev/sdx sfdisk --wipe=always --wipe-partitions=always --label=$pt /dev/sdx <<< ',,L' 2>&1)
    (( count++ ))
    grep -q 'Re-reading the partition table failed' <<< "$cmdout" && break
done

echo "Passes: $count"
```

It never fails.

Update: minor script simplification.

**Comment by karelzak** [comment]
Good point. 

Yes, I have seen the flock in udevd code some time ago (we had conflict between fsck and udevd years ago).

The question is if we really need the option if you can use "flock $dev sfdisk $dev" :-) I'll think about it.

**Comment by marcosfrm** [comment]
Yeah, I am not sure too. But it is a cool feature. Perhaps a hint in the man page is enough!

**Comment by karelzak** [comment]
Let's resolve this by man page for now. Thanks!
