### ISSUE TITLE
mount: "propagation flags" is wrong, it is "propagation type"

### ISSUE THREAD

**Issue by sourcejedi** [karelzak/util-linux#565]
> Since util-linux 2.23 the mount command allows to use several  propaga‐
       tion  flags  together  and  also  together with other mount operations.
       This feature is EXPERIMENTAL.  The propagation  flags  are  applied  by
       additional  mount(2)  system  calls when the preceding mount operations
       were successful.  Note that this use case is not atomic.  It is  possi‐
       ble to specify the propagation flags in fstab(5) as mount options (pri‐
       vate, slave, shared, unbindable, rprivate,  rslave,  rshared,  runbind‐
       able).
>
>  For example:
>
>              mount --make-private --make-unbindable /dev/sda1 /foo
>
> is the same as:
>
>              mount /dev/sda1 /foo
>              mount --make-private /foo
>              mount --make-unbindable /foo

But actually, talking about multiple "propagation flags" is bogus.   There is only one "propagation type" per mount point.  You cannot be both public and unbindable, for example.  The specific equivalence happens to be true, but it is confused about what is actually going on.

```
mount --bind /mnt /mnt
mount --make-unbindable /mnt
findmnt -o TARGET,PROPAGATION|grep mnt
└─/mnt                                private,unbindable
mount --make-private /mnt
findmnt -o TARGET,PROPAGATION|grep mnt
└─/mnt                                private
```

`mount` should probably reject requests to set multiple different propagation types.

(Since it has been wrong (and findmnt is as well :( ), maybe `mount` needs to special-case private+unbindable, accept it as meaning unbindable, and maybe print a warning.  I notice that `mount --make-unbindable --make-private` is currently equivalent to `mount --make-private`...  So maybe that needs to be rejected.  Or maybe it would be ok to change and interpret that as identical to `--make-private --make-unbindable`).

---

I noticed this because the real mount system call says

> *  Change  the  propagation  type  of  an  existing  mount:  mountflags
>    includes one of MS_SHARED, MS_PRIVATE, MS_SLAVE, or MS_UNBINDABLE.

and the [shared-subtree.txt](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) says 

> Shared subtree provides four different flavors of mounts; struct vfsmount to be
precise
>
>	a. shared mount
>	b. slave mount
>	c. private mount
>	d. unbindable mount

**Comment by karelzak** [comment]
We do not implement any policies for syscall in userspace by mount(8)  (mount -a is exception). The feature allow to replace
```
mount --bind /foo /foo
mount --make-private /foo
mount --make-unbindable /foo
```
(or another sequence) by one command:
```
mount -o bind,private,unbindable /foo /foo
```
It's kernel business to set the final propagation for the node. mount(8) does not care. The important is that you can use propagation flags together with normal mounts in fstab or command line. That's all the story.

I did a small change to the man page to talk about "propagation (topology) changes" rather than flags, because it's also about MS_BIND.

And findmnt follows kernel, "private,unbindable" is from /proc/self/mountinfo.

**Comment by sourcejedi** [comment]
I think the manpage would (still) benefit from being less ambiguous, about "private,unbindable" and "unbindable,private" having the same effect as "unbindable" and "private" respectively.

---

> It's kernel business to set the final propagation for the node.

I think this would make more sense if `mount` was passing flags in to a _single_ invocation of the `mount` system call.  But it seems misleading to take an attribute that the kernel repeatedly told us can only take one of four values, and explicitly offer to set the attribute to different values in sequence.  (And not clarify that this is what happens in our example).  Most readers will not be experts in the mount system call.

(There are more complex considerations like `--make-rslave --make-private`, but I don't think it's particularly necessary or sensible to allow that in a single call anyway).

> And findmnt follows kernel, "private,unbindable" is from /proc/self/mountinfo.

joy.  And I thought backwards compatibility would be the only barrier to my suggestion.  I guess the kernel could safely change as well, but it's less likely to do so.
