### ISSUE TITLE
`column -ts '<TAB>'` misaligns tab delimited files

### ISSUE THREAD

**Issue by unode** [karelzak/util-linux#575]
column -ts '<TAB>' <(echo "<TAB>col1<TAB>col2\nrow<TAB>1<TAB>2")

where `<TAB>` is a literal TAB character introduced with <kbd>Ctrl</kbd>+<kbd>v</kbd> <kbd>Tab</kbd>, produces:

```
col1  col2
row   1     2
```

instead of the correct:

```
     col1  col2
row  1     2
```

which is produced if instead of a `<TAB>` a <kbd>,</kbd> is used:

     column -ts ',' <(echo ",col1,col2\nrow,1,2")

```
     col1  col2
row  1     2
```

The cause seems to be that the `<TAB>` character is considered 'whitespace' and is stripped from the beginning of the line, causing the alignment shift.

**Comment by karelzak** [comment]
Yes, column(1) ignores space chars at the begin of the input line. Fixed. Let's hope it does not introduce any regression.
```
echo -e "\tcol1\tcol2\nrow\t1\t2" | ./column -t -s "$(echo -e '\t')"  --table-columns A,B,C
A    B     C
     col1  col2
row  1     2
```
