### ISSUE TITLE
column.1  --fillrows option doc seems backwards

### ISSUE THREAD

**Issue by ahmogit** [karelzak/util-linux#580]
The --fillrows option to column(1) seems to fill rows first (in accordance with my expectation based on the option name) but the man page documents it as "Fill columns before filling rows".  

Is my expectation wrong?

**Comment by karelzak** [comment]
Already fixed in version 2.30-rc1. Update. The current upstream:
```
       -x, --fillrows
              Fill rows before filling columns.
```
