### ISSUE TITLE
[feature request] script: Record terminal size

### ISSUE THREAD

**Issue by egmontkob** [karelzak/util-linux#583]
Hi,

`script` and `scriptreplay` are useful for recording and replaying terminal sessions – well, they were designed to do this.

If there are any special cursor moving or similar operations, chances are that replaying only makes sense at the exact same window size, and the output falls apart badly at other sizes.

I happen to use `script` a lot, or ask others to use it, in order to debug issues where it's not clear initially whether the bug is in the terminal emulator or in the application. I always have to ask them to take a note of the window size separately so that I can replay or manually evaluate the contents of typescript.

It would be a great aid, and hopefully pretty easy to do, to record the initial window size in `typescript`, e.g. it could begin like "Script started on [timestamp] at size [W]x[H]". Maybe the same at the end as well. And maybe at the end it could even warn if the window was at least once resized during its operation, even if it was later restored to the original.

(Optionally, it could even record window size changes during its operation, either in the timing file, or in yet another one. I understand that this can only be done approximately; due the asynchronous nature of communication between `script` and the underlying terminal emulator, `script` cannot always exactly know at which byte the terminal size changed, and hence the recorded files couldn't always be replayed exactly. Therefore I don't mind at all if you reject this part. Recording the initial size would still be a neat improvement.)

Thanks a lot in advance for considering this feature request!

**Comment by karelzak** [comment]
Good idea. I think we can record more information in the header like terminal type , etc.
```
Script started on 2018-03-05 13:02:08+0100 [term="xterm-256color", lines=53, columns=190]
```
I'll add this to our TODO. Thanks!

Maybe the final solution would be to optionally add "event" records to the timing file to save non-data changes like terminal resize, signals, etc. The current script implementation uses signalfd() and poll() for everything, so from code point of view all is synchronous (although reality is different).

**Comment by egmontkob** [comment]
Recording $TERM is a great idea too – how come it didn't occur to me? :-D

**Comment by karelzak** [comment]
Implemented.
```
   Script started on 2018-05-14 12:52:32+02:00 [TERM="xterm-256color" TTY="/dev/pts/3" COLS="190" LINES="53"]
or

   Script started on 2018-05-14 12:54:01+02:00 [<not executed on terminal>]
```

and "done" line:
```
    Script done on 2018-05-14 13:56:31+02:00 [COMMAND_EXIT_CODE="0"]
```

**Comment by karelzak** [comment]
Well, I have replaced COLS with COLUMNS. It seems better :-)
