### ISSUE TITLE
uuid_* manpages falsely claim that the functions comply to DCE 1.1 specification

### ISSUE THREAD

**Issue by mgorny** [karelzak/util-linux#592]
Some of the `uuid*` manpages claim that they conform to DCE 1.1:

    .SH "CONFORMING TO"
    OSF DCE 1.1

However, the API used by libuuid is *not compatible* with the one specified by [DCE 1.1](http://pubs.opengroup.org/onlinepubs/9629399/). Applications written using it do not work with DCE-conforming implementations such as the one used by FreeBSD.

Having this claim in manpages makes users wrongly believe that their programs will be portable while they will be not.

**Comment by karelzak** [comment]
Hmm.. I think the "CONFORMING TO" means UUID format rather than the library API. I'll make it more obvious from the man pages.
