### ISSUE TITLE
'column' unnecessarily ignores empty lines

### ISSUE THREAD

**Issue by matsaman** [karelzak/util-linux#593]
Empty lines can be useful, especially for formatting text, which is what this 'column' command is for after all.

They're real easy to remove with so many other tools.

Seems like feature creep. It's harder to add them back in than it is to remove them with an additional tool.

Perhaps at this point at least an opt-in parameter for not ignoring them?

**Comment by karelzak** [comment]
Do you mean that empty line on input should be interpreted as empty line in the table?

 I'll think about it, but it will definitely require a new command line option to keep the default behaviour backwardly compatible.

**Comment by matsaman** [comment]
Yes, thanks for the consideration, & the util maintenance. :)

**Comment by frostschutz** [comment]
I remember jumping through hoops to make empty lines and comments act as a separator for `column` when reformatting `/etc/fstab`.

https://unix.stackexchange.com/a/96150/30851

But it's probably simply not what the tool was meant to be used for directly. (Even though the manpage actually has an example for `/etc/fstab` that uses sed to remove `#comments` first).

**Comment by karelzak** [comment]
Implemented. You have to use a new command line option --table-empty-lines.
