### ISSUE TITLE
login causes agetty to behave undesirablely

### ISSUE THREAD

**Issue by maandree** [karelzak/util-linux#6]
'agetty' as for a user name and passes it forward to 'login', but if 'login' fails to log in it will
ask for a new user name. And 'login' does not handle input in the same way as 'agetty'.

'login' should be able to ask for user names, and so should 'agetty', and they do not need
to behave the same way. But if 'login' is given a user name it should never as for a new one,
only for a new password and except the user to cancel using ^C or ^D if the username is
incorrect.

**Comment by tmccombs** [comment]
Is there a reason not to do this? Could there at least be an option to not prompt for the username again?

**Comment by karelzak** [comment]
This is behavior is de facto standard and getty and login can be from different sources -- so some common behavior is expected and it's probably bad idea to change the default.

There is a reason why agetty asks for a username, on serial lines is the communication analyzed by agetty and used to configure the line. So, at least for serial lines, it's a bad idea to not ask for username.

Anyway:
* there is option agetty --skip-login, it forces agetty to not ask for username, but it immediately executes login(1). 
* login(1) is possible to configure by LOGIN_RETRIES=1 in /etc/login.defs to not ask for username/password more than once.

From my point of view, you can get the desired behavior by configuration now. (so closing)

(I see that the original request from @maandree is from the year 2012; the current situation is probably better as agetty and login from util-linux are more configurable.)

@tmccombs, thanks for reminding this issue.

**Comment by tmccombs** [comment]
Does setting LOGIN_RETRIES in /etc/login.defs impacts more than just `login` though?

My use case is that I run agetty with --skip-login and supply my username, since I'm the only user on the computer. But if I mistype my password it then prompts me for a username, which is unexpected and a little inconvenient.

**Comment by karelzak** [comment]
If I good remember than LOGIN_RETRIES has been introduced for login(1) from util-linux, so I guess nothing else uses this option (and google agree with me ;-)).

Note that login(1) itself does not ask for anything. It uses PAM and drops username from the session only if PAM reports that the username is unknown.

**Comment by tmccombs** [comment]
>  [login] drops username from the session only if PAM reports that the username is unknown

I don't think that's true. https://github.com/karelzak/util-linux/blob/76054e152730637e97ebccedf3395d7db9b19a24/login-utils/login.c#L876 sets the username to NULL for several error conditions, including `PAM_AUTH_ERR`, which I believe happens on an invalid password, even if the username is valid. 

I suppose the LOGIN_RETRIES option will work for me, but  maybe there should be an option to avoid clearing PAM_USER on each try? It's totally up to you, but if you think that would be valuable, I'd be happy to make a PR.

**Comment by karelzak** [comment]
> > [login] drops username from the session only if PAM reports that the username is unknown
> 
> I don't think that's true.
> 
> https://github.com/karelzak/util-linux/blob/76054e152730637e97ebccedf3395d7db9b19a24/login-utils/login.c#L876
> sets the username to NULL for several error conditions, including `PAM_AUTH_ERR`, which I believe happens on an invalid password, even if the username is valid.

Ah, you're right. I've missed this pam_set_item() at the end of the loop.

> I suppose the LOGIN_RETRIES option will work for me, but maybe there should be an option to avoid clearing PAM_USER on each try? It's totally up to you, but if you think that would be valuable, I'd be happy to make a PR.

I think the current behavior makes sense -- for example, I sometimes type "kzak" (which is valid username on my workstation) but I want "root", so it's a good thing that login(1) asks me again :-)

Anyway, you're right that an option to control this behavior would be valuable. 

So, go ahead -- I look forward to your PR ;-)
