### ISSUE TITLE
uuid: uuidd ... FAILED (daemon start)

### ISSUE THREAD

**Issue by jakirkham** [karelzak/util-linux#600]
When build 2.31 or 2.31.1 and running the test suite, found the uuidd daemon test failed. Was running as a non-`root` user. Using CentOS 6.9 in a Docker image. Built using devtoolset-2.

**Comment by jakirkham** [comment]
Also this message shows up right before.

```
lt-uuidd: couldn't bind unix socket /staged-recipes/build_artefacts/util-linux_1521247607082/work/util-linux-2.31.1/tests/output/uuid/uuiddKVSEmt8cDheUF: File name too long
```

**Comment by jakirkham** [comment]
Good to know. Thanks for the info and fix. Feel free to close.

**Comment by karelzak** [comment]
@jakirkham thanks for your report. 
@rudimeier thanks for your bugfix :-)
