### ISSUE TITLE
misc/cal - add vertical calendar option

### ISSUE THREAD

**Issue by nmr50** [karelzak/util-linux#604]
Hello mighty author(s) !
Please add option to cal to show calendar itself in a vertical mode, the same way how it works in bsdmainutils' ncal:
```
    March 2018        
Mo     5 12 19 26   
Tu     6 13 20 27   
We     7 14 21 28   
Th  1  8 15 22 29   
Fr  2  9 16 23 30   
Sa  3 10 17 24 31   
Su  4 11 18 25    
```
Thanks in advance!
ps. ncal freebsd related sources can be found here: https://github.com/freebsd/freebsd/blob/master/usr.bin/ncal/ncal.c

**Comment by utix** [comment]
I can work on it.
I propose to do different steps

- [ ] Prepare the actual code, without changing the behavior, for example rename some fields like `week_width` that will become `month_width`
- [ ] Add `-c` parameter to display in column

**Comment by utix** [comment]
First WIP version available here https://github.com/utix/util-linux/commits/cal_column

**Comment by kerolasa** [comment]
Please remember `bash-completion/cal` update when adding option(s).

**Comment by kerolasa** [comment]
And tests. Good --column test will use the option in combination with various ways how cal can be run, that is to print a single month, three months, a year, time range, Monday and Sunday as first day of the week, in Julian mode, and some combinations of these.

**Comment by utix** [comment]
I have planned all those tests:

```call_cal "Gregorian - Monday-based week" -1mc $MYTIME                            
call_cal "Gregorian - Sunday-based week" -1sc $MYTIME                            
call_cal "Julian - Monday-based week" -1mjc $MYTIME                              
call_cal "Julian - Sunday-based week" -1sjc $MYTIME                              
call_cal "Gregorian - Monday-based week with week numbers" -1mwc $MYTIME         
call_cal "Gregorian - Sunday-based week with week numbers" -1swc $MYTIME         
call_cal "Julian - Monday-based week with week numbers" -1mjwc $MYTIME           
call_cal "Julian - Sunday-based week with week numbers" -1sjwc $MYTIME           
call_cal "Gregorian - Monday-based week" -3mc $MYTIME                            
call_cal "Gregorian - Sunday-based week" -3sc $MYTIME                            
call_cal "Julian - Monday-based week" -3mjc $MYTIMET                             
call_cal "Julian - Sunday-based week" -3sjc $MYTIME                              
call_cal "Gregorian - Monday-based week with week numbers" -3mwc $MYTIME         
call_cal "Gregorian - Sunday-based week with week numbers" -3swc $MYTIME         
call_cal "Julian - Monday-based week with week numbers" -3mjwc $MYTIME           
call_cal "Julian - Sunday-based week with week numbers" -3sjwc $MYTIME           
                                                                                 
call_cal "Normal span" "-cSn 3" $MYTIME                                          
call_cal "Large span" "-cSn 21" $MYTIME                                          
call_cal "Very Large span" "-cSn 51" $MYTIME                                     
call_cal "Extreme span" "-cSn 201" $MYTIME ```

**Comment by utix** [comment]
> Please remember `bash-completion/cal` update when adding option(s).

Thanks for the reminder, I have updated it.

**Comment by nmr50** [comment]
OK, thanks to thoe who have helped with this vertical option implementation.
I'll be waiting for the new version of util-linux :)
