### ISSUE TITLE
partx --update /dev/sda automounts partitions

### ISSUE THREAD

**Issue by stikonas** [karelzak/util-linux#605]
When I run partx --update /dev/sda on my unmountd EFI partition with fstab entry 
/dev/sda1               /boot/efi       vfat            defaults        0 2
it ends up mounted.

I don't think this is the indended behaviour. Certainly man partx does not mention anything like that.

**Comment by stikonas** [comment]
OK, let's close it. It looks like it is systemd that is actually mounting it to do fsck.

**Comment by rudimeier** [comment]
On Saturday 24 March 2018, Andrius Štikonas wrote:
> OK, let's close it. It looks like it is systemd that is actually
> mounting it to do fsck.

Yeah, welcome to the systemd world. They've managed to make umount(1) 
unusable. Like this RESOLVED WONTFIX bug:

https://bugzilla.suse.com/show_bug.cgi?id=902612

Either don't use systemd or don't use umount. Maybe we should "improve" 
umount to print a warning:

 "warning: device was umounted successfully but it may be mountend again
           randomly in 2 seconds or next week by systemd"

The funny thing is that there is no single use-case why a device should 
be auto-mounted again after the system-administrator has manually 
umounted it. But this does not fit into the event driven "modern" 
systemd design, thus can't be implemented :))

**Comment by stikonas** [comment]
Well, that bug was still useful for me. Thanks!
I can run
udevadm control --stop-exec-queue
before KDE Partition Manager starts executing jobs and then
udevadm control --start-exec-queue
when it finishes.
It will get automounted but later. Better than messing up user data..

**Comment by stikonas** [comment]
Ok, it seems I found a good workaround.
partx --update /dev/sdb triggers systemd automount
but blockdev --rereadpt /dev/sdb does not
