### ISSUE TITLE
namei: precise error messages

### ISSUE THREAD

**Issue by chneukirchen** [karelzak/util-linux#608]
When namei(1) fails to stat a file for any reason, it will always print
"No such file or directory"

```
% namei -m /root/foo/bar      
f: /root/foo/bar
 drwxr-xr-x /
 drwxr-x--- root
            foo - No such file or directory
```

I think it would be more useful if it printed "Permission denied" in this case, as the stat fails with EACCES. Then namei is useful for checking permission issues, too.

Likewise, this output is confusing:
```
% namei /dev/null/foo      
f: /dev/null/foo
 d /
 d dev
 c null
   foo - No such file or directory
```

I'd be willing to implement this if you want to merge it.

**Comment by karelzak** [comment]
Good catch. Thanks!
Fixed:
```
$ namei -m ~/foo/bar  
f: /home/kzak/foo/bar
 dr-xr-xr-x /
 drwxr-xr-x home
 drwxr----- kzak
            foo - No such file or directory

 $ namei -m /root/foo/bar  
f: /root/foo/bar
 dr-xr-xr-x /
 dr-xr-x--- root
            foo - Permission denied
```
