### ISSUE TITLE
RFE: a tiny helper tool for adjusting "oom_score_adj"

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#609]
We have various tools for setting various process parameters with various tools, but there's no nice tool for adjusting the OOM score when executing something. It would be awesome if util-linux would maybe gain a new tiny tool maybe called "choom" for changing the OOM score adjust values. Example:

`choom -n 1000 /usr/bin/foo`

Or so. or even `choom -p 4711 -n 750` for changing the OOM score adjust value for PID 4711 to 750.

i.e. a tool that feels a bit like nice or renice, but adjust the OOM score.

Yes, adjusting the OOM adjust value manually is pretty easy, as you can just echo into it, but it would still be nicer to have a wrapper tool that parses a command line and then execs it.

**Comment by karelzak** [comment]
Sounds like a good idea.

**Comment by poettering** [comment]
Excellent! thank you!
