### ISSUE TITLE
Add support for bitlocker

### ISSUE THREAD

**Issue by gsgrippal** [karelzak/util-linux#617]
Add bitlocker support to udevadm

http://www.forensicswiki.org/wiki/BitLocker_Disk_Encryption

**Comment by gsgrippal** [comment]
Also to fdisk and all the other tools within this project.

**Comment by stikonas** [comment]
@karelzak Yes, gsgrippal meant detection of signature. Right now GParted has some custom code in src/GParted_Core.cc (function GParted_Core::detect_filesystem_internal) to detect bitlocker block devices and gsgrippal also wants KDE Partition Manager to detect bitlocker too. Yet instead of duplicating that code I think it's better for it to just live in blkid, so that it can be shared.

**Comment by karelzak** [comment]
Test images: https://github.com/e-ago/bitcracker/tree/master/Images

**Comment by gsgrippal** [comment]
I want that in the future nautilus and KDE dolphin can automatically display the encrypted device in the left panel, similar to this:

![Dolphin with experimental bitlocker support](http://oi67.tinypic.com/2lb2h6h.jpg)

**Comment by gsgrippal** [comment]
@stikonas ok I know that. What I don't know if dolphin or kde device notifier use util-linux to detect media, or they do like gparted and just fetch data with their own methods.

**Comment by stikonas** [comment]
@gsgrippal. No, not own methods. I think Solid and udisks2 as Solid backend. But dolphin wouldn't show it there anyway if it can't mount it. Dont' think many distributions ship bitlocker FUSE module.

**Comment by gsgrippal** [comment]
@stikonas if dolphin doesn't do that, it may need improvement. Currently, Windows 10 automatically detects when a volume is bitlocker partially/totally encrypted (you can pause process and resume after a reboot).

It also shows a different symbol depending if it's locked or unlocked (either by user entering password or auto-unlock at boot):

![locked with bitlocker](http://oi64.tinypic.com/33epj6s.jpg)
![unlocked with bitlocker](http://oi67.tinypic.com/35c4qpi.jpg)

The volume name can only be obtained once it's decrypted.

**Comment by stikonas** [comment]
@gsgrippal well, of course windows detects is own proprietary encryption method. On the other hand it does not detect LUKS partitions.
As for truecrypt/veracrypt, you aren't exactly right. All distros ship cryptsetup which can open tcrypt, veracrypt and luks volumes.

**Comment by gsgrippal** [comment]
@stikonas I was not sure about the cryptsetup thing so I said "almost the same..."

If I install LibreCrypt (https://github.com/t-d-k/LibreCrypt) on Windows 10, will it be auto-recognize from My Computer like dislocker volumes, or do I have to manually mount them like Veracrypt?

**Comment by stikonas** [comment]
@gsgrippal I don't know. I don't use Windows.

**Comment by karelzak** [comment]
I have added BitLocker detection, for Win7 version:
```
./blkid -p -o udev /dev/loop1p1
ID_FS_VERSION=2
ID_FS_TYPE=BitLocker
ID_FS_USAGE=crypto
ID_PART_ENTRY_SCHEME=dos
ID_PART_ENTRY_UUID=bef26573-01
ID_PART_ENTRY_TYPE=0x7
ID_PART_ENTRY_NUMBER=1
ID_PART_ENTRY_OFFSET=128
ID_PART_ENTRY_SIZE=75776
ID_PART_ENTRY_DISK=7:1
``
BitLockerToGo:
```
./blkid -p -o udev /home/kzak/Downloads/imgWin7
ID_FS_VERSION=2
ID_FS_TYPE=BitLocker
ID_FS_USAGE=crypto
```
Unfortunately, it's without LABEL and UUID.  The Win7 BitLocked is based on NTFS header, but it does not use volume_label and volume_serial from the header. Maybe for BitLockerToGo would be possible to use LABEL from FAT superblock, not sure.

Anyway, libblkid cannot be used to unlock the device, it's just detection library. You need to use another tools (https://github.com/libyal/libbde ?) to unlock the device. 

The ideal solution would be to follow what we have for LUKS, udevd (by libblkid) detects BitLocker and then (for example systemd) asks for key/password.... but this  is out of libblkid :-)

Note that lsblk reads information from udev db, with the bitlocker detection you will see "BitLocker" as FSTYPE (e.g. lsblk --fs).

**Comment by gsgrippal** [comment]
@karelzak what's the difference between libbde and dislocker, and which one do you recommend me?
https://github.com/Aorimn/dislocker

**Comment by gsgrippal** [comment]
Also I think could provide more information, for example if the volume is 100% encrypted or not, or other parameters.

**Comment by stikonas** [comment]
Isn't extra info for LUKS provided only by cryptsetup, not by util-linux. In that case I would say same applies to bitlocker.

**Comment by mhogomchungu** [comment]
Google search led me here when i was searching to find out of blkd supports bitlocker signature detection.

For those interested in managing bitlocker volumes using a GUI tool, I have a project called "zuluCrypt"[1] and i am working[2] on adding support for bitlocker volumes using "dislocker"[3] backend.

[1] https://mhogomchungu.github.io/zuluCrypt/

[2] https://github.com/mhogomchungu/zuluCrypt/issues/109

[3] https://github.com/Aorimn/dislocker
