### ISSUE TITLE
Add support for msftres and msftdata

### ISSUE THREAD

**Issue by gsgrippal** [karelzak/util-linux#623]
lsblk do not detect msftres and msftdata, while blkid does.

It affects KDE Partition Manager:
https://bugs.kde.org/show_bug.cgi?id=393434

**Comment by stikonas** [comment]
The question is does mstfres even have any file system? I don't have any test images, but it might be that it's just an unformatted partition.

**Comment by karelzak** [comment]
lsblk reads data from udev db, it does not read (by default) from the device. What do you mean with "not detect msftres and msftdata"?

I'm not sure what is expected for the "Microsoft reserved partition", I have no clue if there is any filesystem...

Just for the record:
PARTLABEL and PARTUUID are based on Partition Table. This is completely independent on stuff stored on the partitions. LABEL and UUID are based on filesystem stored on the partition (device).

**Comment by stikonas** [comment]
It seems to me that msftres has no meaningful file system at all. It's just unformatted partition with some specific GPT partition type. I can be wrong though.

Msftdata seems to be FAT or NTFS with some specific gpt partition type. So in this case maybe it is already recognized?

On 24 April 2018 11:52:46 BST, Karel Zak <notifications@github.com> wrote:
>lsblk reads data from udev db, it does not read (by default) from the
>device. What do you mean with "not detect msftres and msftdata"?
>
>I'm not sure what is expected for the "Microsoft reserved partition", I
>have no clue if there is any filesystem...
>
>Just for the record:
>PARTLABEL and PARTUUID are based on Partition Table. This is completely
>independent on stuff stored on the partitions. LABEL and UUID are based
>on filesystem stored on the partition (device).
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/karelzak/util-linux/issues/623#issuecomment-383889021

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gsgrippal** [comment]
Ok fixed, the desired information is displayed in the output column `PARTLABEL` which is NOT shown by default.

```
lsblk -o name,mountpoint,label,partlabel,size
```
```
root@ubuntu:~# lsblk -o name,mountpoint,label,partlabel,size
NAME           MOUNTPOINT                    LABEL  PARTLABEL                      SIZE
nvme0n1                                                                          xxx,xG
├─nvme0n1p1    /boot/efi                     SYSTEM EFI system partition           300M
├─nvme0n1p2                                         Microsoft reserved partition   128M
├─nvme0n1p3                                         Basic data partition         xxx,xG
└─nvme0n1p4                                                                        x,xG
```
