### ISSUE TITLE
Add support to recognize Windows recovery environment

### ISSUE THREAD

**Issue by gsgrippal** [karelzak/util-linux#625]
```
root@kubuntu:~# fdisk -l /dev/nvme0n1
Disk /dev/nvme0n1: xxxx.x GiB, xxxx bytes, xxxx sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier:

Device              Type
/dev/nvme0n1p1      EFI System
/dev/nvme0n1p2      Microsoft reserved
/dev/nvme0n1p3      Microsoft basic data
/dev/nvme0n1p4      Windows recovery environment
```

lsblk does not recognize PARTLABEL for "Windows recovery environment"
```
root@ubuntu:~# lsblk -o name,mountpoint,label,partlabel,size
NAME           MOUNTPOINT                    LABEL  PARTLABEL                      SIZE
nvme0n1                                                                          xxx,xG
├─nvme0n1p1    /boot/efi                     SYSTEM EFI system partition           300M
├─nvme0n1p2                                         Microsoft reserved partition   128M
├─nvme0n1p3                                         Basic data partition         xxx,xG
└─nvme0n1p4                                                                        1,7G
```

**Comment by karelzak** [comment]
The partition type and partition label are two different things. The type is some GUID number (for GPT) and label is some string. Try:
```
   # fdisk -l -o Device,Type,Type-UUID,Name
```
Note that fdisk uses Name instead of PARTLABEL and Type is human readable alias GUID (Type-UUID).

For some reason Windows set Name (PARTLABEL) to human readable alias of GUID, but except the recovery partition where label is not set.

Anyway, the type is available as PARTTYPE, try:
```
   $  lsblk -o NAME,PARTLABEL,PARTTYPE
```
You can set the PARTLABEL by:
```
  # sfdisk --part-label /dev/nvme0n1 4 "Windows recovery environment"
```
or you can use another string if you want. The PARTLABEL (Name) is there for humans only.

There is nothing to improve in lsblk or fdisk.

**Comment by karelzak** [comment]
Note that for GPT each partition contains three identifiers

- partition type GUID (PARTTYPE in lsblk)
- partition name (PARTLABEL in lsblk)
- partition UUID (PARTUUID in lsblk)

**Comment by gsgrippal** [comment]
The command fdisk does show `Windows recovery environment`, however lsblk still no mention to it. For what I see each command has its own way of calling things, this is a mess. There should be some standard between apps, it's not ideal that some commands calls a LABEL what other calls TYPE and a third one NAME.

Even with `lsblk -O` no mention to `Windows recovery environment`, you don't want to add it to any column, I guess you want to outlaw it for some inexplicable reason. 

```
sudo fdisk -l -o Device,Type,Type-UUID,Name  /dev/nvme0n1
Disk /dev/nvme0n1: xxxxxGiB, xxxxxx bytes, xxxxx sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: xxxx-xxxx-xx-xxx-xxxxx

Device         Type                         Type-UUID                            Name
/dev/nvme0n1p1 EFI System                   xxxxx                                EFI system partition
/dev/nvme0n1p2 Microsoft reserved           xxxxxx                               Microsoft reserved partition
/dev/nvme0n1p3 Microsoft basic data         xxxxxx                               Basic data partition
/dev/nvme0n1p4 Windows recovery environment xxxxxxx
```
```
sudo lsblk -o NAME,PARTLABEL,PARTTYPE
NAME           PARTLABEL                    PARTTYPE
nvme0n1                                     
├─nvme0n1p1    EFI system partition         c12a7328-f81f-11d2-ba4b-00a0c93ec93b
├─nvme0n1p2    Microsoft reserved partition e3c9e316-0b5c-4db8-817d-f92df00215ae
├─nvme0n1p3    Basic data partition         ebd0a0a2-b9e5-4433-87c0-68b6b72699c7
└─nvme0n1p4                                 de94bba4-06d1-4d40-a16a-bfd50179d6ac
```

**Comment by karelzak** [comment]
Again, PARTLABEL string is stored in partition table and for win recovery there is nothing, so lsblk shows nothing. I don't understand what do you expect.. we don't generate this string, we do not write the partition table. 

fdisk shows human readable alias for "de94bba4-06d1-4d40-a16a-bfd50179d6ac", the label (Name) is also empty.

Ask author of partitioning tool used to for your disk (Microsoft?) to set the field or do it manually by sfdisk.

**Comment by gsgrippal** [comment]
I was expecting to see a "human readable alias", so maybe add that column?  I have a hard time guessing out what "de94bba4-06d1-4d40-a16a-bfd50179d6ac" means or if it's a random generated identifier.
