### ISSUE TITLE
linux distro to test latest util-linux source code

### ISSUE THREAD

**Issue by gsgrippal** [karelzak/util-linux#629]
Which linux distro do you recommend me to test the latest changes committed to git? I'm running ubuntu currently but doesn't seem bleeding edge.

**Comment by karelzak** [comment]
Well, I guess nobody pushs unstable stuff to distros. The changes for end-users are usually available after release. You have to use git to pull changes, compile and try locally ... or wait for release and your distro update.

**Comment by gsgrippal** [comment]
I've found out that's not necessary to install the binaries to test them, they are available in the util-linux git directory and can be run directly from there, as root.
