### ISSUE TITLE
autogen.sh does not detect bison version on debian testing

### ISSUE THREAD

**Issue by gsgrippal** [karelzak/util-linux#630]
`You must have bison version >= 2.x, but you have .`
```
bison --version
bison (GNU bison) 3.0.4
```

**Comment by gsgrippal** [comment]
Here:
https://github.com/karelzak/util-linux/blob/master/autogen.sh#L76

`lexver=$(bison --version | awk '/bison \(GNU Bison\)/ { print $4 }')`

Replace with
`bison --version |  awk '/ison\)/ { print $4 }'`

**Comment by gsgrippal** [comment]
Could you please report the bug to bison? I hate mailing lists and don't have an email account for that.

**Comment by rudimeier** [comment]
Maybe better
`bison --version | awk '/^bison \(GNU [Bb]ison\)/ { print $4 }'`
or just
`bison --version | awk 'NR==1{print $NF}'`

**Comment by gsgrippal** [comment]
Or 
```
bison --version | awk '/[Bb][Ii][Ss][Oo][Nn]\)/ { print $0 }'
bison --version | head -n1  | awk '// { print $4 }'
```
But I would avoid the [Bb]ison because they can go all uppercase or something.

The NR and NF are built-ins, no idea if the awk of all platforms support that. For example, binaries in busybox for android usually have lots of built-ins missing. I would use the NR and NF version.

**Comment by gsgrippal** [comment]
This should be great too
`bison --version | grep -i gnu | grep -i bison | awk -F' '  ' { print $NF } '`

**Comment by karelzak** [comment]
Let's keep is simple and stupid, add  [Bb] seems good enough.
