### ISSUE TITLE
inconsistent ID_FS_LABEL naming

### ISSUE THREAD

**Issue by gsgrippal** [karelzak/util-linux#632]
```
sudo ./blkid -p -o udev /mnt/bitlocker/dislocker-file
ID_FS_LABEL=DISK_TB
ID_FS_LABEL_ENC=DISK\x20TB
ID_FS_UUID=XXXXXX
ID_FS_UUID_ENC=XXXXXXXX
ID_FS_TYPE=ntfs
ID_FS_USAGE=filesystem
```
```
sudo ./blkid --version
blkid from util-linux 2.32.83-f4375
```
Note that the label shown on Windows 10 is "DISK TB" and not "DISK_TB". Furthermore the `\x20` is pretty clear, it's a space.

However, a simple command gets it right:
```
blkid /mnt/bitlocker/dislocker-file
dislocker-file: LABEL="DISK TB" UUID="XXXXXXXX" TYPE="ntfs"
blkid --version
blkid from util-linux 2.32.83-f4375
```
 It may be related to Microsoft BitLocker

**Comment by karelzak** [comment]
This is expected behaviour. The udev environment do not accept whitespaces.

**Comment by karelzak** [comment]
Note that for new stuff like ID_PART_ENTRY_NAME= (PARTLABEL) it uses only hex-escapes, but for LABEL= we need to be backwardly compatible.
