### ISSUE TITLE
swapon and fallocated files

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#633]
swapon man page discourages fallocate. But this _works_ in EXT4 (kernel 4.16):

```
# fallocate -l 1G /swap
# chmod 0600 /swap 
# mkswap /swap 
Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
no label, UUID=41268fc9-da3d-4540-a82e-35ed86f4fd5e
# swapon /swap
# swapon
NAME  TYPE  SIZE USED PRIO
/swap file 1024M   0B   -2
```

~~Appears that the file with holes limitation is solved.~~

And in XFS too? (not merged yet)

https://www.spinics.net/lists/linux-xfs/msg17823.html

**Comment by marcosfrm** [comment]
fallocate alocates stuff _without_ holes. Ubuntu is using it by default on EXT4:

https://salsa.debian.org/installer-team/partman-swapfile/blob/1/finish.d/create_swapfile#L38

This will be supported on XFS starting with 4.18:

https://lkml.org/lkml/2018/6/5/888

**Comment by karelzak** [comment]
It seems the XFS change is still not merged into Linus' tree.

Anyway, I have improved the note in the man pages.

**Comment by karelzak** [comment]
Ah,  already merged as

commit 67482129cdabf7cede1301d2415ef4f0156d35cd
Author: Darrick J. Wong <darrick.wong@oracle.com>
Date:   Thu May 10 08:38:15 2018 -0700

    iomap: add a swapfile activation function

**Comment by marcosfrm** [comment]
Please also edit sys-utils/swapon.8 to be inline with https://github.com/karelzak/util-linux/commit/77983e4a21588eb75515b307aed0c4c2f67afb79. Cant we put the kernel version there (4.18 for XFS)?

BTW, Linux 5.0 will bring swap file support to Btrfs:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ed46ff3d423780fa5173b38a844bf0fdb210a2a7

(do not know if fallocate will work)

**Comment by karelzak** [comment]
Good points, fixed:
* added info about the kernel versions
* keep only link to swapon in mkswap man page
* cleanup all the stuff
* more details about btrfs requirements
