### ISSUE TITLE
The ntfs cluster limit has been extended to 2MB

### ISSUE THREAD

**Issue by jpandre** [karelzak/util-linux#641]
Windows 10 Creators edition has extended the ntfs cluster limit to 2MB. As a consequence blkid does not identify recent partitions with clusters beyond 65K as ntfs ones.

Below is an UNTESTED patch for accepting big clusters. A new meaning has been assigned to the number of sectors per cluster when this is greater than 128.

See https://bugzilla.redhat.com/show_bug.cgi?id=1575227 for more about this.

--- ntfs.c.ref	2018-05-25 12:00:22.937792800 +0200
+++ ntfs.c	2018-05-25 12:12:55.919038000 +0200
@@ -72,7 +72,8 @@
 } __attribute__((__packed__));
 
 #define MFT_RECORD_VOLUME	3
-#define NTFS_MAX_CLUSTER_SIZE	(64 * 1024)
+/* Windows 10 Creators edition has extended the cluster size limit to 2MB */
+#define NTFS_MAX_CLUSTER_SIZE	(2 * 1024 * 1024)
 
 enum {
 	MFT_RECORD_ATTR_VOLUME_NAME		= 0x60,
@@ -97,16 +98,19 @@
 	 * Check bios parameters block
 	 */
 	sector_size = le16_to_cpu(ns->bpb.sector_size);
-	sectors_per_cluster = ns->bpb.sectors_per_cluster;
 
 	if (sector_size < 256 || sector_size > 4096)
 		return 1;
 
-	switch (sectors_per_cluster) {
+	switch (ns->bpb.sectors_per_cluster) {
 	case 1: case 2: case 4: case 8: case 16: case 32: case 64: case 128:
+		sectors_per_cluster = ns->bpb.sectors_per_cluster;
 		break;
 	default:
-		return 1;
+		if ((ns->bpb.sectors_per_cluster < 240)
+		    || (ns->bpb.sectors_per_cluster > 249))
+			return 1;
+		sectors_per_cluster = 1 << (256 - ns->bpb.sectors_per_cluster);
 	}
 
 	if ((uint16_t) le16_to_cpu(ns->bpb.sector_size) *

**Comment by karelzak** [comment]
Thanks! 

Can you provide any test image with such NTFS? I'd like to add the image to tests/ts/blkid/images-fs/ to be sure all works as expected. It should be enough to use dd(1) and xz to create the image.

**Comment by jpandre** [comment]
Hi,

Karel Zak wrote:
> Thanks!
>
> Can you provide any test image with such NTFS? I'd like to add the image
> to tests/ts/blkid/images-fs/ to be sure all works as expected. It should
> be enough to use dd(1) and xz to create the image.

I have posted a test partition image on
https://bugzilla.redhat.com/show_bug.cgi?id=1582491
with explanation on how to extract it. Using dd(1)
would have taken ages though this is a void partition.

**Comment by jpandre** [comment]
Oops, I see my patch was not complete. A few lines below
my original patch, there is :

if ((uint16_t) le16_to_cpu(ns->bpb.sector_size) *
              ns->bpb.sectors_per_cluster > NTFS_MAX_CLUSTER_SIZE)

and this should be changed to :

if ((uint16_t) le16_to_cpu(ns->bpb.sector_size) *
              sectors_per_cluster > NTFS_MAX_CLUSTER_SIZE)

(as sectors_per_cluster is not equal to ns->bpb.sectors_per_cluster
any more).


Karel Zak wrote:

**Comment by karelzak** [comment]
./blkid -p big-rebuilt.ntfs
big-rebuilt.ntfs: LABEL="DVD+BD (Sicherungskopie)" UUID="C2E23160E2315A3D" TYPE="ntfs" USAGE="filesystem" PTTYPE="dos"

I guess it's OK.

**Comment by jpandre** [comment]
LGTM

Karel Zak wrote:
> ./blkid -p big-rebuilt.ntfs
> big-rebuilt.ntfs: LABEL="DVD+BD (Sicherungskopie)"
> UUID="C2E23160E2315A3D" TYPE="ntfs" USAGE="filesystem" PTTYPE="dos"
>
> I guess it's OK.
>
