### ISSUE TITLE
column does not correctly handle empty cells

### ISSUE THREAD

**Issue by contentfree** [karelzak/util-linux#644]
Sample data:
```
row1,column1,column2,column3
row2,column1,,column3
row3,,column2,
```

Expected output of `column -ts, sample.csv`:
```
row1  column1  column2  column3
row2  column1           column3
row3           column2 
```

Actual output:
```
row1  column1  column2  column3
row2  column1  column3
row3  column2
```

**Comment by karelzak** [comment]
Sounds like already fixed https://github.com/karelzak/util-linux/issues/575

**Comment by contentfree** [comment]
@karelzak Hmm, doesn't look related to me – though you'll certainly know better than me. #575 addresses leading spaces. Does that happen at the line level (how I read it) or at the column level?

**Comment by karelzak** [comment]
Version? 

I have tested all versions between v2.27 and the current git at it works everywhere :-) Yes, you're right, #575 is mostly about leading spaces.

```
$ column -ts, ~/a
row1  column1  column2  column3
row2  column1           column3
row3           column2  

$ cat ~/a
row1,column1,column2,column3
row2,column1,,column3
row3,,column2,
```

**Comment by contentfree** [comment]
Hmm, then it's likely a relic of whatever version of `column` ships with
macOS. Thanks for the attention! Feel free to close this.
