### ISSUE TITLE
Why util-linux releases are so slow?

### ISSUE THREAD

**Issue by superbonaci** [karelzak/util-linux#647]
I've been looking here:
https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/

And latest version, v2.32, is several months old already. Why isn't as new release every month or so? It is way too slow.

**Comment by karelzak** [comment]
https://github.com/karelzak/util-linux/blob/master/Documentation/release-schedule.txt

it's usually 2-3 releases per year and 1 or 2 maintenance releases for each release (hmm... we need v2.32.1 now). For now it seems good enough, I don't see any complains from distros.
