### ISSUE TITLE
/run/mount/utab is not namespace aware

### ISSUE THREAD

**Issue by zyga** [karelzak/util-linux#649]
Hello

I'm working on a system where there are two mount namespaces. The initial mount namespace and the application-specific mount namespace. The application's mount namespace is widely different _but_ it shares some part of the filesystem with the host.

The issue is that `/run/mount/utab` has no provisions for tracking which mount namespace the meta-data applies to. After thinking about this for a short while I don't see a simple way to do that, given the nature of mount namespace sharing. It cannot be simply based on the mount namespace ID because parts of one namespace can propagate into another namespace. It probably cannot be based on mount ID alone as the identifier is not replicated with bind mounts.

Honestly I don't have an idea yet. I'm looking at what ought to happen and how to model that now.

**Comment by karelzak** [comment]
This is reason why classic /etc/mtab is deprecated and unused  and /run/mount/utab is as minimalistic as possible. The ideal situation is to have the file empty -- it means no NFS and userspace specific mount options (like user= ).
