### ISSUE TITLE
agetty: pass -p to login with autologin

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#655]
Is there a way to do that?

If I use

```
--login-options '-p -f username' ...
```

or

```
--login-options '-p' --autologin username ...
```

agetty asks for user name.

**Comment by karelzak** [comment]
You need "login -f" to avoid authentication (at least for login(1) from util-linux). The option --login-options completely overwrites the way how agetty composes login(1) command line. It means you have to specify everything there. For example:
```
--autologin kzak --login-options '-p -f kzak'
```
or
```
--autologin kzak --login-options '-p -f \u'
```
works for me ('kzak' is the username).
