### ISSUE TITLE
Building script on Mac OS 

### ISSUE THREAD

**Issue by tab1293** [karelzak/util-linux#657]
I am unable to build the `term-util/script` tool on Mac OS. I am seeing this error when trying to compile:
```
$ make term-utils/script
gcc -g -O2    term-utils/script.c   -o term-utils/script
term-utils/script.c:63:10: fatal error: 'sys/signalfd.h' file not found
#include <sys/signalfd.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [term-utils/script] Error 1
```
Is there any way to build the `term-util/script` from this repository on Mac OS? If not is there another open source of version of the `script` program that builds on Mac OS? My system already has a `script` program in `/usr/bin` but I can not find the source code for the binary that is included on my machine.

**Comment by rudimeier** [comment]
On Friday 29 June 2018, Tom Berger wrote:

> term-utils/script.c:63:10: fatal error: 'sys/signalfd.h' file not
> found #include <sys/signalfd.h>

> Is there any way to build the `term-util/script` from this repository
> on Mac OS?

script.c from util-linux 2.26.2 was still not using sys/signalfd.h and 
AFAIR it was building on OSX.

> If not is there another open source of version of the 
> `script` program that builds on Mac OS?

Maybe a BSD script(1) would, like this one from FreeBSD
https://svnweb.freebsd.org/base/stable/9/usr.bin/script/

**Comment by tab1293** [comment]
Tried building 2.26.2 but running in to more errors:
```
$ make term-utils/script
gcc -g -O2    term-utils/script.c   -o term-utils/script
term-utils/script.c:67:10: fatal error: 'closestream.h' file not found
#include "closestream.h"
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [term-utils/script] Error 1

$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in po
make[2]: Nothing to be done for `all'.
  CC       text-utils/more-more.o
In file included from text-utils/more.c:63:
./include/strutils.h:78:13: error: conflicting types for 'strmode'
extern void strmode(mode_t mode, char *str);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/string.h:164:7: note: previous declaration is here
void     strmode(int __mode, char *__bp);
         ^
1 error generated.
make[2]: *** [text-utils/more-more.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
Looks like there is some conflict with Mac's libraries? Any idea how to resolve?

**Comment by karelzak** [comment]
Frankly, 2.26 is too old. The current upstream version is 2.32 :-) 

Note that the build-system is non-recursive and it has internally clue about all the directories, so you need to use only binary name as make argument. For example
```
  make script
```
In your example 'make' completely bypass our Makefile, the gcc command line is without -I include/ and config.h etc.
