### ISSUE TITLE
lscpu L3 cache size on Ryzen 5 1600

### ISSUE THREAD

**Issue by atomsymbol** [karelzak/util-linux#663]
lscpu version 2.32 reports the CPU has 8 MiB cache, while the correct value is 16 MiB:

    $ lscpu
    Model name:          AMD Ryzen 5 1600 Six-Core Processor
    L3 cache:            8192K

/sys (Linux 4.17.0) provides the correct cache IDs:

    $ cat /sys/devices/system/cpu/cpu0/cache/index3/id
    0
    $ cat /sys/devices/system/cpu/cpu6/cache/index3/id
    1
    $ cat /sys/devices/system/cpu/cpu0/cache/index3/size
    8192K

It would be nice if lscpu printed the number of L1/L2/L3 caches, such as:

    L1d cache: 6*32K
    L1i cache: 6*64K
    L2 cache:  6*512K
    L3 cache:  2*8192K

For comparison, lstopo version 1.11.2 (http://www.open-mpi.org/projects/hwloc/) works OK.

**Comment by karelzak** [comment]
lscpu uses             
  ```                     
    /sys/devices/system/cpu/cpu0/cache/index3/shared_cpu_list
```                 
do get information about topology.
                       
The basic summary output prints information about the size of the
individual cache and nothing else. If you want info how the cache is
shared you need   "lscpu -e ".

> L1d cache: 6 * 32K
> L1i cache: 6 * 64K
> L2 cache:  6 * 512K
> L3 cache:  2 * 8192K

Sounds like a good idea, the question is backward compatibility of the
output... (imagine you have: lscpu | awk '/L3 cache/ { print $3 }' in
a script). Maybe we can add the number of the caches behind the size or
so.                    
                       
I'll think about it :-)

**Comment by ErwanAliasr1** [comment]
That is very true. On my EPYC, L3 is reported as 8192K while its 64MB.
Maybe we could have the actual l3 per core and having another l3 reporting for the whole socket ?

**Comment by karelzak** [comment]
> That is very true. On my EPYC, L3 is reported as 8192K while its 64MB.
> Maybe we could have the actual l3 per core and having another l3 reporting for the whole socket ?

Something like:
```
L3 cache (pre-core/all): 8192K / 64MiB
```
or
```
L3 cache (pre core): 8192K
L3 cache:            64MiB
```
The second solution will not break scripts, although it will print a different size.

**Comment by ErwanAliasr1** [comment]
I would say all the printing is done per socket so 'fixing' the L3 cache to report the whole L3 cache makes sense.
Adding a new line that brings the information per socket is then just an improvement.

Note this will also apply for l1 & l2.

I have some EPYC processors that offer lots of numa nodes. Are you interested by the /sys to have a real use case ?

**Comment by karelzak** [comment]
> I would say all the printing is done per socket so 'fixing' the L3 cache to report the whole L3 cache makes sense.
> Adding a new line that brings the information per socket is then just an improvement.

Good point of view ;-) Let's follow this idea... 

You can send a patch if want -- I'm busy with another stuff in next days. And yes, it would be nice to have /sys and /proc dump for EPYCl; We have script for this purpose https://github.com/karelzak/util-linux/blob/master/tests/ts/lscpu/mk-input.sh   ... but not sure if it covers all necessary files.

**Comment by ErwanAliasr1** [comment]
I collected the epyc but the test is reported failed.
erwanvelu@laptop:~/Devel/util-linux/tests/ts/lscpu (master)$ cat plop 
        lscpu: lscpu                          ...
                : armv7                       ... OK
                : ppc-qemu                    ... OK
                : ppc64-POWER7-64cpu          ... OK
                : ppc64-POWER7                ... OK
                : s390-kvm                    ... OK
                : s390-lpar-drawer            ... OK
                : s390-lpar                   ... OK
                : s390-zvm                    ... OK
                : sparc64                     ... OK
                : vbox-win                    ... OK
                : x86_64-64cpu                ... OK
                : x86_64-dell_e4310           ... OK
                : x86_64-epyc_7451            ... FAILED (lscpu/lscpu-x86_64-epyc_7451)
           ... FAILED (1 from 13 sub-tests)


What is the preferred way to get details of what made that test failing ?

**Comment by ErwanAliasr1** [comment]
I wasn't aware of the expected directory.
I made PR #759 to provide the EPYC case. Could be useful for this issue.

**Comment by karelzak** [comment]
There are expected/ output/ and diff/ directories.

**Comment by karelzak** [comment]
OK, I did some improvement to the code and now:
```
./lscpu  --sysroot tests/output/lscpu/dumps/x86_64-epyc_7451/ 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       48 bits physical, 48 bits virtual
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        8
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD EPYC 7451 24-Core Processor
Stepping:            2
CPU MHz:             2894.214
CPU max MHz:         2300.0000
CPU min MHz:         1200.0000
BogoMIPS:            4590.83
Virtualization:      AMD-V
L1d cache per core:  32 KiB
L1d cache:           1.5 MiB
L1i cache per core:  64 KiB
L1i cache:           3 MiB
L2 cache per core:   512 KiB
L2 cache:            24 MiB
L3 cache per core:   8 MiB
L3 cache:            128 MiB
```
Note that in your previous example (suggestion) it seems you have counted cache size for one socket only. For lsblk -e it's obvious there is 96 cpus (2 threads per core, 2 sockets, 24 cores per socket), L1, L2 are per core, L3 is always shared between three cores. So, the result is 

- L1d cache:          1.5 MiB
- L1i cache:           3 MiB
- L2 cache:            24 MiB
- L3 cache:            128 MiB

Is it correct?

**Comment by ErwanAliasr1** [comment]
Sorry for the lag. I was at OCP Summit.
The reported information is correct therefore the output still confuses me a little.
As we discussed, when "per core" is not defined, we display the amount of cache, but system wise.
Shouldn't we have it also reported per socket ? i.e Core(s) are reported per socket.

Note also that BogoMips are also meant per socket while its not explicit and then misleading since all non "per something" are system wise metrics.

**Comment by karelzak** [comment]
Frankly, maybe the best will be to report complete sum (all core and all sockets) as one number and do not report "per something" in the default summary. I think it was your original suggestion :-)

The CPU topology maybe be pretty complicated in some cases and I've doubts it makes sense to follow the topology for the cache reporting.

Maybe later we can add extra option --list-caches to report size of the individual cache and another details from /sys, something like:
```
NAME SIZE  ITEM-SIZE   TYPE          Ways
L3   126M         8M   Data             8
L2    22M       512K   Instruction      4

```
For now it would be enough to report the sum of the sizes only. Comments?

**Comment by ErwanAliasr1** [comment]
Yeah that would avoid the confusion especially since EPYC is providing more complex NUMA architectures.
That said, I'm still split with global reporting.
This kind of information is useful to optimize applications or understand the processor topology.
Imagine the reporting on a  2 or 4-way system, it would be difficult for one to estimate the capabilities of a single processor.
When you see the incoming ROME platform will provide up to 64 cores/128 threads, extracting the right information per CPU will be non-trivial even if not difficult.

**Comment by karelzak** [comment]
Caches output implemented:
```
./lscpu  --caches --sysroot tests/output/lscpu/dumps/x86_64-epyc_7451/
NAME ONE-SIZE ALL-SIZE WAYS TYPE        LEVEL
L1d       32K     1.5M    8 Data            1
L1i       64K       3M    4 Instruction     1
L2       512K      24M    8 Unified         2
L3         8M     128M   16 Unified         3
```
I'll also add some more details like coherency_line_size, number_of_sets, physical_line_partition later.

**Comment by ErwanAliasr1** [comment]
That's nice to split the cache reporting.
What is the final reporting of caches looks like from lscpu itself ?

**Comment by karelzak** [comment]
```
./lscpu   --sysroot tests/output/lscpu/dumps/x86_64-epyc_7451/
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       48 bits physical, 48 bits virtual
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        8
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD EPYC 7451 24-Core Processor
Stepping:            2
Frequency boost:     enabled
CPU MHz:             2894.214
CPU max MHz:         2300.0000
CPU min MHz:         1200.0000
BogoMIPS:            4590.83
Virtualization:      AMD-V
L1d cache:           1.5 MiB
L1i cache:           3 MiB
L2 cache:            24 MiB
L3 cache:            128 MiB
NUMA node0 CPU(s):   0-5,48-53
NUMA node1 CPU(s):   6-11,54-59
NUMA node2 CPU(s):   12-17,60-65
NUMA node3 CPU(s):   18-23,66-71
NUMA node4 CPU(s):   24-29,72-77
NUMA node5 CPU(s):   30-35,78-83
NUMA node6 CPU(s):   36-41,84-89
NUMA node7 CPU(s):   42-47,90-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
```

**Comment by ErwanAliasr1** [comment]
Nice !
Thanks for the patch.
I may have access to some ROME platform at some point and will provide the output of it to ensure everything is fine.

**Comment by karelzak** [comment]
It would be nice to have another /sys and /proc dump :-)

**Comment by ErwanAliasr1** [comment]
I will when I'll have some and once the product will be officially on the market. ;)

**Comment by yuyichao** [comment]
I think this change makes sense in general but it really just caused me a lot of trouble.... I didn't realize the `lscpu` on a ubuntu 18.04 and an arch linux machine are reporting different numbers and wondered for 2 days why writing to unshared L2 cache from each core causes memory access conflicts.

I'm not sure what was the backward compatibility requirement here but it'll be **really** nice if the summary output could be made less ambiguous (even adding a second line is fine). I'd also argue that the fix has already broken backward compatibility for any scripts that's not simply showing the values... I doubt I'd be the only one that got confused by this expecting the old output value....

**Comment by yuyichao** [comment]
> could be made less ambiguous

I'd say even changing the word to make it clear it's "total" size would have been immensely helpful...
