### ISSUE TITLE
taskset : process launch with a specified affinity in RHEL7.4 fails

### ISSUE THREAD

**Issue by rajubi1981** [karelzak/util-linux#665]
Hello,

As per the RHEL7 and taskset manual page if we try to launch with a specific affinity it does not works.
Shown as below:
Existing affinity mask and cores for sshd

[root@localhost ~]# cat /var/run/sshd.pid 
28945
[root@localhost ~]# taskset -p 28945
pid 28945's current affinity mask: fc
[root@localhost ~]# taskset -pc 28945
pid 28945's current affinity list: 2-7

Now suppose I want to run it on core, 1-3
[root@localhost ~]# taskset -c 1,3 service sshd restart
Redirecting to /bin/systemctl restart sshd.service

[root@localhost ~]# cat /var/run/sshd.pid 
29998
[root@localhost ~]# taskset -pc 29998
pid 29998's current affinity list: 2-7

[root@localhost ~]# taskset -p 29998
pid 29998's current affinity mask: fc

Same if we try through mask
[root@localhost ~]# taskset fa service sshd restart
Redirecting to /bin/systemctl restart sshd.service
[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]# cat /var/run/sshd.pid 
30572
[root@localhost ~]# taskset -pc 30572
pid 30572's current affinity list: 2-7
[root@localhost ~]# taskset -p 30572
pid 30572's current affinity mask: fc
[root@localhost ~]# 

RPM used are:
util-linux-2.23.2-52.el7.x86_64 [This is latest RPM as per RHEL RPM repo]

[root@localhost ~]# rpm -qi util-linux
Name        : util-linux
Version     : 2.23.2
Release     : 52.el7
Architecture: x86_64
Install Date: Thursday 19 July 2018 07:19:24 PM IST
Group       : System Environment/Base
Size        : 8642769
License     : GPLv2 and GPLv2+ and LGPLv2+ and BSD with advertising and Public Domain
Signature   : RSA/SHA256, Friday 02 February 2018 08:15:43 PM IST, Key ID 199e2f91fd431d51
Source RPM  : util-linux-2.23.2-52.el7.src.rpm
Build Date  : Friday 02 February 2018 07:28:56 PM IST
Build Host  : x86-034.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : http://en.wikipedia.org/wiki/Util-linux
Summary     : A collection of basic system utilities
Description :
The util-linux package contains a large variety of low-level system
utilities that are necessary for a Linux system to function. Among
others, Util-linux contains the fdisk configuration tool and the login
program.

[root@localhost ~]# uname -a
Linux localhost 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Can you please tell me has any option changes.
Am I doing anything wrong or is there any issue with taskset command in RHEL7.4.

**Comment by rajubi1981** [comment]
[root@UseMe1234 ~]# taskset -p 44 service sshd restart
taskset: invalid PID argument: 'restart'

**Comment by rajubi1981** [comment]
Taskset with systemd does not works. Need help

**Comment by karelzak** [comment]
systemd manages the affinity for you. See "systemd.exec" and  CPUAffinity= option. All you need is to add this option to the .service file for the sshd.service.
