### ISSUE TITLE
Documentation for building

### ISSUE THREAD

**Issue by eldiener** [karelzak/util-linux#666]
Is it really asking too much that there by at least one file in the repository which explains how to build
util-linux and/or how to build only certain portions of util-linux if that is possible ? I probably want to use only libblkid and libfdisk. I assume ./autogen.sh, ./configure, and make, but how hard is it to explain the build process and its options ?

**Comment by karelzak** [comment]
https://github.com/karelzak/util-linux/blob/master/Documentation/howto-compilation.txt
```
$ ./configure --help
...
  --disable-all-programs  disable everything, might be overridden by  --enable-<name>
```
it means: 
```
$ ./configure --disable-all-programs --enable-libblkid --enable-libfdisk --enable-libuuid
```

I'll add note about --disable-all-programs to the howton
