### ISSUE TITLE
fdisk: Use of uninitialized variable when no partitions exist

### ISSUE THREAD

**Issue by fuzzykiller** [karelzak/util-linux#667]
When trying to delete partitions but none exist, the `n` variable in `generic_menu_cb` remains uninitialized, resulting in strange numbers displaying. It’s not harmful, just confusing for users.

https://github.com/karelzak/util-linux/blob/d29b7ced3b263ac9eda8a37703be0153ad67e882/disk-utils/fdisk-menu.c#L656

There should probably be another branch that skips the remainder of `case 'd'`.

Repro:
```
# truncate -s100M test.img
# fdisk test.img

Welcome to fdisk (util-linux 2.32).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x827e25e9.

Command (m for help): d
No partition is defined yet!
Could not delete partition 93840461057817
```

**Comment by karelzak** [comment]
Thanks!
