### ISSUE TITLE
column: synopsis implies that filenames are required when they aren't. 

### ISSUE THREAD

**Issue by johnmwu** [karelzak/util-linux#669]
The SYNOPSIS section of `column`'s manpage reads:

**column** [options] file...

I believe that it should read 

**column** [options] [file]...

As reading from STDIN is supported, meaning that specifying a file is not necessary. In other words, 

`ps -f | column -s' ' -c10` works perfectly fine. 

EDIT: I'm using an old version of `column`. Sorry about that.

**Comment by karelzak** [comment]
Yes, already fixed by commit c927a0b9e715eb975035697c67bcea26c3dd44b2.
