### ISSUE TITLE
fstrim: add a mode that actually follows mount -a behavior

### ISSUE THREAD

**Issue by pkern** [karelzak/util-linux#673]
In [Debian bug #889668](https://bugs.debian.org/889668) the question of enabling fstrim by default on Debian came up. It looks like the intention of fstrim's `-a` flag was to be sort of equivalent to `mount -a`. Unfortunately the current behavior is to crawl `/proc/self/mountinfo` instead of `/etc/fstab` for mounts and then trimming all of them. This seems to be undesirable if removable media are attached or certain file systems have been mounted somewhat temporarily. `fstrim -a` seems to be designed as a background action anyway so the current behavior of a weekly timer stomping over your currently mounted disk is a little surprising. Would it be possible to add another mode (or fix the existing one) to read from `/etc/fstab` instead? That'd seem to be safer to enable by default.

**Comment by karelzak** [comment]
Good point. 
I think we can add -A to fstrim all mounted *and* specified within /etc/fstab.

**Comment by pkern** [comment]
To clarify: I think you meant to say all filesystems specified within 
`/etc/fstab` that are mounted. Yes, that'd be splendid. :)

**Comment by karelzak** [comment]
The question is what to do with fstrim.service where we have -a|--all. Keep it unchanged or update to -A?

Note that on systemd based systems you do not have to specify all in /etc/fstab -- it's unusual, but you can use mount units too (aka systemd.mount(5))

**Comment by pkern** [comment]
Thank you very much, Karel, for the swift implementation of this feature!

You are right that mount units make this slightly more difficult to get right. My feeling is that the default should apply to static configuration, so `-a` → `-A` in the service. And I also feel that querying systemd is sort of out of scope for this. I.e. to model this correctly maybe there'd need to be an `fstrim@.timer` tied to the `.mount` units? Generators can't inspect the current state and respond to it either, though, as far as I know.

**Comment by lucab** [comment]
We (@coreos) indeed hit the fstab-less case, I opened https://github.com/karelzak/util-linux/pull/1016 with a quick fix to at least avoid noisy errors.
