### ISSUE TITLE
Add model and serial to fdisk

### ISSUE THREAD

**Issue by srussel** [karelzak/util-linux#682]
It would be helpful if fdisk printed the disk model and serial, either at startup or included in the print command output. This would help to ensure I am working on the correct disk.

**Comment by karelzak** [comment]
Good idea. Implemented.
```
# fdisk -l /dev/sda
Disk /dev/sda: 223.6 GiB, 240057409536 bytes, 468862128 sectors
Disk model: KINGSTON SH103S3
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: E471810B-5954-48E6-B4F0-5D369ADCC514

...
```

**Comment by karelzak** [comment]
That's not so easy. lablk(8) reads the number from udev db, because it's sometimes pretty tricky and udev has scsi_id binary for this purpose. I'm not sure this feature is important enough to link with libudev.
