### ISSUE TITLE
uuidgen, libuuid: UUID v5 not compatible with RFC 4122

### ISSUE THREAD

**Issue by alieh-rymasheuski** [karelzak/util-linux#683]
```bash
$ uuidgen --namespace 00000000-0000-0000-0000-000000000000 --name 'foo' --sha1
aa752cea-8222-5bc8-8cd9-555b090c0ccb

$ echo -n '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0foo' | openssl sha1
(stdin)= aa752cea8222cbc8ecd9555b090c0ccb813cfca4

$ python -c "import uuid ; print(uuid.uuid5(uuid.UUID(int=0), 'foo'))"
aa752cea-8222-5bc8-acd9-555b090c0ccb
```

(note `8cd9` in uuidgen vs `acd9` in Python, and `ecd9` in the hash)

For a variant mark that takes two bits (http://pubs.opengroup.org/onlinepubs/9629399/apdxa.htm#tagtcjh_36 DCE variant, "most significant bits (bits 6 and 7) of the clock_seq_hi_and_reserved" from https://tools.ietf.org/html/rfc4122#section-4.3) uuidgen sets bit 5 to zero too: https://github.com/karelzak/util-linux/blob/917f53cf13c36d32c175f80f2074576595830573/libuuid/src/gen_uuid.c#L608

Line 607 sets 3 MSBs to zero, no matter the size of variant.
Line 608 sets 2 MSBs to 0x4, or 3 MSBs to 0x6 or 0x7.

**Comment by karelzak** [comment]
@pprindeville any comment? :-)

**Comment by karelzak** [comment]
Fixed. Thanks for your report!
