### ISSUE TITLE
`script` hangs when killing the child process with ^C

### ISSUE THREAD

**Issue by mortie** [karelzak/util-linux#686]
Running `script --command 'sleep 5'`, and hitting ctrl+c before the sleep command exits, causes script to hang indefinitely.

I've confirmed that this happens with a fresh build from this repository (`script from util-linux 2.32.371-350f`) as well as the version from the Arch repositories (`script from util-linux 2.32.1`). It also happens an Ubuntu Mate 18.04 VM (`script from util-linux 2.31.1`). It does not happen in an Ubuntu 16.04 VM (`script from util-linux 2.27.1`).

I did a git bisect, and this commit introduced the issue: https://github.com/karelzak/util-linux/commit/2e7a92270114cc652ea090251a374e917adb7a72

**Comment by karelzak** [comment]
Oh, you have also provided patches. I had read only the issue by email and fixed it by another patch. Sorry.

Thanks for you report!
