### ISSUE TITLE
lsblk: prefer udev instead of sysfs for device model

### ISSUE THREAD

**Issue by chessman** [karelzak/util-linux#690]
sysfs device model is truncated to 16 characters:
```
> cat /sys/block/sda/device/model 
Crucial_CT128MX1
> udevadm info --query=property /dev/sda | grep MODEL=
ID_MODEL=Crucial_CT128MX100SSD1
```
sysfs uses INQUARY response which has the 16 characters limitation and udev uses something else.

Is it possible to use udev instead of sysfs?

**Comment by karelzak** [comment]
Good catch. Implemented. Thanks for your report!
