### ISSUE TITLE
umount bash completion needs full path, unlike mount.

### ISSUE THREAD

**Issue by zqqw** [karelzak/util-linux#703]
Assuming you are in your homedir, if you do e.g. mount /dev/sdxx Doc TAB it works, but for umount you need to do umount /ho TAB (presuming that was the only thing mounted in /home) as the bash completion for umount only works with full paths from root, ~/Doc or Doc won't work.
I get this in both Artix linux and AntiX Sid.

**Comment by karelzak** [comment]
@kerolasa seems we need a patch ;-)

**Comment by karelzak** [comment]
Fixed. Thanks for tour report.
