### ISSUE TITLE
unshare -m in a chroot: cannot change root filesystem propagation: Invalid argument

### ISSUE THREAD

**Issue by mgorny** [karelzak/util-linux#718]
How to reproduce:
1. Prepare a small chroot in a regular directory,
2. `chroot` into it,
3. `unshare -m` fails:
    ```
    # unshare -m 
    unshare: cannot change root filesystem propagation: Invalid argument
    ```

FWIU the issue is that unshare is trying the equivalent of `mount --make-rprivate /` which apparently doesn't work if `/` is not a mountpoint. To be honest, I don't really have any idea how to solve this.

**Comment by zmedico** [comment]
If the caller knows that the mount propagation flags do not need to be changed, then this works:
```
unshare -m --propagation unchanged
```
Based on `/proc/[pid]/mountinfo` documentation in the proc(5) manpage, and empirical analysis of /proc/self/mountinfo in various states, this command might be used as a heuristic to detect a shared / or /proc mount which would indicate that the mount propagation flags need to be changed:
```
grep -qE '^[^[:space:]]+ [^[:space:]]+ [^[:space:]]+ [^[:space:]]+ (/|/proc) [^[:space:]]+ ([^[:space:]]+:[^[:space:]]+ )*(shared:[^[:space:]]+ )' /proc/self/mountinfo
```

**Comment by mgorny** [comment]
Well, I'm more concerned about the case when propagation is shared, and we need to create a new private mount inside the chroot.

**Comment by karelzak** [comment]
It seems that for example 
```
 $ findmnt -o+PROPAGATION
```
is a better way how to get the current propagation flag that your grep monster :-)

And yes, "--propagation unchanged" has been implemented to avoid unnecessary propagation changes. 

If do not have "/" as mountpoint than you can create it by "mount --bind /foo /foo" before you call chroot; and then you can change the propagation of the /foo although the directory is not originally a mountpoint.

I guess this should be enough.

**Comment by karelzak** [comment]
For example:
```
# mount --bind /mnt/test /mnt/test

# findmnt -o+PROPAGATION /mnt/test
TARGET    SOURCE               FSTYPE OPTIONS     PROPAGATION
/mnt/test /dev/sda4[/mnt/test] ext4   rw,relatime shared

# mount --make-rprivate /mnt/test

# findmnt -o+PROPAGATION /mnt/test
TARGET    SOURCE               FSTYPE OPTIONS     PROPAGATION
/mnt/test /dev/sda4[/mnt/test] ext4   rw,relatime private
```
now /mnt/test is 'private' mountpoint although it was originally regular directory only.
