### ISSUE TITLE
fstrim -A: ignores root filesystem

### ISSUE THREAD

**Issue by grawity** [karelzak/util-linux#719]
Some distributions such as Arch Linux do not always put the root filesystem in /etc/fstab (as the entry would be completely redundant with root= and rootflags= in the kernel command line).

Due to #673, fstrim.service now strictly follows fstab – this means that the root filesystem on such systems just silently stopped being trimmed by default.

Because the root filesystem is always a fixed mount, IMHO it should be always trimmed by `fstrim -A`, regardless of having an fstab entry. This exception would be independent of what init system is used.

**Comment by karelzak** [comment]
Good point. Fixed.
