### ISSUE TITLE
sfdisk - "--dump" reports silly "first-lba" and "last-lba" values and uses silly names

### ISSUE THREAD

**Issue by thx1111** [karelzak/util-linux#720]
Arch Linux
util-linux 2.33-2

sfdisk(8) says:
The optional header lines specify generic information that apply to the partition table.  The header-line format is:
...
first-lba
&nbsp;&nbsp;&nbsp;&nbsp;Specify the first usable sector for GPT partitions.
last-lba
&nbsp;&nbsp;&nbsp;&nbsp;Specify the last usable sector for GPT partitions.

Here is an example of sfdisk output for a partition table aligned on 4kiB boundaries:

$ sfdisk -d /dev/sdc
label: gpt
label-id: 69871B67-C7F7-4938-A755-8DCE2D0FE0F4
device: /dev/sdc
unit: sectors
first-lba: 34
last-lba: 234441614

/dev/sdc1 : start=          40, size=        2008, type=21686148-6449-6E6F-744E-656564454649, uuid=9B939A41-68EF-4AB4-9CBE-3992B5E7839A, name="BIOS Boot Partition"
/dev/sdc2 : start=        2048, size=      524288, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=4CCAFE34-BED5-4E0C-ADB6-DA7C835437A4, name="UEFI System Partition"
/dev/sdc3 : start=      526336, size=    16777216, type=0657FD6D-A4AB-43C4-84E5-0933C84B4F4F, uuid=5A61F3E9-FF95-4FA9-AB72-990D14FBBC31, name="Linux Swap Partition"
/dev/sdc4 : start=    17303552, size=   217138056, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=2FDEF117-0EE1-48C1-AFA4-DA2D82A12F16, name="One Big Partition"

Obviously, "the first usable sector for GPT partitions" is LBA sector 40, not sector 34, as is being reported.  This is easy enough to identify as the first allocated sector after the Primary GPT is sector 40, not sector 34.  As I understand, the UEFI specification stipulates that a minimum of 16,384 bytes, regardless of sector size, be allocated for the Partition Entry Array.  That is "minimum", not "equal to".  Nothing says that the Partition Entry Array cannot be larger than 16,384 bytes.

sfdisk seems to have "hard coded" this 34 sector value - which is wrong.

And then, since LBA sectors are numbered starting with zero, "the last usable sector for GPT partitions" is equal to the total number of LBA sectors on the block device minus one, minus the Secondary GPT, without the sector for the Protective MBR.  In the example, the "last-lba" given is simply the actual total number of sectors, as reported by, for instance, hdparm, "LBAsects=234441648", minus one, minus the *minimum* 33 sector Secondary GPT.  The actual last usable LBA sector address for GPT partitions would be the total number of LBA sectors on the device, minus one, minus the *actual* Primary GPT size, which, in the example, is the total number of LBA sectors minus 40 sectors.

sfdisk "last-lba" seems to again use some "hard coded" 33 sector value for the Secondary GPT - which is wrong.

BTW, it would be nice if the terminology used was something more like "firstLBA" and "lastLBA", or "first_lba" and "last_lba", so that the reader does not have to stop, and think, if what has been reported by sfdisk is actually "<first_LBA> minus <total_number_of_LBA_sectors>" and "<last_LBA> minus <total_number_of_LBA_sectors>".  Of course, the "a-b" interpretation makes no sense, but using the "dash" or "minus_sign" is annoying, since sfdisk is all about reporting numbers and counts to someone who has probably just been thinking intently in terms of "a+b" and "a-b".  Just be polite, and use, like, "a_b" or "aB" or "a_B", so that the name does not look like a mathematical expression.

**Comment by karelzak** [comment]
The FirstUsableLBA and LastUsableLBA define area where is possible address partitions. These fields are "hardcoded" within GPT header. The first partition start does not have to match the FirstUsableLBA as we align partitions to 1MiB offset (2048 sectors).

The size of Partition Entry Array is "hardcoded" in the header independently on FirstUsableLBA (but of course all the settings have to make sense together). If you enlarge the Array then FirstUsableLBA will move. The *default* size of the Array is based on the default number of supported partitions (128 in libfdisk).

For example fdisk provides in expert menu a way to enlarge the size of the Partition Entry Array.

It's really not (s)fdisk specific. Try GNU Parted:
```
 # modprobe scsi_debug dev_size_mb=100
 # parted /dev/sdc "mklabel gpt"

 # sfdisk --dump /dev/sdc
 label: gpt
 label-id: 58599E19-E3DD-4BA2-AD1E-9868B3ADA5E6
 device: /dev/sdc
 unit: sectors
 first-lba: 34
 last-lba: 204766
```
You can change it:
```
# fdisk  /dev/sdc
Command (m for help): x
Expert command (m for help): l
New maximum entries (1-4294967295, default 128): 256

Partition table length changed from 128 to 256.
...
sfdisk --dump /dev/sdc
label: gpt
label-id: 58599E19-E3DD-4BA2-AD1E-9868B3ADA5E6
device: /dev/sdc
unit: sectors
first-lba: 66
last-lba: 204734
table-length: 256
```

**Comment by Earnestly** [comment]
Just to note, `sfdisk` is now showing `first-lba` as `2048` for me despite the `last-lba` still being `size / sectorsize - 34`.

**Comment by karelzak** [comment]
Many years ago, "we" (people around block devices and partition tables) made a conclusion that standardizing 1MiB as first-lba (for MBR and GPT) is a good idea due to compatibility with all types of block devices (with regard to sector sizes). 

> Can lsblk show the table size?

What do you mean by the size -- the usable area (number of sectors) between the first and last LBA, or the number of possible partitions? 

The information provided by lsblk about the partition table goes from udev DB, and the source is libblkid. We can add more information to udev DB if necessary. For now, blkid is pretty minimalistic about the PT:
```
# blkid -o udev -p /dev/sda
ID_PART_TABLE_UUID=e471810b-5954-48e6-b4f0-5d369adcc514
ID_PART_TABLE_TYPE=gpt
```

**Comment by thx1111** [comment]
Following-up on the original issue, in retrospect, this was a combination of my ignorance and shortcomings with the various partitioning tools.

> You can change it:

"*It*?  *It* what?  What *it*?"  I had to go back an re-read the GPT header format, for instance, at https://en.wikipedia.org/wiki/GUID_Partition_Table , trying to make sense of this.  But, there it is:
```
80 (0x50)    4 bytes    Number of partition entries in array
```
When correctly set, everything works fine.

And also, incidentally, another important item to recognize:
```
84 (0x54)    4 bytes    Size of a single partition entry (usually 80h or 128)
```
While there might be a tendency to naively assume that this is a fixed number, it is *not* a fixed number.

I find `cgdisk` convenient for creating a GPT header, but had not realized that `cgdisk` does not fully set-up the Partition table header, LBA 1, and does not seem to offer any way, by itself, to do this!  `cgdisk` neither asks the user, nor offers the user the opportunity, to set "Number of partition entries in array".

And then, in practice, for the most part, the kernel will also happily ignore a misconfigured "Number of partition entries" - probably up until trying to actually use those last entries in the array.  I haven't checked.  And, I don't know that any of the other partitioning tools, other than `fdsik`, support changing - or even reporting - the "Number of partition entries".

So, while the user might simply be advised to "RTFM", I would also suggest that this failure to fully configure, let alone report, the *complete* GPT header is a fault with the many disk partitioning utilities.
