### ISSUE TITLE
The fix for escape chars breaks /etc/issue output

### ISSUE THREAD

**Issue by bcv** [karelzak/util-linux#733]
My /etc/issue which had an ascii art of tux is now clobbered. 
This commit

https://github.com/karelzak/util-linux/commit/f8ee3af9fabc4369c36fdbd706a17deb246a751c#diff-d7efd2b3dbb10e54185f001dc21d43db

seems to have changed behaviour

$ cat /etc/issue
    .--.
   |o_o |
   |:_/ |
  //    |
 (|     | )
/'\_   _/`\
\___)=(___/    

and what I get on the agetty prompt is 
login: _
_
    .--.
   |o_o |
   |:_/ |
  //    |
 (|     | )
/'   _/`__)=(___/    

All \ is interpreted now. No matter how many times I put a \ (even if escaped as \\\) it never prints '\' anymore.

To check the /etc/issue file tux logo pl. use 
$ cowsay -f tux  ' '

**Comment by karelzak** [comment]
I'm not able to reproduce the problem. For example:
```
$  cowsay -f tux ' ' | sed 's|\\|\\\\|g' > /etc/issue
```
works for me.

**Comment by boxcars-at-gmx-dot-net** [comment]
FWIW, I experienced this problem with util-linux 2.33 but I do not with util-linux 2.33.1.

**Comment by bcv** [comment]
works now with 2.33.1-0.1 (debian buster)
