### ISSUE TITLE
fstrim --all should skip read-only filesystems/block devices

### ISSUE THREAD

**Issue by dboehmer** [karelzak/util-linux#738]
I have a cronjob running inside a KVM virtual machine that executes `fstrim --all` regularly. Since I've attached an older disk image as read-only SCSI disk 2 and mounted it inside the VM in a temporary path `fstrim` exits with code 64 and prints the following error message:

    fstrim: /path/to/my_mountpoint: FITRIM ioctl failed: Remote I/O error

The ioctl error might occur in a layer somewhere down the road but I think `fstrim` should skip this device anyway because of any of these reasons:

1. the mountpoint is mounted with the `ro` option
1. `/sys/class/block/sdb2/ro` tells the block device for this partition is read-only
1. `/sys/class/block/sdb/ro` and `/sys/block/sdb/ro` tell the block device for the whole disk is read-only&mdash;although I don't know whether fstrim can have any understanding of partition and disk devices

I think the checks 1 and 2 should be deterministic, clear and easy to implement. But I don't know enough Linux programming in C to provide a PR.

The issues occurs on Debian's current stable release Stretch. I've also tested the behavior with current HEAD revision 86f42e5a2a9d8a483ad0ca85fdf090172fb4d385.

**Comment by karelzak** [comment]
Fixed. Thanks for your report.

**Comment by karelzak** [comment]
Note that the implementation checks for read-only device, not for read-only filesystem. It seems call FITRIM ioctl for read-only filesystem is no-op, but it does not return an error. 
```
# mount -o remount,ro /boot
# strace -e ioctl ./fstrim /boot
...
ioctl(3, FITRIM, {start=0, len=0xffffffffffffffff, minlen=0}) = 0
```

**Comment by dboehmer** [comment]
Hmm, is it safe to rely on this behavior? I just imagine this ever changes and then having a system with `fstrim --all` run by cron and mounting a block device read-only would make `fstrim` manipulate the device&mdash;unexpected and possibly harmful.

**Comment by karelzak** [comment]
It's kernel business. If possible we do not implement any polices in userspace. 

The trim ioctl is a filesystem driven operation, I guess filesystem driver is aware of the filesystem mount mode :-)

**Comment by dboehmer** [comment]
Thank you for this super-fast fix and your explanation!
