### ISSUE TITLE
whereis lists /usr/lib subdirectories ahead of /(s)bin binaries

### ISSUE THREAD

**Issue by ucko** [karelzak/util-linux#741]
On systems where `/(s)bin` and `/usr/(s)bin` are distinct, `whereis -b` lists subdirectories of `/usr/lib` ahead of executables in `/bin` or `/sbin`.  For instance:
```
$ whereis -b systemd
systemd: /usr/lib/systemd /bin/systemd /etc/systemd /lib/systemd /usr/share/systemd
```
I acknowledge that (as in #292) `which` may well be a more appropriate choice of tool here, and that it can even sometimes make sense to mention directories.  All the same, I'd suggest reordering `bindirs` so that directories dedicated to executables appear ahead of directories that primarily contain libraries, headers, and/or data.

Thanks for your consideration!

**Comment by karelzak** [comment]
OK, I have reordered the paths, so now:

        "/usr/bin",
        "/usr/sbin",
        "/bin",
        "/sbin",
#if defined(MULTIARCHTRIPLET)
        "/lib/" MULTIARCHTRIPLET,
        "/usr/lib/" MULTIARCHTRIPLET,
        "/usr/local/lib/" MULTIARCHTRIPLET,
#endif
        "/usr/lib",
        "/usr/lib64",
        "/etc",
        "/usr/etc",
        "/lib",
        "/lib64",

**Comment by ucko** [comment]
Great, thanks!
