### ISSUE TITLE
MS_NOEXEC flag, rather than an -o noexec option

### ISSUE THREAD

**Issue by xnox** [karelzak/util-linux#746]
I would like to use `mount` utility to mount `/run` with `MS_NOEXEC` flag, rather than an `-o noexec` option.

However, I don't see that, that is possible at the moment.

Similarly, I'd like `MS_EXEC|MS_NOEXEC` flags be supported for remounts and bind mounts.

**Comment by karelzak** [comment]
Frankly, I'm not sure if I understand your request.
```
  mount /dev/foo /run -o noexec
```
is internally converted to MS_NOEXEC for mount(2) syscall.

**Comment by xnox** [comment]
@karelzak horum..... let me check which `mount` implementation i'm using, maybe it's not using util-linux then!
