### ISSUE TITLE
lsblk serial not corect for scsi devices

### ISSUE THREAD

**Issue by svenwiltink** [karelzak/util-linux#750]
lsblk outputs the wwn for scsi devices instead of the serial. The bug is caused by libudev outputting the wrong value, but it also does output the correct value in a different field. See the post I made on the mailing list for more details:
https://lists.freedesktop.org/archives/systemd-devel/2019-February/042143.html

I am not sure if libudev or lsblk should fix it, but I wanted to post it here as well to keep you informed as well.

-Sven

**Comment by svenwiltink** [comment]
I was asked to create a bugreport at the distribution bugtracker: https://bugs.launchpad.net/ubuntu/+source/udev/+bug/1815064

**Comment by karelzak** [comment]
Fixed. Thanks.
