### ISSUE TITLE
blkid return 2 for new lvm volumes

### ISSUE THREAD

**Issue by aplanas** [karelzak/util-linux#764]
After creating a lv in a lvm system, but before it is formatted, a blkid to this volume returns 2 (BLKID_EXIT_NOTFOUND).

I follow the code path until chain probe in blkid_do_safeprobe. For this case superblocks is enabled and return 1 (not result), topology is disabled, and partitions is enabled but return again 1.

I would expect that for a non-partitioned LVM, this device gets found somehow. I am not sure if the problem is a missing probe or the superblocks probe that can return 0 for new LVMs.

**Comment by karelzak** [comment]
It would be nice to have step by step procedure to reproduce the problem. You can also use

   LIBBLKID_DEBUG=all blkid /dev/something

to provide more details.

**Comment by aplanas** [comment]
@karelzak sure!

The output of different commands are here, including some information about the environment that can help to reproduce the issue:

http://paste.opensuse.org/view//73526051

**Comment by aplanas** [comment]
@karelzak is this helpful, or do I need to provide more information?

BTW: I tested also the version from git, I compiled only blkid and using LD_LIBRARY_PATH I make sure to execute the correct new libraries. The git version also return 2 for new LVM volumes (not yet formatted)

**Comment by karelzak** [comment]
From  the output it's obvious that libblkid sees nothing on the device ... perfectly wiped device ;-)

What do you mean with "not yet formatted"?
```
# blkid -p /dev/sdc
..nothing

# pvcreate /dev/sdc
  Physical volume "/dev/sdc" successfully created.

# blkid -p /dev/sdc
/dev/sdc: UUID="QE0oVi-9atg-9DQP-SriT-RSjc-5VSb-hmfsu0" VERSION="LVM2 001" TYPE="LVM2_member" USAGE="raid"
```

**Comment by aplanas** [comment]
Well, maybe I am wrong, but this can reproduce what I think that is the issue:

```bash
# First create the partitions
# fdisk /dev/sd[abc]

# Each partition is unformatted, but blkid found the device
# blkid /dev/sda1; echo $?
/dev/sda1 PARTUUID="8b75db83-01"
0

# If I write a non-existent partition return 2 as expected
# blkid /dev/sda2; echo $?
2

# Create now a physical volume
# pvcreate /dev/sd[abc]1

# ... volume group
# vgcreate vg-01 /dev/sda1 /dev/sdb1 /dev/sdc1

# ... and create three random logical volumes, each of 1G
# lvcreate -L 1G -n lv-01 vg-01
# lvcreate -L 1G -n lv-02 vg-01
# lvcreate -L 1G -n lv-03 vg-01

# We can see that each logical volume is now a block device
# lsblk
NAME              MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
fd0                 2:0    1     4K  0 disk 
loop0               7:0    0 247.8M  1 loop /run/initramfs/squashfs_container
loop1               7:1    0   1.9G  1 loop /run/rootfsbase
sda                 8:0    0    24G  0 disk 
└─sda1              8:1    0    24G  0 part 
  ├─vg--01-lv--01 254:0    0     1G  0 lvm  
  ├─vg--01-lv--02 254:1    0     1G  0 lvm  
  └─vg--01-lv--03 254:2    0     1G  0 lvm  
sdb                 8:16   0    24G  0 disk 
└─sdb1              8:17   0    24G  0 part 
sdc                 8:32   0    24G  0 disk 
└─sdc1              8:33   0    24G  0 part 
sdd                 8:48   0     4G  0 disk 
sr0                11:0    1   334M  0 rom  /run/initramfs/live

# And the mapping is correct
# ls -la /dev/vg-01/
total 0
drwxr-xr-x  2 root root  100 Mar  7 16:53 .
drwxr-xr-x 19 root root 4240 Mar  7 16:54 ..
lrwxrwxrwx  1 root root    7 Mar  7 16:53 lv-01 -> ../dm-0
lrwxrwxrwx  1 root root    7 Mar  7 16:53 lv-02 -> ../dm-1
lrwxrwxrwx  1 root root    7 Mar  7 16:53 lv-03 -> ../dm-2

# ls -la /dev/mapper/
total 0
drwxr-xr-x  2 root root     120 Mar  7 16:53 .
drwxr-xr-x 19 root root    4240 Mar  7 16:56 ..
crw-------  1 root root 10, 236 Mar  7 16:39 control
lrwxrwxrwx  1 root root       7 Mar  7 16:53 vg--01-lv--01 -> ../dm-0
lrwxrwxrwx  1 root root       7 Mar  7 16:53 vg--01-lv--02 -> ../dm-1
lrwxrwxrwx  1 root root       7 Mar  7 16:53 vg--01-lv--03 -> ../dm-2

# ls -la /dev/dm-*
brw-rw---- 1 root disk 254, 0 Mar  7 16:58 /dev/dm-0
brw-rw---- 1 root disk 254, 1 Mar  7 16:53 /dev/dm-1
brw-rw---- 1 root disk 254, 2 Mar  7 16:53 /dev/dm-2

# But blkid return 2 (BLKID_EXIT_NOTFOUND) for each new device, and this is where
# I think that is an error
# blkid /dev/vg-01/lv-01; echo $?
2

# blkid -p /dev/dm-0; echo $?
2

# blkid -p /dev/mapper/vg--01-lv--01; echo $?
2

# Now I apply a file system format to the first logical volume
# mkfs.ext2 /dev/vg-01/lv-01 
mke2fs 1.44.5 (15-Dec-2018)
Discarding device blocks: done                            
Creating filesystem with 262144 4k blocks and 65536 inodes
Filesystem UUID: a4575d14-9183-481d-8662-be86a4979073
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376

Allocating group tables: done                            
Writing inode tables: done                            
Writing superblocks and filesystem accounting information: done

# And correctly blkid found it
# blkid /dev/vg-01/lv-01; echo $?
/dev/vg-01/lv-01: UUID="a4575d14-9183-481d-8662-be86a4979073" TYPE="ext2"
0
```

I see an inconsistent when I apply a `blkid` over `/dev/sda1` (print nothing in `sdout`, but returns 0), and `blkid` over `/dev/vg-01/lv-01` or any other alias (including the canonical name), and print nothing in `stdout`, but returns 2. More over when `lsblk` is already showing the block device.

**Comment by karelzak** [comment]
> # Each partition is unformatted, but blkid found the device
> # blkid /dev/sda1; echo $?
> /dev/sda1 PARTUUID="8b75db83-01"
> 0

This is correct and expected behaviour. In this case it returns partition UUID from partition table. You can (for example) use PARTUUID= in your fstab.

For low-level probing (-p) we have a new --no-part-details to disable these information
```
# blkid -p /dev/sdc1; echo $?
/dev/sdc1: PART_ENTRY_SCHEME="dos" PART_ENTRY_UUID="e21250a6-01" PART_ENTRY_TYPE="0x83" PART_ENTRY_NUMBER="1" PART_ENTRY_OFFSET="2048" PART_ENTRY_SIZE="202752" PART_ENTRY_DISK="8:32"
0

# blkid --no-part-details -p /dev/sdc1; echo $? 
2

> # If I write a non-existent partition return 2 as expected
> # blkid /dev/sda2; echo $?
> 2

Yes, the device does not exist.
...

> # But blkid return 2 (BLKID_EXIT_NOTFOUND) for each new device, and this is where
> # I think that is an error
> # blkid /dev/vg-01/lv-01; echo $?
> 2
> 
> # blkid -p /dev/dm-0; echo $?
> 2

because there is nothing libblkid can provide about the device -- the device is not a partition so PARTUUID= is also no available.

> I see an inconsistent when I apply a `blkid` over `/dev/sda1` (print nothing in `sdout`, but returns 0), and
> `blkid` over `/dev/vg-01/lv-01` or any other alias (including the canonical name), and print nothing in 
> `stdout`, but returns 2. More over when `lsblk` is already showing the block device.

It returns zero if it's possible to provide some (or specified) information, otherwise it returns 2.

If you don't like it than you can use "--no-part-details -p" in the next version (it's not released yet).

Frankly, the best is to use "lsblk /dev/sdc1 -n -o FSTYPE" -- it uses information from udev and it's more user-friendly.

**Comment by aplanas** [comment]
> ```
>  # But blkid return 2 (BLKID_EXIT_NOTFOUND) for each new device, and this is where
>  # I think that is an error
>  # blkid /dev/vg-01/lv-01; echo $?
>  2
>  
>  # blkid -p /dev/dm-0; echo $?
>  2
> ```
> 
> because there is nothing libblkid can provide about the device -- the device is not a partition so PARTUUID= is also no available.

I think that there is a missunderstanding, of course that no PARTUUID is avaiable, but returning 2 is a bug. The device exist. Is there. I am not complaining of not printing anything, but returning BLKID_EXIT_NOTFOUND for a present device looks a bug to me.

**Comment by karelzak** [comment]
What is your suggestion?

BLKID_EXIT_NOTFOUND means no token *or* no device found. There is no special exist code for found-nothing but device exists. Don't forget that blkid also translates tokens (UUID, etc.) to device names. The code is the same...

We cannot return 0 in this case -- it will break backward compatibility.

**Comment by aplanas** [comment]
> What is your suggestion?

Was indeed return 0, as in the /dev/sda1 case in the previous example.

> BLKID_EXIT_NOTFOUND means no token _or_ no device found. There is no special exist code for found-nothing but device exists. Don't forget that blkid also translates tokens (UUID, etc.) to device names. The code is the same...

I see ... Is the inconsistency with the /dev/sda1 case what makes me wonder here. In this case the PARTUUID is not found, but a 0 is returned, so means that the device is found. In the case of LVM also no PARTUUID is found, but returns 2. 

> We cannot return 0 in this case -- it will break backward compatibility.

Oh. And returning 2 in the /dev/sda1 case will also break backward compatibility? IMHO this is even worse.

**Comment by karelzak** [comment]
> > What is your suggestion?
> 
> Was indeed return 0, as in the /dev/sda1 case in the previous example.

Hmm... I probably lost in our discussions. I don't see example where it returns 0 and nothing is possible gather about sda1 (partition). I see at least PARTUUID=.

I think man blkid is pretty obvious about situation it returns 0:
```
If the specified device or device addressed by specified token (option --match-token) was found 
and it's possible to gather any information about the device, an exit  code  0  is   returned. 
Note the option --match-tag filters output tags, but it does not affect return code.
```
The blkid purpose is to gather device identifiers and content identification. It does not make sense return 0 (success) if we cannot found any identifier or content.

May be we can differentiate between "no information" and "no device" and return 2 for the first situation and 1 for the second, but definitely no zero (success).

I'll a little bit clean up RETURN CODE section in man page to make it more obvios.

**Comment by aplanas** [comment]
> > > What is your suggestion?
> > 
> > Was indeed return 0, as in the /dev/sda1 case in the previous example.
> 
> Hmm... I probably lost in our discussions. I don't see example where it returns 0 and nothing is possible gather about sda1 (partition). I see at least PARTUUID=.

You are absolutely right. PARTUUID is always printed for valid partitions, and for devices that do not have partition table, 2 is returned. That is consistent with the LVM behavior. I am still puzzled about this, as I was sure that was not the case in my local tests. I was wrong.

> I'll a little bit clean up RETURN CODE section in man page to make it more obvios.

Thanks for https://github.com/karelzak/util-linux/commit/5bf5752e28ffde28dea48abea48c720396bf88e4, this help me to understand that when there is no way to get any data for a valid block device, a return BLKID_EXIT_NOTFOUND is expected.

Thanks for your help!
