### ISSUE TITLE
fdisk/cfdisk/sfdisk doesn't display full size unit names

### ISSUE THREAD

**Issue by nl6720** [karelzak/util-linux#773]
_fdisk_, _cfdisk_ and _sfdisk_  use `K`, `M`, `G`, etc. for partition sizes both when printing the partition table and when viewing information about a specific partition. These units are ambiguous and can lead to confusion.
I think it would better if _fdisk_ displayed `KiB`, `MiB`, `GiB`, etc.

E.g., instead of 
```
Device     Boot   Start      End Sectors  Size Id Type
test.img1          2048     4021    1974  987K 83 Linux
test.img2          4096  2052095 2048000 1000M 83 Linux
test.img3       2052096 10440703 8388608    4G 83 Linux
```
```
         Device: test.img2
          Start: 4096
            End: 2052095
        Sectors: 2048000
      Cylinders: 128
           Size: 1000M
             Id: 83
           Type: Linux
    Start-C/H/S: 0/65/2
      End-C/H/S: 127/187/60
```
it would be shown as:
```
Device     Boot   Start      End Sectors  Size    Id Type
test.img1          2048     4021    1974  987 KiB 83 Linux
test.img2          4096  2052095 2048000 1000 MiB 83 Linux
test.img3       2052096 10440703 8388608    4 GiB 83 Linux
```
```
         Device: test.img2
          Start: 4096
            End: 2052095
        Sectors: 2048000
      Cylinders: 128
           Size: 1000 MiB
             Id: 83
           Type: Linux
    Start-C/H/S: 0/65/2
      End-C/H/S: 127/187/60
```

**Comment by karelzak** [comment]
We use everywhere in util-linux 2^N notation and I guess all modern Linux userspace utils use this way. 

The "iB" is not used to save space in outputs columns (the same as lsblk, etc.), but  you can see it the fdisk -l summary lines. 

Sorry, I don't think we want to change it.

**Comment by nl6720** [comment]
Of other tools, I know that [gdisk](https://www.rodsbooks.com/gdisk/) uses `*iB`.

I find it strange that the disk size in fdisk uses the full unit abbreviation while partitions get only one letter.
One would think that due to the difference in decimal and binary units, being precise about the used unit would be very important.
