### ISSUE TITLE
Taskset hangs with cpu-list' 0--1'

### ISSUE THREAD

**Issue by rien** [karelzak/util-linux#775]
## How to reproduce?
Run `taskset -c 0--1 true`, it will hang with 100% cpu usage.

## System information
Taskset 2.33.1, running on Void Linux (Linux 4.19.29)

**Comment by karelzak** [comment]
Thanks!

**Comment by karelzak** [comment]
Fixed by commit 65bcbf105bfc5f6510b8df8db09d9458f942c799.
