### ISSUE TITLE
Autologin on ttys doesn't work anymore

### ISSUE THREAD

**Issue by q2dg** [karelzak/util-linux#777]
Hello. I did long time ago a trick (which worked!) to enter automatically into a specific user session when pressing CTRL+ALT+FX (ttyX) without having to write its password. The trick (which is documented in https://wiki.archlinux.org/index.php/Getty#Automatic_login_to_virtual_console, for instance) is simply adding the option --autologin username to "agetty" binary invoked by the ExecStart line in /usr/lib/systemd/system/getty@.service file. But doing this currently, sometimes (!?) username is automatically catched but its password is asked anyway. If tried removing the -o "-p -- \\u" parameter from described line in agetty arguments because it's a "new kid on the block" but without luck.
I'm using util-linux 2.32 (shipped in Fedora 29).

I've reported this to systemd (see https://github.com/systemd/systemd/issues/12083) but they say it's a "login" binary's responsability.

Thanks.

**Comment by karelzak** [comment]
I'm not able to reproduce this problem.
```
# grep Exec /etc/systemd/system/getty@tty2.service
ExecStart=-/sbin/agetty --autologin kzak --noclear %I $TERM
```
works for me. I have also tried "--login-pause --autologin kzak" and it wotks too.

just:
```
cp /etc/systemd/system/getty@.service /etc/systemd/system/getty@tty2.service
vim /etc/systemd/system/getty@tty2.service
systemctl daemon-reload
systemctl enable getty@tty2.service
systemctl start getty@tty2.service
```
... or systemctl restart, etc.

You can see login(1) or agetty in systemctl status output:
```
systemctl status getty@tty2.service
● getty@tty2.service - Getty on tty2
   Loaded: loaded (/etc/systemd/system/getty@tty2.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-03-25 14:33:32 CET; 3min 47s ago
     Docs: man:agetty(8)
           man:systemd-getty-generator(8)
           http://0pointer.de/blog/projects/serial-console.html
 Main PID: 12660 (agetty)
    Tasks: 1 (limit: 4915)
   Memory: 180.0K
   CGroup: /system.slice/system-getty.slice/getty@tty2.service
           └─12660 /sbin/agetty --login-pause --autologin kzak --noclear tty2 linux
```
Maybe you forgot properly activate the service, systemctl status is our friend :-)

**Comment by karelzak** [comment]
And note:

util-linux-2.32.1-1.fc29.x86_64
systemd-239-12.git8bca462.fc29.x86_64

**Comment by q2dg** [comment]
Oooh, sorry, I forgot to execute "systemctl daemon-reload"! Oh, sorry sorry sorry for the inconvenience.
And thanks a lot for your time: I apologize!!!

**Comment by karelzak** [comment]
No problem, better report than ignore ;-)
