### ISSUE TITLE
su - produces wrong error message

### ISSUE THREAD

**Issue by blueskycaffe** [karelzak/util-linux#778]
Quite by accident, I found that the "su -" command produces the wrong error message under certain circumstances.

If you change the ownership of su to some account without root access, then when you try to switch to the root account it tells you the password is incorrect, which is wrong.

I reckon that is because without root access, su cannot access the shadow password file, so it cannot compare the password entered from the keyboard with the one stored, producing the wrong error message.

I think this can be fixed by having su to check the ownership when first startup, the same way sudo does.

**Comment by karelzak** [comment]
su uses PAM, so it has no clue why authentication failed.  Unfortunately, it seems in this case pam_strerror() returns nothing usable. 

I'll change "incorrect password" to more generic "authentication failed". 

I don't think check for the ownership makes sense as your use-case is very unusual and in theory it's possible to authenticate without access to password file (e.g. kerberos/ldap/...) and setuid() without root permissions (e.g. CAP_SETUID).
