### ISSUE TITLE
\r in path confuses libmount

### ISSUE THREAD

**Issue by keszybz** [karelzak/util-linux#780]
Based on https://github.com/systemd/systemd/issues/12018. Systemd uses libmount to parse `/proc/self/mountinfo`.

```console
$ mkdir "$(echo -e foo\\rbar)"
$ sudo mount -t tmpfs tmpfs foo^Mbar/
$ findmnt | grep foo
│ └─/tmp/foo                                tmpfs                          tmpfs       rw,bar,seclabel
```

Quoting https://github.com/systemd/systemd/issues/12018#issuecomment-479583575:
`fscanf()` will split fields on whitespace, and what counts as whitespace is both locale-specific and *different to* the actual file format (even in the C locale).  The Linux kernel, the  GNU C library, and other utilities are quite specific that only SPC and TAB are field separator characters; whereas `fscanf()` will *also incorrectly* split fields on VT and CR.

* GNU C library [using `__strsep()` with TAB and SPC](https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/misc/mntent_r.c#L159)  and [decoding field contents](https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/misc/mntent_r.c#L67)
* [netdata specifying only TAB and SPC as the the separators](https://github.com/netdata/netdata/blob/8fbf817ef83b3524b15f908251909d9d6feb5532/collectors/proc.plugin/proc_self_mountinfo.c#L182) in the call to `procfile_open()`
* [Linux only encoding *some* whitespace characters](https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/fs/proc_namespace.c#L146) in the first place
* [source of `fstab-decode`](https://sources.debian.org/src/sysvinit/2.93-8/src/fstab-decode.c/#L42)

Whether or not CR is a good idea in a mount point name, one should *parse the data file correctly*.

**Comment by karelzak** [comment]
Fixed in the master branch; now all the code is without sscanf().
```
 # mkdir "$(echo -e /mnt/test/foo\\rbar)"
 # mount -t tmpfs tmpfs "$(echo -e /mnt/test/foo\\rbar)"

 #  findmnt $(echo -e /mnt/test/foo\\rbar)
 TARGET               SOURCE FSTYPE OPTIONS
 /mnt/test/foo\x0dbar tmpfs  tmpfs  rw,relatime

 # umount "$(echo -e /mnt/test/foo\\rbar)"
```

**Comment by karelzak** [comment]
And backported to stable/v2.33 too. The release will be available ASAP (tomorrow?)
