### ISSUE TITLE
cfdisk: more than one frac digits return wrong sizes eg. 7.16G => 8.6G

### ISSUE THREAD

**Issue by howaboutsynergy** [karelzak/util-linux#782]
When using cfdisk to create new partition, inputting a size such as 7.16G yields a partition of size 8.6G, but a size of 7.1G yields 7.1G (which is correct), this is due to the code being bugged when using more than one digits after the `.` (dot), specifically this part happens:

https://github.com/karelzak/util-linux/blob/450016eb72abbfb0a339e49247947684ffab1e08/lib/strutils.c#L170

As a mitigation, to prevent wrong sizes from being computed/accepted at all, I'm using this patch:
```diff
diff -upr util-linux-2.32/lib/strutils.c util-linux-2.32.mod/lib/strutils.c
--- util-linux-2.32/lib/strutils.c	2017-09-27 11:05:13.698361518 +0200
+++ util-linux-2.32.mod/lib/strutils.c	2018-07-03 20:46:44.627681308 +0200
@@ -165,6 +165,10 @@ check_suffix:
 			goto err;
 		}
 		do_scale_by_power(&y, base, frac_pwr);
+		if (frac >= 10) { //FIXME: more than 1 fraction digits not supported eg. 7.4G ok, but 7.45G not good!
+			rc = -EINVAL;
+			goto err;
+		}
 		x += y;
 	}
 done:
```

tested `util-linux 2.33.2-1` on ArchLinux

I'll gladly provide more info or test any suggestions. Thank you!

PS: other bad sizes:
1.1111111KB => 111112100 instead of 1137.7777664
7.16G => 9193914368 instead of 7687991459.84
_7.1G => 7621050368 seems correct(kinda!) should be 7623566950.4 (diff is 2516582.4, not sure why)_
1.023K => 1214 instead of 1047.552
1.0123K => 1854 instead of 1036.5952
1.0234K => 2584 instead of 1047.9616
1.234K => 24424 instead of 1263.616
1.23K => 3324 instead of 1259.52

**Comment by karelzak** [comment]
Hmm... it really seems that the algorithm behind frac is pretty poor. It works incorrectly also for one frac numbers:
```
$ ./test_strutils --size 0.5KiB
                   0.5KiB :                  500 :     500B :        500 B
$ echo "1024*0.5" | bc -l
512.0
```
... half of KiB is really not 500 bytes, should be 512. 

I'll try to improve it. It would be probably better to base the algorithm on division of the base number (e.g. for KiB frac 5 means: 1024 / (10 / 5)) rather than on do_scale_by_power().

**Comment by karelzak** [comment]
Closing. It should be improved now.

**Comment by howaboutsynergy** [comment]
Improved is always better. Thanks so much!
