### ISSUE TITLE
have more errors reports

### ISSUE THREAD

**Issue by GitSoftwareNow** [karelzak/util-linux#784]
CCLD     mkfs.cramfs
./.libs/libcommon.a(libcommon_la-blkdev.o): In function `blkdev_get_size':
/home/util-linux-2.23.2/lib/blkdev.c:93: undefined reference to `get_linux_version'
collect2: ld returned 1 exit status
make[2]: *** [mkfs.minix] 错误 1
copying selected object files to avoid basename conflicts...
./.libs/libcommon.a(libcommon_la-blkdev.o): In function `blkdev_get_size':
/home/util-linux-2.23.2/lib/blkdev.c:93: undefined reference to `get_linux_version'
collect2: ld returned 1 exit status
make[2]: *** [mkfs.bfs] 错误 1
./.libs/libcommon.a(libcommon_la-blkdev.o): In function `blkdev_get_size':
/home/util-linux-2.23.2/lib/blkdev.c:93: undefined reference to `get_linux_version'
collect2: ld returned 1 exit status
make[2]: *** [fsck.cramfs] 错误 1
make[2]: Leaving directory `/home/util-linux-2.23.2'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory `/home/util-linux-2.23.2'
make: *** [all] 错误 2

**Comment by karelzak** [comment]
Such report is useless.... 

... "make" command line? 
... operation system?
... ./configure command line?
... ./configure warnings?

**Comment by GitSoftwareNow** [comment]
> Such report is useless....
> 
> ... "make" command line?
> ... operation system?
> ... ./configure command line?
> ... ./configure warnings?

such as command line, I have finished on linux system ./configure --prefix=/usr makeundefined reference to get_linux_version'

**Comment by karelzak** [comment]
Can you provide output from "make V=1"?

**Comment by GitSoftwareNow** [comment]
> Can you provide output from "make V=1"?

what's meavn of make V=1?

**Comment by kerolasa** [comment]
The 'make V=1' will cause compilation to print more messages.
Reference: https://www.gnu.org/software/automake/manual/html_node/Debugging-Make-Rules.html

**Comment by karelzak** [comment]
Insufficient information. Closing.
