### ISSUE TITLE
I tried to build source code of util-linux then i got following error 

### ISSUE THREAD

**Issue by akbarsaleemt** [karelzak/util-linux#792]
blockdev.o: In function `report_device':
/home/systebui/akbar/package/utils/util-linux-2.20.1/build/disk-utils/../../disk-utils/blockdev.c:453: undefined reference to `sysfs_init'
/home/systebui/akbar/package/utils/util-linux-2.20.1/build/disk-utils/../../disk-utils/blockdev.c:457: undefined reference to `sysfs_read_u64'
/home/systebui/akbar/package/utils/util-linux-2.20.1/build/disk-utils/../../disk-utils/blockdev.c:458: undefined reference to `sysfs_deinit'
collect2: error: ld returned 1 exit status
make[2]: *** [blockdev] Error 1
make[2]: Leaving directory `/home/systebui/akbar/package/utils/util-linux-2.20.1/build/disk-utils'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/systebui/akbar/package/utils/util-linux-2.20.1/build'
make: *** [all] Error 2
systebui@VTLW002L:~/akbar/package/utils/uti

**Comment by karelzak** [comment]
Frankly, v2.20 is pure archaeology... :-)  the current upstream is v2.33 and v2.34-rc1.

**Comment by karelzak** [comment]
Please, update to the current upstream version. Closing.
