### ISSUE TITLE
attribution?

### ISSUE THREAD

**Issue by bjd-pfq** [karelzak/util-linux#803]
My name is in rev.c, yet not in the contributions list in AUTHORS.

**Comment by karelzak** [comment]
The contribution list is generated from git, so contributors from pre-git era are missing there ;-(
Anyway, it's easy to fix ;-) What's your name (as used in rev.c)?

**Comment by karelzak** [comment]
@bjd-pfq ping :-)

**Comment by edneville** [comment]
Looking at associated git hub, and commits, I'd say its Bauke Jan Douma. @bjd-pfq?

**Comment by bjd-pfq** [comment]
Indeed it is. But... I replied by PM in May. Did that not arrive?

**Comment by edneville** [comment]
Doesn't look like it, but at least it's logged in the issue now.

**Comment by karelzak** [comment]
@edneville thanks for investigation :-) Fixed.
