### ISSUE TITLE
Unable to cross-compile util-linux 2.34

### ISSUE THREAD

**Issue by mihammouda** [karelzak/util-linux#812]
HI,
I'm trying to cross-compile util-linux 2.34 for an arm64 device, make
command work fine but install no, this is the error:
libtool: warning: relinking 'libmount.la'
libtool: install: (cd /data/build/rootfs/sources/util-linux/util-linux-2.34; /bin/bash "/data/build/rootfs/sources/util-linux/util-linux-2.34/libtool"  --silent --tag CC --mode=relink aarch64-linux-gnu-gcc -fsigned-char -fno-common -Wall -Werror=sequence-point -Wextra -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wno-missing-field-initializers -Wredundant-decls -Wsign-compare -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -Wnested-externs -Wpointer-arith -Wstrict-prototypes -Wimplicit-function-declaration -Wdiscarded-qualifiers -I./libblkid/src -I./libmount/src -I./libmount/src -I/data/build/rootfs/builds/ncurses/usr/include -Wl,--version-script,./libmount/src/libmount.sym -version-info 2:0:1 -L/data/build/rootfs/builds/ncurses/usr/lib -o libmount.la -rpath /usr/lib lib/libmount_la-monotonic.lo libmount/src/la-cache.lo libmount/src/la-fs.lo libmount/src/la-init.lo libmount/src/la-iter.lo libmount/src/la-lock.lo libmount/src/la-optmap.lo libmount/src/la-optstr.lo libmount/src/la-tab.lo libmount/src/la-tab_diff.lo libmount/src/la-tab_parse.lo libmount/src/la-tab_update.lo libmount/src/la-test.lo libmount/src/la-utils.lo libmount/src/la-version.lo libmount/src/la-context.lo libmount/src/la-context_loopdev.lo libmount/src/la-context_mount.lo libmount/src/la-context_umount.lo libmount/src/la-monitor.lo libmount/src/la-btrfs.lo libcommon.la libblkid.la -lrt -inst-prefix-dir /data/build/rootfs/builds/util-linux)
/data/build/rootfs/sources/util-linux/util-linux-2.34/libtool: line 10533: aarch64-linux-gnu-gcc: command not found
libtool:   error: error: relink 'libmount.la' with the above command before installing it
Makefile:5928: recipe for target 'install-usrlib_execLTLIBRARIES' failed

OS: Ubuntu 18.04
Commands:
./configure --host=aarch64-linux-gnu --prefix="/usr" --without-tinfo
make
sudo -E make DESTDIR="${ROOTFSBUILDS}/util-linux" install
Can you help me?
Thanks in advance

**Comment by karelzak** [comment]
Frankly, I have no experience with cross-compilation. Not sure, but maybe all you need is to add/install aarch64-linux-gnu-gcc to PATH :-)

Maybe @rudimeier has any idea.

**Comment by mihammouda** [comment]
Hi Karelzak,
The cross compiler is already in my PATH. I see that "make DESTDIR="${ROOTFSBUILDS}/util-linux" install" work fine, for now i used this workaround. I'm investigating the issue
Thank you for your replay
Mihamed

**Comment by karelzak** [comment]
Hmm... DESTDIR is place-holder to install to another places. It's nowhere defined in build-system. It sounds like build-system stuff (libtool) is looking for commands relatively to install paths. Maybe use explicit DESTDIR is the right way.

Closing, report if find something we can change in our makefiles. Thanks.
