### ISSUE TITLE
checkout on case insensitive filesystem

### ISSUE THREAD

**Issue by glensc** [karelzak/util-linux#818]
Just letting you know that such problem exist

```
$ git clone https://github.com/karelzak/util-linux
Cloning into 'util-linux'...
remote: Enumerating objects: 236, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 94587 (delta 151), reused 154 (delta 95), pack-reused 94351
Receiving objects: 100% (94587/94587), 140.66 MiB | 5.72 MiB/s, done.
Resolving deltas: 100% (71484/71484), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'tests/expected/libmount/context-X-mount.mkdir'
  'tests/expected/libmount/context-x-mount.mkdir'
```

their content is (currently) identical, so it's not an issue yet.

from quick look of commits can't figure out why these both were needed:
- https://github.com/karelzak/util-linux/commit/701c69617e50ed8c15bc2c5bc7bf6eee1cb04b23 - adds lowercase variant
- https://github.com/karelzak/util-linux/commit/06e204889f38fa9c231b9744f2ed7f9c8cbfbb7b - adds uppercase variant

**Comment by karelzak** [comment]
We have X-* as well as x-* mount options, so we need two tests. Anyway, I have improved the name of the tests to make it more robust for your FS ;-)
