### ISSUE TITLE
fstrim.service prevents /home in a separate partition from being trimmed

### ISSUE THREAD

**Issue by tomgar** [karelzak/util-linux#824]
I have /home in a separate partition and I noticed checking the systemd journal that fstrim ignored my /home. After research, I found the fstrim.service file has a ProtectHome=yes value, which prevents fstrim from trimming it.

Once I added an override to set up ProtectHome=no, fstrim now sees my /home and trims it in every run.

**Comment by karelzak** [comment]
Oh, good point. Thanks! 

I think ProtectHome=read-only should be good enough.
