### ISSUE TITLE
mountpoint behaves unexpected on symlinked directories.

### ISSUE THREAD

**Issue by eike-fokken** [karelzak/util-linux#832]
Say you have directories

/
/bin/
/home/user/somefolder/

where /home is mounted from a filesystem different from that of /,
but /bin/ is on the root filesystem (not a mountpoint).

If I now make a symlink
/home/user/somefolder/bin -> /bin

then mountpoint says that /home/user/somefolder/bin is not a mountpoint.
I think this is bad because it behaves as a mountpoint and you actually leave your file system when accessing files in bin. For example you can't hardlink across the symlink.

**Comment by kerolasa** [comment]
The mountpoint(1) is a tool to determine if a path is or isn't mount point, so I would argue that command behaves correctly in previous comment. But there is a good question in this bug, should mountpoint(1) traverse symlinks? I think it should not, or if it should maybe 'is a symlink to a mountpoint' would be better text.

    $ mountpoint /boot
    /boot is a mountpoint
    $ ln -s /boot /tmp/foobar
    $ mountpoint /tmp/foobar
    /tmp/foobar is a mountpoint

**Comment by karelzak** [comment]
@eike-fokken 
The behaviour described in the first comment is correct. The mountpoint is something you can umount or do another mountpoint specific operations. The /bin from your example is really not a node in kernel mount tree.

@kerolasa 
mountpoint(1) follows symlinks as another tools -- you can use symlinks in your fstab, etc. Maybe we can add --nofollow option if another behaviour is necessary for some use-case.

**Comment by eike-fokken** [comment]
I like the idea of a nofollow option a lot.
Would a pull request be welcome that implements a nofollow option?
Would a pull request be welcome that prints out something like:
`/home/somefolder/bin is not a mountpoint but on a different filesystem than /home/somefolder`?

If so, should I follow guidelines apart from those in howto-contribute.txt?

**Comment by karelzak** [comment]
PR is fine, but please keep the changes relevant for the --nofollow only. If we need another functionality -- (for example report different FS) than it should be implementde by another patch. Thanks.

**Comment by karelzak** [comment]
@eike-fokken it seems @kerolasa has been faster with --nofollow PR...

**Comment by eike-fokken** [comment]
Nice!
