### ISSUE TITLE
Using "Unnamed-fields format" for GPT

### ISSUE THREAD

**Issue by suntong** [karelzak/util-linux#836]
Hi again Karel, 

Could you give me an example how to prepare GPT using the "Unnamed-fields format"? 

I'm especially interested in specifying the `name` part. 

I've tried:

```
,24000MiB,,*,,,live
,20000MiB,,,,,swap,S
```

but I didn't get the name, and the partition type `S` (swap) is not applied either. 

Then I tried:

```
,24000MiB,name=live
,20000MiB,name=swap,type=S
```

But got `line 1: unsupported command`

Pls help. 
Thx!

**Comment by suntong** [comment]
Sorry, I've mixed the "Unnamed-fields format" with "Named-fields format".

**Comment by karelzak** [comment]
Note that named-fields format is probably better, because it's self-documenting and user-friedly. It also provides more fields. The unnamed format is just for backward compatibility and for basic tasks -- it does not provide things like uuid or name.
