### ISSUE TITLE
Bash completion doesn't match non-canonical device names or files

### ISSUE THREAD

**Issue by kevinoid** [karelzak/util-linux#842]
The Bash completion scripts for commands which usually operate on block devices (`blkdiscard`, `*disk`, `mkfs*`) won't complete files other than the names of block devices from `lsblk -pnro name`.  This excludes block devices under `/dev/disk/`, disk image files, custom device nodes, and probably other things which make the tools frustrating to use in these cases.

Would you be open to accepting a PR which completes these, either by default or as a fallback if `compgen -W "$(lsblk -pnro name)"` returns no matches?

Thanks for considering,
Kevin

**Comment by kerolasa** [comment]
I'm sure everyone agrees improvements are welcome. But why only as fallback? If there useful possibilities just list everything by default.

**Comment by kevinoid** [comment]
For sure.  I'd be happy to change `compgen -W "$(lsblk -pnro name)"` to `compgen -f`.  The only down-sides that I can think of are: 1) `<tab>` and `/<tab>` show contents of `/` instead of jumping straight to block devices, and 2) there will be a lot more output from `/dev/<tab>` which will show everything instead of just block devices.

I think `compgen -f` would be preferable, but assumed it would get push back from the author of `compgen -W "$(lsblk -pnro name)"` and would be harder to justify than fallback.  What do you think?

**Comment by kerolasa** [comment]
Isn't there no better way to find custom devices paths than `compgen -f`? If not then scrapping `lsblk -pnro name` in favour of `compgen -f` is probably best option.

**Comment by kevinoid** [comment]
Sure, I could come up with a way to limit completions to block devices (either with or without fallback to regular files), but it may be annoying/surprising for users who want to run against a image file (e.g. `sfdisk -d driveimage.raw`), which might make `compgen -f` preferable (both for simplicity of implementation and behavior).

**Comment by karelzak** [comment]
hmm... add /dev/disk/by-* to the default will generate huge list with many duplicates and aliases. I think this directory should be added to the list only if user explicitly specifies /dev/disk/ on command line. The same with the current directory, for example:
```
blkdiscard   <tab>                 --> show $(lsblk -pnro name)
blkdiscard  /dev/disk  <tab>       --> show all the funny aliases
blkdiscard  ./   <tab>             --> show all files 
```
I have no clue how difficult is to implement it, but it would be nice if user can control it by path prefix (/dev/disk, ./ ...) and default should be $(lsblk -pnro name) is nothing specified.

**Comment by kevinoid** [comment]
Thanks @karelzak, sounds good to me.  That should be reasonably straightforward to implement.  I'll take a stab at it soon.
