### ISSUE TITLE
fdisk adds half kilobyte with offsets inconsistently?

### ISSUE THREAD

**Issue by mikelcaz** [karelzak/util-linux#843]
Hi! I'm trying to partition a file image and I'm very puzzled by this. Is this normal?

| | Offset specified in ... | Final size of the partition |
|-|-|-|
| Small file | Units | Offset + 512 bytes |
| Small file | Sectors | Offset + 512 bytes |
| Big file | Units | Offset + 0 bytes |
| Big file | Sectors | Offset + 512 bytes |

Given a 1440 KiB image:

```
Created a new DOS disklabel [...]

Command (m for help): n
[...]
First sector (1-2879, default 1): 2048
Last sector, +sectors or +size{K,M,G,T,P} (63-2879, default 2879): +1K

Created a new partition 1 of type 'Linux' and of size 1.5 KiB.
```

> +1K(iB) becomes into 1.5K(iB).

I also tried with '1', '8' and '63' as the starting sector, with different (but small) file sizes, and with other 'size offsets' for the partition.

With sectors instead of units:

```
Last sector, +sectors [...]: +2

Created a new partition 1 of type 'Linux' and of size 1.5 KiB.
```

But in a big file, I get this with units:

```
First sector (2048-131071, default 2048): 2048
Last sector, [...]: +1K

Created a new partition 1 of type 'Linux' and of size 1 KiB.
```

However, with sectors:

```
Last sector, +sectors [...]: +2

Created a new partition 1 of type 'Linux' and of size 1.5 KiB.
```

**Comment by karelzak** [comment]
+2 or +1K is correctly interpreted and the final size is expected to be 1.5K (as partition size also includes the start sector, +0 as "Last sector" means 1 sector long partition).

The inconsistency with +1K on a big file is a bug. 

(The bug is visible only when fdisk do not align the size. This alignment logic is ignored for partitions smaller than "grain", for big files it's 1MiB, for very small files it's one sector, so you do not see the problem for small files....)

Fixed. Thanks for your report!

**Comment by mikelcaz** [comment]
Thank you. Please let me ask something more, @karelzak. I had imagined the odd one was the third case, but then... why the offset does not include the first sector? It seems weird to me, because we have a notation to write (let's say) '+32GiB', and nonetheless the only way to actually have 32 GiB (or any other unit besides sectors) is... telling the number of raw sectors minus one. I mean: I can't just write '+32GiB - 1[sector]'!

**Comment by karelzak** [comment]
The +size{suffix} notation is only hint for fdisk. It will always try to align the size (well, except for very small partitions), so I have doubts it makes sense to try to use the user's input in any precise way.

Anyway, the dialogue is about "Last sector", not about size of the partition, and "+" means number of sectors after the first sector. So, from this point of view it makes sense, although it seems strange at the first glance. All this is pretty old (>15years) and now it's too late to try to improve it (as people use it in scripts, etc.)

**Comment by karelzak** [comment]
... and +32GiB so huge number that 512 bytes is nothing, especially if fdisk will align the end of the partition to  optimal I/O limits ;)
