### ISSUE TITLE
dmesg: color codes are escaped since commit 3661aab4cf7509b03f749477082553f4eee7dc0e 

### ISSUE THREAD

**Issue by howaboutsynergy** [karelzak/util-linux#858]
Displaying of colors (à la `less -R`) got fixed by:
```
commit 3661aab4cf7509b03f749477082553f4eee7dc0e (HEAD, refs/bisect/bad)
Date:   Thu Aug 1 11:43:58 2019 +0200

    dmesg: fix output hex encoding
    
    The current code ignores single-byte non-printable characters.
```
so they now look escaped, like this:
```
$ logger "$(tput setab 1)this be in red$(tput sgr0) but this in normal." ; dmesg|grep -i "this be in red"
[49357.243822] user[31957]: \x1b[41mthis be in red\x1b(B\x1b[m but this in normal.
```

I'm guessing this is intended? although: the `--raw` arg to `dmesg` seems a bit confusing:
> -r, --raw
>      print  the  raw  message buffer, i.e. do not strip the log-level prefixes.

Is it supposed to print the raw message buffer in raw form or in escaped form(the latter, currently)? or is that **just** a reference to not stripping the log-level prefixes instead?

Thanks.

**Comment by howaboutsynergy** [comment]
Some real-world effects of this now:
```
$ dmesg|grep -- '\\x'
...
[   37.707737] profile-sync-daemon[1145]: \x1b[01mfirefox sync successful\x1b[00m
...
[38652.957468] pacman[29486]: \x1b[31m\x1b[1m  ==> WARNING: \x1b(B\x1b[mList of packages which are linked against legacy xfconf (4.12.x)

```
(^ practically irrelevant)

With the below for-fun test-patch, these are the only results:
```
$ dmesg|grep -- '\\x'
[    7.320007] systemd[1]: Created slice system-systemd\x2dbacklight.slice.
[    8.864260] systemd[1]: Created slice system-zram\x2dsetup.slice.
```

```diff
diff --git a/sys-utils/dmesg.c b/sys-utils/dmesg.c
index 9f2e5b804..e0c432833 100644
--- a/sys-utils/dmesg.c
+++ b/sys-utils/dmesg.c
@@ -651,9 +651,9 @@ static void safe_fwrite(const char *buf, size_t size, int indent, FILE *out)
 				hex = 1;
 		}
 
-		if (hex)
+		/*if (hex)
 			rc = fwrite_hex(p, len, out);
-		else if (*p == '\n' && *(p + 1) && indent) {
+		else */if (*p == '\n' && *(p + 1) && indent) {
 		        rc = fwrite(p, 1, len, out) != len;
 			if (fprintf(out, "%*s", indent, "") != indent)
 				rc |= 1;
```

**Comment by karelzak** [comment]
So, you want to say that dmesg should not care about what it prints on terminal, right? 

I'm not sure if we want to blindly print non-printable chars. The \hex is used since year 2011, the recent change is only bug fix for single-byte chars. And we use the same way in many another tools.

The idea with hardcoded colors in the logs is nice, but it's terminal specific hack...

Not sure what change in dmesg is expected in this case :-(

**Comment by howaboutsynergy** [comment]
> So, you want to say that dmesg should not care about what it prints on terminal, right?

No no, that would probably be a bad idea security-wise (can't find that doc right now). Though, an arg whether or not to print it raw or escaped would be nice.(or see below)
> 
> I'm not sure if we want to blindly print non-printable chars. The \hex is used since year 2011, the recent change is only bug fix for single-byte chars. And we use the same way in many another tools.
> 
> The idea with hardcoded colors in the logs is nice, but it's terminal specific hack...
> 
> Not sure what change in dmesg is expected in this case :-(

I guess none, or just making sure that the `--raw` arg isn't confusing: at first I thought it's like `less -R`, but the `ie.` tells me it's only about not stripping the log-level prefixes, though the first sentence `print the raw message buffer` implies it would be printed raw - this is why I found it confusing.

Otherwise please feel free to close this then :)

**Comment by howaboutsynergy** [comment]
actually, nevermind :) sorry for the noise

**Comment by karelzak** [comment]
... but we have no way how to disable escape at all, maybe we need something like --no-escape. It's bad that there is no way how to get really raw data from kernel. I'll add these option.
