### ISSUE TITLE
`setterm --clear rest` doesn't work

### ISSUE THREAD

**Issue by bugrasan** [karelzak/util-linux#861]
versions: `setterm from util-linux 2.33.1` on Ubuntu 19.04 and `setterm from util-linux 2.34` on Manjaro

according to setterm help:
`--clear         [all|rest]        clear screen and set cursor position`
also according to man page:
`--clear [all|rest]
Without  an  argument or with the argument all, the entire screen is cleared and the cursor is set to the home position, just like clear(1) does.  With the argument rest, the screen is cleared from the current cursor position to the end.`

however then i do:
```
$ setterm --clear rest
setterm: argument error: 'rest'
```
according to source code this needs to be `reset`
https://github.com/karelzak/util-linux/blob/2c308875a7fa1aaa44892c368f6b37bcfcb8879a/term-utils/setterm.c#L617

furthermore according to the man page description above `--clear` can be used `Without an argument or...`, however:
```
$ setterm --clear
setterm: option '--clear' requires an argument
Try 'setterm --help' for more information.
```
however according to source code it requires a argument https://github.com/karelzak/util-linux/blob/2c308875a7fa1aaa44892c368f6b37bcfcb8879a/term-utils/setterm.c#L500

**Comment by karelzak** [comment]
Thanks for your report! Fixed. 

Note that optional arguments in GNU universe requires '=', for example --clear=all. I have fixed man page and --help to make it more obvious for end-users.
