### ISSUE TITLE
libuuid license?

### ISSUE THREAD

**Issue by kallisti5** [karelzak/util-linux#877]
libuuid used to be BSD/AS-IS.. i'm sure the code still is.
Is a libuuid built from the project still under the BSD/AS-IS license?

**Comment by kallisti5** [comment]
Nevermind. We forked it and cleaned up the questionable license issue.

**Comment by karelzak** [comment]
The problem should be fixed by commit dde4b59369a18d6b49648277069a79a1d58a4690, will be in version v2.35.
