### ISSUE TITLE
hwclock: better error reporting

### ISSUE THREAD

**Issue by leahneukirchen** [karelzak/util-linux#879]
Please print the errno status in `open_rtc` on failure. I was just very confused to see this:

```
hwclock from util-linux 2.34
System Time: 1570439840.340120
Trying to open: /dev/rtc0
No usable clock interface found.
hwclock: Cannot access the Hardware Clock via any known method.
```

(chronyd already had the rtc open, so printing EBUSY would have helped a lot, without me resorting to strace.)

**Comment by karelzak** [comment]
Good point, improved for --verbose. Thanks for your report.
