### ISSUE TITLE
login hang on large nofile limit

### ISSUE THREAD

**Issue by microcai** [karelzak/util-linux#883]
```
	for (cnt = get_fd_tabsize() - 1; cnt > 2; cnt--)
		close(cnt);
```
this code will try to close millions of fd(s) and hang for a very long time if nofile limit is set very large.

**Comment by microcai** [comment]
see how systemd does https://github.com/systemd/systemd/blob/5238e9575906297608ff802a27e2ff9effa3b338/src/basic/fd-util.c#L217

**Comment by karelzak** [comment]
Fixed.
