### ISSUE TITLE
RFE: nologin: support -l, -i and --login parameters and ignore them

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#895]
nologin is typically used in /etc/passwd as a shell replacement. Hence it would be great if it would accept and ignore some parameters that shells usually implement. Specifically: -l/--login, -i (for login/interactive shell), which bash, dash, zsh all implement.

Note that these options aren't POSIX definitions but practically all shells that I found implement them. Hence nologin should probably too.

I figure nologin should just eat up these switches and do the very same thing it would normally do.

This would help to make this more explanatory:

https://github.com/systemd/systemd/issues/8634

we currently invoke the listed shell of the user specified in "machinectl shell myuser@mycontainer" and then you get an ugly error, about "-l" not being accepted. Would be nice to get a nicer error that just says login not permitted.

(Yes I am aware we could also set argv[0][0]='-' when invoking the shell, to get a login shell in a way compatible with nologin, but that's hard to do if you only have POSIX shell for that.)

**Comment by kerolasa** [comment]
It might be easiest to ignore unknown options, for example this way: https://github.com/karelzak/util-linux/pull/896

**Comment by poettering** [comment]
(well, that's up to the maintainers, how they want that implemented; ignoring them all would work for me too, but I personally don't want to hide error conditions to agressively, so i'd just ignore the ones known to be used and still print errors for the others...)

**Comment by karelzak** [comment]
Merged.
