### ISSUE TITLE
sys-utils/hwclock -parse-date.y:47:10: fatal error: hwclock.h: No such file or directory

### ISSUE THREAD

**Issue by Polynomial-C** [karelzak/util-linux#899]
commit 8e1b131e0aa1063928a830300279f8fce706f407 seems to have broken build of hwclock:
```
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I/var/tmp/portage/sys-apps/util-linux-9999/work/util-linux-9999  -include config.h -I/var/tmp/portage/sys-apps/util-linux-9999/work/util-linux-9999/include -DLOCALEDIR=\"/usr/share/locale\" -D_PATH_RUNSTATEDIR=\"/var/lib/run\" -D_PATH_SYSCONFSTATICDIR=\"/usr/lib\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -fsigned-char -fno-common -Wall -Werror=sequence-point -Wextra -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wno-missing-field-initializers -Wredundant-decls -Wsign-compare -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -Wnested-externs -Wpointer-arith -Wstrict-prototypes -Wformat-security -Wimplicit-function-declaration -Wdiscarded-qualifiers -march=native -mtune=native -O2 -pipe -c -o sys-utils/hwclock-parse-date.o sys-utils/hwclock-parse-date.c
/var/tmp/portage/sys-apps/util-linux-9999/work/util-linux-9999/sys-utils/hwclock-parse-date.y:47:10: fatal error: hwclock.h: No such file or directory
   47 | #include "hwclock.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:8747: sys-utils/hwclock-parse-date.o] Error 1
```

**Comment by karelzak** [comment]
It works for me (and on travis CI) and your gcc command line seems correct,  ... do you have the file (sys-utils/hwclock.h)? Maybe you need "git clean -xdf && git pull" or so...

**Comment by Polynomial-C** [comment]
This is a fresh git clone so everything is available. Compilation happens in a separate build-directory so maybe that's the issue here?

**Comment by Polynomial-C** [comment]
Yes, it's an issue when using a separate build-directory. Once I compile in-source, the error is gone.

**Comment by karelzak** [comment]
Ah, I see. Thanks for your report. Fixed now.

**Comment by kerolasa** [comment]
Sorry for commenting after request is closed. Maybe travis should run `make distcheck` rather than `make dist` to catch these breakages. I did not test if following works, but it might.

    diff --git a/.travis.yml b/.travis.yml
    index a4f51f3ed..5bcde162d 100644
    --- a/.travis.yml
    +++ b/.travis.yml
    @@ -13,7 +13,7 @@ compiler:
     env:
       - MAKE_CHECK="nonroot"
       - MAKE_CHECK="root"
    -  - MAKE_CHECK="dist"
    +  - MAKE_CHECK="distcheck"
     
     matrix:
       include:
