### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nemobis** [karelzak/util-linux#900]
```
$ lscpu
Segmentation fault
```

lscpu from util-linux 2.33.1
Linux 4.14.154-grsec-kapsi #1 SMP Sat Nov 16 21:42:59 EET 2019 x86_64 GNU/Linux
Dell R6515: AMD EPYC 7402P 2,8 GHz 24C/48T

Cf. [ lscpu crashs when /dev/mem is not stable to read ](https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1674258), [lscpu crashes on certain arm64 devices](https://bugzilla.redhat.com/show_bug.cgi?id=1455238). I cannot test with another kernel or higher privileges, sorry.

**Comment by karelzak** [comment]
Can you try "strace -e open,openat lscpu"? It sounds you have no /sys/firmware/dmi/tables/DMI at all.

**Comment by karelzak** [comment]
And do you have /sys/firmware/efi directory?

It sounds like on your system lscpu don't found  /sys/firmware/dmi/tables/DMI, and then it found efi   (/sys/firmware/efi/systab) and and it tries to read /dev/mem according stuff from the firmware. 

For example on Cortex-A9:
```
stat64("/sys/firmware/dmi/tables/DMI", 0xbeff8ef0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sys/firmware/efi/systab", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/efi/systab", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
```
this is expected (no efi, no dmi, ignore /dev/mem).

**Comment by karelzak** [comment]
Uf, I see "AMD EPYC" ... it does not sounds lie ARM.

**Comment by nemobis** [comment]
Yes, this is not ARM. I just mentioned that bug because it's the only 
one I saw.

Karel Zak, 20/11/19 14:00:
> /sys/firmware/dmi/tables/DMI at all

There is but it's not readable:

----

$ stat /sys/firmware/dmi/tables/DMI
   File: /sys/firmware/dmi/tables/DMI
   Size: 3594            Blocks: 0          IO Block: 4096   regular file
Device: 11h/17d Inode: 22256       Links: 1
Access: (0400/-r--------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-11-20 15:29:12.942767165 +0200
Modify: 2019-11-20 15:29:12.942767165 +0200
Change: 2019-11-20 15:29:12.942767165 +0200
  Birth: -

$ ls -lh /sys/firmware/efi
total 0
-r--r--r--  1 root root 4,0K marras 20 15:28 config_table
dr-xr-xr-x  2 root root    0 marras 19 18:15 efivars
-r--r--r--  1 root root 4,0K marras 20 15:28 fw_platform_size
-r--r--r--  1 root root 4,0K marras 20 15:28 fw_vendor
-r--r--r--  1 root root 4,0K marras 20 15:28 runtime
drwxr-xr-x 16 root root    0 marras 20 14:01 runtime-map
-r--------  1 root root 4,0K marras 20 15:28 systab
drwxr-xr-x 74 root root    0 marras 19 18:15 vars

----

**Comment by karelzak** [comment]
It's expected that /sys/firmware/dmi/tables/DMI is readable for root only. In this case it falls back to EFI, and if EFI not readable than it tries some hardcoded addresses in /dev/mem (for __x86_64__ and __i386__). It should be visible in strace output.

It seems your kernel use grsecurity, maybe it's reason why you see the problem. 

Anyway, we need more information -- why and where in code it segfault. For now it's too generic report :-)

**Comment by nemobis** [comment]
> Anyway, we need more information -- why and where in code it segfault. For now it's too generic report :-)

Indeed, thank you. I'm only a user of this machine, so let's close this. If anyone in a similar situation is interested, now they know how to report it.
