### ISSUE TITLE
util-linux 2.25.1  hwclock Segmentation fault

### ISSUE THREAD

**Issue by zhaochengwei** [karelzak/util-linux#901]
![image](https://user-images.githubusercontent.com/13081827/69323096-03a9de00-0c81-11ea-918e-2e08ddc0bcf2.png)

**Comment by karelzak** [comment]
v2.25.1 is from Sep 2014, in year 2019 we have v2.34 :-)  And seems like glibc issue or so.

**Comment by zhaochengwei** [comment]
> v2.25.1 is from Sep 2014, in year 2019 we have v2.34 :-) And seems like glibc issue or so.

OK thank you, upgrade 2.27.1 and solve the problem.
