### ISSUE TITLE
Remove the "only root can use" check completely

### ISSUE THREAD

**Issue by poige** [karelzak/util-linux#904]
— due to there're capabilities (for a long time) in Linux and it simply spoils it.

```
% sudo mkdir /run/z
% mount -t tmpfs -o size=2g /dev/null /run/z
mount: only root can use "--options" option
% busybox mount -t tmpfs -o size=2g /dev/null /run/z
mount: permission denied (are you root?)
```

After setting cap_sys_admin to busybox and to mount:
```
% busybox mount -t tmpfs -o size=2g /dev/null /run/z
% mount -t tmpfs -o size=2g /dev/null /run/z
mount: only root can use "--options" option
```

**Comment by karelzak** [comment]
Removed ;-) I worked on this feature in previous weeks. Merged now. For more details, see:
https://lore.kernel.org/util-linux/20191119143408.b6pcbhtsiubxdcob@10.255.255.10/T/#u

For example mount without suid, but with cap_sys_admin:
```
$ getcap  ./mount.static
./mount.static = cap_sys_admin+ep
$ ls -la ./mount.static
-rwxrwxr-x 1 kzak kzak 5308440 Dec  3 15:30 ./mount.static

$ ./mount.static -t tmpfs -o size=2g /dev/null /run/z
$ findmnt /run/z
TARGET SOURCE    FSTYPE OPTIONS
/run/z /dev/null tmpfs  rw,relatime,size=2097152k,uid=1000,gid=1000
```

(note the example is with mount.static to avoid  libtools and shell script in build root.)
