### ISSUE TITLE
A potential license conflict issue?

### ISSUE THREAD

**Issue by yongli3** [karelzak/util-linux#908]
I am using the logger.c to support systemd journal log. Just enable HAVE_LIBSYSTEMD during build.
But I found that libsystemd is released under LGPL, util-linux is using GPLv2. 
I am not sure if the logger.c can link to libsystemd, it seems that there is a license conflict?

**Comment by karelzak** [comment]
That's a common situation. Almost all open-source libs are LGPL (see Glibc), and applications are GPL. LGPL is explicitly designed for libraries, and it's possible to link it with an arbitrary application, including proprietary close-code stuff. For more details see: https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License
