### ISSUE TITLE
blkdiscard should require exclusive access to device?

### ISSUE THREAD

**Issue by jiri-lunacek** [karelzak/util-linux#915]
Hi.
After an unfortunate incident on one of our systems (dropped data using blkdiscard due to a typo), I was wondering if this tool should not check that the device is not used.

Most utils that work with block devices require this. (Including device-mapper, md raid, lvm, mount etc.). umount of mountpoint that is merely used by a single console will fail but the system will allow you to discard the whole drive the system is running on.

Thanks for comments.

Jiri

**Comment by karelzak** [comment]
@lczerner any objection to add O_EXCL to open() for the ioctl?

**Comment by lczerner** [comment]
This sounds fine, but it would be nice to have an option to override it as well.

**Comment by karelzak** [comment]
OK, it's too late for v2.35; O_EXCL and --force (to override) will be available in v2.36. Thanks.
