### ISSUE TITLE
RFE: add ability to set UUID and disk name via libfdisk API calls

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#916]
I am looking for a way to set GPT disk UUID via libfdisk API calls. i.e. i create a new GPT label and set the overall disk UUID before writing it out. There are calls for reading the this field back in fdisk_get_disklabel_id() but I want to be able to write it instead (background: a reproducible partitioning tool that generates the UUIDs from a reproducible random source so that disk images can be regenerated safely).

Or in other words: I want to be able to set the `DiskGUID` field mentioned in EFI spec section 5.3.2.

**Comment by karelzak** [comment]
There is fdisk_set_disklabel_id(), but it's dialog-driven API ;-(

Another way is to use script API and set "label-id" before you create the label.
```
sc = fdisk_new_script();

fdisk_script_set_header(sc, "label-id", "uuid string");
fdisk_set_script(cxt, sc);

fdisk_create_disklabel(cxt, "gpt");
... 
```
The script is a common way how to push many options to the label drivers when you want to avoid dialogs.

**Comment by karelzak** [comment]
And it's pretty simple to extend the scripts if you will need anything else in the future. It's also possible to dump/read the script to the file.

**Comment by poettering** [comment]
Hmm, would still prefer if there was an explicit API for that.

(But I remember we talked about this before, and last time too I opted to use the "ask" API to solve the issue, will do so now too. I must say I would much prefer avoiding the script and ask APIs though for my purposes)

**Comment by karelzak** [comment]
Well, dance with ask API if do not want dialog is ugly ;-) ... but the script is an elegant way. Ignore the name of this API, it does parse anything, it's just a list of keys and values which are usable for PT driver.

Anyway, you're right for so commonly used things like ID it would be nice to have an explicit function.  I'll implement it for the next release.

**Comment by poettering** [comment]
excellent! thank you very much!
