### ISSUE TITLE
RFE: Please take a BSD lock on block devices whose super block/partition table is modified

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#921]
I'd really like to see mkswap/fdisk/… to take a BSD file lock on the block device nodes it opens, implementing this:

https://systemd.io/BLOCK_DEVICE_LOCKING

This would fix issues like this for us, that can be fixed only in ugly ways otherwise:

https://github.com/systemd/systemd/pull/13162

I am aware #563 btw. I am looking for a way to avoid chaining flock and mkswap like that, since I want to invoke this from clean systemd codepaths, and I'd rather not do "fake shell scripting" ;-) Also it's ugly that the device node is opened twice that way..

I can see that simply taking the BSD locks might be considered API breakage (given that people might take the BSD locks already beforehand, for example by wrapping the mkswap/fdisk call in flock, as suggested in some man pages), hence this should be opt-in I figure. i.e. these tools should maybe gain a common --lock=yes switch each, that does this and that defaults to "no"?

Besides a cmdline arg it might be cool to have an env var for this too. Why? so that it is easier for me to make use of this new feature from systemd: if we could set this via an env var we could just set that env var when calling the tool from systemd, and it would do the right thing both on old and on new util-linux. If we only had the cmdline option it would not be possible to be compatible with both, since if we pass the cmdline arg we'd start to fail on old util-linux versions...

Another reason why taking the lock natively in fdisk/mkswap/… is much nicer than wrapping those calls in "flock" is that "lslocks" looks so much nicer if the processes shown actually say "fdisk" and "mkswap" rather than all "flock"...

(When this is implemented the "flock" part in sfdisk man page should probably be dropped/replaced. If this is not implemented — which I'd find very sad — then that part from the sfdisk man page should probably be copied to cfdisk/fdisk/mkswap/… and all other tools that touch the superblock/partition tabe of a block device)

**Comment by poettering** [comment]
if this is implemented it would be fantastic if the env var would have a generic name so that the same env var can be honoured by all the various other mkfs/mkswap/fdisk-like tools too. i.e.  `$LOCK_BLOCK_DEVICE=1` instead of `$MKSWAP_LOCK=1` or so?

**Comment by poettering** [comment]
@karelzak I also filed https://github.com/tytso/e2fsprogs/issues/30 now, asking for a similar mechanism in mke2fs. If what I propose above is acceptable to you @karelzak and to @tytso it would be great if we could agree on the same env var to bind this behaviour on.

**Comment by karelzak** [comment]
I personally do not see a problem with this flock(LOCK_EX) plan. (Well, the possible issue may be some deadlock scenario, but it's probably very unusual to lock more device in our tools, and if yes it has to be done in careful way (all or nothing)).

Frankly, for the last decade, I call for a way how to temporary disable udev when another tool is doing nasty things with the device, because sometimes it's necessary to re-open devices and udev inotify may trigger really bad things on incomplete device content.

  $LOCK_BLOCK_DEVICE=1 as well as --lock=yes|no sounds good for me. 

It would be nice if we will implement it in some standardized way in all basic tools, it means fdisks-like tools, mkfs-like tools, blkdiscard, wipefs, ... @tytso any objection?

**Comment by poettering** [comment]
if we can agree on a good name for the env var and the switch I'd update the BLOCK_DEVICE_LOCKING document to ask tools to use the same naming, so that we can turn on this behaviour in all tools at once.

**Comment by tytso** [comment]
Asked on the e2fsprogs issue:

How do you prevent udev from trying to probe the device before mke2fs has a chance to run (and take the BSD file lock on the block device)? It doesn't seem to be a complete solution.

And if the answer is you inhibit udev until the mkfs program has a chance to start, why not wait until mkfs completes? I would think you would want to collect the exit status from the mkfs program, so you can report a failure to initialize the file system?

Perhaps we should have this as a discussion on linux-fsdevel, so we can make sure all of the stakeholders can have a discussion instead of having to copy-pasting the discussion across multiple random github issues?

**Comment by tytso** [comment]
I'll also note that mke2fs very deliberately writes the superblock as the last thing that it does, so the chances that a race will result in udev (or libblkid) getting massively confused is not likely to happen.

The other thing we need is a standardized way for udev to notice (or be notified) when a file system label has been changed, either when e2label changes it on an unmounted file system, or in the future, when we start using FS_IOC_SETFSLABEL to set the label on a mounted file system.  (See a recent discussion on linux-fsdevel about what assumptions we should be making about character set encodings for that ioctl.)

**Comment by poettering** [comment]
> How do you prevent udev from trying to probe the device before mke2fs has a chance to run (and take the BSD file lock on the block device)? It doesn't seem to be a complete solution.

mke2fs should take an exclusive blocking lock (LOCK_EX without LOCK_NB). udev itself takes a shared non-blocking lock (LOCK_SH with LOCK_NB) and watches for IN_CLOSE events on the device node, in which case it tries to probe again.

Thus if udev is currently probing the device mke2fs would briefly wait until it stops doing so. it would then acquire the lock, do its thing, close the device again (which implicitly releases the lock and triggers IN_CLOSE), which is indication for udev to check again. While mke2fs runs with the lock acquired udev stays away from the device, will not open the device, not interfere not read or probe it.

> And if the answer is you inhibit udev until the mkfs program has a chance to start, why not wait until mkfs completes? I would think you would want to collect the exit status from the mkfs program, so you can report a failure to initialize the file system?

udev always stays running, and never blocks on any such locks. However the tools which want to to "own" a device for a moment acquire a lock, potentially waiting until udev is done.

udev rules are supposed to finish quickly and they usually do. If people have long running udev rules they are misusing udev, it's not for that, and we enforce timeouts on that, thus guaranteeing that udev's BSD lock is eventually released.

> Perhaps we should have this as a discussion on linux-fsdevel, so we can make sure all of the stakeholders can have a discussion instead of having to copy-pasting the discussion across multiple random github issues?

I am not subscribed there. But feel free to CC me (le…rt@poe…ng.net), if you want to bring that up there...

> I'll also note that mke2fs very deliberately writes the superblock as the last thing that it does, so the chances that a race will result in udev (or libblkid) getting massively confused is not likely to happen.

In udev we we install the inotify watch on the device node as result of the configured udev rules saying so. The udev rules also probe the device via blkid. Thus blkid in udev is generally run without the inotify watch established yet. This is only non-racy if everyone respects the BSD file lock on the device node, because only then we can be sure that in the time between the probing and the establishment of the inotify watch noone else changed the superblock again...  (yes there are other options, but all sound really ugly, for example, we could implicitly retrigger a "change" udev event each time we istall an inotify event, or similar, but that's all ugly. I am pretty sure that taking proper BSD locks each time a superblock/partition table is changed is the right approach since it clearly declares "watch now" and "don't watch now" times and we can synchronize on those.

> The other thing we need is a standardized way for udev to notice (or be notified) when a file system label has been changed, either when e2label changes it on an unmounted file system, or in the future, when we start using FS_IOC_SETFSLABEL to set the label on a mounted file system. (See a recent discussion on linux-fsdevel about what assumptions we should be making about character set encodings for that ioctl.)

e2label opens the block device, makes its change and closes it again. The latter will trigger IN_CLOSE which makes udev reprobe the device. Thus, this mostly works, except for races which can also be addressed by taking the LOCK_EX BSD lock we are suggesting here. If e2label does that then everything should be robust and reliable: udev will either see the old or the new label and will see the IN_CLOSE and thus reprobe whenever needed.

FS_IOC_SETFSLABEL is a more complicated question. i presume that's something you invoke on an fd referring to a file on the fs, instead of on the block device. Thus, IN_CLOSE is never generated on the block device, because noone opens the block device when it is invoked.

Somehow the kernel needs to tell userspace about such fs label changes I figure. Maybe just sent a "changed" uevent or so.

**Comment by poettering** [comment]
> (Well, the possible issue may be some deadlock scenario, but it's probably very unusual to lock more device in our tools, and if yes it has to be done in careful way (all or nothing)).

Yeah, it would be great if we had flock() that took a timeout parameter... But I think we should be fine at least if the other owner of the lock is udev, as we put strict timeouts on udev rule runtime, thus if for some reason the block device prober/blkid hangs we should notice this eventually and abort it thus releasing the lock.

**Comment by marcosfrm** [comment]
What about `mkfs.{bfs,cramfs,minix}`? The idea is to push this concept to all mkfs related tools I figure.

**Comment by karelzak** [comment]
> What about `mkfs.{bfs,cramfs,minix}`? The idea is to push this concept to all mkfs related tools I figure.

Yes, it would be nice to add this too, but I had no time to do it ...

**Comment by jiayi0118** [comment]
@karelzak @poettering  If the input device is a partition, for example ``` mkfs.minix --lock /dev/sdc1 ```, util-linux will lock the partition block device sdc1 rather than the main block device sdc. This violates the lock concept of udev: https://systemd.io/BLOCK_DEVICE_LOCKING/.

See the latest discussion in tytso/e2fsprogs#30

**Comment by karelzak** [comment]
Well, fdisk-like programs lock whole-disk devices. 

I'm not sure if locking whole-disk devices for mkfs-like programs makes sense when it operates on partitions only. The option --lock is there mostly for use-cases when want to make the filesystem on whole-disk (`mkfs.foo --lock /dev/sdc`). This is also the reason why locking is not enabled by default.

**Comment by poettering** [comment]
The udev locking proto is for whole block devices, even if only partitions shall be modified. If the mkfs stuff wants to stay compatible with that (and I think that would be good), it should take the lock on the whole block device.

If the goal for the mkfs locks is to ensure udev (and other sw implementing the locking protol) doesn't read half initialized partitions, then the lock really should be on the whole block device.

systemd doesn't do per-partition locks, because when proving it goes to the partition table always anyway to pick up part uuid/label in addition to fs uuid/label. Moreover, it shouldn't be a contended lock, hence finegrained locking doesn't get you anything. by doing fine-grained locking you'd need to define a locking protocol to deal with ABBA issues, and that's just a mess.
