### ISSUE TITLE
It seems abnormal when I  type  ctl+d twice during  executing fdisk /dev/sda

### ISSUE THREAD

**Issue by fayeinseu** [karelzak/util-linux#923]
version:2.32.1
steps to reproduce the problem:
1.fdisk /dev/sda
2.keyboard input：t or type
3.choose a partition randomly.
4.keyboard input:ctl+d twice
I read the source code ，it seems that "t = ask_partition_type(cxt);" in fdisk.c has been called in
endless loop。

**Comment by karelzak** [comment]
It should be fixed in the current git tree, please try it. Thanks.

**Comment by karelzak** [comment]
Closing. I cannot reproduce it on the current code.
