### ISSUE TITLE
Required constants in blkidP.h don't appear to be public

### ISSUE THREAD

**Issue by jbaublitz** [karelzak/util-linux#929]
While it appears `blkid_init_debug` was added to the public API, the constants used in the mask argument don't appear to be public. Would you like me to submit a PR to bring those into the public API? If so, does it make the most sense to move the constants over to blkid.h.in?

**Comment by karelzak** [comment]
I'd like to avoid the constants in the API.

For now, the common solution is to use 0 as the mask and then libblkid follows $LIBBLKID_DEBUG. If you want to hardcode some mask (bad idea) then you need to use LIBBLKID_DEBUG=help to get the currently supported masks. 

For libblkid binding to another language, it would be best to export  blkid_init_debug() without any argument and internally use 0.

**Comment by jbaublitz** [comment]
Okay this is good to know! Is it even worth exposing that method in that case? As for the environment variable, I'll make sure to document that either way as the supported interface for libblkid.

**Comment by karelzak** [comment]
If you want to support LIBMOUNT_DEBUG= than you need to somehow initialize the debug stuff in the library, so you need to call blkid_init_debug(). And we want to keep it in the developer's hands rather than use for example __attribute__((constructor)) or so.

**Comment by jbaublitz** [comment]
Okay, this is helpful, thanks. I'll close this out!
