### ISSUE TITLE
Libmount license ?

### ISSUE THREAD

**Issue by Raghavendrakamatagi-eng** [karelzak/util-linux#930]
Hello contributors,

Could you please confirm the license for libmount (LGPL-2.1+ OR GPL-2.0+)?Since we are using only a libmount component from the util-linux package.
Is there any influence of util-linux source (header files) files in libmount?

Thanks
Raghavendra

**Comment by karelzak** [comment]
Already answered by email -- the library uses LGPL, and it includes some Public Domain and LGPL code from lib/ and include/ directories.

**Comment by Raghavendrakamatagi-eng** [comment]
Hello Karelzak,

In our context  we have to avoid LGPL version 3.0 because of tivoization risk on embedded devices, maybe you can help us confirm that these four files under LGPL-3.0 can be removed from libmount? 

/util-linux-2.30/libmount/python/context.c
/util-linux-2.30/libmount/python/fs.c
/util-linux-2.30/libmount/python/pylibmount.c
/util-linux-2.30/libmount/python/tab.c

If not possible to remove, maybe it can be relicensed as "LGPL version 2.1 or above" ?

Many thanks
