### ISSUE TITLE
Libmount license?

### ISSUE THREAD

**Issue by Raghavendrakamatagi-eng** [karelzak/util-linux#932]
Hello Karelzak,

In our context  we have to avoid LGPL version 3.0 because of tivoization risk on embedded devices, maybe you can help us confirm that these four files under LGPL-3.0 can be removed from libmount? 

/util-linux-2.30/libmount/python/context.c
/util-linux-2.30/libmount/python/fs.c
/util-linux-2.30/libmount/python/pylibmount.c
/util-linux-2.30/libmount/python/tab.c

If not possible to remove, maybe it can be relicensed as "LGPL version 2.1 or above" ?

Many thanks

_Originally posted by @Raghavendrakamatagi-eng in https://github.com/karelzak/util-linux/issues/930#issuecomment-573597405_

**Comment by karelzak** [comment]
libmount/python is NOT libmount.so -- it's python binding and compiled only when --with-python enabled and it's compiled to pylibmount.so.
