### ISSUE TITLE
Possible data lost

### ISSUE THREAD

**Issue by axet** [karelzak/util-linux#938]
Hello! I tried your recent release (v2.35-rc2) and it corrupt my linux partition. Can you check if new buffer size 1M does not overlap partition during move? I did move my windows partition to the left in about 4gb, and next linux partition no longer mountable. I remember step size was 1M and I do not remember any sector overlaps it suppose to be last step issue (moving more sectors from aligned partition). I have to use --force parameter because it is same disk I'm running linux on. This is result partition map:

Device Start End Sectors Size Type
/dev/sda1 40 409639 409600 200M EFI System
/dev/sda2 409640 419840039 419430400 200G unknown
/dev/sda3 419840040 522236891 102396852 48,8G Microsoft basic data
/dev/sda4 532313012 977105023 444792012 212,1G Linux filesystem

command was:

echo 419840040 | ./sfdisk -N 3 --force /dev/sda3

EDIT: quick look at sfdisk.c shows you never recalculate step_bytes if it smaller than partition end, very likely partition overlap.

**Comment by karelzak** [comment]
Hmm... you're probably right.  

The relation between step and step_bytes seems broken, the move for() loop works with the step (aligned to nsectors), but step_bytes is calculated before step is aligned. We need to make sure in the move for() loop that the next move is not after the partition end.

Pretty stupid bug. Sorry.

**Comment by axet** [comment]
No worries I backup most of data, only game saves were lost. Based on data I report here can be another issue beside obvious overflow.

Size of windows partition is 102396852*512=52427188224, it is not 1MiB aligned (102396852.*512/1024/1024/1024=48.82662391662598), that is how MS create partitions using build-in disk management, but space between my windows and linux partition > 1MiB which conclude: I faced another issue. I guess it is easy to reproduce using simple losetup test.

Windows create empty space after partition for unknown exact size, now I have 3149 unused sectors before linux partition (this probably same value as it used to be before crash)

My approximate partition numbers before crash is:

/dev/sda1 40 409639 409600 200M EFI System
/dev/sda2 409640 419840039 419430400 200G unknown
/dev/sda3 422297639 524694491 102396852 48,8G Microsoft basic data
/dev/sda4 532313012 977105023 444792012 212,1G Linux filesystem

I did create simple loopback device as hdd.img

dd if=/dev/zero of=hdd.img bs=1G

/dev/loop18p1         2048  206847  204800   100M 83 Linux
100M unused
/dev/loop18p2       206848  818176  611329 298,5M 83 Linux
1.5M unused
/dev/loop18p3      1026048 2097151 1071104   523M 83 Linux

kpartx -av hdd.img # mount loopdevice with partition mapping
mkdir 1 2 3
mkfs.ext4 /dev/mapper/loop18p2
mkfs.ext4 /dev/mapper/loop18p3
mount /dev/mapper/loop18p3



# echo 206848 | ./sfdisk -N 2 --move-data /dev/loop18 
Checking that no-one is using this disk right now ... OK

Disk /dev/loop18: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xb92748ab

Old situation:

Device        Boot   Start     End Sectors   Size Id Type
/dev/loop18p1         2048  206847  204800   100M 83 Linux
/dev/loop18p2       411648 1022976  611329 298,5M 83 Linux
/dev/loop18p3      1026048 2097151 1071104   523M 83 Linux

/dev/loop18p2: 
New situation:
Disklabel type: dos
Disk identifier: 0xb92748ab

Device        Boot   Start     End Sectors   Size Id Type
/dev/loop18p1         2048  206847  204800   100M 83 Linux
/dev/loop18p2       206848  818176  611329 298,5M 83 Linux
/dev/loop18p3      1026048 2097151 1071104   523M 83 Linux

Data move:
  start sector: (from/to) 411648 / 206848
  sectors: 611329
  step size: 1048576 bytes

Moved 38541 from 611329 sectors (6,304%).sfdisk: /dev/loop18p2: failed to move data: Success

The partition table has been altered.
Calling ioctl() to re-read partition table.




umount /dev/mapper/loop18p3

# mount /dev/mapper/loop18p3 3
mount: /home/axet/local/util-linux/3: mount(2) system call failed: Structure needs cleaning.

**Comment by karelzak** [comment]
Yes, nice example, I use scsi_debug rather than loop to keep it simple
```
# modprobe scsi_debug dev_size_mb=1024
# echo -e ',100M,L\n411648,611329,L\n1026048,,L\n' | ./sfdisk /dev/sdb
# mkfs.ext2 /dev/sdb3
# shasum /dev/sdb3
f8b725dd052ecf8abdddaae2171308c61f7baec9  /dev/sdb3

# echo 206848 | ./sfdisk -N 2 --move-data=log /dev/sdb
...
# shasum /dev/sdb3
83b3874ee79c5b24abfdce9b66b942446b84c48a  /dev/sdb3
```
Now see log-sdb2:
```
# Area size (sectors/bytes): 611329/313000448
# Sector size: 512
# Step size (in bytes): 1048576
```
area_size / step_bytes = 313000448/1048576 = 298.50048828125000000000
:-(((

**Comment by karelzak** [comment]
It also seems that broken is the way how it aligns the step. I'll fix it.

**Comment by karelzak** [comment]
It seems all the problems have been introduced when I moved from page-size to i/o size... 

We need 2.35.a ASAP :-)

**Comment by axet** [comment]
Looks fine. But not quite sure why step_size of 1M affecting partition standing further apart then 1M...

**Comment by karelzak** [comment]
> Looks fine. But not quite sure why step_size of 1M affecting partition standing further apart then 1M...

because the size in sectors (step) was completely different than step_size (in bytes) due to broken alignment (applied to "step" only)... the problem was visible for partition with misaligned size only. It's fixed by the second patch.
