### ISSUE TITLE
failed to prepare mount: Operation not permitted when using user and x-gvfs-show

### ISSUE THREAD

**Issue by valr** [karelzak/util-linux#941]
Hi,

I'm facing an issue when trying to mount an NFS share using mount.nfs (that uses libmount).

Here is my fstab:
nas:/volume1/music   /nas/music   nfs   noauto,user,_netdev,bg,x-gvfs-show   0   0

As user I'm trying to mount the directory (here with libmount debug activated):
export LIBMOUNT_DEBUG=0xffff
mount.nfs  nas:/volume1/music  /nas/music

I get this error in the debug output:
...
6494: libmount: CXT: final target '/nas/music' [rc=-1]
6494: libmount: CXT: mount: preparing failed
mount.nfs: failed to prepare mount: Operation not permitted

When I look at the code of libmount, I see a diff in libmount/src/context.c in the function mnt_context_prepare_target.

In version 2.34

```
    /* mkdir target */
    if (cxt->action == MNT_ACT_MOUNT
        && !mnt_context_is_restricted(cxt)
        && (cxt->user_mountflags & MNT_MS_XCOMMENT ||
             cxt->user_mountflags & MNT_MS_XFSTABCOMM)) {

        rc = mkdir_target(tgt, cxt->fs);
        if (rc) {
            if (!mnt_context_switch_ns(cxt, ns_old))
                return -MNT_ERR_NAMESPACE;
            return rc; /* mkdir or parse error */
        }
    }
```

In version 2.35:

```
    /* X-mount.mkdir target */
    if (cxt->action == MNT_ACT_MOUNT
        && (cxt->user_mountflags & MNT_MS_XCOMMENT ||
            cxt->user_mountflags & MNT_MS_XFSTABCOMM)) {

        /* supported only for root or non-suid mount(8) */
        if (!mnt_context_is_restricted(cxt))
            rc = mkdir_target(tgt, cxt->fs);
        else
            rc = -EPERM;
    }
```

As I understand, the code in 2.35 will give -EPERM as non-root (user) each time, as soon as you have a mount comment (x-...), preventing the mount command to succeed.

Could you tell me your view on this? Am I misusing the fstab mount options?
Thanks

**Comment by karelzak** [comment]
This is bug, we need check if mkdir is requested and necessary. I'll fix it. Thanks!

**Comment by karelzak** [comment]
The bugfix will be released in version v2.35.1 (probably this week).

**Comment by valr** [comment]
Cool, thanks!

**Comment by cIddegh** [comment]
That bug bit me, too. Also waiting for the bugfix!
