### ISSUE TITLE
chrt does not work with musl libc

### ISSUE THREAD

**Issue by jonnyh64** [karelzak/util-linux#943]
Musl libc does not support sched_setscheduler, as the Linux syscall does not follow Posix semantics (Linux: set thread priority, Posix: set process priority), breaking the chrt utility.

I see two options to “fix“ this in chrt.c:

1. use sched_setattr instead. This basically means to remove the following code:
—-
	/* old API is good enough for non-deadline */
	if (ctl->policy != SCHED_DEADLINE)
		return set_sched_one_by_setscheduler(ctl, pid);
—-
(And maybe adapt some code further below).

2. Replace the libc function call by a direct syscall.

Would you accept a patch for one of both solutions?

**Comment by karelzak** [comment]
On Tue, Jan 28, 2020 at 10:49:16AM -0800, jonnyh64 wrote:
> Musl libc does not support sched_setscheduler, as the Linux syscall does not follow Posix semantics (Linux: set thread priority, Posix: set process priority), breaking the chrt utility.
> 
> I see two options to “fix“ this in chrt.c:
> 
> 1. use sched_setattr instead. This basically means to remove the following code:
> —-
> 	/* old API is good enough for non-deadline */
> 	if (ctl->policy != SCHED_DEADLINE)
> 		return set_sched_one_by_setscheduler(ctl, pid);
> —-
> (And maybe adapt some code further below).
> 
> 2. Replace the libc function call by a direct syscall.

I think direct syscall is the best solution which we already use on
many places. It's trivial change.

> Would you accept a patch for one of both solutions?

Yes, please, go ahead. I'd like to release v2.35.1 on Friday -- we can
add this fix to the release.

    Karel


-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Comment by jonnyh64** [comment]
Pull request submitted: https://github.com/karelzak/util-linux/pull/944

**Comment by karelzak** [comment]
Fixed.
