### ISSUE TITLE
logger can't reconnect tcp conenction to syslog

### ISSUE THREAD

**Issue by marcin-github** [karelzak/util-linux#945]
Hello!
I use logger to forward messages generated by long running process from stdin via tcp to remote syslog. When I eg. restart remote syslog then tcp connection is closed, no reconnection happens and I loose all of the rest messages.

**Comment by karelzak** [comment]
Version? 

It should be possible since v2.32 (or so) http://github.com/karelzak/util-linux/commit/caf6ac6e596b09615b5f4bffe588ec1268d8c596

**Comment by marcin-github** [comment]
Almost good version ;)
util-linux/bionic-updates,now 2.31.1-0.4ubuntu3.4 
Thank you!
