### ISSUE TITLE
fstrim.service is no longer trimming filesystems without manual intervention

### ISSUE THREAD

**Issue by Swipe650** [karelzak/util-linux#948]
Since v2.35 fstrim.service is no longer trimming filesystems from fstab entries without manual intervention by the user.

The workaround is to comment out:

`ProtectSystem=strict`

and

`ProtectHome=read-only` (if /home is a separate partition)

I believe this is ever since [this](https://github.com/karelzak/util-linux/issues/857) issue was reported which was addressed by;

[f227757c fstrim: ignore non-directory mountpoints](https://github.com/karelzak/util-linux/commit/f227757c77bf0992de4c3c03349ab4a345e6b409#diff-fc84b294acaac50fce6fc0717eb52812)

**Comment by karelzak** [comment]
If I good understand, then Protect{Home,System} forces all mountpoints are accessible read-only. This should not be a problem as fstrim(8) uses the mountpoints in read-only mode.

**Comment by karelzak** [comment]
Hmm... but it really seems you're right as it does not work ;-(

**Comment by karelzak** [comment]
I see access(path, W_OK) ...

**Comment by Swipe650** [comment]
Unfortunately, I don't have enough knowledge of this but I can point you to many people confirming the issue that fstab mountpoints in fstab are no longer accessible since the change in v2.35 unless ProtectSystem=strict is commented out.

[Reddit /r/archlinux](https://www.reddit.com/r/archlinux/comments/ex64oz/fstrimservice_is_no_longer_trimming_filesystems/)

[Arch Linux forum](https://bbs.archlinux.org/viewtopic.php?id=252451)

**Comment by karelzak** [comment]
Thanks! It will be fixed in v2.35.2.
