### ISSUE TITLE
settimeofday is deprecated

### ISSUE THREAD

**Issue by zqqw** [karelzak/util-linux#957]
[https://sourceware.org/ml/libc-announce/2020/msg00001.html](https://sourceware.org/ml/libc-announce/2020/msg00001.html)
[https://forum.artixlinux.org/index.php/topic,1311.msg9203/topicseen.html#msg9203](https://forum.artixlinux.org/index.php/topic,1311.msg9203/topicseen.html#msg9203)

**Comment by karelzak** [comment]
More references:
systemd: https://github.com/systemd/systemd/issues/13305

**Comment by zqqw** [comment]
Some server software I know of checks in preference 1) NTP 2) Local time reference 3) The server's own RTC at boot to set the OS time, so hwclock or something similar is still useful there for scripting the logic.

**Comment by 2005songliwei** [comment]
I also met the same issue when update glibc to 2.31 by run hwclock -s
# hwclock -s
hwclock: settimeofday() failed: Invalid argument

**Comment by karelzak** [comment]
The version merged to master branch: https://github.com/karelzak/util-linux/commit/cd781c405be82540484da3bfe3d3f17a39b8eb5c

Closing.
