### ISSUE TITLE
Accept shortcuts in sfdisk --part-type

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#958]
When creating partitions, `sfdisk` accepts L,S,H,U,R,V shortcuts. With `--part-type` it does not.

```
# sfdisk --part-type /dev/sdb 1
0FC63DAF-8483-4772-8E79-3D69D8477DE4
```

I want to change partition 1 to "Linux RAID".

```
# sfdisk --part-type /dev/sdb 1 R
sfdisk: /dev/sdb: partition 1: failed to set partition type
```

Needs GUID:

```
# sfdisk --part-type /dev/sdb 1 A19D880F-05FC-4D3B-A006-743F0F84911E

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
```

sfdisk 2.32.1 from CentOS 8.

**Comment by marcosfrm** [comment]
(plus E,X if DOS label)

**Comment by karelzak** [comment]
This is a problem, because now 'E' means 0x0E ("W95 FAT16 (LBA)"), but as a shortcut, it means extended partition. Maybe we can ignore this problem and force people to explicitly use 0E or 0x0E. Not sure, I need to think about it...

It would be nice support shortcuts also in fdisk dialogs.

**Comment by marcosfrm** [comment]
You are right. Legacy DOS stuff :-(

**Comment by karelzak** [comment]
Implemented, the patches:

* add "Ex" shortcut, deprecate 'E'
* add aliases (human-readable word), for example, 'swap'
* shortcuts and aliases are usable for --part-type now (but interpreted as the last possibility)
* fdisk extended to use aliases
