### ISSUE TITLE
Diagnostic on attempt to umount a non-mounted filesystem has become confusing

### ISSUE THREAD

**Issue by ahmogit** [karelzak/util-linux#961]
In 2.34.8, issuing umount as non-root user on a non-mounted FS having the 'user' attribute resulted in the meaningful diagnostic 

`      $ umount /foo/bar`
`      umount: /foo/bar: not mounted.`

But as of 2.35.1, the diagnosis has changed to

`      umount: /foo/bar: must be superuser to unmount`

To my eyes, this change in the diagnostic text is confusing and misleading: The error that the user made was to specify a mount point on which no filesystem was mounted.  The message issued by 2.34.8 was informative of that. The new message in 2.35.1 fails to inform the user what the real problem is, and also implies (incorrectly) that if the user had  root privs, he _would_ be able to unmount /foo/bar. This is also misleading because if no FS is mounted there, then /foo/bar is just a mountpoint, and the notion of unmounting it doesn't even make sense.

NOTES: In the example, /foo/bar is listed in /etc/fstab as follows:

` LABEL=whatever            /foo/bar             ext3    noauto,user                                     0  2`

**Comment by karelzak** [comment]
Fixed. The bugfix will be backported to v2.35.2. 

Thanks for your report!
