### ISSUE TITLE
su: ENV_SUPATH should include /usr/local/sbin

### ISSUE THREAD

**Issue by yecril71pl** [karelzak/util-linux#964]
I am on [SUSE / WSL](https://en.opensuse.org/openSUSE%3AWSL). SUSE rc scripts (see man:service) do not work for me because they require `systemd`.  I have created a working `/usr/local/sbin/rcxrdp` but I cannot see it under `su`.

**Comment by karelzak** [comment]
As described in su.1 man page, the default is (for root user):
```
if ((rc = logindefs_setenv("PATH", "ENV_SUPATH", NULL)) != 0)
          rc = logindefs_setenv("PATH", "ENV_ROOTPATH", _PATH_DEFPATH_ROOT);
```
it means if there is no ENV_SUPATH in /etc/login.defs then use ENV_ROOTPATH from the same file. If ENV_ROOTPATH also not defined than default to hardcoded _PATH_DEFPATH_ROOT ("/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin" or "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin".

So, it sounds like you have something in /etc/login.defs.

For non-root users, it defaults to ENV_PATH where is no sbin/ at all.

**Comment by karelzak** [comment]
Note that this kind of issue is better to report to the distribution bug tracking system rather than to upstream due to distribution-specific policies/settings.

**Comment by yecril71pl** [comment]
I admit I am confused.  The path is set correctly when logging in with `-l` but weird and undocumented things happen to the path when logging in without `-l`.  I think we can close this by saying that `su` without `-l` is discouraged and unsupported.  I am sorry for the misunderstanding.
