### ISSUE TITLE
Default behavior when the shell selected in `chsh` is not on `/etc/shells`

### ISSUE THREAD

**Issue by FFY00** [karelzak/util-linux#967]
Hello, according to the `chsh` man page when I run it with a shell that isn't listed in `/etc/shells` it will just issue a warning. I never explicitly changed any config related to this behavior but `chsh` doesn't seem to want to change my shell if it is not listed in `/etc/shells`. Where is this configuration stored? Is the default behavior correct?

**Comment by karelzak** [comment]
The man page is incomplete (I'll fix it), the warning message is the default for root user, but for non-root users it prints error message and exits. This behavior may be modified --disable-chsh-only-listed, and in this case the default is to print the warning only.

**Comment by karelzak** [comment]
Thanks for your report
