### ISSUE TITLE
lscpu: HiSilicon aarch64 0xD01 cpupart model name is wrong

### ISSUE THREAD

**Issue by ZhengZhenyu** [karelzak/util-linux#969]
The official name for HiSilicon aarch64 0xD01 cpupart model is ``Kunpeng-920`` rather than ``tsv110``, should correct it

**Comment by karelzak** [comment]
It seems that "HiSilicon tsv110" is a pretty commonly used name for this architecture, let's hope that Kunpeng-920 trade name won't be too confusing for advanced users ;-)

Fixed, thanks!
