### ISSUE TITLE
Typo in `text-utils/hexdump-conv.c'

### ISSUE THREAD

**Issue by cedric-sun** [karelzak/util-linux#976]
When `hexdump` is invoked with `_u` format string, for control char `0x10` it prints `dcl` instead of `dc1`.

https://github.com/karelzak/util-linux/blob/e0e29759981430e572087dfc27334939ec47fd24/text-utils/hexdump-conv.c#L93

;) really a typo hiding for years

**Comment by karelzak** [comment]
Wow. Now, I know how stupid font uses my firefox. I have read "it prints dcl instead of dc1" at least 5 times before I get the difference :-)

Very good catch! Fixed.
