### ISSUE TITLE
Human readable color name for "white"

### ISSUE THREAD

**Issue by marcosfrm** [karelzak/util-linux#979]
Should not `white` be in this list?

https://github.com/karelzak/util-linux/blob/stable/v2.35/lib/color-names.c#L29

Its definition in `include/color-names.h` is unused, no?

My use case is `\e{white}` in `/etc/issue` (`agetty`'s job).

**Comment by karelzak** [comment]
Good point. Fixed. Thanks!

**Comment by marcosfrm** [comment]
Thanks. `agetty` man page needs update:

https://github.com/karelzak/util-linux/blob/stable/v2.35/term-utils/agetty.8#L398
