### ISSUE TITLE
chfn is not building

### ISSUE THREAD

**Issue by mator** [karelzak/util-linux#982]
Hello!

Checking out (git clone) latest master branch sources, does not build `chfn`.

Trying to build with :
```
        Type 'make' or 'make <utilname>' to compile.
```
reports:
```
util-linux$ make chfn
  CCLD     chfn
gcc: fatal error: no input files
compilation terminated.
make: *** [Makefile:6831: chfn] Error 1
```

Is it intentional that `chfn` is not building?! Thanks

**Comment by karelzak** [comment]
It works for me. Please, see (and copy & past) ./configure output. Maybe you do not have required dependencies (shadow.h and getusershell()).

**Comment by mator** [comment]
ahh, sorry for the noise, libpam-dev and libuser-dev was not installed....

**Comment by mator** [comment]
ahh, sorry for the noise, libpam-dev and libuser-dev was not installed....

**Comment by mator** [comment]
ahh, sorry for the noise, libpam-dev and libuser-dev was not installed....

**Comment by mator** [comment]
ahh, sorry for the noise, libpam-dev and libuser-dev was not installed....

**Comment by mator** [comment]
.

**Comment by mator** [comment]
.

**Comment by mator** [comment]
ahh, sorry for the noise, libpam-dev and libuser-dev was not installed....

**Comment by karelzak** [comment]
No problem, Closing.
