### ISSUE TITLE
Possible data lost during --move-data

### ISSUE THREAD

**Issue by axet** [karelzak/util-linux#984]
Hello! Karel! It is me again. I found another possible data lost when using sfdisk with move-data flag. This time it is related to IO errors.

My harddrive is old (25000 hours) and it start to show symptoms of IO errors and sometimes it failed read a sector. When using gparted IO errors displayed to user and operation like move partition allow user to choice from "retry, ignore, stop". This behavior can prevent data lost during failed partition move command, because If any bad block occurs during move operation user able to react (hit ignore) and prevent breaking whole partition and file structure down (theoretically it is possible to cancel move partition command if it is not yet overlap it self during move command, or move already moved data back where it was before move operation starts).

Checking your sfdisk move_partition_data() function it shows possible data lost during IO operations since on any IO errors it reacts with 'goto fail' which can cause damage to whole partition as described above. Can you please ignore errors on read/write operations (log it) or allow user to choice from "retry, ignore, stop".

PS: New speed meter progress is amazing, it can help detect harddrive health issues since I know optimal speed and actual transfer speeds! Cheers!

EDIT: I think it is good idea to write same step_size buffer (1M) sector by sector again (512 or 4096 bytes depend on device physical sector size) and ignore failed sectors on write errors. And trying to re-read step_size buffer from harddrive sector by sector on read errors. Then take actions (ignore by default, it can be sfdisk flag what to do: stop, ignore). Always good to give user options: rollback, ignore, stop.

EDIT: it looks like this :(

```
root@axet-laptop:/home/axet/local/util-linux# echo 1536411648 | ./sfdisk /dev/sdb -N 5 --move-data
Checking that no-one is using this disk right now ... OK

Disk /dev/sdb: 1,84 TiB, 2000398933504 bytes, 3907029167 sectors
Disk model: Expansion Desk  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C23D939B-2149-4A1B-AE20-72BED18470B0

Old situation:

Device          Start        End   Sectors   Size Type
/dev/sdb1        2048     411647    409600   200M EFI System
/dev/sdb2      411648  512411647 512000000 244,1G Apple APFS
/dev/sdb3   512411648 1024411647 512000000 244,1G Linux filesystem
/dev/sdb4  1024411648 1536411505 511999858 244,1G Microsoft basic data
/dev/sdb5  3072411648 3907026943 834615296   398G Microsoft basic data

/dev/sdb5: 
New situation:
Disklabel type: gpt
Disk identifier: C23D939B-2149-4A1B-AE20-72BED18470B0

Device          Start        End   Sectors   Size Type
/dev/sdb1        2048     411647    409600   200M EFI System
/dev/sdb2      411648  512411647 512000000 244,1G Apple APFS
/dev/sdb3   512411648 1024411647 512000000 244,1G Linux filesystem
/dev/sdb4  1024411648 1536411505 511999858 244,1G Microsoft basic data
/dev/sdb5  1536411648 2371026943 834615296   398G Microsoft basic data

Data move:
  start sector: (from/to) 3072411648 / 1536411648
  sectors: 834615296
  step size: 1048576 bytes

Moved 380231681 from 834615296 sectors (45,558%, 44,0 MiB/s).sfdisk: /dev/sdb5: failed to move data: Success

The partition table has been altered.
Calling ioctl() to re-read partition table.
/dev/sdb: fsync device failed: Input/output error
root@axet-laptop:/home/axet/local/util-linux# 
```

**Comment by karelzak** [comment]
I have implemented it in way it just reports I/O errors and continues to the next step. 

It would be nice to have any dialog for this case and read/write in sectors when an error detected in the step... but I have no time for this right now. I'll keep this issue open.

**Comment by marcosfrm** [comment]
> I have implemented it in way it just reports I/O errors and continues to the next step.

Change welcome in 2.35 stable branch. :-)

**Comment by karelzak** [comment]
Released.
