### ISSUE TITLE
what‘s the reason to add "sysfs_devname_to_devno(buf);"? 

### ISSUE THREAD

**Issue by fayeinseu** [karelzak/util-linux#987]
when /sys/block/* is not consistent with the /dev directory ,fdisk -l cannot show the disk info.for example:
ll /sys/block/
total 12
lrwxrwxrwx. 1 root root 29 Mar 19 11:01 dm-0 -> ../devices/virtual/block/dm-0
lrwxrwxrwx. 1 root root 29 Mar 19 11:01 dm-1 -> ../devices/virtual/block/dm-1
lrwxrwxrwx. 1 root root 91 Mar 19 11:01 sda -> ../devices/pci0000:00/0000:00:02.3/0000:06:00.0/virtio6/host0/target0:0:0/0:0:0:0/block/sda
lrwxrwxrwx. 1 root root 91 Mar 19 11:01 sdb -> ../devices/pci0000:00/0000:00:02.3/0000:06:00.0/virtio6/host0/target0:0:0/0:0:0:1/block/sdb
lrwxrwxrwx. 1 root root 91 Mar 19 11:01 sdc -> ../devices/pci0000:00/0000:00:02.3/0000:06:00.0/virtio6/host0/target0:0:0/0:0:0:1/block/sdb
the content of /proc/partition:
cat /proc/partitions
major minor #blocks name

8 16 1048576 sdc
253 0 36491264 sda
the sdc can't be read by fdisk -l, I've noticed the change from (7fe16fd). vesion before this commit can show disk sdc normally.(ps: this happens in docker )

**Comment by fayeinseu** [comment]
when /sys/block/* is not consistent with the /dev directory ,fdisk -l cannot show the disk info.for example:
ll /sys/block/
total 12
lrwxrwxrwx. 1 root root 29 Mar 19 11:01 dm-0 -> ../devices/virtual/block/dm-0
lrwxrwxrwx. 1 root root 29 Mar 19 11:01 dm-1 -> ../devices/virtual/block/dm-1
lrwxrwxrwx. 1 root root 91 Mar 19 11:01 sda -> ../devices/pci0000:00/0000:00:02.3/0000:06:00.0/virtio6/host0/target0:0:0/0:0:0:0/block/sda
lrwxrwxrwx. 1 root root 91 Mar 19 11:01 sdb -> ../devices/pci0000:00/0000:00:02.3/0000:06:00.0/virtio6/host0/target0:0:0/0:0:0:1/block/sdb
lrwxrwxrwx. 1 root root 91 Mar 19 11:01 sdc -> ../devices/pci0000:00/0000:00:02.3/0000:06:00.0/virtio6/host0/target0:0:0/0:0:0:1/block/sdb
the content of /proc/partition:
 cat /proc/partitions
major minor  #blocks  name

   8       16    1048576 sdc
 253        0   36491264 sda
the sdc can't be read by fdisk -l, I've noticed the change from (https://github.com/karelzak/util-linux/commit/7fe16fdaf40283cd8ff6fd05958f9f9aa3811409). vesion before this commit can show disk sdc normally.(ps: this happens in docker )

**Comment by karelzak** [comment]
Reasons:
* we assume that /sys is right as it's how kernel see your block devices, /dev is (usually) generated by udevd according to /sys -- so, /sys seems like a good source
* we need devno to detect DM private devices
* we need devno to detect whole-disk devices - the original primitive detection based on device name is useless in many cases (e.g. nvme0n1 is whole-disk)

The question is why your /dev does not match with your /sys.

**Comment by fayeinseu** [comment]
thank you for your detailed answer ！The docker that the problem occurred has messy mapping which result from soft links.So it is not a fdisk problem，thanks again.
