### ISSUE TITLE
man kill lies

### ISSUE THREAD

**Issue by qwelias** [karelzak/util-linux#991]
From the manual:
> Example.  Send signals QUIT, TERM and KILL in sequence and wait for 1000 milliseconds between the signals `kill --verbose --timeout 1000 TERM --timeout 1000 KILL --signal QUIT 12345`

I'm not sure if my `kill` distribution is broken or something, but
```
$ sleep 5 & kill --verbose --timeout 1000 TERM --timeout 1000 KILL --signal QUIT $!
[1] 60475
kill: unknown signal: SIG-VERBOSE
kill: type kill -l for a list of signals
```

**Comment by marcosfrm** [comment]
`kill` is often a builtin shell command. To use util-linux's `kill`, call:

```
$ command kill
```

**Comment by kerolasa** [comment]
I tried to reproduce your error message, and it took couple tries before
getting lucky.

The util-linux kill that was compiled without UL_HAVE_PIDFD:

    $ /usr/bin/kill --verbose --timeout 1000 TERM --timeout 1000 KILL --signal QUIT $$
    kill: invalid signal name or number: -timeout

Bash:

    $ kill --verbose --timeout 1000 TERM --timeout 1000 KILL --signal QUIT $$
    bash: kill: -verbose: invalid signal specification

Dash:

    $ kill --verbose --timeout 1000 TERM --timeout 1000 KILL --signal QUIT $$
    dash: 1: kill: Illegal option --

Zsh, bingo!

    $ kill --verbose --timeout 1000 TERM --timeout 1000 KILL --signal QUIT $$
    kill: unknown signal: SIG-VERBOSE
    kill: type kill -l for a list of signals

Please try `/usr/bin/kill --help` and if you see `--timeout` option in
output it means pidfd support was found at time of compilation, and might
even work if you use it.

**Comment by qwelias** [comment]
@marcosfrm thanks, indeed
```
$ type kill
kill is a shell builtin
```

@kerolasa 
```
$ /usr/bin/kill --version
kill from util-linux 2.35.1 (with: sigqueue)
```
I do not have the `--timeout` option, but it seems like `sigqueue` should be able to somewhat substitute that for me, thanks!

Is it possible to somehow inform the reader of the manual so they are aware of some functionality being locked behind a comp flag?

**Comment by karelzak** [comment]
So, I guess the man page update is good enough. 

Closing. Thanks Sami!
