### ISSUE TITLE
mount -o move doesn't work

### ISSUE THREAD

**Issue by illiliti** [karelzak/util-linux#997]
```
# mount -o move /dev /mnt/root/dev
mount: /mnt/root/dev: /dev is not a block device.
```
busybox, toybox and even ubase mount supports move option

please add support to this option to be more portable

**Comment by karelzak** [comment]
The reason why it's unsupported is that we do not want "move" in fstab, but you're right that on the command line it makes sense to support "-o move" if we already support "--move".

**Comment by karelzak** [comment]
Fixed.
