### ISSUE TITLE
Function size_to_human_string() problem

### ISSUE THREAD

**Issue by bub75** [karelzak/util-linux#998]
Hi, 

I am preparing an UEFI version of "fdisk" and caught a bug in this function when called with the option SIZE_DECIMAL_2DIGITS: it returns erroneous values, see this example:

$ cat a.c

#include <stdio.h>
#include "include/strutils.h"

static void do_one( int i )
{
	printf( "%d B = %.3f MiB -> %s\n" , 2048 * i , 
		( 2048 * i ) / 1024.0f / 1024.0f , 
		size_to_human_string( 7 , 2048 * i ) ) ;
}

int main()
{
	do_one( 995 ) ;
	do_one( 1005 ) ;
	do_one( 1010 ) ;
	do_one( 1015 ) ;
	do_one( 1020 ) ;
	do_one( 1025 ) ;
	do_one( 1030 ) ;
	do_one( 1050 ) ;
	do_one( 1070 ) ;
	do_one( 1090 ) ;
}

$ cc a.c lib/libcommon_la-strutils.o 
$ ./a.out 
**2037760 B = 1.943 MiB -> 1.97 MiB
2058240 B = 1.963 MiB -> 1.99 MiB
2068480 B = 1.973 MiB -> 1.10 MiB
2078720 B = 1.982 MiB -> 1.101 MiB
2088960 B = 1.992 MiB -> 1.102 MiB**
2099200 B = 2.002 MiB -> 2 MiB
**2109440 B = 2.012 MiB -> 2.1 MiB
2150400 B = 2.051 MiB -> 2.5 MiB
2191360 B = 2.090 MiB -> 2.9 MiB**
2232320 B = 2.129 MiB -> 2.13 MiB
$ 

Thank you for your work !

**Comment by karelzak** [comment]
You're right, it seems 
```                       frac = (frac / (1ULL << (exp - 10)) + 5) / 10;
                        if (frac % 10 == 0)
                                frac /= 10;     /* convert N.90 to N.9 */
```
is preaty broken...

**Comment by bub75** [comment]
You can replace this computation by:
```
          /* get 3 digits after decimal point */
          frac = ( frac * 1000 ) / (1ULL << exp) ;
          /* round 4/5 and keep 2 digits after decimal point */
          frac = ( frac + 5 ) / 10 ;
          /* rounding could have overflowed */
          if ( frac == 100 ) { dec ++ ; frac = 0 ; }
```
and then replace the call to snprintf() a few lines below by:
```
          /*snprintf(buf, sizeof(buf), "%d%s%" PRIu64 "%s", dec, dp, frac, suffix);*/
          snprintf(buf, sizeof(buf), "%d%s%02" PRIu64, dec, dp, frac ) ;
          /* remove trailing zeroes */
          while ( buf[ strlen( buf ) ] == '0' ) buf[ strlen( buf ) ] = '\0' ;
          /* remove trailing decimal point */
          if ( buf[ strlen( buf ) ] == '.' ) buf[ strlen( buf ) ] = '\0' ;
          /* cat unit */
          strncat( buf , sizeof(buf) , suffix ) ;
```
Thank's again for the work and wish you well!

**Comment by karelzak** [comment]
Good idea. Applied. Thanks!

**Comment by bub75** [comment]
Hi again, 

Sorry to only see it now but that change caused a regression for big big values ~Exbibyte, the problem being that multiplying "frac" by 1000 overflows int64_t in this situation and seems to creates a bad ".01" fractional part.

I would suggest avoiding the overflow with a construction like:
```
        /* get 3 digits after decimal point without overflowing int64_t */
        if ( frac >= 32768LL * 1024 ) {
                frac = ( frac / 1024 * 1000 ) / ( 1ULL << ( exp - 10 ) ) ;
        } else {
                frac = ( frac * 1000 ) / ( 1ULL << ( exp ) ) ;
        }
```
Thanks again for the work and wish you well!

**Comment by karelzak** [comment]
Ah, I have missed this in our regression tests...
```
>         /* get 3 digits after decimal point without overflowing int64_t */
>         if ( frac >= 32768LL * 1024 ) {
```
It's unint64_t, so I guess we can use `if (frac >= UINT64_MAX / 1000)` here. 
```
>                 frac = ( frac / 1024 * 1000 ) / ( 1ULL << ( exp - 10 ) ) ;
>         } else {
>                 frac = ( frac * 1000 ) / ( 1ULL << ( exp ) ) ;
>         }
```
Now it works as expected (for UINT64_MAX input):
```
    ./test_strutils --size 18446744073709551615
     18446744073709551615 : 18446744073709551615 :      16E :       16 EiB :        16 EiB
```
Thanks!
